"""Merge law metadata into Quarto search.json for full-text search coverage.

Run after `quarto render` and before deploying to gh-pages.
Reads laws.json (generated by quarto.py) and appends entries to _site/search.json.
"""
import json
import re
import sys
from pathlib import Path

GITHUB_BASE = "https://github.com/sondreskarsten/norwegian-laws"


def dept_to_page(dept: str, kind: str = "lov") -> str:
    safe = re.sub(r"[^\w\s-]", "", dept).strip().replace(" ", "-").lower()
    prefix = "forskrift-dept" if kind == "forskrift" else "dept"
    return f"book/{prefix}-{safe}.html"


def merge_laws_into_search(site_dir: str = "_site", laws_json: str = "laws.json"):
    search_path = Path(site_dir) / "search.json"
    laws_path = Path(laws_json)

    if not search_path.exists():
        print(f"  {search_path} not found, skipping search index merge")
        return
    if not laws_path.exists():
        print(f"  {laws_path} not found, skipping search index merge")
        return

    with open(search_path, encoding="utf-8") as f:
        search_entries = json.load(f)
    with open(laws_path, encoding="utf-8") as f:
        laws = json.load(f)

    existing_count = len(search_entries)

    for law in laws:
        depts = law.get("departement", [])
        dept_str = ", ".join(depts)
        kind = law.get("kind", "lov")
        href = dept_to_page(depts[0], kind) if depts else "book/sok.html"
        text_parts = [
            law.get("korttittel", ""),
            dept_str,
            law.get("refid", ""),
            law.get("ikrafttredelse", ""),
        ]
        text = " ".join(p for p in text_parts if p)
        search_entries.append({
            "objectID": f"{kind}:{law['file']}",
            "href": href,
            "title": law.get("tittel", ""),
            "section": dept_str,
            "text": text,
        })

    with open(search_path, "w", encoding="utf-8") as f:
        json.dump(search_entries, f, ensure_ascii=False)

    print(f"  Search index: {existing_count} → {len(search_entries)} entries (+{len(laws)} laws)")


if __name__ == "__main__":
    site = sys.argv[1] if len(sys.argv) > 1 else "_site"
    laws = sys.argv[2] if len(sys.argv) > 2 else "laws.json"
    merge_laws_into_search(site, laws)
