# Nærings- og fiskeridepartementet

*604 forskrifter*

| Forskrift | Lovdata | Historikk |
|-----------|---------|-----------|
| [Bergverksordning for Spitsbergen (Svalbard) fremlagt av den norske regjering.](/norwegian-laws/forskrifter/forskrift-1925-08-07-3767.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1925-08-07-3767) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1925-08-07-3767.md) |
| [Forskrift 25. juni 1971 nr. 9 om tillatelse for utenlandske fiskefartøy til fisk](/norwegian-laws/forskrifter/forskrift-1971-06-25-9.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1971-06-25-9) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1971-06-25-9.md) |
| [Forskrift for definisjon av begrepet olje og oljeholdig blanding i lov om vern m](/norwegian-laws/forskrifter/forskrift-1974-06-18-3650.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1974-06-18-3650) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1974-06-18-3650.md) |
| [Forskrift for flyttbare innretninger med produksjonstekniske installasjoner og u](/norwegian-laws/forskrifter/forskrift-1994-02-10-123.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1994-02-10-123) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1994-02-10-123.md) |
| [Forskrift for garantiordningen for fiskere](/norwegian-laws/forskrifter/forskrift-1990-01-26-68.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1990-01-26-68) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1990-01-26-68.md) |
| [Forskrift for implementering av rådsforordning (EU) 2020/699 av 25. mai 2020 om ](/norwegian-laws/forskrifter/forskrift-2023-05-02-645.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-05-02-645) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-05-02-645.md) |
| [Forskrift for meklingsnemnda for arbeidstakeroppfinnelser](/norwegian-laws/forskrifter/forskrift-1973-04-06-9740.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1973-04-06-9740) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1973-04-06-9740.md) |
| [Forskrift om Akvakulturregisteret (A-registerforskriften).](/norwegian-laws/forskrifter/forskrift-2005-12-28-1706.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2005-12-28-1706) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2005-12-28-1706.md) |
| [Forskrift om EU-gjødselvarer (EU-gjødselvareforskriften)](/norwegian-laws/forskrifter/forskrift-2024-03-06-538.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-03-06-538) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-03-06-538.md) |
| [Forskrift om EØS-prosedyreregler for offentlig støtte](/norwegian-laws/forskrifter/forskrift-2023-01-02-3.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-01-02-3) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-01-02-3.md) |
| [Forskrift om Kystverkets støtte til Forsvaret (krigsnavigasjonsforskriften)](/norwegian-laws/forskrifter/forskrift-2024-12-13-3092.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-12-13-3092) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-12-13-3092.md) |
| [Forskrift om Prisdirektoratets organisasjon og virksomhet.](/norwegian-laws/forskrifter/forskrift-1964-03-06-8647.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1964-03-06-8647) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1964-03-06-8647.md) |
| [Forskrift om adgang til å delta i kystfartøygruppens fiske og enkelte andre fisk](/norwegian-laws/forskrifter/forskrift-2025-12-19-2811.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-12-19-2811) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-12-19-2811.md) |
| [Forskrift om adgang til å drive fiske og fangst i farvann underlagt annen stats ](/norwegian-laws/forskrifter/forskrift-2016-07-25-943.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2016-07-25-943) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2016-07-25-943.md) |
| [Forskrift om aksjeselskapers og allmennaksjeselskapers adgang til å yte finansie](/norwegian-laws/forskrifter/forskrift-2019-12-09-1698.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-12-09-1698) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-12-09-1698.md) |
| [Forskrift om allmenne prinsipper og krav i næringsmiddelregelverket (matlovsfors](/norwegian-laws/forskrifter/forskrift-2008-12-22-1620.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2008-12-22-1620) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2008-12-22-1620.md) |
| [Forskrift om animalske biprodukter som ikke er beregnet på konsum (animaliebipro](/norwegian-laws/forskrifter/forskrift-2016-09-14-1064.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2016-09-14-1064) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2016-09-14-1064.md) |
| [Forskrift om ansvar og oppgaver til nasjonale referanselaboratorier for salmonel](/norwegian-laws/forskrifter/forskrift-2008-01-02-16.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2008-01-02-16) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2008-01-02-16.md) |
| [Forskrift om anvendelse av helselover og -forskrifter for Svalbard og Jan Mayen](/norwegian-laws/forskrifter/forskrift-2015-06-22-747.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-06-22-747) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-06-22-747.md) |
| [Forskrift om anvendelse av lov 17. april 2009 nr. 19 om havner og farvann for el](/norwegian-laws/forskrifter/forskrift-2009-12-15-1549.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2009-12-15-1549) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2009-12-15-1549.md) |
| [Forskrift om arbeid og utplassering av ungdom på norske skip](/norwegian-laws/forskrifter/forskrift-2002-04-25-423.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2002-04-25-423) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2002-04-25-423.md) |
| [Forskrift om arbeids- og hviletid på fiskefartøy](/norwegian-laws/forskrifter/forskrift-2017-11-10-1758.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-11-10-1758) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-11-10-1758.md) |
| [Forskrift om arbeids- og hviletid på norske passasjer- og lasteskip mv.](/norwegian-laws/forskrifter/forskrift-2007-06-26-705.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2007-06-26-705) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2007-06-26-705.md) |
| [Forskrift om arbeidsavtale og lønnsoppgave mv. [skipsarbeid]](/norwegian-laws/forskrifter/forskrift-2013-08-19-1000.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-08-19-1000) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-08-19-1000.md) |
| [Forskrift om arbeidsmiljø, sikkerhet og helse for de som har sitt arbeid om bord](/norwegian-laws/forskrifter/forskrift-2005-01-01-8.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2005-01-01-8) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2005-01-01-8.md) |
| [Forskrift om auke av maksimalt tillaten biomasse for løyve til akvakultur med la](/norwegian-laws/forskrifter/forskrift-2015-06-17-817.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-06-17-817) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-06-17-817.md) |
| [Forskrift om avgift til forskning og utvikling i fiskeri- og havbruksnæringen](/norwegian-laws/forskrifter/forskrift-2018-09-05-1320.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2018-09-05-1320) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2018-09-05-1320.md) |
| [Forskrift om avliving av dyr](/norwegian-laws/forskrifter/forskrift-2013-01-13-60.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-01-13-60) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-01-13-60.md) |
| [Forskrift om avsiling av vann og prøvetaking mv. av industrifangster ved landing](/norwegian-laws/forskrifter/forskrift-2023-08-08-1311.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-08-08-1311) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-08-08-1311.md) |
| [Forskrift om ballastsystem på flyttbare innretninger (ballastforskriften)](/norwegian-laws/forskrifter/forskrift-2016-01-27-67.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2016-01-27-67) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2016-01-27-67.md) |
| [Forskrift om ballastvannbehandling på skip og flyttbare innretninger](/norwegian-laws/forskrifter/forskrift-2017-09-08-1368.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-09-08-1368) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-09-08-1368.md) |
| [Forskrift om begrensninger i fisket etter torsk, rognkjeks, makrell, kveite og k](/norwegian-laws/forskrifter/forskrift-2010-02-26-252.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2010-02-26-252) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2010-02-26-252.md) |
| [Forskrift om behandling av saker for Konkurranseklagenemnda](/norwegian-laws/forskrifter/forskrift-2018-12-14-2031.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2018-12-14-2031) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2018-12-14-2031.md) |
| [Forskrift om bekjempelse av lakselus i akvakulturanlegg](/norwegian-laws/forskrifter/forskrift-2012-12-05-1140.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2012-12-05-1140) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2012-12-05-1140.md) |
| [Forskrift om bemanning av flyttbare innretninger](/norwegian-laws/forskrifter/forskrift-1996-04-01-319.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1996-04-01-319) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1996-04-01-319.md) |
| [Forskrift om bemanning av norske skip (bemanningsforskriften 2009)](/norwegian-laws/forskrifter/forskrift-2009-06-18-666.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2009-06-18-666) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2009-06-18-666.md) |
| [Forskrift om beredskapsfartøy](/norwegian-laws/forskrifter/forskrift-1991-10-16-853.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1991-10-16-853) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1991-10-16-853.md) |
| [Forskrift om beredskapslagring av petroleumsprodukt.](/norwegian-laws/forskrifter/forskrift-2006-09-01-1019.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2006-09-01-1019) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2006-09-01-1019.md) |
| [Forskrift om beregning og innbetaling av produktavgift](/norwegian-laws/forskrifter/forskrift-1998-12-11-1390.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1998-12-11-1390) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1998-12-11-1390.md) |
| [Forskrift om besiktelse, bygging og utrustning av passasjerskip i innenriksfart](/norwegian-laws/forskrifter/forskrift-2000-03-28-305.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2000-03-28-305) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2000-03-28-305.md) |
| [Forskrift om beskyttelse av korallrev mot ødeleggelser som følge av fiskeriaktiv](/norwegian-laws/forskrifter/forskrift-2016-01-08-8.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2016-01-08-8) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2016-01-08-8.md) |
| [Forskrift om beskyttelse av opprinnelsesbetegnelser, geografiske betegnelser og ](/norwegian-laws/forskrifter/forskrift-2002-07-05-698.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2002-07-05-698) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2002-07-05-698.md) |
| [Forskrift om betalinger mv. til Patentstyret og Klagenemnda for industrielle ret](/norwegian-laws/forskrifter/forskrift-2014-03-26-333.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2014-03-26-333) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2014-03-26-333.md) |
| [Forskrift om brannsikring på skip](/norwegian-laws/forskrifter/forskrift-2014-07-01-1099.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2014-07-01-1099) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2014-07-01-1099.md) |
| [Forskrift om bruk av arbeidsformidlingsvirksomhet på skip](/norwegian-laws/forskrifter/forskrift-2013-08-19-999.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-08-19-999) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-08-19-999.md) |
| [Forskrift om bruk av fartøy i oljevern](/norwegian-laws/forskrifter/forskrift-2011-02-08-130.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2011-02-08-130) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2011-02-08-130.md) |
| [Forskrift om bruk av sjøtrafikksentralenes tjenesteområde og bruk av bestemte fa](/norwegian-laws/forskrifter/forskrift-2021-02-10-523.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-02-10-523) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-02-10-523.md) |
| [Forskrift om bruk av skipsarrest om bord på norske skip](/norwegian-laws/forskrifter/forskrift-2009-08-06-1032.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2009-08-06-1032) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2009-08-06-1032.md) |
| [Forskrift om bruk av sorteringsristsystem i fiske med stormasket trål](/norwegian-laws/forskrifter/forskrift-2010-12-20-1786.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2010-12-20-1786) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2010-12-20-1786.md) |
| [Forskrift om bruk av tvangsmulkt og overtredelsesgebyr ved brudd på havressurslo](/norwegian-laws/forskrifter/forskrift-2011-12-20-1437.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2011-12-20-1437) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2011-12-20-1437.md) |
| [Forskrift om bygg- og anleggsberedskap](/norwegian-laws/forskrifter/forskrift-2013-06-28-807.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-06-28-807) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-06-28-807.md) |
| [Forskrift om bygging av fiske- og fangstfartøy med lengde på 15 m Loa og derover](/norwegian-laws/forskrifter/forskrift-1991-10-15-712.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1991-10-15-712) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1991-10-15-712.md) |
| [Forskrift om bygging av fiske- og fangstfartøyer.](/norwegian-laws/forskrifter/forskrift-1983-01-07-12.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1983-01-07-12) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1983-01-07-12.md) |
| [Forskrift om bygging av flyttbare innretninger](/norwegian-laws/forskrifter/forskrift-1987-09-04-856.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1987-09-04-856) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1987-09-04-856.md) |
| [Forskrift om bygging av skip](/norwegian-laws/forskrifter/forskrift-2014-07-01-1072.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2014-07-01-1072) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2014-07-01-1072.md) |
| [Forskrift om bygging, utrustning og drift av hurtiggående fartøy som anvendes so](/norwegian-laws/forskrifter/forskrift-1998-01-05-6.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1998-01-05-6) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1998-01-05-6.md) |
| [Forskrift om bygging, utrustning og drift av skip i territorialfarvannet ved Sva](/norwegian-laws/forskrifter/forskrift-2019-06-07-710.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-06-07-710) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-06-07-710.md) |
| [Forskrift om bygging, utrustning og tilsyn av mindre lasteskip](/norwegian-laws/forskrifter/forskrift-2025-12-16-2652.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-12-16-2652) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-12-16-2652.md) |
| [Forskrift om bytte av vassildkvote for årene 2026 og 2027 for fartøy med vassild](/norwegian-laws/forskrifter/forskrift-2025-12-18-2690.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-12-18-2690) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-12-18-2690.md) |
| [Forskrift om dagpenger for fiskere og fangstfolk under arbeidsløshet (A-trygdfor](/norwegian-laws/forskrifter/forskrift-2011-06-01-565.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2011-06-01-565) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2011-06-01-565.md) |
| [Forskrift om delvis unntak fra gjennomføringsforbudet i konkurranseloven § 19 fø](/norwegian-laws/forskrifter/forskrift-2009-03-09-292.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2009-03-09-292) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2009-03-09-292.md) |
| [Forskrift om den offentlige kontrollen med bruken av farmakologisk virksomme sto](/norwegian-laws/forskrifter/forskrift-2020-03-04-705.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-03-04-705) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-03-04-705.md) |
| [Forskrift om desinfeksjon av inntaksvann til og avløpsvann fra akvakulturrelater](/norwegian-laws/forskrifter/forskrift-1997-02-20-192.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1997-02-20-192) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1997-02-20-192.md) |
| [Forskrift om det alminnelige prisreguleringsfond.](/norwegian-laws/forskrifter/forskrift-1992-01-24-4316.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1992-01-24-4316) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1992-01-24-4316.md) |
| [Forskrift om det europeiske sjøsikkerhetsbyrået EMSA (European Maritime Safety A](/norwegian-laws/forskrifter/forskrift-2011-03-11-271.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2011-03-11-271) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2011-03-11-271.md) |
| [Forskrift om dispensasjon fra konkurranseloven § 3-1 og § 3-2 for drosjesentrale](/norwegian-laws/forskrifter/forskrift-2002-10-18-1165.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2002-10-18-1165) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2002-10-18-1165.md) |
| [Forskrift om drift av akvakulturanlegg (akvakulturdriftsforskriften)](/norwegian-laws/forskrifter/forskrift-2008-06-17-822.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2008-06-17-822) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2008-06-17-822.md) |
| [Forskrift om driftsordninger på norske skip.](/norwegian-laws/forskrifter/forskrift-1992-09-15-704.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1992-09-15-704) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1992-09-15-704.md) |
| [Forskrift om drikkevann og drikkevannsanlegg på flyttbare innretninger](/norwegian-laws/forskrifter/forskrift-2015-12-04-1406.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-12-04-1406) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-12-04-1406.md) |
| [Forskrift om dykking fra skip](/norwegian-laws/forskrifter/forskrift-2020-04-27-876.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-04-27-876) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-04-27-876.md) |
| [Forskrift om dyrehelse (dyrehelseforskriften)](/norwegian-laws/forskrifter/forskrift-2022-04-06-631.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-04-06-631) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-04-06-631.md) |
| [Forskrift om dyrevelferd ved fremvisning av dyr](/norwegian-laws/forskrifter/forskrift-2016-09-05-1035.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2016-09-05-1035) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2016-09-05-1035.md) |
| [Forskrift om eksport av næringsmidler, animaliebiprodukter, fôrvarer, levende dy](/norwegian-laws/forskrifter/forskrift-2020-06-18-1547.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-06-18-1547) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-06-18-1547.md) |
| [Forskrift om elektronisk rapportering for utenlandske fiske- og fangstfartøy i N](/norwegian-laws/forskrifter/forskrift-2010-08-31-1231.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2010-08-31-1231) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2010-08-31-1231.md) |
| [Forskrift om elektronisk stiftelse og registrering av aksjeselskaper og om elekt](/norwegian-laws/forskrifter/forskrift-2025-08-06-1612.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-08-06-1612) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-08-06-1612.md) |
| [Forskrift om elektroniske skjema for kunngjøringer om offentlige anskaffelser (e](/norwegian-laws/forskrifter/forskrift-2025-06-21-1437.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-06-21-1437) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-06-21-1437.md) |
| [Forskrift om endring av forskrift om landings- og sluttseddel (landingsforskrift](/norwegian-laws/forskrifter/forskrift-2026-02-03-128.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2026-02-03-128) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2026-02-03-128.md) |
| [Forskrift om endring i ERS-forskriften og opphevelse av forskrift om kystfiskeap](/norwegian-laws/forskrifter/forskrift-2025-12-01-2374.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-12-01-2374) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-12-01-2374.md) |
| [Forskrift om endring i forskrift for flyttbare innretninger med produksjonstekni](/norwegian-laws/forskrifter/forskrift-1997-02-18-234.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1997-02-18-234) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1997-02-18-234.md) |
| [Forskrift om endring i forskrift om statlige fartsgrenser på sjøen](/norwegian-laws/forskrifter/forskrift-2023-06-21-1009.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-06-21-1009) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-06-21-1009.md) |
| [Forskrift om endring i forskrift om terskelverdier for beslutning om å unnlate r](/norwegian-laws/forskrifter/forskrift-2023-02-13-186.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-02-13-186) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-02-13-186.md) |
| [Forskrift om endring i forskrifter til anskaffelsesloven](/norwegian-laws/forskrifter/forskrift-2026-04-14-617.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2026-04-14-617) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2026-04-14-617.md) |
| [Forskrift om erstatning for tapte eiendeler](/norwegian-laws/forskrifter/forskrift-1986-02-03-241.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1986-02-03-241) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1986-02-03-241.md) |
| [Forskrift om ervervstillatelse, registrering og merking av fiskefartøy mv. (erve](/norwegian-laws/forskrifter/forskrift-2012-12-07-1144.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2012-12-07-1144) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2012-12-07-1144.md) |
| [Forskrift om et råd for drivstoffberedskap og drivstoffnæringens beredskapsplikt](/norwegian-laws/forskrifter/forskrift-2018-06-29-1104.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2018-06-29-1104) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2018-06-29-1104.md) |
| [Forskrift om etablererprøve for daglig leder av serveringssted](/norwegian-laws/forskrifter/forskrift-2000-01-18-46.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2000-01-18-46) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2000-01-18-46.md) |
| [Forskrift om etablering og utvidelse av akvakulturanlegg, zoobutikker m.m.](/norwegian-laws/forskrifter/forskrift-2008-06-17-823.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2008-06-17-823) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2008-06-17-823.md) |
| [Forskrift om evakuerings- og redningsredskaper på flyttbare innretninger](/norwegian-laws/forskrifter/forskrift-2016-02-02-90.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2016-02-02-90) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2016-02-02-90.md) |
| [Forskrift om fangst av fisk som skal holdes levende, samt restitusjon og melloml](/norwegian-laws/forskrifter/forskrift-2021-12-23-3891.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-12-23-3891) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-12-23-3891.md) |
| [Forskrift om fangst av kongekrabbe utenfor kvoteregulert område](/norwegian-laws/forskrifter/forskrift-2004-08-06-1147.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2004-08-06-1147) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2004-08-06-1147.md) |
| [Forskrift om fangst av ål](/norwegian-laws/forskrifter/forskrift-2011-12-20-1463.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2011-12-20-1463) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2011-12-20-1463.md) |
| [Forskrift om fangstbasert akvakultur](/norwegian-laws/forskrifter/forskrift-2014-12-15-1831.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2014-12-15-1831) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2014-12-15-1831.md) |
| [Forskrift om fangstdokument som skal benyttes ved fiske og overføring av patagon](/norwegian-laws/forskrifter/forskrift-2000-04-18-414.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2000-04-18-414) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2000-04-18-414.md) |
| [Forskrift om fangstdokumentasjon for makrellstørje (Thunnus thynnus), storøyet t](/norwegian-laws/forskrifter/forskrift-2009-03-20-332.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2009-03-20-332) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2009-03-20-332.md) |
| [Forskrift om fangstdokumentasjon ved fiske etter patagonisk tannfisk (Dissostich](/norwegian-laws/forskrifter/forskrift-2000-01-06-6.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2000-01-06-6) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2000-01-06-6.md) |
| [Forskrift om fangstdokumentasjon ved import, eksport og re-eksport av patagonisk](/norwegian-laws/forskrifter/forskrift-2000-01-06-7.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2000-01-06-7) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2000-01-06-7.md) |
| [Forskrift om fangstsertifikat mv.](/norwegian-laws/forskrifter/forskrift-2009-12-18-1693.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2009-12-18-1693) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2009-12-18-1693.md) |
| [Forskrift om farleder (farledsforskriften)](/norwegian-laws/forskrifter/forskrift-2019-12-11-1834.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-12-11-1834) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-12-11-1834.md) |
| [Forskrift om farlig last på norske skip](/norwegian-laws/forskrifter/forskrift-2014-07-01-944.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2014-07-01-944) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2014-07-01-944.md) |
| [Forskrift om fartsgrenser på sjøen](/norwegian-laws/forskrifter/forskrift-2021-04-19-1214.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-04-19-1214) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-04-19-1214.md) |
| [Forskrift om fartsområde for lasteskip registrert i norsk internasjonalt skipsre](/norwegian-laws/forskrifter/forskrift-1989-08-11-802.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1989-08-11-802) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1989-08-11-802.md) |
| [Forskrift om fartsområder](/norwegian-laws/forskrifter/forskrift-1981-11-04-3793.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1981-11-04-3793) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1981-11-04-3793.md) |
| [Forskrift om fartøy som blir brukte av lag eller foreiningar](/norwegian-laws/forskrifter/forskrift-2022-09-21-1628.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-09-21-1628) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-09-21-1628.md) |
| [Forskrift om fartøy som blir brukte av opplæringsinstitusjonar](/norwegian-laws/forskrifter/forskrift-2022-09-21-1627.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-09-21-1627) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-09-21-1627.md) |
| [Forskrift om fartøy under 24 meter som fører 12 eller færre passasjerer](/norwegian-laws/forskrifter/forskrift-2020-01-14-63.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-01-14-63) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-01-14-63.md) |
| [Forskrift om fartøys meldeplikter etter havne- og farvannsloven](/norwegian-laws/forskrifter/forskrift-2015-12-21-1790.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-12-21-1790) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-12-21-1790.md) |
| [Forskrift om farvannsskilt og navigasjonsinnretninger](/norwegian-laws/forskrifter/forskrift-2012-12-19-1329.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2012-12-19-1329) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2012-12-19-1329.md) |
| [Forskrift om fastlegging av utmålsgrenser på Svalbard.](/norwegian-laws/forskrifter/forskrift-1970-06-26-8939.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1970-06-26-8939) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1970-06-26-8939.md) |
| [Forskrift om fastsettelse av metoder for prøvetaking og analyse i forbindelse me](/norwegian-laws/forskrifter/forskrift-2020-02-28-702.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-02-28-702) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-02-28-702.md) |
| [Forskrift om fastsettelse av tvangsmulkt i henhold til skipssikkerhetsloven § 50](/norwegian-laws/forskrifter/forskrift-2008-12-31-1587.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2008-12-31-1587) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2008-12-31-1587.md) |
| [Forskrift om fastsettelse av tvangsmulkt i medhold av lov om offentlige anskaffe](/norwegian-laws/forskrifter/forskrift-2016-12-22-1842.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2016-12-22-1842) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2016-12-22-1842.md) |
| [Forskrift om fellesansvar for utfisking mv. av rømt oppdrettsfisk](/norwegian-laws/forskrifter/forskrift-2015-02-05-89.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-02-05-89) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-02-05-89.md) |
| [Forskrift om ferie for arbeidstakere på skip](/norwegian-laws/forskrifter/forskrift-1989-12-22-1285.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1989-12-22-1285) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1989-12-22-1285.md) |
| [Forskrift om fiske etter reker med fartøy fra Canada i Svalbards territorialfarv](/norwegian-laws/forskrifter/forskrift-1996-07-19-736.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1996-07-19-736) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1996-07-19-736.md) |
| [Forskrift om fiske etter reker med fartøy fra Canada i fiskevernsonen ved Svalba](/norwegian-laws/forskrifter/forskrift-1996-07-19-727.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1996-07-19-727) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1996-07-19-727.md) |
| [Forskrift om fiske etter reker med fartøy fra Færøyene i Svalbards territorialfa](/norwegian-laws/forskrifter/forskrift-1996-07-19-739.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1996-07-19-739) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1996-07-19-739.md) |
| [Forskrift om fiske etter reker med fartøy fra Færøyene i fiskevernsonen ved Sval](/norwegian-laws/forskrifter/forskrift-1996-07-19-730.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1996-07-19-730) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1996-07-19-730.md) |
| [Forskrift om fiske etter reker med fartøy fra Grønland i Svalbards territorialfa](/norwegian-laws/forskrifter/forskrift-1996-07-19-740.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1996-07-19-740) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1996-07-19-740.md) |
| [Forskrift om fiske etter reker med fartøy fra Grønland i fiskevernsonen ved Sval](/norwegian-laws/forskrifter/forskrift-1996-07-19-731.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1996-07-19-731) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1996-07-19-731.md) |
| [Forskrift om fiske etter reker med fartøy fra Island i Svalbards territorialfarv](/norwegian-laws/forskrifter/forskrift-1996-07-19-741.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1996-07-19-741) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1996-07-19-741.md) |
| [Forskrift om fiske etter reker med fartøy fra Island i fiskevernsonen ved Svalba](/norwegian-laws/forskrifter/forskrift-1996-07-19-732.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1996-07-19-732) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1996-07-19-732.md) |
| [Forskrift om fiske etter reker med fartøy fra Norge i Svalbards territorialfarva](/norwegian-laws/forskrifter/forskrift-1996-07-19-743.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1996-07-19-743) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1996-07-19-743.md) |
| [Forskrift om fiske etter reker med fartøy fra Norge i fiskevernsonen ved Svalbar](/norwegian-laws/forskrifter/forskrift-1996-07-19-734.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1996-07-19-734) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1996-07-19-734.md) |
| [Forskrift om fiske etter reker med fartøy fra Russland i Svalbards territorialfa](/norwegian-laws/forskrifter/forskrift-1997-05-09-447.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1997-05-09-447) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1997-05-09-447.md) |
| [Forskrift om fiske etter reker med fartøy fra Russland i fiskevernsonen ved Sval](/norwegian-laws/forskrifter/forskrift-1997-05-09-446.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1997-05-09-446) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1997-05-09-446.md) |
| [Forskrift om fiske etter reker med fartøy fra medlemsstater i Det europeiske fel](/norwegian-laws/forskrifter/forskrift-1996-07-19-742.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1996-07-19-742) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1996-07-19-742.md) |
| [Forskrift om fiske etter reker med fartøy fra medlemsstater i Det europeiske fel](/norwegian-laws/forskrifter/forskrift-1996-07-19-733.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1996-07-19-733) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1996-07-19-733.md) |
| [Forskrift om fiske etter reker – stenging av områder i fiskevernsonen ved Svalba](/norwegian-laws/forskrifter/forskrift-2000-09-20-1697.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2000-09-20-1697) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2000-09-20-1697.md) |
| [Forskrift om fiske med landnot ved fiske med fartøy som ikke er merkeregistrert](/norwegian-laws/forskrifter/forskrift-2011-02-10-593.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2011-02-10-593) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2011-02-10-593.md) |
| [Forskrift om fiskefartøy med største lengde under 15 meter](/norwegian-laws/forskrifter/forskrift-2013-11-22-1404.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-11-22-1404) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-11-22-1404.md) |
| [Forskrift om flyselskapenes plikt til å melde inn billettpriser.](/norwegian-laws/forskrifter/forskrift-1998-11-02-1050.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1998-11-02-1050) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1998-11-02-1050.md) |
| [Forskrift om flyteutstyr om bord på fritidsfartøy.](/norwegian-laws/forskrifter/forskrift-1995-05-08-409.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1995-05-08-409) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1995-05-08-409.md) |
| [Forskrift om forbud mot fangst av Ross-sel.](/norwegian-laws/forskrifter/forskrift-1968-07-05-1.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1968-07-05-1) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1968-07-05-1.md) |
| [Forskrift om forbud mot fangst av pelssel og sjøelefanter på Bouvetøya og Peter ](/norwegian-laws/forskrifter/forskrift-1953-02-27-3.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1953-02-27-3) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1953-02-27-3.md) |
| [Forskrift om forbud mot fiske i gytefelt for torsk](/norwegian-laws/forskrifter/forskrift-2019-03-25-321.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-03-25-321) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-03-25-321.md) |
| [Forskrift om forbud mot fiske i gyteområder for torsk i Norges økonomiske sone s](/norwegian-laws/forskrifter/forskrift-2025-12-19-2806.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-12-19-2806) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-12-19-2806.md) |
| [Forskrift om forbud mot fiske og fangst av brugde, pigghå, håbrann og silkehai](/norwegian-laws/forskrifter/forskrift-2013-12-13-1507.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-12-13-1507) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-12-13-1507.md) |
| [Forskrift om forbud mot fisket etter lodde i Barentshavet i 2026](/norwegian-laws/forskrifter/forskrift-2025-12-17-2640.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-12-17-2640) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-12-17-2640.md) |
| [Forskrift om forbud mot fisket etter torsk og hyse i fiskerisonen ved Jan Mayen](/norwegian-laws/forskrifter/forskrift-2018-12-20-2217.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2018-12-20-2217) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2018-12-20-2217.md) |
| [Forskrift om forbud mot høsting av haneskjell og sjøpølse](/norwegian-laws/forskrifter/forskrift-2019-10-18-1385.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-10-18-1385) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-10-18-1385.md) |
| [Forskrift om forbud mot landing av fisk og andre særskilte tiltak mot ulovlig, u](/norwegian-laws/forskrifter/forskrift-1993-08-06-802.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1993-08-06-802) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1993-08-06-802.md) |
| [Forskrift om forbud mot negative servitutter som begrenser etablering av dagligv](/norwegian-laws/forskrifter/forskrift-2023-12-11-2037.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-12-11-2037) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-12-11-2037.md) |
| [Forskrift om forbud mot omlasting av og ilandføring i norsk havn av pelagisk sna](/norwegian-laws/forskrifter/forskrift-2023-06-23-1095.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-06-23-1095) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-06-23-1095.md) |
| [Forskrift om forbud mot utslipp av kloakk fra fritidsbåter i Oslofjorden](/norwegian-laws/forskrifter/forskrift-2024-05-31-886.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-05-31-886) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-05-31-886.md) |
| [Forskrift om forbud mot å fiske blåkveite i fiskevernsonen ved Svalbard](/norwegian-laws/forskrifter/forskrift-2010-12-02-1524.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2010-12-02-1524) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2010-12-02-1524.md) |
| [Forskrift om forbud mot å fiske blåkveite i territorialfarvannet ved Svalbard](/norwegian-laws/forskrifter/forskrift-2010-12-02-1518.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2010-12-02-1518) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2010-12-02-1518.md) |
| [Forskrift om forbud mot å fiske lodde i Svalbards territorialfarvann](/norwegian-laws/forskrifter/forskrift-2011-12-13-1331.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2011-12-13-1331) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2011-12-13-1331.md) |
| [Forskrift om forbud mot å fiske lodde i fiskevernsonen ved Svalbard](/norwegian-laws/forskrifter/forskrift-2011-12-13-1332.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2011-12-13-1332) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2011-12-13-1332.md) |
| [Forskrift om forbud mot å fiske norsk vårgytende sild i fiskevernsonen ved Svalb](/norwegian-laws/forskrifter/forskrift-2025-12-22-2833.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-12-22-2833) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-12-22-2833.md) |
| [Forskrift om forbud mot å fiske norsk vårgytende sild i territorialfarvannet ved](/norwegian-laws/forskrifter/forskrift-2025-12-22-2832.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-12-22-2832) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-12-22-2832.md) |
| [Forskrift om forbud mot å fiske reker i NAFO-området](/norwegian-laws/forskrifter/forskrift-2024-12-18-3383.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-12-18-3383) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-12-18-3383.md) |
| [Forskrift om forbud mot å gjennomføre grensekryssende fiskeoperasjoner mv.](/norwegian-laws/forskrifter/forskrift-2024-12-11-3049.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-12-11-3049) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-12-11-3049.md) |
| [Forskrift om forebygging av sammenstøt på sjøen (Sjøveisreglene)](/norwegian-laws/forskrifter/forskrift-1975-12-01-5.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1975-12-01-5) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1975-12-01-5.md) |
| [Forskrift om forebygging av, kontroll med og utryddelse av overførbare spongifor](/norwegian-laws/forskrifter/forskrift-2004-03-30-595.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2004-03-30-595) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2004-03-30-595.md) |
| [Forskrift om forskottserstatning ved skade på fiskeredskaper forårsaket av utenl](/norwegian-laws/forskrifter/forskrift-1988-01-25-111.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1988-01-25-111) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1988-01-25-111.md) |
| [Forskrift om fortegnelse over fremmedstoffer som omfattes av matloven.](/norwegian-laws/forskrifter/forskrift-2001-03-28-357.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2001-03-28-357) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2001-03-28-357.md) |
| [Forskrift om forvalter](/norwegian-laws/forskrifter/forskrift-2008-09-15-1021.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2008-09-15-1021) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2008-09-15-1021.md) |
| [Forskrift om frakt av last på norske skip og lektere](/norwegian-laws/forskrifter/forskrift-2014-07-01-945.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2014-07-01-945) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2014-07-01-945.md) |
| [Forskrift om fredningsområder for hummer](/norwegian-laws/forskrifter/forskrift-2006-07-06-883.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2006-07-06-883) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2006-07-06-883.md) |
| [Forskrift om fremstilling for kontroll for utenlandske fartøy som driver fiske i](/norwegian-laws/forskrifter/forskrift-2005-07-19-1834.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2005-07-19-1834) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2005-07-19-1834.md) |
| [Forskrift om fôrhygiene](/norwegian-laws/forskrifter/forskrift-2010-01-14-39.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2010-01-14-39) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2010-01-14-39.md) |
| [Forskrift om fôrvarer](/norwegian-laws/forskrifter/forskrift-2002-11-07-1290.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2002-11-07-1290) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2002-11-07-1290.md) |
| [Forskrift om førstehandsomsetning av viltlevande marine ressursar](/norwegian-laws/forskrifter/forskrift-2013-12-20-1665.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-12-20-1665) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-12-20-1665.md) |
| [Forskrift om garanti for arbeidsvederlag og hjemreise for arbeidstakere på flytt](/norwegian-laws/forskrifter/forskrift-2005-02-18-146.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2005-02-18-146) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2005-02-18-146.md) |
| [Forskrift om garanti for trygderettigheter for arbeidstakere på norske skip](/norwegian-laws/forskrifter/forskrift-2005-02-18-145.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2005-02-18-145) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2005-02-18-145.md) |
| [Forskrift om gebyr for tjenester som utføres av Sjøfartsdirektoratet (Sjøfartsdi](/norwegian-laws/forskrifter/forskrift-2009-12-21-1738.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2009-12-21-1738) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2009-12-21-1738.md) |
| [Forskrift om gebyr for utstedelse av sertifikater og påtegninger til maritimt pe](/norwegian-laws/forskrifter/forskrift-2009-12-21-1739.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2009-12-21-1739) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2009-12-21-1739.md) |
| [Forskrift om gebyr og avgift i forbindelse med akvakulturvirksomhet](/norwegian-laws/forskrifter/forskrift-2001-12-21-1597.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2001-12-21-1597) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2001-12-21-1597.md) |
| [Forskrift om gebyr til Brønnøysundregistrene](/norwegian-laws/forskrifter/forskrift-2015-12-11-1668.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-12-11-1668) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-12-11-1668.md) |
| [Forskrift om gebyr til Mattilsynet](/norwegian-laws/forskrifter/forskrift-2026-04-27-745.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2026-04-27-745) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2026-04-27-745.md) |
| [Forskrift om gebyrer for Norsk akkrediterings tjenester](/norwegian-laws/forskrifter/forskrift-2021-07-19-2432.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-07-19-2432) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-07-19-2432.md) |
| [Forskrift om gebyrer for utstedelse av radiooperatørsertifikat og lisenser til s](/norwegian-laws/forskrifter/forskrift-2025-12-10-2852.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-12-10-2852) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-12-10-2852.md) |
| [Forskrift om gebyrer for utstedelse av radiooperatørsertifikater.](/norwegian-laws/forskrifter/forskrift-1991-12-20-846.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1991-12-20-846) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1991-12-20-846.md) |
| [Forskrift om gjennomføring av Europaparlaments- og rådsforordning (EU) 2017/352 ](/norwegian-laws/forskrifter/forskrift-2019-06-11-861.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-06-11-861) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-06-11-861.md) |
| [Forskrift om gjennomføring av EØS-avtalen vedlegg XVI punkt 6 (Rfo EØF/Euratom n](/norwegian-laws/forskrifter/forskrift-1992-12-04-910.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1992-12-04-910) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1992-12-04-910.md) |
| [Forskrift om gjennomføring av fiske, fangst og høsting av viltlevende marine res](/norwegian-laws/forskrifter/forskrift-2021-12-23-3910.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-12-23-3910) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-12-23-3910.md) |
| [Forskrift om gjennomføring av forordning (EF) nr. 136/2004 om fastsettelse av fr](/norwegian-laws/forskrifter/forskrift-2005-11-30-1347.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2005-11-30-1347) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2005-11-30-1347.md) |
| [Forskrift om gjennomføring av forordning (EF) nr. 599/2004 om vedtakelse av en h](/norwegian-laws/forskrifter/forskrift-2005-11-30-1349.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2005-11-30-1349) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2005-11-30-1349.md) |
| [Forskrift om gjennomføring av forordning (EF) nr. 745/2004 om fastsettelse av ti](/norwegian-laws/forskrifter/forskrift-2006-01-31-103.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2006-01-31-103) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2006-01-31-103.md) |
| [Forskrift om gjennomføring av forordning (EU) nr. 1025/2012 av 25. oktober 2012 ](/norwegian-laws/forskrifter/forskrift-2014-09-09-1164.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2014-09-09-1164) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2014-09-09-1164.md) |
| [Forskrift om gjennomføring av konkurransereglene i EØS-avtalen mv.](/norwegian-laws/forskrifter/forskrift-2011-12-21-1518.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2011-12-21-1518) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2011-12-21-1518.md) |
| [Forskrift om gjennomføring i norsk rett av forordning (EU) 2020/1668 om fastsett](/norwegian-laws/forskrifter/forskrift-2023-10-16-1635.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-10-16-1635) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-10-16-1635.md) |
| [Forskrift om gjennomføring i norsk rett av forordning (EU) nr. 1024/2012 om admi](/norwegian-laws/forskrifter/forskrift-2015-12-15-1729.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-12-15-1729) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-12-15-1729.md) |
| [Forskrift om godkjenning av annen utdanning i stedet for mesterutdanning](/norwegian-laws/forskrifter/forskrift-2015-04-09-418.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-04-09-418) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-04-09-418.md) |
| [Forskrift om godkjenning og bruk av desinfeksjonsmidler i akvakulturanlegg og tr](/norwegian-laws/forskrifter/forskrift-2008-06-17-821.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2008-06-17-821) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2008-06-17-821.md) |
| [Forskrift om grenseverdier for koksidiostatika eller histomonostatika i næringsm](/norwegian-laws/forskrifter/forskrift-2013-07-01-814.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-07-01-814) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-07-01-814.md) |
| [Forskrift om grenseverdier for legemiddelrester i næringsmidler fra dyr](/norwegian-laws/forskrifter/forskrift-2012-05-30-512.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2012-05-30-512) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2012-05-30-512.md) |
| [Forskrift om handelsverksemd med brukte eller kasserte ting mv.](/norwegian-laws/forskrifter/forskrift-1999-12-22-1379.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1999-12-22-1379) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1999-12-22-1379.md) |
| [Forskrift om havner og farvann på Svalbard](/norwegian-laws/forskrifter/forskrift-2021-03-12-721.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-03-12-721) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-03-12-721.md) |
| [Forskrift om havners beredskap for og støtte til Forsvaret under krig, krigsfare](/norwegian-laws/forskrifter/forskrift-2024-09-27-2307.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-09-27-2307) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-09-27-2307.md) |
| [Forskrift om havnestatskontroll](/norwegian-laws/forskrifter/forskrift-2014-11-24-1458.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2014-11-24-1458) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2014-11-24-1458.md) |
| [Forskrift om helikopterdekk på flyttbare innretninger](/norwegian-laws/forskrifter/forskrift-2021-03-18-815.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-03-18-815) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-03-18-815.md) |
| [Forskrift om helsesertifikater – akvatiske dyr og visse animalske produkter dera](/norwegian-laws/forskrifter/forskrift-2022-04-06-626.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-04-06-626) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-04-06-626.md) |
| [Forskrift om helsesertifikater – landdyr og avlsmateriale derav – forordning (EU](/norwegian-laws/forskrifter/forskrift-2022-04-06-627.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-04-06-627) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-04-06-627.md) |
| [Forskrift om helsesertifikater – næringsmidler og dyr – forordning (EU) 2020/223](/norwegian-laws/forskrifter/forskrift-2022-04-06-625.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-04-06-625) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-04-06-625.md) |
| [Forskrift om helseundersøkelse av arbeidstakere på norske skip og flyttbare innr](/norwegian-laws/forskrifter/forskrift-2014-06-05-805.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2014-06-05-805) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2014-06-05-805.md) |
| [Forskrift om helseundersøkelse av loser og losaspiranter](/norwegian-laws/forskrifter/forskrift-2018-12-20-2257.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2018-12-20-2257) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2018-12-20-2257.md) |
| [Forskrift om hvilke fag som er lagt under lov om mesterbrev i håndverk og annen ](/norwegian-laws/forskrifter/forskrift-2000-12-08-1281.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2000-12-08-1281) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2000-12-08-1281.md) |
| [Forskrift om høsting av hummer](/norwegian-laws/forskrifter/forskrift-2021-12-23-3890.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-12-23-3890) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-12-23-3890.md) |
| [Forskrift om høsting av krill og andre dyreplankton](/norwegian-laws/forskrifter/forskrift-2006-03-22-347.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2006-03-22-347) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2006-03-22-347.md) |
| [Forskrift om høsting av tang og tare](/norwegian-laws/forskrifter/forskrift-1995-07-13-642.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1995-07-13-642) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1995-07-13-642.md) |
| [Forskrift om høyeste midlertidige grenseverdier for radioaktiv forurensning i næ](/norwegian-laws/forskrifter/forskrift-2022-09-14-1580.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-09-14-1580) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-09-14-1580.md) |
| [Forskrift om ikrafttredelse av forskrift om endring i forskrift om sikkerhetstil](/norwegian-laws/forskrifter/forskrift-1995-05-09-466.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1995-05-09-466) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1995-05-09-466.md) |
| [Forskrift om import av toskallede bløtdyr, pigghuder, sekkdyr og sjøsnegler fra ](/norwegian-laws/forskrifter/forskrift-2020-11-20-2424.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-11-20-2424) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-11-20-2424.md) |
| [Forskrift om imøtegåelse av uberettiget geoblokkering og andre former for forskj](/norwegian-laws/forskrifter/forskrift-2020-12-04-2594.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-12-04-2594) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-12-04-2594.md) |
| [Forskrift om inndraging av fangst og bruk av inndregne midlar](/norwegian-laws/forskrifter/forskrift-2010-03-12-390.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2010-03-12-390) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2010-03-12-390.md) |
| [Forskrift om innføring av Bremnes-modellen som prøveordning i norsk lakse- og ør](/norwegian-laws/forskrifter/forskrift-2016-06-30-855.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2016-06-30-855) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2016-06-30-855.md) |
| [Forskrift om innføring av produktpatent på legemidler og næringsmidler på selve ](/norwegian-laws/forskrifter/forskrift-1989-10-13-1043.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1989-10-13-1043) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1989-10-13-1043.md) |
| [Forskrift om innførsel av næringsmidler og fôrvarer](/norwegian-laws/forskrifter/forskrift-1998-12-23-1471.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1998-12-23-1471) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1998-12-23-1471.md) |
| [Forskrift om innkjøpsregler i forsyningssektorene (forsyningsforskriften)](/norwegian-laws/forskrifter/forskrift-2016-08-12-975.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2016-08-12-975) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2016-08-12-975.md) |
| [Forskrift om innkreving av avgift til fiskeriforskning og overvåkning (fiskerifo](/norwegian-laws/forskrifter/forskrift-2013-12-17-1567.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-12-17-1567) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-12-17-1567.md) |
| [Forskrift om innkreving av kontrollavgift i fiskeflåten](/norwegian-laws/forskrifter/forskrift-2020-12-21-3090.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-12-21-3090) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-12-21-3090.md) |
| [Forskrift om innkvarteringsberedskap](/norwegian-laws/forskrifter/forskrift-2025-06-06-1410.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-06-06-1410) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-06-06-1410.md) |
| [Forskrift om innredning, rekreasjonstilbud, kost og forpleining på skip](/norwegian-laws/forskrifter/forskrift-2017-04-21-515.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-04-21-515) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-04-21-515.md) |
| [Forskrift om innretning og føring av dagbøker på skip og flyttbare innretninger](/norwegian-laws/forskrifter/forskrift-1992-09-15-693.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1992-09-15-693) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1992-09-15-693.md) |
| [Forskrift om innsamling og overføring av molekylære analytiske data ved utbrudd ](/norwegian-laws/forskrifter/forskrift-2026-03-17-426.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2026-03-17-426) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2026-03-17-426.md) |
| [Forskrift om innsyn i aksjeeierboken, aksjeeierregisteret og forvalterregistrert](/norwegian-laws/forskrifter/forskrift-2024-11-17-2804.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-11-17-2804) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-11-17-2804.md) |
| [Forskrift om internkontroll for å oppfylle akvakulturlovgivningen (IK-Akvakultur](/norwegian-laws/forskrifter/forskrift-2004-03-19-537.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2004-03-19-537) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2004-03-19-537.md) |
| [Forskrift om internkontroll for å oppfylle næringsmiddellovgivningen](/norwegian-laws/forskrifter/forskrift-1994-12-15-1187.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1994-12-15-1187) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1994-12-15-1187.md) |
| [Forskrift om iverksettelse av forbud mot lysfiske i Skagerrak uten observatør om](/norwegian-laws/forskrifter/forskrift-2012-01-03-8.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2012-01-03-8) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2012-01-03-8.md) |
| [Forskrift om kapasitetsjusteringer for tillatelser til akvakultur med matfisk i ](/norwegian-laws/forskrifter/forskrift-2020-02-04-105.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-02-04-105) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-02-04-105.md) |
| [Forskrift om kapasitetsjusteringer for tillatelser til akvakultur med matfisk i ](/norwegian-laws/forskrifter/forskrift-2022-06-07-972.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-06-07-972) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-06-07-972.md) |
| [Forskrift om kapasitetsjusteringer for tillatelser til akvakultur med matfisk i ](/norwegian-laws/forskrifter/forskrift-2024-03-22-515.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-03-22-515) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-03-22-515.md) |
| [Forskrift om kapasitetsøkning for tillatelser til akvakultur med matfisk i sjø a](/norwegian-laws/forskrifter/forskrift-2017-12-20-2397.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-12-20-2397) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-12-20-2397.md) |
| [Forskrift om kart over underjords- og dagbruddsanlegg](/norwegian-laws/forskrifter/forskrift-2010-12-20-1784.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2010-12-20-1784) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2010-12-20-1784.md) |
| [Forskrift om kartleggingsfisket etter torsk i fiskerisonen ved Jan Mayen i 2026](/norwegian-laws/forskrifter/forskrift-2026-04-23-639.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2026-04-23-639) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2026-04-23-639.md) |
| [Forskrift om klagenemnd for offentlige anskaffelser](/norwegian-laws/forskrifter/forskrift-2002-11-15-1288.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2002-11-15-1288) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2002-11-15-1288.md) |
| [Forskrift om klagerett for den som har sitt arbeid på skip](/norwegian-laws/forskrifter/forskrift-2013-08-19-998.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-08-19-998) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-08-19-998.md) |
| [Forskrift om kommunal beredskap mot akutt forurensning](/norwegian-laws/forskrifter/forskrift-2022-01-04-10.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-01-04-10) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-01-04-10.md) |
| [Forskrift om kommunenes beregning og innkreving av farvannsavgift (farvannsavgif](/norwegian-laws/forskrifter/forskrift-2019-12-11-1838.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-12-11-1838) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-12-11-1838.md) |
| [Forskrift om konkurranselovens anvendelse på Svalbard](/norwegian-laws/forskrifter/forskrift-2008-10-17-1126.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2008-10-17-1126) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2008-10-17-1126.md) |
| [Forskrift om konsesjonskontrakter (konsesjonskontraktforskriften)](/norwegian-laws/forskrifter/forskrift-2016-08-12-976.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2016-08-12-976) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2016-08-12-976.md) |
| [Forskrift om konsesjonsordning for fiske utenfor norsk fiskerijurisdiksjon](/norwegian-laws/forskrifter/forskrift-2007-03-02-232.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2007-03-02-232) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2007-03-02-232.md) |
| [Forskrift om konstruksjon og utrustning av boligkvarteret på flyttbare innretnin](/norwegian-laws/forskrifter/forskrift-1986-12-17-2318.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1986-12-17-2318) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1986-12-17-2318.md) |
| [Forskrift om konstruksjon, utstyr og drift av fiskefartøy med lengde 15 meter el](/norwegian-laws/forskrifter/forskrift-2000-06-13-660.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2000-06-13-660) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2000-06-13-660.md) |
| [Forskrift om kontroll av dykkesystem m.m. på norske skip i sjøen.](/norwegian-laws/forskrifter/forskrift-1984-04-10-940.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1984-04-10-940) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1984-04-10-940.md) |
| [Forskrift om kontroll av maritim tjeneste](/norwegian-laws/forskrifter/forskrift-1988-11-25-940.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1988-11-25-940) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1988-11-25-940.md) |
| [Forskrift om kontroll av rutegående roro- og hurtiggående passasjerskip](/norwegian-laws/forskrifter/forskrift-2025-06-24-1308.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-06-24-1308) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-06-24-1308.md) |
| [Forskrift om kontrolltiltak for restmengder av visse stoffer i animalske nærings](/norwegian-laws/forskrifter/forskrift-2000-01-27-65.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2000-01-27-65) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2000-01-27-65.md) |
| [Forskrift om kontrolltiltak overfor arbeidstakere som er omfattet av lov om stil](/norwegian-laws/forskrifter/forskrift-2019-01-25-53.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-01-25-53) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-01-25-53.md) |
| [Forskrift om kran og løft på flyttbare innretninger](/norwegian-laws/forskrifter/forskrift-2017-12-21-2381.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-12-21-2381) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-12-21-2381.md) |
| [Forskrift om kraner som brukes til lasting og lossing på skip i åpent farvann](/norwegian-laws/forskrifter/forskrift-1986-01-13-31.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1986-01-13-31) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1986-01-13-31.md) |
| [Forskrift om krav for å beskytte fiske-, dyre- og plantehelse i forbindelse med ](/norwegian-laws/forskrifter/forskrift-2025-11-21-2316.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-11-21-2316) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-11-21-2316.md) |
| [Forskrift om krav til anerkjente klasseselskap](/norwegian-laws/forskrifter/forskrift-2025-08-01-1582.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-08-01-1582) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-08-01-1582.md) |
| [Forskrift om krav til automatisk identifikasjonssystem (AIS) for utenlandske fis](/norwegian-laws/forskrifter/forskrift-2012-04-30-375.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2012-04-30-375) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2012-04-30-375.md) |
| [Forskrift om krav til automatiske diskontinuerlige summeringsvekter (summerende ](/norwegian-laws/forskrifter/forskrift-2007-12-21-1737.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2007-12-21-1737) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2007-12-21-1737.md) |
| [Forskrift om krav til automatiske gravimetriske fyllemaskiner](/norwegian-laws/forskrifter/forskrift-2007-12-21-1747.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2007-12-21-1747) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2007-12-21-1747.md) |
| [Forskrift om krav til automatiske jernbanevekter](/norwegian-laws/forskrifter/forskrift-2007-12-21-1741.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2007-12-21-1741) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2007-12-21-1741.md) |
| [Forskrift om krav til avgassmålere](/norwegian-laws/forskrifter/forskrift-2007-12-21-1744.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2007-12-21-1744) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2007-12-21-1744.md) |
| [Forskrift om krav til elektrisitetsmålere](/norwegian-laws/forskrifter/forskrift-2007-12-28-1753.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2007-12-28-1753) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2007-12-28-1753.md) |
| [Forskrift om krav til fartøy som skal fiske og føre fangsten levende](/norwegian-laws/forskrifter/forskrift-2005-12-22-1682.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2005-12-22-1682) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2005-12-22-1682.md) |
| [Forskrift om krav til flasker brukt som målebeholdere (måleflasker)](/norwegian-laws/forskrifter/forskrift-2007-12-21-1732.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2007-12-21-1732) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2007-12-21-1732.md) |
| [Forskrift om krav til gassmålere](/norwegian-laws/forskrifter/forskrift-2025-01-29-98.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-01-29-98) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-01-29-98.md) |
| [Forskrift om krav til ikke-automatiske vekter](/norwegian-laws/forskrifter/forskrift-2007-12-21-1735.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2007-12-21-1735) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2007-12-21-1735.md) |
| [Forskrift om krav til instrumenter for automatisk veiing av enkeltmengder (catch](/norwegian-laws/forskrifter/forskrift-2007-12-21-1742.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2007-12-21-1742) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2007-12-21-1742.md) |
| [Forskrift om krav til instrumenter til flerdimensjonale målinger (flerdimensjons](/norwegian-laws/forskrifter/forskrift-2007-12-21-1746.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2007-12-21-1746) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2007-12-21-1746.md) |
| [Forskrift om krav til internkontrollsystem for måleredskaper og målinger](/norwegian-laws/forskrifter/forskrift-2026-03-12-399.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2026-03-12-399) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2026-03-12-399.md) |
| [Forskrift om krav til kalibrering av måletanker som brukes til beregning av økon](/norwegian-laws/forskrifter/forskrift-2007-12-21-1748.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2007-12-21-1748) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2007-12-21-1748.md) |
| [Forskrift om krav til leider på fartøy som er underlagt havressurslovgivningen](/norwegian-laws/forskrifter/forskrift-2016-03-22-322.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2016-03-22-322) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2016-03-22-322.md) |
| [Forskrift om krav til lengdemålingsinstrumenter](/norwegian-laws/forskrifter/forskrift-2007-12-21-1740.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2007-12-21-1740) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2007-12-21-1740.md) |
| [Forskrift om krav til materielle lengdemål](/norwegian-laws/forskrifter/forskrift-2007-12-21-1739.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2007-12-21-1739) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2007-12-21-1739.md) |
| [Forskrift om krav til minstealder og båtførerbevis mv. for fører av fritidsbåt](/norwegian-laws/forskrifter/forskrift-2009-03-03-259.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2009-03-03-259) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2009-03-03-259.md) |
| [Forskrift om krav til målesystem for kontinuerlig og dynamisk måling av andre væ](/norwegian-laws/forskrifter/forskrift-2007-12-21-1738.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2007-12-21-1738) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2007-12-21-1738.md) |
| [Forskrift om krav til nettoinnhold i ferdigpakninger](/norwegian-laws/forskrifter/forskrift-2021-06-16-2130.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-06-16-2130) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-06-16-2130.md) |
| [Forskrift om krav til slepebåt for flyttbare innretninger som er underveis i ter](/norwegian-laws/forskrifter/forskrift-2014-12-05-1546.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2014-12-05-1546) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2014-12-05-1546.md) |
| [Forskrift om krav til taksametre](/norwegian-laws/forskrifter/forskrift-2009-10-01-1226.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2009-10-01-1226) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2009-10-01-1226.md) |
| [Forskrift om krav til teknisk standard for akvakulturanlegg for fisk i sjø, inns](/norwegian-laws/forskrifter/forskrift-2022-08-22-1484.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-08-22-1484) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-08-22-1484.md) |
| [Forskrift om krav til teknisk standard for landbaserte akvakulturanlegg for fisk](/norwegian-laws/forskrifter/forskrift-2017-06-19-941.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-06-19-941) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-06-19-941.md) |
| [Forskrift om krav til transportbåndvekter](/norwegian-laws/forskrifter/forskrift-2007-12-21-1736.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2007-12-21-1736) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2007-12-21-1736.md) |
| [Forskrift om krav til utstyr og installasjon av posisjonsrapporteringsutstyr](/norwegian-laws/forskrifter/forskrift-2010-03-24-454.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2010-03-24-454) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2010-03-24-454.md) |
| [Forskrift om krav til vannmålere](/norwegian-laws/forskrifter/forskrift-2007-12-21-1745.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2007-12-21-1745) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2007-12-21-1745.md) |
| [Forskrift om krav til varmeenergimålere](/norwegian-laws/forskrifter/forskrift-2007-12-21-1743.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2007-12-21-1743) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2007-12-21-1743.md) |
| [Forskrift om krav til vekter og automatiske veiesystemer til bruk ved landing av](/norwegian-laws/forskrifter/forskrift-2026-02-04-165.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2026-02-04-165) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2026-02-04-165.md) |
| [Forskrift om kvalifikasjoner og sertifikater for sjøfolk](/norwegian-laws/forskrifter/forskrift-2011-12-22-1523.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2011-12-22-1523) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2011-12-22-1523.md) |
| [Forskrift om kvalitet på fisk og fiskevarer](/norwegian-laws/forskrifter/forskrift-2013-06-28-844.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-06-28-844) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-06-28-844.md) |
| [Forskrift om kvoter i jakt på kystsel i 2026](/norwegian-laws/forskrifter/forskrift-2025-12-09-2503.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-12-09-2503) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-12-09-2503.md) |
| [Forskrift om landings- og sluttseddel (landingsforskriften)](/norwegian-laws/forskrifter/forskrift-2014-05-06-607.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2014-05-06-607) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2014-05-06-607.md) |
| [Forskrift om laste- og losseinnretninger på skip](/norwegian-laws/forskrifter/forskrift-1978-01-17-4.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1978-01-17-4) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1978-01-17-4.md) |
| [Forskrift om lasteskip som skal føre industrielt personell](/norwegian-laws/forskrifter/forskrift-2024-06-28-1391.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-06-28-1391) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-06-28-1391.md) |
| [Forskrift om legemidler til dyr](/norwegian-laws/forskrifter/forskrift-2022-09-08-1573.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-09-08-1573) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-09-08-1573.md) |
| [Forskrift om leveringsplikt for fartøy med torsketråltillatelse](/norwegian-laws/forskrifter/forskrift-2003-09-12-1131.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2003-09-12-1131) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2003-09-12-1131.md) |
| [Forskrift om losberedskapsavgift, losings- og farledsbevisavgift (losavgifter)](/norwegian-laws/forskrifter/forskrift-1994-12-23-1128.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1994-12-23-1128) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1994-12-23-1128.md) |
| [Forskrift om losers tjenestefrihet av sikkerhetshensyn](/norwegian-laws/forskrifter/forskrift-1991-12-10-810.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1991-12-10-810) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1991-12-10-810.md) |
| [Forskrift om losplikt og bruk av farledsbevis (lospliktforskriften)](/norwegian-laws/forskrifter/forskrift-2014-12-17-1808.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2014-12-17-1808) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2014-12-17-1808.md) |
| [Forskrift om lossing, lasting, lagring og transport innen kommunens sjøområde og](/norwegian-laws/forskrifter/forskrift-2009-12-15-1543.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2009-12-15-1543) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2009-12-15-1543.md) |
| [Forskrift om manntal for fiskarar og fangstmenn](/norwegian-laws/forskrifter/forskrift-2008-12-18-1436.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2008-12-18-1436) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2008-12-18-1436.md) |
| [Forskrift om matinformasjon til forbrukerne (matinformasjonsforskriften)](/norwegian-laws/forskrifter/forskrift-2014-11-28-1497.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2014-11-28-1497) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2014-11-28-1497.md) |
| [Forskrift om medisinfôr (medisinfôrforskriften)](/norwegian-laws/forskrifter/forskrift-2022-04-07-587.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-04-07-587) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-04-07-587.md) |
| [Forskrift om melde- og rapporteringsplikt ved sjøulykker og andre hendelser til ](/norwegian-laws/forskrifter/forskrift-2008-06-27-744.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2008-06-27-744) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2008-06-27-744.md) |
| [Forskrift om melding av foretakssammenslutninger mv.](/norwegian-laws/forskrifter/forskrift-2013-12-11-1466.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-12-11-1466) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-12-11-1466.md) |
| [Forskrift om melding av opplysninger om utleverte og brukte legemidler til dyr](/norwegian-laws/forskrifter/forskrift-2009-07-03-971.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2009-07-03-971) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2009-07-03-971.md) |
| [Forskrift om merking av villfanget hummer som omsettes](/norwegian-laws/forskrifter/forskrift-2012-09-20-889.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2012-09-20-889) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2012-09-20-889.md) |
| [Forskrift om merking og omsetning av fôrvarer](/norwegian-laws/forskrifter/forskrift-2011-04-02-360.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2011-04-02-360) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2011-04-02-360.md) |
| [Forskrift om midlertidig lineegnetilskudd i 2025](/norwegian-laws/forskrifter/forskrift-2024-12-19-3320.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-12-19-3320) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-12-19-3320.md) |
| [Forskrift om midlertidig tilskudd for fiskerinæringen i Oslofjorden](/norwegian-laws/forskrifter/forskrift-2026-05-12-780.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2026-05-12-780) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2026-05-12-780.md) |
| [Forskrift om midlertidig tilskudd som kompensasjon for CO2-avgift på drivstoff f](/norwegian-laws/forskrifter/forskrift-2020-12-17-2950.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-12-17-2950) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-12-17-2950.md) |
| [Forskrift om midlertidig tilskudd til drivstoff for kystrekeflåten i 2023](/norwegian-laws/forskrifter/forskrift-2022-12-20-2357.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-12-20-2357) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-12-20-2357.md) |
| [Forskrift om midlertidig tilskudd til drivstoff for kystrekeflåten i 2024](/norwegian-laws/forskrifter/forskrift-2023-12-21-2264.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-12-21-2264) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-12-21-2264.md) |
| [Forskrift om midlertidig tilskudd til drivstoff for kystrekeflåten i 2025](/norwegian-laws/forskrifter/forskrift-2024-12-20-3492.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-12-20-3492) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-12-20-3492.md) |
| [Forskrift om midlertidig tilskudd til drivstoff for kystrekeflåten i 2026](/norwegian-laws/forskrifter/forskrift-2025-12-22-2837.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-12-22-2837) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-12-22-2837.md) |
| [Forskrift om miljødeklarasjon i forbindelse med miljødifferensiering for skip og](/norwegian-laws/forskrifter/forskrift-2000-11-28-1194.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2000-11-28-1194) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2000-11-28-1194.md) |
| [Forskrift om miljømessig sikkerhet for skip og flyttbare innretninger](/norwegian-laws/forskrifter/forskrift-2012-05-30-488.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2012-05-30-488) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2012-05-30-488.md) |
| [Forskrift om målenheter og måling](/norwegian-laws/forskrifter/forskrift-2007-12-20-1723.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2007-12-20-1723) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2007-12-20-1723.md) |
| [Forskrift om måling av skip og flyttbare innretninger](/norwegian-laws/forskrifter/forskrift-2015-06-30-823.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-06-30-823) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-06-30-823.md) |
| [Forskrift om navigasjon og navigasjonshjelpemidler for skip og flyttbare innretn](/norwegian-laws/forskrifter/forskrift-2014-09-05-1157.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2014-09-05-1157) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2014-09-05-1157.md) |
| [Forskrift om næringsmessig transport av dyr](/norwegian-laws/forskrifter/forskrift-2012-02-08-139.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2012-02-08-139) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2012-02-08-139.md) |
| [Forskrift om næringsmiddelhygiene (næringsmiddelhygieneforskriften)](/norwegian-laws/forskrifter/forskrift-2008-12-22-1623.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2008-12-22-1623) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2008-12-22-1623.md) |
| [Forskrift om obligatoriske volumstørrelser for visse alkoholholdige produkter](/norwegian-laws/forskrifter/forskrift-2008-09-18-1079.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2008-09-18-1079) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2008-09-18-1079.md) |
| [Forskrift om offentlig kontroll for å sikre etterlevelse av regelverket for mat,](/norwegian-laws/forskrifter/forskrift-2020-03-03-704.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-03-03-704) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-03-03-704.md) |
| [Forskrift om offentlig kontroll – IMSOC – forordning (EU) 2019/1715](/norwegian-laws/forskrifter/forskrift-2020-03-09-715.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-03-09-715) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-03-09-715.md) |
| [Forskrift om offentlig kontroll – animalsk produksjon, forordning (EU) 2019/624 ](/norwegian-laws/forskrifter/forskrift-2020-03-09-720.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-03-09-720) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-03-09-720.md) |
| [Forskrift om offentlig kontroll – dokumentasjonskrav ved import, forordning (EU)](/norwegian-laws/forskrifter/forskrift-2020-03-09-710.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-03-09-710) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-03-09-710.md) |
| [Forskrift om offentlig kontroll – dyrehelse, forordning (EU) 2022/160 og forordn](/norwegian-laws/forskrifter/forskrift-2024-06-13-975.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-06-13-975) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-06-13-975.md) |
| [Forskrift om offentlig kontroll – generelle regler for grensekontroll forordning](/norwegian-laws/forskrifter/forskrift-2020-03-09-708.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-03-09-708) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-03-09-708.md) |
| [Forskrift om offentlig kontroll – grensekontrollstasjoner – forordning (EU) 2019](/norwegian-laws/forskrifter/forskrift-2020-03-09-709.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-03-09-709) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-03-09-709.md) |
| [Forskrift om offentlig kontroll – importkontroll av ikke animalske produkter – f](/norwegian-laws/forskrifter/forskrift-2020-03-09-717.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-03-09-717) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-03-09-717.md) |
| [Forskrift om offentlig kontroll – importkontroll for antimikrobielle legemidler ](/norwegian-laws/forskrifter/forskrift-2025-03-24-620.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-03-24-620) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-03-24-620.md) |
| [Forskrift om offentlig kontroll – krav til transporten ved import og transitt, f](/norwegian-laws/forskrifter/forskrift-2020-03-09-711.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-03-09-711) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-03-09-711.md) |
| [Forskrift om offentlig kontroll – lister over tredjestater det er tillatt å innf](/norwegian-laws/forskrifter/forskrift-2021-08-26-2617.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-08-26-2617) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-08-26-2617.md) |
| [Forskrift om offentlig kontroll – positivlisten 2021 – forordning (EU) 2021/630 ](/norwegian-laws/forskrifter/forskrift-2022-06-02-1010.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-06-02-1010) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-06-02-1010.md) |
| [Forskrift om offentlig kontroll – standardmal for årsrapport, forordning (EU) 20](/norwegian-laws/forskrifter/forskrift-2020-03-04-706.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-03-04-706) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-03-04-706.md) |
| [Forskrift om offentlig kontroll – særlige regler om grensekontrollen, forordning](/norwegian-laws/forskrifter/forskrift-2020-03-09-712.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-03-09-712) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-03-09-712.md) |
| [Forskrift om offentlig kontroll – utfyllende bestemmelser om krav til import – f](/norwegian-laws/forskrifter/forskrift-2023-12-27-2337.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-12-27-2337) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-12-27-2337.md) |
| [Forskrift om offentlig kontroll – utfyllende bestemmelser om utpeking av offisie](/norwegian-laws/forskrifter/forskrift-2022-05-03-836.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-05-03-836) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-05-03-836.md) |
| [Forskrift om offentlig støtte gjennom skatte- og avgiftsordninger](/norwegian-laws/forskrifter/forskrift-2023-02-08-165.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-02-08-165) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-02-08-165.md) |
| [Forskrift om offentlige anskaffelser (anskaffelsesforskriften)](/norwegian-laws/forskrifter/forskrift-2016-08-12-974.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2016-08-12-974) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2016-08-12-974.md) |
| [Forskrift om omregningsfaktorer fra produktvekt og antall til rund vekt](/norwegian-laws/forskrifter/forskrift-2009-05-20-534.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2009-05-20-534) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2009-05-20-534.md) |
| [Forskrift om omsetning m.v. av agn.](/norwegian-laws/forskrifter/forskrift-1954-02-05-2.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1954-02-05-2) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1954-02-05-2.md) |
| [Forskrift om oppkreving av gebyr til statskassen for besiktelser, sertifikatutst](/norwegian-laws/forskrifter/forskrift-1996-02-02-115.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1996-02-02-115) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1996-02-02-115.md) |
| [Forskrift om opplysninger til Mattilsynet](/norwegian-laws/forskrifter/forskrift-2010-09-28-1302.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2010-09-28-1302) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2010-09-28-1302.md) |
| [Forskrift om opplysningsplikt for transportplanlegging](/norwegian-laws/forskrifter/forskrift-2019-12-11-1836.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-12-11-1836) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-12-11-1836.md) |
| [Forskrift om opplysningsplikt og bevissikring](/norwegian-laws/forskrifter/forskrift-2013-12-11-1491.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-12-11-1491) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-12-11-1491.md) |
| [Forskrift om opplæring og sertifisering av loser](/norwegian-laws/forskrifter/forskrift-2018-12-20-2218.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2018-12-20-2218) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2018-12-20-2218.md) |
| [Forskrift om opprettelse av et harmonisert europeisk rapporteringssystem for sjø](/norwegian-laws/forskrifter/forskrift-2024-12-18-3315.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-12-18-3315) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-12-18-3315.md) |
| [Forskrift om opptak til mesterutdanningen](/norwegian-laws/forskrifter/forskrift-2003-05-16-652.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2003-05-16-652) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2003-05-16-652.md) |
| [Forskrift om opptelling og registrering av ombordværende på passasjerskip](/norwegian-laws/forskrifter/forskrift-1999-09-06-1047.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1999-09-06-1047) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1999-09-06-1047.md) |
| [Forskrift om overgangsbestemmelser i anledning ikrafttredelse av lov 11. juni 19](/norwegian-laws/forskrifter/forskrift-1993-11-22-1039.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1993-11-22-1039) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1993-11-22-1039.md) |
| [Forskrift om overgangsbestemmelser til lov 12. april 2024 nr. 17 om endringer i ](/norwegian-laws/forskrifter/forskrift-2024-06-19-1059.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-06-19-1059) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-06-19-1059.md) |
| [Forskrift om overgangsbestemmelser til lov 15. april 2016 nr. 2 om endringer i k](/norwegian-laws/forskrifter/forskrift-2016-06-17-672.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2016-06-17-672) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2016-06-17-672.md) |
| [Forskrift om overgangsordning for krav til kjønnssammensetning i styret i foreta](/norwegian-laws/forskrifter/forskrift-2023-12-20-2131.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-12-20-2131) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-12-20-2131.md) |
| [Forskrift om overgangsregler for lov 11. mai 2012 nr. 25 om endringer i lov om o](/norwegian-laws/forskrifter/forskrift-2012-06-08-499.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2012-06-08-499) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2012-06-08-499.md) |
| [Forskrift om overgangsregler for lov 17. juni 2016 nr. 73 om offentlige anskaffe](/norwegian-laws/forskrifter/forskrift-2016-08-12-978.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2016-08-12-978) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2016-08-12-978.md) |
| [Forskrift om overgangsregler og om oppheving av forskrifter gitt med hjemmel i l](/norwegian-laws/forskrifter/forskrift-2019-12-11-1837.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-12-11-1837) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-12-11-1837.md) |
| [Forskrift om overgangsregler til lov 20. juni 2025 nr. 105 om Enhetsregisteret o](/norwegian-laws/forskrifter/forskrift-2025-10-01-1974.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-10-01-1974) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-10-01-1974.md) |
| [Forskrift om overtredelsesgebyr etter havne- og farvannsloven](/norwegian-laws/forskrifter/forskrift-2019-12-11-1869.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-12-11-1869) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-12-11-1869.md) |
| [Forskrift om overtredelsesgebyr etter skipssikkerhetsloven, skipsarbeidsloven og](/norwegian-laws/forskrifter/forskrift-2020-07-27-1596.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-07-27-1596) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-07-27-1596.md) |
| [Forskrift om passasjerskip i norsk internasjonalt skipsregister (NIS)](/norwegian-laws/forskrifter/forskrift-2021-06-28-2257.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-06-28-2257) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-06-28-2257.md) |
| [Forskrift om passasjerskip i spesiell fart](/norwegian-laws/forskrifter/forskrift-1977-02-15-2.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1977-02-15-2) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1977-02-15-2.md) |
| [Forskrift om plassering m.v. av innredning og om forpleiningstjenesten for beset](/norwegian-laws/forskrifter/forskrift-1991-10-15-713.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1991-10-15-713) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1991-10-15-713.md) |
| [Forskrift om plikt for fiske- og fangstfartøy til å lytte på radio (kanal 16) og](/norwegian-laws/forskrifter/forskrift-2010-06-23-1228.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2010-06-23-1228) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2010-06-23-1228.md) |
| [Forskrift om plikt til å gi opplysninger om drift av fiske- og fangstfartøy](/norwegian-laws/forskrifter/forskrift-2015-05-26-547.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-05-26-547) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-05-26-547.md) |
| [Forskrift om pliktig innmelding av grunnundersøkelser og naturfareutredninger](/norwegian-laws/forskrifter/forskrift-2024-12-17-3181.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-12-17-3181) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-12-17-3181.md) |
| [Forskrift om posisjonerings- og ankringssystemer på flyttbare innretninger (ankr](/norwegian-laws/forskrifter/forskrift-2009-07-10-998.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2009-07-10-998) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2009-07-10-998.md) |
| [Forskrift om posisjonsrapportering og elektronisk rapportering for norske fiske-](/norwegian-laws/forskrifter/forskrift-2009-12-21-1743.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2009-12-21-1743) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2009-12-21-1743.md) |
| [Forskrift om priser og betalingsbetingelser for eksport av tørrfisk.](/norwegian-laws/forskrifter/forskrift-1982-10-05-1440.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1982-10-05-1440) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1982-10-05-1440.md) |
| [Forskrift om produksjon og omsetning av fritidsfartøy og vannscootere mv.](/norwegian-laws/forskrifter/forskrift-2016-01-15-35.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2016-01-15-35) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2016-01-15-35.md) |
| [Forskrift om produksjon, omsetning og import av gjødselvarer av organisk opphav ](/norwegian-laws/forskrifter/forskrift-2025-01-29-116.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-01-29-116) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-01-29-116.md) |
| [Forskrift om produksjonsområder for akvakultur av matfisk i sjø av laks, ørret o](/norwegian-laws/forskrifter/forskrift-2017-01-16-61.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-01-16-61) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-01-16-61.md) |
| [Forskrift om prøving, kontroll, godkjenning og vedlikehold m.v. av containere.](/norwegian-laws/forskrifter/forskrift-1984-04-02-827.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1984-04-02-827) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1984-04-02-827.md) |
| [Forskrift om radiokommunikasjonsutstyr for norske skip og flyttbare innretninger](/norwegian-laws/forskrifter/forskrift-2014-07-01-955.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2014-07-01-955) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2014-07-01-955.md) |
| [Forskrift om rapportering (posisjon, fangst og aktivitet) og kontroll mv. ved fi](/norwegian-laws/forskrifter/forskrift-2010-08-30-1230.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2010-08-30-1230) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2010-08-30-1230.md) |
| [Forskrift om rapportering (posisjon, fangst og aktivitet) og kontroll mv. ved fi](/norwegian-laws/forskrifter/forskrift-2010-08-30-1229.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2010-08-30-1229) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2010-08-30-1229.md) |
| [Forskrift om rapportering av fangster fra turistfiskevirksomheter](/norwegian-laws/forskrifter/forskrift-2017-12-20-2445.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-12-20-2445) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-12-20-2445.md) |
| [Forskrift om rapportering til Det internasjonale fond for erstatning av oljesøls](/norwegian-laws/forskrifter/forskrift-2015-12-21-1789.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-12-21-1789) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-12-21-1789.md) |
| [Forskrift om rapporteringsplikt ved fangst av kongekrabbe med ikke-merkeregister](/norwegian-laws/forskrifter/forskrift-2010-03-17-396.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2010-03-17-396) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2010-03-17-396.md) |
| [Forskrift om reaksjoner, sanksjoner med mer ved overtredelse av akvakulturloven](/norwegian-laws/forskrifter/forskrift-2013-12-20-1675.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-12-20-1675) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-12-20-1675.md) |
| [Forskrift om redningsredskaper på skip](/norwegian-laws/forskrifter/forskrift-2014-07-01-1019.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2014-07-01-1019) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2014-07-01-1019.md) |
| [Forskrift om registrering av andre flytende innretninger.](/norwegian-laws/forskrifter/forskrift-1994-04-26-321.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1994-04-26-321) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1994-04-26-321.md) |
| [Forskrift om registrering av ansvarsmerker](/norwegian-laws/forskrifter/forskrift-2010-12-20-1812.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2010-12-20-1812) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2010-12-20-1812.md) |
| [Forskrift om registrering av fartøy som skal delta i fiske etter reker i fiskeve](/norwegian-laws/forskrifter/forskrift-1997-07-11-784.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1997-07-11-784) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1997-07-11-784.md) |
| [Forskrift om registrering av offentlig støtte](/norwegian-laws/forskrifter/forskrift-2023-01-02-4.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-01-02-4) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-01-02-4.md) |
| [Forskrift om registrering av opplysninger om konsern i Enhetsregisteret](/norwegian-laws/forskrifter/forskrift-2025-10-24-2096.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-10-24-2096) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-10-24-2096.md) |
| [Forskrift om registrering av skip i Norsk Internasjonalt Skipsregister (NIS)](/norwegian-laws/forskrifter/forskrift-1992-07-30-592.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1992-07-30-592) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1992-07-30-592.md) |
| [Forskrift om registrering av skip i norsk ordinært skipsregister](/norwegian-laws/forskrifter/forskrift-1992-07-30-593.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1992-07-30-593) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1992-07-30-593.md) |
| [Forskrift om registrering og offentleggjering av mellombalansar](/norwegian-laws/forskrifter/forskrift-2020-10-24-2199.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-10-24-2199) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-10-24-2199.md) |
| [Forskrift om registrering og rapportering ved fiske i farvann utenfor noen stats](/norwegian-laws/forskrifter/forskrift-1999-06-30-1499.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1999-06-30-1499) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1999-06-30-1499.md) |
| [Forskrift om registrering som kjøper av fangst](/norwegian-laws/forskrifter/forskrift-2010-11-26-1475.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2010-11-26-1475) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2010-11-26-1475.md) |
| [Forskrift om regulering av brosme og lange nord for 62° N i 2026](/norwegian-laws/forskrifter/forskrift-2025-12-18-2688.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-12-18-2688) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-12-18-2688.md) |
| [Forskrift om regulering av eksporten av fisk, fiskevarer og marine produkter](/norwegian-laws/forskrifter/forskrift-1991-03-22-157.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1991-03-22-157) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1991-03-22-157.md) |
| [Forskrift om regulering av fangst av haneskjell (Chlamys Islandica) i fiskeverns](/norwegian-laws/forskrifter/forskrift-1989-01-10-12.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1989-01-10-12) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1989-01-10-12.md) |
| [Forskrift om regulering av fangst av kongekrabbe i kvoteregulert område øst for ](/norwegian-laws/forskrifter/forskrift-2025-12-19-2809.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-12-19-2809) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-12-19-2809.md) |
| [Forskrift om regulering av fangst av sel i Vesterisen og Østisen i 2026](/norwegian-laws/forskrifter/forskrift-2026-03-12-398.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2026-03-12-398) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2026-03-12-398.md) |
| [Forskrift om regulering av fangst av skjell ved Jan Mayen](/norwegian-laws/forskrifter/forskrift-1989-10-10-1100.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1989-10-10-1100) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1989-10-10-1100.md) |
| [Forskrift om regulering av fangst av snøkrabbe i 2026](/norwegian-laws/forskrifter/forskrift-2025-12-19-2855.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-12-19-2855) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-12-19-2855.md) |
| [Forskrift om regulering av fangst av vågehval i 2026](/norwegian-laws/forskrifter/forskrift-2026-03-10-378.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2026-03-10-378) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2026-03-10-378.md) |
| [Forskrift om regulering av fiske etter blålange](/norwegian-laws/forskrifter/forskrift-2009-12-07-1462.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2009-12-07-1462) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2009-12-07-1462.md) |
| [Forskrift om regulering av fiske for å beskytte sårbare marine økosystemer](/norwegian-laws/forskrifter/forskrift-2011-07-01-755.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2011-07-01-755) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2011-07-01-755.md) |
| [Forskrift om regulering av fiske i Grønlands økonomiske sone i 2026](/norwegian-laws/forskrifter/forskrift-2025-12-29-2899.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-12-29-2899) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-12-29-2899.md) |
| [Forskrift om regulering av fiske i Oslofjorden](/norwegian-laws/forskrifter/forskrift-2025-12-19-2889.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-12-19-2889) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-12-19-2889.md) |
| [Forskrift om regulering av fiske i farvann utenfor noen stats fiskerijurisdiksjo](/norwegian-laws/forskrifter/forskrift-1998-03-04-173.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1998-03-04-173) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1998-03-04-173.md) |
| [Forskrift om regulering av fiske med bunnredskap i områder utenfor nasjonal juri](/norwegian-laws/forskrifter/forskrift-2009-02-09-154.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2009-02-09-154) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2009-02-09-154.md) |
| [Forskrift om regulering av fiske med norske fartøyer i Antarktis (CCAMLR-området](/norwegian-laws/forskrifter/forskrift-1998-03-13-195.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1998-03-13-195) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1998-03-13-195.md) |
| [Forskrift om regulering av fisket etter blåkveite nord for 62° N i 2026](/norwegian-laws/forskrifter/forskrift-2025-12-19-2829.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-12-19-2829) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-12-19-2829.md) |
| [Forskrift om regulering av fisket etter brisling i 2025–2026](/norwegian-laws/forskrifter/forskrift-2025-06-23-1281.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-06-23-1281) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-06-23-1281.md) |
| [Forskrift om regulering av fisket etter bunnfisk i Færøyenes fiskerisone i 2026](/norwegian-laws/forskrifter/forskrift-2026-01-05-4.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2026-01-05-4) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2026-01-05-4.md) |
| [Forskrift om regulering av fisket etter dyphavsarter i NEAFC' reguleringsområde ](/norwegian-laws/forskrifter/forskrift-2025-11-25-2340.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-11-25-2340) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-11-25-2340.md) |
| [Forskrift om regulering av fisket etter hestmakrell i 2026](/norwegian-laws/forskrifter/forskrift-2025-12-08-2458.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-12-08-2458) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-12-08-2458.md) |
| [Forskrift om regulering av fisket etter hyse i Nordsjøen og Skagerrak i 2026](/norwegian-laws/forskrifter/forskrift-2025-12-19-2813.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-12-19-2813) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-12-19-2813.md) |
| [Forskrift om regulering av fisket etter hyse i fiskevernsonen ved Svalbard i 202](/norwegian-laws/forskrifter/forskrift-2025-12-22-2831.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-12-22-2831) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-12-22-2831.md) |
| [Forskrift om regulering av fisket etter kolmule i 2026](/norwegian-laws/forskrifter/forskrift-2025-12-19-2822.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-12-19-2822) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-12-19-2822.md) |
| [Forskrift om regulering av fisket etter kveite nord for 62° N i 2026](/norwegian-laws/forskrifter/forskrift-2026-05-04-762.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2026-05-04-762) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2026-05-04-762.md) |
| [Forskrift om regulering av fisket etter leppefisk i 2026](/norwegian-laws/forskrifter/forskrift-2025-12-22-2836.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-12-22-2836) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-12-22-2836.md) |
| [Forskrift om regulering av fisket etter makrell i 2026](/norwegian-laws/forskrifter/forskrift-2025-12-19-2821.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-12-19-2821) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-12-19-2821.md) |
| [Forskrift om regulering av fisket etter makrellstørje (Thunnus thynnus) i 2026](/norwegian-laws/forskrifter/forskrift-2026-03-05-356.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2026-03-05-356) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2026-03-05-356.md) |
| [Forskrift om regulering av fisket etter norsk vårgytende sild (nvg) i 2026](/norwegian-laws/forskrifter/forskrift-2025-12-19-2844.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-12-19-2844) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-12-19-2844.md) |
| [Forskrift om regulering av fisket etter reker i Nordsjøen og Skagerrak i 2025–20](/norwegian-laws/forskrifter/forskrift-2025-06-27-1361.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-06-27-1361) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-06-27-1361.md) |
| [Forskrift om regulering av fisket etter rognkjeks i 2026](/norwegian-laws/forskrifter/forskrift-2025-12-19-2744.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-12-19-2744) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-12-19-2744.md) |
| [Forskrift om regulering av fisket etter rødspette i Nordsjøen og Skagerrak i 202](/norwegian-laws/forskrifter/forskrift-2025-12-19-2731.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-12-19-2731) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-12-19-2731.md) |
| [Forskrift om regulering av fisket etter sei i Nordsjøen og Skagerrak i 2026](/norwegian-laws/forskrifter/forskrift-2025-12-19-2737.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-12-19-2737) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-12-19-2737.md) |
| [Forskrift om regulering av fisket etter sild i Nordsjøen og Skagerrak i 2026](/norwegian-laws/forskrifter/forskrift-2025-12-19-2828.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-12-19-2828) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-12-19-2828.md) |
| [Forskrift om regulering av fisket etter snabeluer (S. mentella) nord for 62° N i](/norwegian-laws/forskrifter/forskrift-2025-12-19-2890.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-12-19-2890) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-12-19-2890.md) |
| [Forskrift om regulering av fisket etter tobis i 2026](/norwegian-laws/forskrifter/forskrift-2025-12-08-2459.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-12-08-2459) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-12-08-2459.md) |
| [Forskrift om regulering av fisket etter torsk i NAFO-underområde 3L i 2025–2026](/norwegian-laws/forskrifter/forskrift-2025-09-25-1933.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-09-25-1933) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-09-25-1933.md) |
| [Forskrift om regulering av fisket etter torsk i NAFO-underområde 3M i 2026](/norwegian-laws/forskrifter/forskrift-2026-01-23-83.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2026-01-23-83) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2026-01-23-83.md) |
| [Forskrift om regulering av fisket etter torsk i Nordsjøen og Skagerrak i 2026](/norwegian-laws/forskrifter/forskrift-2025-12-19-2805.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-12-19-2805) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-12-19-2805.md) |
| [Forskrift om regulering av fisket etter torsk i fiskevernsonen ved Svalbard i 20](/norwegian-laws/forskrifter/forskrift-2025-12-22-2830.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-12-22-2830) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-12-22-2830.md) |
| [Forskrift om regulering av fisket etter torsk, hyse og sei nord for 62 grader no](/norwegian-laws/forskrifter/forskrift-2025-12-19-2826.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-12-19-2826) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-12-19-2826.md) |
| [Forskrift om regulering av fisket etter uer i Svalbards territorialfarvann](/norwegian-laws/forskrifter/forskrift-2009-12-17-1593.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2009-12-17-1593) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2009-12-17-1593.md) |
| [Forskrift om regulering av fisket etter uer i fiskevernsonen ved Svalbard](/norwegian-laws/forskrifter/forskrift-2009-12-17-1592.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2009-12-17-1592) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2009-12-17-1592.md) |
| [Forskrift om regulering av fisket etter vassild og strømsild i 2026](/norwegian-laws/forskrifter/forskrift-2025-12-18-2689.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-12-18-2689) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-12-18-2689.md) |
| [Forskrift om regulering av fisket etter øyepål i 2026](/norwegian-laws/forskrifter/forskrift-2025-12-08-2460.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-12-08-2460) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-12-08-2460.md) |
| [Forskrift om regulering av fisket for fartøy som fører færøysk flagg i Norges øk](/norwegian-laws/forskrifter/forskrift-2026-01-05-5.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2026-01-05-5) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2026-01-05-5.md) |
| [Forskrift om regulering av fisket for fartøy som fører grønlandsk flagg i Norges](/norwegian-laws/forskrifter/forskrift-2026-01-12-26.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2026-01-12-26) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2026-01-12-26.md) |
| [Forskrift om regulering av fisket i det nordvestlige Atlanterhav (NAFO-området)](/norwegian-laws/forskrifter/forskrift-2009-12-11-1507.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2009-12-11-1507) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2009-12-11-1507.md) |
| [Forskrift om regulering av fisket med fartøy som fører britisk flagg i Norges øk](/norwegian-laws/forskrifter/forskrift-2026-01-07-15.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2026-01-07-15) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2026-01-07-15.md) |
| [Forskrift om regulering av fisket med fartøy som fører flagg fra medlemsstater i](/norwegian-laws/forskrifter/forskrift-2026-01-12-28.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2026-01-12-28) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2026-01-12-28.md) |
| [Forskrift om regulering av fisket med fartøy som fører russisk flagg i Norges øk](/norwegian-laws/forskrifter/forskrift-2026-01-14-44.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2026-01-14-44) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2026-01-14-44.md) |
| [Forskrift om regulering av fisket med fartøy som fører svensk flagg i Norges øko](/norwegian-laws/forskrifter/forskrift-2026-01-05-13.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2026-01-05-13) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2026-01-05-13.md) |
| [Forskrift om regulering av fisket med torsketrål og snurrevad – stenging av områ](/norwegian-laws/forskrifter/forskrift-2017-08-09-1240.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-08-09-1240) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-08-09-1240.md) |
| [Forskrift om regulering av høsting av rødåte](/norwegian-laws/forskrifter/forskrift-2024-12-05-2943.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-12-05-2943) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-12-05-2943.md) |
| [Forskrift om regulering av norske fartøys fiske i britisk sone i 2026](/norwegian-laws/forskrifter/forskrift-2025-12-19-2742.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-12-19-2742) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-12-19-2742.md) |
| [Forskrift om regulering av rekefisket i Svalbards territorialfarvann og indre fa](/norwegian-laws/forskrifter/forskrift-1996-07-19-735.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1996-07-19-735) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1996-07-19-735.md) |
| [Forskrift om regulering av rekefisket i fiskevernsonen ved Svalbard.](/norwegian-laws/forskrifter/forskrift-1996-07-19-726.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1996-07-19-726) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1996-07-19-726.md) |
| [Forskrift om regulering av sel på norskekysten](/norwegian-laws/forskrifter/forskrift-2009-12-22-1745.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2009-12-22-1745) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2009-12-22-1745.md) |
| [Forskrift om regulering av ungdoms rett til å delta i fisket i 2026 (ungdomsfisk](/norwegian-laws/forskrifter/forskrift-2026-04-17-614.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2026-04-17-614) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2026-04-17-614.md) |
| [Forskrift om regulering av utførsel av vågehval.](/norwegian-laws/forskrifter/forskrift-2001-06-29-799.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2001-06-29-799) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2001-06-29-799.md) |
| [Forskrift om regulering ved fiske og fangst mv. i Svalbards territorialfarvann o](/norwegian-laws/forskrifter/forskrift-1978-04-28-20.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1978-04-28-20) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1978-04-28-20.md) |
| [Forskrift om renter på overtredelsesgebyr for brudd på konkurranseloven](/norwegian-laws/forskrifter/forskrift-2024-11-26-2909.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-11-26-2909) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-11-26-2909.md) |
| [Forskrift om rester av plantevernmidler i næringsmidler og fôrvarer](/norwegian-laws/forskrifter/forskrift-2009-08-18-1117.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2009-08-18-1117) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2009-08-18-1117.md) |
| [Forskrift om retningslinjer og rapport om godtgjørelse for ledende personer](/norwegian-laws/forskrifter/forskrift-2020-12-11-2730.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-12-11-2730) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-12-11-2730.md) |
| [Forskrift om rettsvern for avtaler om inntredelsesrett i langsiktige kraftavtale](/norwegian-laws/forskrifter/forskrift-2011-02-11-133.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2011-02-11-133) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2011-02-11-133.md) |
| [Forskrift om risikoanalyse for flyttbare innretninger](/norwegian-laws/forskrifter/forskrift-1993-12-22-1239.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1993-12-22-1239) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1993-12-22-1239.md) |
| [Forskrift om saksbehandlingsgebyr etter lov om havner og farvann](/norwegian-laws/forskrifter/forskrift-2010-12-20-1760.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2010-12-20-1760) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2010-12-20-1760.md) |
| [Forskrift om samordnet innkreving av avgift på fiskeeksport](/norwegian-laws/forskrifter/forskrift-2000-12-13-1253.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2000-12-13-1253) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2000-12-13-1253.md) |
| [Forskrift om samordning og tidsfrister i behandlingen av akvakultursøknader](/norwegian-laws/forskrifter/forskrift-2010-05-18-708.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2010-05-18-708) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2010-05-18-708.md) |
| [Forskrift om satelittbasert overvåking av utenlandske fiskefartøys aktivitet i N](/norwegian-laws/forskrifter/forskrift-1999-12-16-1342.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1999-12-16-1342) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1999-12-16-1342.md) |
| [Forskrift om sikker lasting og lossing av bulkskip](/norwegian-laws/forskrifter/forskrift-2003-08-29-1114.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2003-08-29-1114) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2003-08-29-1114.md) |
| [Forskrift om sikkerhet, pirat- og terrorberedskapstiltak og bruk av maktmidler o](/norwegian-laws/forskrifter/forskrift-2004-06-22-972.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2004-06-22-972) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2004-06-22-972.md) |
| [Forskrift om sikkerhetsopplæring for fiskere.](/norwegian-laws/forskrifter/forskrift-1989-02-10-88.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1989-02-10-88) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1989-02-10-88.md) |
| [Forskrift om sikkerhetsstillelse for forlatte arbeidstakeres rettigheter på nors](/norwegian-laws/forskrifter/forskrift-2017-12-19-2293.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-12-19-2293) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-12-19-2293.md) |
| [Forskrift om sikkerhetsstyring for mindre lasteskip, passasjerskip og fiskefartø](/norwegian-laws/forskrifter/forskrift-2016-12-16-1770.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2016-12-16-1770) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2016-12-16-1770.md) |
| [Forskrift om sikkerhetsstyringssystem for norske skip og flyttbare innretninger](/norwegian-laws/forskrifter/forskrift-2014-09-05-1191.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2014-09-05-1191) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2014-09-05-1191.md) |
| [Forskrift om sikkerhetstiltak for skip som opererer i polare farvann](/norwegian-laws/forskrifter/forskrift-2016-11-23-1363.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2016-11-23-1363) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2016-11-23-1363.md) |
| [Forskrift om sikkerhetstiltak m.m. på passasjerskip, lasteskip og lektere](/norwegian-laws/forskrifter/forskrift-1987-06-15-507.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1987-06-15-507) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1987-06-15-507.md) |
| [Forskrift om sikring av havneanlegg](/norwegian-laws/forskrifter/forskrift-2013-05-29-538.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-05-29-538) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-05-29-538.md) |
| [Forskrift om sikring av havner](/norwegian-laws/forskrifter/forskrift-2013-05-29-539.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-05-29-539) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-05-29-539.md) |
| [Forskrift om sikringstiltak for gassfyrte anlegg m.m. som bruker propan eller an](/norwegian-laws/forskrifter/forskrift-1983-10-20-1580.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1983-10-20-1580) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1983-10-20-1580.md) |
| [Forskrift om sikringstiltak mot brann og eksplosjon på flyttbare innretninger](/norwegian-laws/forskrifter/forskrift-1984-01-31-227.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1984-01-31-227) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1984-01-31-227.md) |
| [Forskrift om sikringstiltak mot brann på fiske- og fangstfartøy](/norwegian-laws/forskrifter/forskrift-1987-09-04-743.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1987-09-04-743) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1987-09-04-743.md) |
| [Forskrift om sjømannslovens virkeområde](/norwegian-laws/forskrifter/forskrift-1986-01-31-222.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1986-01-31-222) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1986-01-31-222.md) |
| [Forskrift om skip som bruker drivstoff med flammepunkt under 60 °C](/norwegian-laws/forskrifter/forskrift-2016-12-27-1883.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2016-12-27-1883) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2016-12-27-1883.md) |
| [Forskrift om skips navn, kjenningssignal, merking og hjemsted mv.](/norwegian-laws/forskrifter/forskrift-2002-06-27-754.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2002-06-27-754) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2002-06-27-754.md) |
| [Forskrift om skipsarbeidslovens virkeområde](/norwegian-laws/forskrifter/forskrift-2013-08-19-990.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-08-19-990) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-08-19-990.md) |
| [Forskrift om skipsførerens og rederiets plikter i tilfelle straffbare handlinger](/norwegian-laws/forskrifter/forskrift-2005-03-01-235.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2005-03-01-235) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2005-03-01-235.md) |
| [Forskrift om skipssikkerhetslovens virkeområde for flyttbare innretninger](/norwegian-laws/forskrifter/forskrift-2007-06-26-706.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2007-06-26-706) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2007-06-26-706.md) |
| [Forskrift om skipsutstyr](/norwegian-laws/forskrifter/forskrift-2016-08-30-1042.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2016-08-30-1042) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2016-08-30-1042.md) |
| [Forskrift om skyteprøve ved fangst av vågehval](/norwegian-laws/forskrifter/forskrift-2022-10-19-1961.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-10-19-1961) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-10-19-1961.md) |
| [Forskrift om slakterier og tilvirkingsanlegg for akvakulturdyr](/norwegian-laws/forskrifter/forskrift-2006-10-30-1250.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2006-10-30-1250) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2006-10-30-1250.md) |
| [Forskrift om slepearrangement og forflytning av flyttbare innretninger (slepefor](/norwegian-laws/forskrifter/forskrift-2015-12-04-1392.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-12-04-1392) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-12-04-1392.md) |
| [Forskrift om sommertid](/norwegian-laws/forskrifter/forskrift-2007-12-14-1420.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2007-12-14-1420) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2007-12-14-1420.md) |
| [Forskrift om spesielle kvoteordninger for kystfiskeflåten](/norwegian-laws/forskrifter/forskrift-2003-11-07-1309.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2003-11-07-1309) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2003-11-07-1309.md) |
| [Forskrift om spesielle tillatelser til å drive enkelte former for fiske og fangs](/norwegian-laws/forskrifter/forskrift-2006-10-13-1157.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2006-10-13-1157) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2006-10-13-1157.md) |
| [Forskrift om stabilitet, vanntett oppdeling og vanntette/værtette lukningsmidler](/norwegian-laws/forskrifter/forskrift-1991-12-20-878.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1991-12-20-878) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1991-12-20-878.md) |
| [Forskrift om staten sine kontrollørar for fiskesalslaga](/norwegian-laws/forskrifter/forskrift-2013-12-20-1647.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-12-20-1647) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-12-20-1647.md) |
| [Forskrift om statens overtagelse av krigsrisikoen for fiskeflåten.](/norwegian-laws/forskrifter/forskrift-1939-12-22-8707.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1939-12-22-8707) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1939-12-22-8707.md) |
| [Forskrift om statlige fartsgrenser på sjøen](/norwegian-laws/forskrifter/forskrift-2021-12-16-3622.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-12-16-3622) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-12-16-3622.md) |
| [Forskrift om stenging av område i Barentshavet for fiske med torsketrål og snurr](/norwegian-laws/forskrifter/forskrift-1993-08-20-822.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1993-08-20-822) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1993-08-20-822.md) |
| [Forskrift om stenging av områder for fiske etter sei med not](/norwegian-laws/forskrifter/forskrift-2026-04-09-579.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2026-04-09-579) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2026-04-09-579.md) |
| [Forskrift om stenging av områder i Barentshavet og på kysten av Finnmark utenfor](/norwegian-laws/forskrifter/forskrift-2005-01-28-61.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2005-01-28-61) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2005-01-28-61.md) |
| [Forskrift om stopp i fisket etter havbrisling](/norwegian-laws/forskrifter/forskrift-2021-01-20-210.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-01-20-210) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-01-20-210.md) |
| [Forskrift om strukturkvoteordning mv. for havfiskeflåten](/norwegian-laws/forskrifter/forskrift-2005-03-04-193.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2005-03-04-193) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2005-03-04-193.md) |
| [Forskrift om supplerende sikkerhetstiltak for bulkskip](/norwegian-laws/forskrifter/forskrift-2014-07-01-956.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2014-07-01-956) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2014-07-01-956.md) |
| [Forskrift om sveiseutstyr mv. for sveisegassene acetylen og oksygen på flyttbare](/norwegian-laws/forskrifter/forskrift-2003-04-11-480.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2003-04-11-480) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2003-04-11-480.md) |
| [Forskrift om sveising, sveiseutstyr, varmt arbeid og oppbevaring av gassflasker ](/norwegian-laws/forskrifter/forskrift-2002-04-25-422.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2002-04-25-422) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2002-04-25-422.md) |
| [Forskrift om særlige hygieneregler for næringsmidler av animalsk opprinnelse (an](/norwegian-laws/forskrifter/forskrift-2008-12-22-1624.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2008-12-22-1624) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2008-12-22-1624.md) |
| [Forskrift om særlige regler for skip som er vernet eller fredet og fører flere e](/norwegian-laws/forskrifter/forskrift-2014-06-17-768.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2014-06-17-768) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2014-06-17-768.md) |
| [Forskrift om særskilt fartsområde for fartøyer og flyttbare innretninger i petro](/norwegian-laws/forskrifter/forskrift-1987-06-30-579.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1987-06-30-579) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1987-06-30-579.md) |
| [Forskrift om særskilte beskyttelsestiltak rettet mot import av muslinger fra Tyr](/norwegian-laws/forskrifter/forskrift-2022-03-25-469.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-03-25-469) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-03-25-469.md) |
| [Forskrift om særskilte beskyttelsestiltak ved import av akvakulturprodukter fra ](/norwegian-laws/forskrifter/forskrift-2011-05-19-507.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2011-05-19-507) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2011-05-19-507.md) |
| [Forskrift om særskilte beskyttelsestiltak ved import av fiskevarer fra Albania](/norwegian-laws/forskrifter/forskrift-2008-02-05-108.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2008-02-05-108) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2008-02-05-108.md) |
| [Forskrift om særskilte beskyttelsestiltak ved import av ris og risprodukter fra ](/norwegian-laws/forskrifter/forskrift-2012-01-12-35.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2012-01-12-35) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2012-01-12-35.md) |
| [Forskrift om særskilte beskyttelsestiltak ved innførsel av akvatiske dyr og prod](/norwegian-laws/forskrifter/forskrift-2003-05-30-661.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2003-05-30-661) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2003-05-30-661.md) |
| [Forskrift om særskilte krav til akvakulturrelatert virksomhet i eller ved nasjon](/norwegian-laws/forskrifter/forskrift-2009-06-22-961.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2009-06-22-961) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2009-06-22-961.md) |
| [Forskrift om søknad om mesterbrev med bakgrunn i mesterkvalifikasjon fra andre l](/norwegian-laws/forskrifter/forskrift-2015-04-09-420.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-04-09-420) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-04-09-420.md) |
| [Forskrift om søknad om mesterbrev på bakgrunn av realkompetanse](/norwegian-laws/forskrifter/forskrift-2015-04-09-419.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-04-09-419) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-04-09-419.md) |
| [Forskrift om takstberegning og maksimalpriser for løyvepliktig drosjetransport m](/norwegian-laws/forskrifter/forskrift-2010-09-30-1307.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2010-09-30-1307) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2010-09-30-1307.md) |
| [Forskrift om tap av retten til å føre båtførerbevispliktig fritidsbåt](/norwegian-laws/forskrifter/forskrift-2010-06-25-975.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2010-06-25-975) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2010-06-25-975.md) |
| [Forskrift om tariff for oppkreving av gebyrer i forbindelse med utstedelse og fo](/norwegian-laws/forskrifter/forskrift-1969-06-27-4.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1969-06-27-4) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1969-06-27-4.md) |
| [Forskrift om tekniske krav for godkjenning av merkeutstyr på fiskeredskaper for ](/norwegian-laws/forskrifter/forskrift-1990-10-05-868.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1990-10-05-868) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1990-10-05-868.md) |
| [Forskrift om tekniske tilpasninger og overgangsordninger på matområdet i forbind](/norwegian-laws/forskrifter/forskrift-2004-05-20-756.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2004-05-20-756) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2004-05-20-756.md) |
| [Forskrift om tekniske tilpasninger og overgangsordninger på matområdet i forbind](/norwegian-laws/forskrifter/forskrift-2007-10-29-1199.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2007-10-29-1199) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2007-10-29-1199.md) |
| [Forskrift om tekniske tilpasninger og overgangsordninger på matområdet i forbind](/norwegian-laws/forskrifter/forskrift-2014-08-22-1121.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2014-08-22-1121) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2014-08-22-1121.md) |
| [Forskrift om terskelverdier for beslutning om å unnlate revisjon etter aksjelove](/norwegian-laws/forskrifter/forskrift-2018-01-03-7.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2018-01-03-7) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2018-01-03-7.md) |
| [Forskrift om tildeling av løyve til havbruk med matfisk av laks, aure og regnbog](/norwegian-laws/forskrifter/forskrift-2013-06-24-754.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-06-24-754) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-06-24-754.md) |
| [Forskrift om tildeling av nye tillatelser til akvakultur med matfisk i sjø av la](/norwegian-laws/forskrifter/forskrift-2018-05-15-731.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2018-05-15-731) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2018-05-15-731.md) |
| [Forskrift om tildeling av nye tillatelser til akvakultur med matfisk i sjø av la](/norwegian-laws/forskrifter/forskrift-2018-08-30-1323.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2018-08-30-1323) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2018-08-30-1323.md) |
| [Forskrift om tildeling av nye tillatelser til akvakultur med matfisk i sjø av la](/norwegian-laws/forskrifter/forskrift-2023-09-21-1464.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-09-21-1464) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-09-21-1464.md) |
| [Forskrift om tildeling av produksjonskapasitet til akvakultur med matfisk i sjø ](/norwegian-laws/forskrifter/forskrift-2020-05-15-1012.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-05-15-1012) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-05-15-1012.md) |
| [Forskrift om tildeling av produksjonskapasitet til akvakultur med matfisk i sjø ](/norwegian-laws/forskrifter/forskrift-2022-07-22-1386.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-07-22-1386) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-07-22-1386.md) |
| [Forskrift om tildeling av produksjonskapasitet til akvakultur med matfisk i sjø ](/norwegian-laws/forskrifter/forskrift-2024-06-05-924.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-06-05-924) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-06-05-924.md) |
| [Forskrift om tildeling av rekrutteringskvotebonus](/norwegian-laws/forskrifter/forskrift-2022-11-29-2042.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-11-29-2042) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-11-29-2042.md) |
| [Forskrift om tildeling og drift ved havbeiteverksemd (havbeiteforskrifta)](/norwegian-laws/forskrifter/forskrift-2003-08-28-1110.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2003-08-28-1110) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2003-08-28-1110.md) |
| [Forskrift om tilgang til boligannonsering på Internett](/norwegian-laws/forskrifter/forskrift-2009-09-09-1169.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2009-09-09-1169) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2009-09-09-1169.md) |
| [Forskrift om tillatelse til akvakultur for laks, ørret og regnbueørret (laksetil](/norwegian-laws/forskrifter/forskrift-2022-11-07-1929.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-11-07-1929) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-11-07-1929.md) |
| [Forskrift om tillatelse til å opprette og drive radioutstyr om bord i norske ski](/norwegian-laws/forskrifter/forskrift-2025-12-17-2654.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-12-17-2654) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-12-17-2654.md) |
| [Forskrift om tilleggskrav for manøvrering, styringsdyktighet, utrustning og oper](/norwegian-laws/forskrifter/forskrift-2000-12-22-1574.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2000-12-22-1574) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2000-12-22-1574.md) |
| [Forskrift om tilsetningsstoffer til bruk i fôrvarer](/norwegian-laws/forskrifter/forskrift-2005-04-12-319.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2005-04-12-319) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2005-04-12-319.md) |
| [Forskrift om tilskudd til entreprenørskapsfremmende aktiviteter for ungdom](/norwegian-laws/forskrifter/forskrift-2024-04-15-640.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-04-15-640) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-04-15-640.md) |
| [Forskrift om tilskudd til kompetanseutvikling og informasjon knyttet til drift a](/norwegian-laws/forskrifter/forskrift-2025-10-20-2078.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-10-20-2078) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-10-20-2078.md) |
| [Forskrift om tilskudd til nasjonale følgeprogrammer som forvaltes av Norsk Romse](/norwegian-laws/forskrifter/forskrift-2022-01-28-137.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-01-28-137) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-01-28-137.md) |
| [Forskrift om tilskudd til sysselsetting av arbeidstakere til sjøs](/norwegian-laws/forskrifter/forskrift-2016-02-26-204.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2016-02-26-204) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2016-02-26-204.md) |
| [Forskrift om tilskuddsordning tilknyttet nasjonalt senter for jordobservasjon i ](/norwegian-laws/forskrifter/forskrift-2025-06-20-1136.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-06-20-1136) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-06-20-1136.md) |
| [Forskrift om tilsyn etter havne- og farvannsloven](/norwegian-laws/forskrifter/forskrift-2021-09-21-2839.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-09-21-2839) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-09-21-2839.md) |
| [Forskrift om tilsyn med og håndhevelse av båtpassasjerrettigheter etter sjøloven](/norwegian-laws/forskrifter/forskrift-2016-06-20-752.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2016-06-20-752) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2016-06-20-752.md) |
| [Forskrift om tilsyn og sertifikat for norske skip og flyttbare innretninger](/norwegian-laws/forskrifter/forskrift-2014-12-22-1893.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2014-12-22-1893) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2014-12-22-1893.md) |
| [Forskrift om tiltak for å forebygge, begrense og bekjempe pankreassykdom (PD) ho](/norwegian-laws/forskrifter/forskrift-2017-08-29-1318.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-08-29-1318) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-08-29-1318.md) |
| [Forskrift om tjenestevirksomhet og administrativt samarbeid mellom myndigheter (](/norwegian-laws/forskrifter/forskrift-2009-12-18-1644.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2009-12-18-1644) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2009-12-18-1644.md) |
| [Forskrift om transport av akvakulturdyr](/norwegian-laws/forskrifter/forskrift-2008-06-17-820.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2008-06-17-820) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2008-06-17-820.md) |
| [Forskrift om tryggleik i passasjerområde](/norwegian-laws/forskrifter/forskrift-2021-12-17-3666.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-12-17-3666) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-12-17-3666.md) |
| [Forskrift om turistfiskevirksomheter](/norwegian-laws/forskrifter/forskrift-2017-07-05-1141.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-07-05-1141) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-07-05-1141.md) |
| [Forskrift om tvangsmulkt og lovbrotsgebyr etter omstillingslova](/norwegian-laws/forskrifter/forskrift-2008-06-24-713.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2008-06-24-713) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2008-06-24-713.md) |
| [Forskrift om tvistebehandling på norske skip](/norwegian-laws/forskrifter/forskrift-2002-04-25-424.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2002-04-25-424) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2002-04-25-424.md) |
| [Forskrift om undersøkelse av sjøulykker](/norwegian-laws/forskrifter/forskrift-2012-11-30-1115.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2012-11-30-1115) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2012-11-30-1115.md) |
| [Forskrift om undersøkelse, stansing og bording av utenlandsk skip ved mistanke o](/norwegian-laws/forskrifter/forskrift-2007-07-02-850.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2007-07-02-850) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2007-07-02-850.md) |
| [Forskrift om undervisningskvoter](/norwegian-laws/forskrifter/forskrift-2014-12-19-1825.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2014-12-19-1825) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2014-12-19-1825.md) |
| [Forskrift om unntak for samarbeid mv. innen landbruk og fiske.](/norwegian-laws/forskrifter/forskrift-2004-04-23-651.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2004-04-23-651) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2004-04-23-651.md) |
| [Forskrift om unntak fra klageadgangen i saker avgjort av Norges Eksportråd.](/norwegian-laws/forskrifter/forskrift-1984-03-30-936.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1984-03-30-936) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1984-03-30-936.md) |
| [Forskrift om unntak fra kravene om kontroll av økologiske produkter ved en grens](/norwegian-laws/forskrifter/forskrift-2022-06-21-1172.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-06-21-1172) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-06-21-1172.md) |
| [Forskrift om unntak fra kravet til bruk av flyteutstyr på fritidsbåter](/norwegian-laws/forskrifter/forskrift-2015-04-27-409.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-04-27-409) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-04-27-409.md) |
| [Forskrift om unntak fra lov om havner og farvann for sjø- og landområder samt ar](/norwegian-laws/forskrifter/forskrift-1989-05-12-302.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1989-05-12-302) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1989-05-12-302.md) |
| [Forskrift om unntak fra notifikasjonsplikt for offentlig støtte](/norwegian-laws/forskrifter/forskrift-2023-01-02-2.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-01-02-2) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-01-02-2.md) |
| [Forskrift om utbetaling til norske sjøfolk som seilte ute i krigsårene.](/norwegian-laws/forskrifter/forskrift-1972-08-25-3.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1972-08-25-3) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1972-08-25-3.md) |
| [Forskrift om utforming og innmontering av sorteringsrist i direkte fiske etter s](/norwegian-laws/forskrifter/forskrift-2012-11-26-1105.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2012-11-26-1105) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2012-11-26-1105.md) |
| [Forskrift om utforming og innmontering av sorteringsrist i fisket etter kolmule ](/norwegian-laws/forskrifter/forskrift-2009-04-30-471.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2009-04-30-471) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2009-04-30-471.md) |
| [Forskrift om utforming og innmontering av sorteringsrist i reketrål](/norwegian-laws/forskrifter/forskrift-2012-11-26-1104.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2012-11-26-1104) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2012-11-26-1104.md) |
| [Forskrift om utførselsregulering av fisk og fiskevarer fra sportsfiske](/norwegian-laws/forskrifter/forskrift-2006-06-01-570.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2006-06-01-570) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2006-06-01-570.md) |
| [Forskrift om utlendingers fiske og fangst mv. i Norges økonomiske sone og landin](/norwegian-laws/forskrifter/forskrift-1977-05-13-2.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1977-05-13-2) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1977-05-13-2.md) |
| [Forskrift om utlendingers fiske og fangst mv. i fiskerisonen ved Jan Mayen](/norwegian-laws/forskrifter/forskrift-1999-12-21-1396.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1999-12-21-1396) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1999-12-21-1396.md) |
| [Forskrift om utmåling og lempning av overtredelsesgebyr](/norwegian-laws/forskrifter/forskrift-2013-12-11-1465.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-12-11-1465) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-12-11-1465.md) |
| [Forskrift om utpeking av Kystverket som klageinstans etter lov 21. juni 2019 nr.](/norwegian-laws/forskrifter/forskrift-2021-04-21-1227.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-04-21-1227) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-04-21-1227.md) |
| [Forskrift om utsatte frister på transportområdet knyttet til covid-19](/norwegian-laws/forskrifter/forskrift-2020-06-18-1227.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-06-18-1227) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-06-18-1227.md) |
| [Forskrift om utveksling av opplysninger gjennom registersammenkoblingssystemet (](/norwegian-laws/forskrifter/forskrift-2025-08-06-1613.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-08-06-1613) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-08-06-1613.md) |
| [Forskrift om utvidelse av oppdrettslovens virkeområde.](/norwegian-laws/forskrifter/forskrift-2001-03-16-243.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2001-03-16-243) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2001-03-16-243.md) |
| [Forskrift om utviding av det stadlege verkeområde til lov om forvaltning av vilt](/norwegian-laws/forskrifter/forskrift-2016-01-08-9.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2016-01-08-9) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2016-01-08-9.md) |
| [Forskrift om utøvelse av fangst av vågehval](/norwegian-laws/forskrifter/forskrift-2022-04-01-511.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-04-01-511) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-04-01-511.md) |
| [Forskrift om utøvelse av hvalsafari](/norwegian-laws/forskrifter/forskrift-2019-12-05-1651.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-12-05-1651) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-12-05-1651.md) |
| [Forskrift om utøvelse av selfangst](/norwegian-laws/forskrifter/forskrift-2022-04-28-763.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-04-28-763) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-04-28-763.md) |
| [Forskrift om vakthold for dekksavdelingen og maskinavdelingen på norske fiske- o](/norwegian-laws/forskrifter/forskrift-1987-06-30-580.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1987-06-30-580) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1987-06-30-580.md) |
| [Forskrift om vakthold på passasjer- og lasteskip](/norwegian-laws/forskrifter/forskrift-1999-04-27-537.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1999-04-27-537) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1999-04-27-537.md) |
| [Forskrift om vanntrekk ved landing av pelagisk fanget råstoff til konsum](/norwegian-laws/forskrifter/forskrift-2004-04-15-627.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2004-04-15-627) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2004-04-15-627.md) |
| [Forskrift om varer av edelt metall mv.](/norwegian-laws/forskrifter/forskrift-2011-01-10-12.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2011-01-10-12) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2011-01-10-12.md) |
| [Forskrift om varsel og melding om sjukdom hos dyr på Svalbard](/norwegian-laws/forskrifter/forskrift-2014-12-19-1841.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2014-12-19-1841) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2014-12-19-1841.md) |
| [Forskrift om vern av sårbare marine økosystem i områder utenfor nasjonal jurisdi](/norwegian-laws/forskrifter/forskrift-2014-10-14-1303.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2014-10-14-1303) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2014-10-14-1303.md) |
| [Forskrift om verne-, miljø- og sikkerhetstiltak på flyttbare innretninger](/norwegian-laws/forskrifter/forskrift-1987-09-04-859.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1987-09-04-859) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1987-09-04-859.md) |
| [Forskrift om videretransport av fisk](/norwegian-laws/forskrifter/forskrift-2006-04-21-433.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2006-04-21-433) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2006-04-21-433.md) |
| [Forskrift om vilkår for å få mesterbrev](/norwegian-laws/forskrifter/forskrift-2000-12-08-1280.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2000-12-08-1280) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2000-12-08-1280.md) |
| [Forskrift om vurdering av den praksis som godkjennes ved søknad om mesterbrev.](/norwegian-laws/forskrifter/forskrift-2002-03-13-407.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2002-03-13-407) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2002-03-13-407.md) |
| [Forskrift om åpne treskip som fører flere enn 12 passasjerer](/norwegian-laws/forskrifter/forskrift-2020-01-23-69.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-01-23-69) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-01-23-69.md) |
| [Forskrift om økologisk produksjon og merking av økologiske landbruksprodukter, a](/norwegian-laws/forskrifter/forskrift-2022-06-11-1171.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-06-11-1171) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-06-11-1171.md) |
| [Forskrift som utfyller dyrehelseforskriften med bestemmelser om forebygging og b](/norwegian-laws/forskrifter/forskrift-2022-04-06-634.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-04-06-634) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-04-06-634.md) |
| [Forskrift som utfyller dyrehelseforskriften med bestemmelser om import av visse ](/norwegian-laws/forskrifter/forskrift-2022-04-06-633.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-04-06-633) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-04-06-633.md) |
| [Forskrift som utfyller dyrehelseforskriften med bestemmelser om krav til biosikk](/norwegian-laws/forskrifter/forskrift-2022-04-05-624.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-04-05-624) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-04-05-624.md) |
| [Forskrift som utfyller dyrehelseforskriften med bestemmelser om melding, rapport](/norwegian-laws/forskrifter/forskrift-2022-04-06-632.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-04-06-632) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-04-06-632.md) |
| [Forskrift til lov om Enhetsregisteret (enhetsregisterforskriften)](/norwegian-laws/forskrifter/forskrift-2025-08-06-1610.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-08-06-1610) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-08-06-1610.md) |
| [Forskrift til lov om Foretaksregisteret (foretaksregisterforskriften)](/norwegian-laws/forskrifter/forskrift-2025-08-06-1611.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-08-06-1611) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-08-06-1611.md) |
| [Forskrift til lov om Oppgaveregisteret](/norwegian-laws/forskrifter/forskrift-1997-10-10-1090.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1997-10-10-1090) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1997-10-10-1090.md) |
| [Forskrift til lov om linjekonferanser m.v.](/norwegian-laws/forskrifter/forskrift-1985-12-06-2076.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1985-12-06-2076) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1985-12-06-2076.md) |
| [Forskrift til lov om statlig garantiordning for lån til små og mellomstore bedri](/norwegian-laws/forskrifter/forskrift-2020-03-27-490.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-03-27-490) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-03-27-490.md) |
| [Forskrift til mesterbrevloven](/norwegian-laws/forskrifter/forskrift-1986-12-12-2187.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1986-12-12-2187) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1986-12-12-2187.md) |
| [Forskrift til mineralloven](/norwegian-laws/forskrifter/forskrift-2009-12-23-1842.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2009-12-23-1842) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2009-12-23-1842.md) |
| [Forskrift til patentstyrelova (patentstyreforskrifta)](/norwegian-laws/forskrifter/forskrift-2013-03-01-246.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-03-01-246) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-03-01-246.md) |
| [Forskrift til utfylling og gjennomføring av lov om midlertidig tilskuddsordning ](/norwegian-laws/forskrifter/forskrift-2021-06-04-1792.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-06-04-1792) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-06-04-1792.md) |
| [Forskrift til utfylling og gjennomføring av lov om midlertidig tilskuddsordning ](/norwegian-laws/forskrifter/forskrift-2022-01-28-139.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-01-28-139) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-01-28-139.md) |
| [Forskrift til utfylling og gjennomføring av lov om midlertidig tilskuddsordning ](/norwegian-laws/forskrifter/forskrift-2020-12-21-3085.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-12-21-3085) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-12-21-3085.md) |
| [Forskrift til utfylling og gjennomføring av lov om midlertidig tilskuddsordning ](/norwegian-laws/forskrifter/forskrift-2021-05-01-1367.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-05-01-1367) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-05-01-1367.md) |
| [Forskrifter for gjennomføring av Gatt-avtalen om offentlige innkjøp.](/norwegian-laws/forskrifter/forskrift-1981-11-19-8761.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1981-11-19-8761) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1981-11-19-8761.md) |
| [Forskrifter om bergverksordningen for Jan Mayen.](/norwegian-laws/forskrifter/forskrift-1976-04-23-1.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1976-04-23-1) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1976-04-23-1.md) |
| [Forskrifter om gjensidig inspeksjonsrett for medlemsstatene i Kommisjonen for fi](/norwegian-laws/forskrifter/forskrift-1969-12-19-8955.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1969-12-19-8955) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1969-12-19-8955.md) |
| [Forskrifter om priser for eksport av tørrfisk.](/norwegian-laws/forskrifter/forskrift-1983-01-17-67.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1983-01-17-67) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1983-01-17-67.md) |
| [Forskrifter om prisregler for jern og stål.](/norwegian-laws/forskrifter/forskrift-1974-12-23-4.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1974-12-23-4) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1974-12-23-4.md) |
| [Fullmakt til å gjøre unntak fra tvistemålslovens og straffeprosesslovens bestemm](/norwegian-laws/forskrifter/forskrift-1993-12-17-1315.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1993-12-17-1315) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1993-12-17-1315.md) |
| [Føresegn om kompensasjon for ulønt arbeidsinnsats i Skattefunn-godkjende forskin](/norwegian-laws/forskrifter/forskrift-2006-02-07-123.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2006-02-07-123) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2006-02-07-123.md) |
| [Midlertidig forskrift om automatiske vekter og automatiske veiesystemer ved mott](/norwegian-laws/forskrifter/forskrift-2026-02-03-130.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2026-02-03-130) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2026-02-03-130.md) |
| [Midlertidig forskrift om krav til vekter og automatiske veiesystemer til bruk ve](/norwegian-laws/forskrifter/forskrift-2026-02-04-164.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2026-02-04-164) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2026-02-04-164.md) |
| [Midlertidig forskrift om unntak fra bestemmelsene i økologiforskriften om kontro](/norwegian-laws/forskrifter/forskrift-2020-09-28-1914.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-09-28-1914) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-09-28-1914.md) |
| [Omorganisering av Bergvesenet.](/norwegian-laws/forskrifter/forskrift-1985-11-29-1994.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1985-11-29-1994) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1985-11-29-1994.md) |
| [Overgangsreglar til lov 22. juni 2012 nr. 58 om Patentstyret og Klagenemnda for ](/norwegian-laws/forskrifter/forskrift-2013-03-01-245.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-03-01-245) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-03-01-245.md) |
| [Overgangsregler til lov 20. juni 2023 nr. 80 om endringer i konkurranseloven (sø](/norwegian-laws/forskrifter/forskrift-2023-06-29-1162.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-06-29-1162) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-06-29-1162.md) |
| [Overgangsregler til lov 6. desember 2019 nr. 77 om endringer i aksjelovgivningen](/norwegian-laws/forskrifter/forskrift-2019-12-11-1715.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-12-11-1715) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-12-11-1715.md) |
| [Protokoll om opprettelse av et fond for norsk/svensk industrielt samarbeid](/norwegian-laws/forskrifter/forskrift-1981-05-08-4026.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1981-05-08-4026) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1981-05-08-4026.md) |
| [Tillatelse til akvakultur av andre arter enn laks, ørret og regnbueørret (andre ](/norwegian-laws/forskrifter/forskrift-2004-12-22-1799.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2004-12-22-1799) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2004-12-22-1799.md) |
| [Utvidelse av det geografiske virkeområdet for havne- og farvannsloven](/norwegian-laws/forskrifter/forskrift-2025-12-05-2419.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-12-05-2419) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-12-05-2419.md) |
| [Utvidelse av det geografiske virkeområdet for lov 17. april 2009 nr. 19 om havne](/norwegian-laws/forskrifter/forskrift-2014-10-10-1287.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2014-10-10-1287) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2014-10-10-1287.md) |
| [Vedtak om gebyrer for utpeking av Norge i internasjonale varemerkeregistreringer](/norwegian-laws/forskrifter/forskrift-2014-03-26-334.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2014-03-26-334) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2014-03-26-334.md) |
