# Klima- og miljødepartementet

*185 forskrifter*

| Forskrift | Lovdata | Historikk |
|-----------|---------|-----------|
| [Erklæring angående beskyttelse av kulturverdier i tilfelle av væpnet konflikt.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1952-12-11-2.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1952-12-11-2) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1952-12-11-2.md) |
| [Forskrift for bruk av motorkjøretøyer i utmark og på islagte vassdrag](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1988-05-15-356.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1988-05-15-356) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1988-05-15-356.md) |
| [Forskrift om CO2-kompensasjon for industrien for perioden 2021–2030](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2024-12-19-3395.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-12-19-3395) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-12-19-3395.md) |
| [Forskrift om EU-gjødselvarer (EU-gjødselvareforskriften)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2024-03-06-538.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-03-06-538) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-03-06-538.md) |
| [Forskrift om Klagenemnda for miljøinformasjon](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2003-12-14-1572.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2003-12-14-1572) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2003-12-14-1572.md) |
| [Forskrift om Marka (markalovforskriften)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2015-09-04-1032.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-09-04-1032) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-09-04-1032.md) |
| [Forskrift om Miljøvedtaksregisteret](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2013-06-14-643.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-06-14-643) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-06-14-643.md) |
| [Forskrift om Van Mijenfjorden nasjonalpark på Svalbard](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-06-18-1980.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-06-18-1980) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-06-18-1980.md) |
| [Forskrift om avfallshåndtering og avfalls- og avløpsgebyrer i Longyearbyen plano](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2023-03-01-435.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-03-01-435) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-03-01-435.md) |
| [Forskrift om ballastvannbehandling på skip og flyttbare innretninger](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2017-09-08-1368.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-09-08-1368) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-09-08-1368.md) |
| [Forskrift om begrensning av forurensning (forurensningsforskriften)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2004-06-01-931.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2004-06-01-931) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2004-06-01-931.md) |
| [Forskrift om begrensning i bruk av helse- og miljøfarlige kjemikalier og andre p](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2004-06-01-922.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2004-06-01-922) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2004-06-01-922.md) |
| [Forskrift om beskyttelse av tradisjonell kunnskap knyttet til genetisk materiale](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2016-11-25-1367.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2016-11-25-1367) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2016-11-25-1367.md) |
| [Forskrift om biocider (Biocidforskriften)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2017-04-18-480.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-04-18-480) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-04-18-480.md) |
| [Forskrift om bruk av kommunens myndighet etter lov om motorferdsel i utmark og v](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1988-03-14-225.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1988-03-14-225) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1988-03-14-225.md) |
| [Forskrift om bruk av lov 19. juni 2009 nr. 100 om forvaltning av naturens mangfo](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2018-06-15-890.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2018-06-15-890) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2018-06-15-890.md) |
| [Forskrift om båndtvang for hund på Svalbard](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2002-06-28-651.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2002-06-28-651) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2002-06-28-651.md) |
| [Forskrift om definisjon av marin gassolje i svalbardmiljøloven § 82a](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-12-13-3514.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-12-13-3514) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-12-13-3514.md) |
| [Forskrift om deklarering av kjemikalier til produktregisteret (deklareringsforsk](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2015-05-19-541.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-05-19-541) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-05-19-541.md) |
| [Forskrift om dragehode (Dracocephalum ruyschiana) som prioritert art](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2011-05-20-517.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2011-05-20-517) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2011-05-20-517.md) |
| [Forskrift om drift av akvakulturanlegg (akvakulturdriftsforskriften)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2008-06-17-822.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2008-06-17-822) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2008-06-17-822.md) |
| [Forskrift om dverggås (Anser erythropus) som prioritert art](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2011-05-20-518.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2011-05-20-518) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2011-05-20-518.md) |
| [Forskrift om dvergålegras (Zostera noltei) som prioritert art](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2015-05-22-546.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-05-22-546) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-05-22-546.md) |
| [Forskrift om elfenbenslav som prioritert art](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2020-12-04-2613.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-12-04-2613) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-12-04-2613.md) |
| [Forskrift om elvesandjeger (Cicindela maritima) som prioritert art](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2011-05-20-519.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2011-05-20-519) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2011-05-20-519.md) |
| [Forskrift om endring i forskrift om begrensning i bruk av helse- og miljøfarlige](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2024-11-25-3026.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-11-25-3026) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-11-25-3026.md) |
| [Forskrift om endring i forskrift om faglig ansvarsfordeling mv. etter kulturminn](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2004-12-20-1718.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2004-12-20-1718) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2004-12-20-1718.md) |
| [Forskrift om endring i forskrift om fiske etter anadrome laksefisk i sjøen](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2024-05-20-1009.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-05-20-1009) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-05-20-1009.md) |
| [Forskrift om endring i forskrift om miljøvennlig utforming av energirelaterte pr](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2026-03-05-354.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2026-03-05-354) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2026-03-05-354.md) |
| [Forskrift om endring i forskrift om sikkerhet ved leketøy (leketøyforskriften)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2026-05-07-763.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2026-05-07-763) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2026-05-07-763.md) |
| [Forskrift om endring i forskrift om utføring av aktiviteter i petroleumsvirksomh](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2024-12-18-3263.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-12-18-3263) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-12-18-3263.md) |
| [Forskrift om endringer i forskrift om fiske etter anadrome laksefisk i vassdrag](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2024-05-20-1548.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-05-20-1548) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-05-20-1548.md) |
| [Forskrift om eremitt (Osmoderma eremita) som prioritert art](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2011-05-20-520.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2011-05-20-520) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2011-05-20-520.md) |
| [Forskrift om erstatning for tap og følgekostnader når tamrein blir drept eller s](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2001-05-04-468.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2001-05-04-468) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2001-05-04-468.md) |
| [Forskrift om erstatning når husdyr blir drept eller skadet av rovvilt](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2014-05-30-677.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2014-05-30-677) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2014-05-30-677.md) |
| [Forskrift om etablering og drift av kultiveringsanlegg for fisk og kreps](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1992-12-30-1232.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1992-12-30-1232) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1992-12-30-1232.md) |
| [Forskrift om fangst av elvemusling](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1992-12-30-1230.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1992-12-30-1230) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1992-12-30-1230.md) |
| [Forskrift om fastsetting av myndighet mv. etter kulturminneloven](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2019-02-15-127.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-02-15-127) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-02-15-127.md) |
| [Forskrift om ferdselsbegrensning i Nyrøysaområdet på Bouvetøya.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2005-06-24-687.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2005-06-24-687) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2005-06-24-687.md) |
| [Forskrift om ferdselsforbud ved automatisk freda kulturminner ved Midterhuken, B](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2009-09-23-1220.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2009-09-23-1220) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2009-09-23-1220.md) |
| [Forskrift om ferskvannskreps.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2001-07-13-833.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2001-07-13-833) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2001-07-13-833.md) |
| [Forskrift om fiske etter anadrome laksefisk i sjøen](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-03-15-797.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-03-15-797) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-03-15-797.md) |
| [Forskrift om fiske etter anadrome laksefisk i vassdrag](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-03-15-798.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-03-15-798) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-03-15-798.md) |
| [Forskrift om fiske etter innlandsfisk mv. og fangst av kreps (innlandsfiskeforsk](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2009-06-26-851.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2009-06-26-851) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2009-06-26-851.md) |
| [Forskrift om fiske etter røye på Svalbard i 2026](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2026-01-07-12.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2026-01-07-12) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2026-01-07-12.md) |
| [Forskrift om fiskeravgift](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1993-06-15-532.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1993-06-15-532) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1993-06-15-532.md) |
| [Forskrift om fjellrev (Vulpes lagopus) som prioritert art](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2015-01-23-60.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-01-23-60) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-01-23-60.md) |
| [Forskrift om forbud mot bruk av mineralolje til oppvarming av bygninger og fossi](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2018-06-28-1060.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2018-06-28-1060) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2018-06-28-1060.md) |
| [Forskrift om forbud mot omsetning i Norge av bestemte genmodifiserte produkter.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2000-12-15-1268.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2000-12-15-1268) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2000-12-15-1268.md) |
| [Forskrift om forbud mot utslipp av kloakk fra fritidsbåter i Oslofjorden](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2024-05-31-886.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-05-31-886) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-05-31-886.md) |
| [Forskrift om forurensning og avfall på Svalbard](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2020-07-03-1517.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-07-03-1517) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-07-03-1517.md) |
| [Forskrift om forurensningslovens anvendelse på radioaktiv forurensning og radioa](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2010-11-01-1394.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2010-11-01-1394) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2010-11-01-1394.md) |
| [Forskrift om forvaltning av rovvilt](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2005-03-18-242.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2005-03-18-242) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2005-03-18-242.md) |
| [Forskrift om forvaltning av vilt og ferskvannsfisk på Svalbard og Jan Mayen](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1978-08-11-3765.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1978-08-11-3765) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1978-08-11-3765.md) |
| [Forskrift om framleie av fiskerett.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1993-06-25-570.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1993-06-25-570) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1993-06-25-570.md) |
| [Forskrift om fredning av Bjørnøya naturreservat på Svalbard](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2002-08-16-903.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2002-08-16-903) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2002-08-16-903.md) |
| [Forskrift om fredning av Bouvetøya med tilliggende territorialfarvann som naturr](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1971-12-17-9.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1971-12-17-9) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1971-12-17-9.md) |
| [Forskrift om fredning av Festningen geotopvernområde på Svalbard](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2003-09-26-1190.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2003-09-26-1190) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2003-09-26-1190.md) |
| [Forskrift om fredning av Hopen naturreservat på Svalbard](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2003-09-26-1185.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2003-09-26-1185) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2003-09-26-1185.md) |
| [Forskrift om fredning av Indre Wijdefjorden nasjonalpark på Svalbard](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2005-09-09-1046.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2005-09-09-1046) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2005-09-09-1046.md) |
| [Forskrift om fredning av Jan Mayen naturreservat](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2010-11-19-1456.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2010-11-19-1456) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2010-11-19-1456.md) |
| [Forskrift om fredning av Masimjelt (Oxytropis deflexa) og Purpurkarse (Braya pur](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1983-02-25-512.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1983-02-25-512) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1983-02-25-512.md) |
| [Forskrift om fredning av Nordre Isfjorden nasjonalpark på Svalbard](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2003-09-26-1187.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2003-09-26-1187) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2003-09-26-1187.md) |
| [Forskrift om fredning av Ossian Sars naturreservat](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2003-09-26-1188.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2003-09-26-1188) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2003-09-26-1188.md) |
| [Forskrift om fredning av Sassen-Bünsow Land nasjonalpark på Svalbard](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2003-09-26-1189.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2003-09-26-1189) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2003-09-26-1189.md) |
| [Forskrift om fredning av bygninger og anlegg i Landsverneplan for Forsvaret.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2004-05-06-718.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2004-05-06-718) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2004-05-06-718.md) |
| [Forskrift om fredning av mistelteinen. Delegering av myndighet.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1976-10-29-3763.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1976-10-29-3763) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1976-10-29-3763.md) |
| [Forskrift om fredning av statens kulturhistoriske eiendommer](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2011-11-09-1088.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2011-11-09-1088) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2011-11-09-1088.md) |
| [Forskrift om fredning av truede arter](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2001-12-21-1525.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2001-12-21-1525) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2001-12-21-1525.md) |
| [Forskrift om fredning for Moffen naturreservat på Svalbard](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1983-06-03-1029.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1983-06-03-1029) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1983-06-03-1029.md) |
| [Forskrift om fremmede organismer](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2015-06-19-716.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-06-19-716) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-06-19-716.md) |
| [Forskrift om frivillig deltakelse for organisasjoner i en fellesskapsordning for](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2006-05-03-484.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2006-05-03-484) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2006-05-03-484.md) |
| [Forskrift om fylkeskommunenes oppgaver innenfor friluftslivsområdet](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2019-09-30-1310.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-09-30-1310) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-09-30-1310.md) |
| [Forskrift om fysiske tiltak i vassdrag](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2004-11-15-1468.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2004-11-15-1468) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2004-11-15-1468.md) |
| [Forskrift om gebyr til statskassen for arbeid med kontroll etter produktkontroll](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2024-04-17-649.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-04-17-649) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-04-17-649.md) |
| [Forskrift om gjennomføring av flertallsvedtak vedrørende organisering og drift a](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2000-05-03-378.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2000-05-03-378) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2000-05-03-378.md) |
| [Forskrift om gjenvinning av skip og flyttbare innretninger](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2018-12-06-1813.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2018-12-06-1813) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2018-12-06-1813.md) |
| [Forskrift om gjenvinning og behandling av avfall (avfallsforskriften)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2004-06-01-930.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2004-06-01-930) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2004-06-01-930.md) |
| [Forskrift om grunnsatser for tap av tamrein drept eller skadet av rovvilt reindr](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-06-27-1345.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-06-27-1345) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-06-27-1345.md) |
| [Forskrift om honningblom (Herminium monorchis) som prioritert art](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2011-05-20-521.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2011-05-20-521) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2011-05-20-521.md) |
| [Forskrift om håndtering av dyrekadaver ved utbrudd av smittsomme dyresjukdommer](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2008-05-07-438.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2008-05-07-438) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2008-05-07-438.md) |
| [Forskrift om høsting på Svalbard](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2002-06-24-712.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2002-06-24-712) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2002-06-24-712.md) |
| [Forskrift om innførsel, utførsel, besittelse mv. av truede arter av vill fauna o](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2018-06-15-889.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2018-06-15-889) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2018-06-15-889.md) |
| [Forskrift om inngrep på åpent hav og i Norges økonomiske sone i tilfelle av havf](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1997-09-19-1061.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1997-09-19-1061) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1997-09-19-1061.md) |
| [Forskrift om jakt, felling, fangst og fiske i statsallmenning](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-03-11-681.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-03-11-681) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-03-11-681.md) |
| [Forskrift om jakt, felling, fangst og fiske på statsgrunn utenfor statsallmennin](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2007-08-20-987.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2007-08-20-987) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2007-08-20-987.md) |
| [Forskrift om jakt- og fangsttider samt sanking av egg og dun for jaktsesongene f](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2022-01-21-128.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-01-21-128) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-01-21-128.md) |
| [Forskrift om klassifisering, merking og emballering av stoffer og stoffblandinge](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2012-06-16-622.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2012-06-16-622) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2012-06-16-622.md) |
| [Forskrift om klinisk utprøving og utlevering av GMO-legemidler til behandling el](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2020-10-23-2124.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-10-23-2124) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-10-23-2124.md) |
| [Forskrift om klippeblåvinge (Scolitantides orion) som prioritert art](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2011-05-20-522.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2011-05-20-522) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2011-05-20-522.md) |
| [Forskrift om kommunens myndighet etter forurensningsloven](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2024-12-20-3400.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-12-20-3400) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-12-20-3400.md) |
| [Forskrift om konsekvensutredning etter genteknologiloven](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2005-12-16-1495.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2005-12-16-1495) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2005-12-16-1495.md) |
| [Forskrift om konsekvensutredninger](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2017-06-21-854.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-06-21-854) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-06-21-854.md) |
| [Forskrift om konsekvensutredninger og avgrensing av planområdene på Svalbard](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2002-06-28-650.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2002-06-28-650) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2002-06-28-650.md) |
| [Forskrift om krav til klimagassintensitet for skip som brukes i forbindelse med ](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2026-05-12-793.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2026-05-12-793) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2026-05-12-793.md) |
| [Forskrift om kvoteplikt og handel med kvoter for utslipp av klimagasser (klimakv](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2004-12-23-1851.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2004-12-23-1851) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2004-12-23-1851.md) |
| [Forskrift om lagring og bruk av gjødsel mv.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-01-29-115.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-01-29-115) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-01-29-115.md) |
| [Forskrift om leiropphold på Svalbard](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2002-06-27-731.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2002-06-27-731) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2002-06-27-731.md) |
| [Forskrift om maskiner](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2009-05-20-544.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2009-05-20-544) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2009-05-20-544.md) |
| [Forskrift om merking, transport, import og eksport av genmodifiserte organismer.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2005-09-02-1009.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2005-09-02-1009) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2005-09-02-1009.md) |
| [Forskrift om midlertidig ordning for energitilskudd til næringslivet som følge a](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2022-11-21-1994.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-11-21-1994) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-11-21-1994.md) |
| [Forskrift om miljøavgift for tilreisende til Svalbard](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2006-12-22-1532.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2006-12-22-1532) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2006-12-22-1532.md) |
| [Forskrift om miljømessig sikkerhet for skip og flyttbare innretninger](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2012-05-30-488.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2012-05-30-488) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2012-05-30-488.md) |
| [Forskrift om miljøvennlig utforming av energirelaterte produkter (økodesignforsk](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2011-02-23-190.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2011-02-23-190) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2011-02-23-190.md) |
| [Forskrift om miljøvern og sikkerhet i Antarktis](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2013-04-26-412.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-04-26-412) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-04-26-412.md) |
| [Forskrift om motorferdsel på Svalbard](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2002-06-24-723.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2002-06-24-723) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2002-06-24-723.md) |
| [Forskrift om nasjonalparkene Sør-Spitsbergen, Forlandet og Nordvest-Spitsbergen,](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2014-04-04-377.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2014-04-04-377) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2014-04-04-377.md) |
| [Forskrift om nedsenking av garnredskap](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2003-06-20-737.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2003-06-20-737) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2003-06-20-737.md) |
| [Forskrift om omsetning av tømmer og treprodukter med opprinnelse utenfor Norge](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2015-04-24-406.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-04-24-406) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-04-24-406.md) |
| [Forskrift om oppgaveplikt og om redskaper som er tillatt benyttet ved fiske ette](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2003-02-25-256.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2003-02-25-256) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2003-02-25-256.md) |
| [Forskrift om opprettelse av nasjonalparker, naturresevater og fuglereservater, S](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1973-06-01-1.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1973-06-01-1) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1973-06-01-1.md) |
| [Forskrift om overgangsbestemmelser etter naturmangfoldloven § 77 i forbindelse m](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2010-10-15-1339.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2010-10-15-1339) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2010-10-15-1339.md) |
| [Forskrift om overgangsbestemmelser ved ikrafttreden av lov om miljøvern på Svalb](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2002-06-28-649.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2002-06-28-649) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2002-06-28-649.md) |
| [Forskrift om overtredelsesgebyr etter lakse- og innlandsfiskloven](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-06-01-1741.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-06-01-1741) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-06-01-1741.md) |
| [Forskrift om overtredelsesgebyr etter motorferdselloven](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2024-02-27-355.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-02-27-355) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-02-27-355.md) |
| [Forskrift om overtredelsesgebyr etter svalbardmiljøloven § 96a](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2024-02-06-224.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-02-06-224) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-02-06-224.md) |
| [Forskrift om overtredelsesgebyr for overtredelser av bestemmelser i REACH-forskr](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2023-09-29-1568.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-09-29-1568) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-09-29-1568.md) |
| [Forskrift om pliktig organisering og drift av vassdrag med anadrome laksefisk](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2013-06-25-761.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-06-25-761) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-06-25-761.md) |
| [Forskrift om rammer for vannforvaltningen](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2006-12-15-1446.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2006-12-15-1446) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2006-12-15-1446.md) |
| [Forskrift om reduksjon av utslipp av bensindamp](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1999-02-10-206.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1999-02-10-206) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1999-02-10-206.md) |
| [Forskrift om registrering og merking av eldre preparater av dødt vilt.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2005-03-21-247.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2005-03-21-247) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2005-03-21-247.md) |
| [Forskrift om registrering, vurdering, godkjenning og begrensning av kjemikalier ](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2008-05-30-516.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2008-05-30-516) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2008-05-30-516.md) |
| [Forskrift om rett til å foreta eiendomsinngrep etter oreigningsloven.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1983-07-08-1250.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1983-07-08-1250) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1983-07-08-1250.md) |
| [Forskrift om rovdyravvisende gjerde](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2012-06-22-652.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2012-06-22-652) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2012-06-22-652.md) |
| [Forskrift om rød skogfrue (Cephalanthera rubra) som prioritert art](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2011-05-20-523.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2011-05-20-523) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2011-05-20-523.md) |
| [Forskrift om satser for avgift for jakt-, fangst- og fiskekort m.m. på Svalbard.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2006-12-01-1578.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2006-12-01-1578) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2006-12-01-1578.md) |
| [Forskrift om sikkerhet ved leketøy (leketøyforskriften)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2013-11-18-1403.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-11-18-1403) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-11-18-1403.md) |
| [Forskrift om skadefelling, dødt vilt og bruk av vilt i oppdrett, forskning og dy](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2020-04-01-565.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-04-01-565) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-04-01-565.md) |
| [Forskrift om skredmjelt (Oxytropis campestris ssp. scotica) som prioritert art](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2015-05-29-561.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-05-29-561) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-05-29-561.md) |
| [Forskrift om smittefarlig avfall fra helsetjeneste og dyrehelsetjeneste mv.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2005-10-11-1196.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2005-10-11-1196) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2005-10-11-1196.md) |
| [Forskrift om styring og opplysningsplikt i petroleumsvirksomheten og på enkelte ](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2010-04-29-611.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2010-04-29-611) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2010-04-29-611.md) |
| [Forskrift om svarthalespove (Limosa limosa) som prioritert art](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2011-05-20-524.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2011-05-20-524) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2011-05-20-524.md) |
| [Forskrift om svartkurle (Nigritella nigra) som prioritert art](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2015-05-29-562.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-05-29-562) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-05-29-562.md) |
| [Forskrift om tillatelse til bruk av beltebil.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2005-11-07-1264.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2005-11-07-1264) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2005-11-07-1264.md) |
| [Forskrift om tilskudd fra Svalbards miljøvernfond](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2007-04-30-599.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2007-04-30-599) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2007-04-30-599.md) |
| [Forskrift om tilskudd til Nasjonale turiststier](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2023-11-15-1847.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-11-15-1847) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-11-15-1847.md) |
| [Forskrift om tilskudd til anadrome laksefisk](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2014-11-25-1530.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2014-11-25-1530) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2014-11-25-1530.md) |
| [Forskrift om tilskudd til automatisk fredete og andre arkeologiske kulturminner](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-08-13-2507.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-08-13-2507) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-08-13-2507.md) |
| [Forskrift om tilskudd til besøkssenter for natur](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2023-11-15-1846.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-11-15-1846) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-11-15-1846.md) |
| [Forskrift om tilskudd til besøkssenter for verdensarv](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2023-11-15-1845.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-11-15-1845) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-11-15-1845.md) |
| [Forskrift om tilskudd til fagutvikling i fartøyvernet](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-08-13-2512.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-08-13-2512) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-08-13-2512.md) |
| [Forskrift om tilskudd til fartøyvern](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-08-13-2511.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-08-13-2511) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-08-13-2511.md) |
| [Forskrift om tilskudd til forebyggende tiltak mot rovviltskader og konfliktdempe](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2024-12-12-3074.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-12-12-3074) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-12-12-3074.md) |
| [Forskrift om tilskudd til fredete kulturminner i privat eie](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-08-13-2508.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-08-13-2508) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-08-13-2508.md) |
| [Forskrift om tilskudd til friluftslivsaktivitet](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2023-11-15-1832.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-11-15-1832) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-11-15-1832.md) |
| [Forskrift om tilskudd til frivillige klima- og miljøorganisasjoner samt klima- o](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-06-11-1928.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-06-11-1928) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-06-11-1928.md) |
| [Forskrift om tilskudd til klimatilpasning](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2018-06-25-1169.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2018-06-25-1169) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2018-06-25-1169.md) |
| [Forskrift om tilskudd til klimatiltak i kommunene, fylkeskommunene og Longyearby](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2017-10-26-1771.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-10-26-1771) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-10-26-1771.md) |
| [Forskrift om tilskudd til kommuner for å bedre tilgangen til strandsonen langs O](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2022-09-20-1602.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-09-20-1602) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-09-20-1602.md) |
| [Forskrift om tilskudd til natur- og friluftslivstiltak i områder som er berørt a](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-06-12-1551.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-06-12-1551) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-06-12-1551.md) |
| [Forskrift om tilskudd til naturrestaurering](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-11-02-2228.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-11-02-2228) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-11-02-2228.md) |
| [Forskrift om tilskudd til nitrogenfjerning ved avløpsrenseanlegg](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2023-09-01-1388.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-09-01-1388) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-09-01-1388.md) |
| [Forskrift om tilskudd til oppryddingstiltak i forurenset grunn og forurenset bun](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2015-06-26-808.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-06-26-808) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-06-26-808.md) |
| [Forskrift om tilskudd til stavkirker, bygg og anlegg fra middelalderen, konserve](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-08-13-2510.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-08-13-2510) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-08-13-2510.md) |
| [Forskrift om tilskudd til tekniske og industrielle kulturminner](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-08-13-2509.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-08-13-2509) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-08-13-2509.md) |
| [Forskrift om tilskudd til tiltak for å ivareta natur](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2024-10-04-2408.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-10-04-2408) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-10-04-2408.md) |
| [Forskrift om tilskudd til tiltak i Utvalgte kulturlandskap i jordbruket og verde](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2019-12-18-2024.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-12-18-2024) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-12-18-2024.md) |
| [Forskrift om tilskudd til tiltak i statlig sikrede friluftslivsområder og område](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2023-11-15-1848.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-11-15-1848) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-11-15-1848.md) |
| [Forskrift om tilskudd til tiltak mot marin forsøpling](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2018-12-05-1812.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2018-12-05-1812) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2018-12-05-1812.md) |
| [Forskrift om tilskudd til vannmiljøtiltak, kalking og anadrom laksefisk](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2024-10-04-2409.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-10-04-2409) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-10-04-2409.md) |
| [Forskrift om tilskudd til verdensarv](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-08-13-2514.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-08-13-2514) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-08-13-2514.md) |
| [Forskrift om tilskudd til verdiskaping basert på naturarven](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2014-11-25-1567.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2014-11-25-1567) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2014-11-25-1567.md) |
| [Forskrift om tilskudd til verdiskaping på kulturmiljøområdet](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-08-13-2513.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-08-13-2513) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-08-13-2513.md) |
| [Forskrift om tilskudd til å styrke kunnskapen om og formidlingen av naturmangfol](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2023-11-15-1887.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-11-15-1887) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-11-15-1887.md) |
| [Forskrift om trøndertorvmose (Sphagnum troendelagicum) som prioritert art](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2015-05-29-563.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-05-29-563) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-05-29-563.md) |
| [Forskrift om utforming og utrustning av innretninger med mer i petroleumsvirksom](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2010-04-29-634.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2010-04-29-634) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2010-04-29-634.md) |
| [Forskrift om utføring av aktiviteter i petroleumsvirksomheten (aktivitetsforskri](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2010-04-29-613.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2010-04-29-613) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2010-04-29-613.md) |
| [Forskrift om utlegging av åte og fôring av vilt](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2019-12-17-1878.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-12-17-1878) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-12-17-1878.md) |
| [Forskrift om utnytting i Norge av genetisk materiale med opprinnelse i andre lan](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2022-06-17-1047.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-06-17-1047) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-06-17-1047.md) |
| [Forskrift om utsetting av fisk og andre ferskvannsorganismer for kultiveringsfor](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1993-11-11-1020.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1993-11-11-1020) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1993-11-11-1020.md) |
| [Forskrift om utsetting av utenlandske treslag til skogbruksformål](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2012-05-25-460.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2012-05-25-460) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2012-05-25-460.md) |
| [Forskrift om utvalgte naturtyper etter naturmangfoldloven](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2011-05-13-512.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2011-05-13-512) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2011-05-13-512.md) |
| [Forskrift om utvidelse av det geografiske virkeområdet til forurensningsloven § ](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1997-08-22-945.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1997-08-22-945) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1997-08-22-945.md) |
| [Forskrift om utøvelse av jakt, felling og fangst](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2002-03-22-313.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2002-03-22-313) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2002-03-22-313.md) |
| [Forskrift om varsling ved eksport av visse farlige kjemikalier](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2020-11-04-2293.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-11-04-2293) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-11-04-2293.md) |
| [Forskrift om å begrense utslipp fra bygge- og anleggsplasser](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-04-03-594.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-04-03-594) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-04-03-594.md) |
| [Forskrift om åpning for fiske etter anadrome laksefisk (åpningsforskriften)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2003-06-20-736.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2003-06-20-736) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2003-06-20-736.md) |
| [Forskrift om øvre rammer for overtredelsesgebyr etter naturmangfoldloven § 74](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2020-12-11-2726.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-12-11-2726) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-12-11-2726.md) |
| [Forskrifter om fredning for sibirstjerne Aster sibiricus](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1981-10-02-8783.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1981-10-02-8783) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1981-10-02-8783.md) |
| [Forskrifter om gjennomføring av lov om kontroll med produkter og forbrukertjenes](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1977-08-05-2.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1977-08-05-2) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1977-08-05-2.md) |
| [Kvalitetsnorm for ville bestander av atlantisk laks (Salmo salar)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2013-09-20-1109.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-09-20-1109) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-09-20-1109.md) |
| [Kvalitetsnorm for villrein (Rangifer tarandus)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2020-06-23-1298.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-06-23-1298) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-06-23-1298.md) |
| [Midlertidig forskrift for regulering av naturinngrep på Svalbard og Jan Mayen.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1971-05-28-8617.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1971-05-28-8617) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1971-05-28-8617.md) |
| [Res. om fredning av kongeørn og havørn hele året](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1968-09-06-3.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1968-09-06-3) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1968-09-06-3.md) |
| [Vedtak om fristutsettelse for å fremsette krav om erstatning ved vern av nasjona](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2008-11-13-1693.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2008-11-13-1693) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2008-11-13-1693.md) |
