# Forsvarsdepartementet

*47 forskrifter*

| Forskrift | Lovdata | Historikk |
|-----------|---------|-----------|
| [Bestemmelser om klarering av adgang til og opphold på norsk territorium under fr](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2012-08-31-847.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2012-08-31-847) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2012-08-31-847.md) |
| [Forskrift om Forsvarsdepartementets tilskudd til sikkerhets- og forsvarspolitisk](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2023-10-31-1762.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-10-31-1762) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-10-31-1762.md) |
| [Forskrift om adgang til og opphold på norsk territorium under fredsforhold for f](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1997-05-02-396.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1997-05-02-396) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1997-05-02-396.md) |
| [Forskrift om ansiennitet og kommandomyndighet for befal i Forsvaret](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1957-10-18-9092.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1957-10-18-9092) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1957-10-18-9092.md) |
| [Forskrift om anvendelse av lov om informasjon om bestemt angitte områder, skjerm](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2018-06-22-950.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2018-06-22-950) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2018-06-22-950.md) |
| [Forskrift om behandling av ATOMAL](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2018-12-20-2064.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2018-12-20-2064) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2018-12-20-2064.md) |
| [Forskrift om behandling av saker etter lov om oppfinnelser av betydning for rike](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2000-03-09-215.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2000-03-09-215) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2000-03-09-215.md) |
| [Forskrift om beskikkelse m.v. av sivilmilitært personell.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1946-08-30-1.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1946-08-30-1) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1946-08-30-1.md) |
| [Forskrift om billighetserstatning i Forsvaret.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1993-08-20-814.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1993-08-20-814) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1993-08-20-814.md) |
| [Forskrift om delvis anvendelse av universitets- og høyskoleloven for Forsvarets ](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2018-07-30-1211.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2018-07-30-1211) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2018-07-30-1211.md) |
| [Forskrift om disiplinærordningen i Forsvaret (disiplinærforskriften)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2024-05-26-878.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-05-26-878) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-05-26-878.md) |
| [Forskrift om endring i forskrift om tjeneste for militært tilsatte og for sivilt](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-10-05-2947.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-10-05-2947) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-10-05-2947.md) |
| [Forskrift om forbud mot oppankring på et område utenfor Andøya flystasjon.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1961-01-20-1.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1961-01-20-1) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1961-01-20-1.md) |
| [Forskrift om forbudsområder i sjø](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2024-06-24-1311.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-06-24-1311) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-06-24-1311.md) |
| [Forskrift om forsvars- og sikkerhetsanskaffelser](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2013-10-04-1185.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-10-04-1185) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-10-04-1185.md) |
| [Forskrift om fremmede fartøyers anløp til og ferdsel i norsk territorialfarvann ](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2024-11-01-2627.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-11-01-2627) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-11-01-2627.md) |
| [Forskrift om godtgjørelse fra det offentlige til særskilte advokater i saker ett](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2023-09-28-1501.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-09-28-1501) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-09-28-1501.md) |
| [Forskrift om grenser for krigshavnsområder](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1950-02-17-3575.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1950-02-17-3575) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1950-02-17-3575.md) |
| [Forskrift om innsamling og behandling av opplysninger i Forsvarets helseregister](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2005-09-02-1010.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2005-09-02-1010) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2005-09-02-1010.md) |
| [Forskrift om klagenemnda for krav om erstatning og kompensasjon for psykiske bel](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2011-06-24-651.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2011-06-24-651) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2011-06-24-651.md) |
| [Forskrift om kontroll med informasjon innhentet med luftbårne sensorsystemer](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2018-06-22-951.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2018-06-22-951) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2018-06-22-951.md) |
| [Forskrift om kryptosikkerhet](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2018-12-20-2055.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2018-12-20-2055) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2018-12-20-2055.md) |
| [Forskrift om lov om militær politimyndighets anvendelse for Jan Mayen](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2026-03-06-352.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2026-03-06-352) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2026-03-06-352.md) |
| [Forskrift om militær luftfartsmyndighet](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2015-02-13-123.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-02-13-123) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-02-13-123.md) |
| [Forskrift om militær luftfartsmyndighets krav til bemanning av militære luftfart](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-11-25-2329.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-11-25-2329) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-11-25-2329.md) |
| [Forskrift om militær luftfartsmyndighets krav til militære landingsplasser](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-11-25-2328.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-11-25-2328) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-11-25-2328.md) |
| [Forskrift om militære forbudsområder](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2018-12-20-2057.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2018-12-20-2057) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2018-12-20-2057.md) |
| [Forskrift om militære rekvisisjoner.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1999-09-17-1012.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1999-09-17-1012) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1999-09-17-1012.md) |
| [Forskrift om nedgradering m.m.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1988-10-07-835.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1988-10-07-835) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1988-10-07-835.md) |
| [Forskrift om omforente områder etter lov om gjennomføring av tilleggsavtale mell](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2022-09-09-1552.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-09-09-1552) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-09-09-1552.md) |
| [Forskrift om opptak og annen bruk av informasjon om bestemt angitte bunnforhold](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2023-12-15-2061.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-12-15-2061) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-12-15-2061.md) |
| [Forskrift om opptak, studier og vurdering ved Forsvarets høgskole](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2023-02-14-198.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-02-14-198) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-02-14-198.md) |
| [Forskrift om råd, utvalg og nemnder i Heimevernet (heimevernsforskriften)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2017-06-16-780.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-06-16-780) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-06-16-780.md) |
| [Forskrift om skipssikkerhetslovens anvendelse for Forsvarsdepartementets underli](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2017-06-29-1668.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-06-29-1668) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-06-29-1668.md) |
| [Forskrift om særskilt kompensasjonsordning for psykiske belastningsskader som fø](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2009-12-22-1768.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2009-12-22-1768) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2009-12-22-1768.md) |
| [Forskrift om tilskudd til doktorgradsprosjekter innenfor veteranrelatert forskni](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2024-08-07-1924.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-08-07-1924) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-08-07-1924.md) |
| [Forskrift om tilskudd til frivillig aktivitet på forsvars- og sikkerhetsområdet](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-12-16-3738.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-12-16-3738) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-12-16-3738.md) |
| [Forskrift om tjeneste for militært tilsatte og for sivilt tilsatte i Forsvarsdep](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2017-06-24-997.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-06-24-997) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-06-24-997.md) |
| [Forskrift om tros- og livssynstjeneste i Forsvaret](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2018-12-20-2094.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2018-12-20-2094) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2018-12-20-2094.md) |
| [Forskrift om undersøkelser av ulykker og hendelser i Forsvaret](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2017-08-21-1331.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-08-21-1331) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-08-21-1331.md) |
| [Forskrift om verneplikt og heimevernstjeneste (vernepliktsforskriften)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2017-06-16-779.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-06-16-779) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-06-16-779.md) |
| [Forskrifter for ytelse av statsbidrag til skytebaner.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1974-04-05-5.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1974-04-05-5) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1974-04-05-5.md) |
| [Forskrifter om meniges æresord til fienden.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1962-11-09-1.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1962-11-09-1) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1962-11-09-1.md) |
| [Forskrifter vedr. egentlige militære kommandosaker (jfr. Grunnlovens §§ 28 og 31](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1963-03-08-8.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1963-03-08-8) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1963-03-08-8.md) |
| [Regler for fastsettelse av krigsskueplass i overensstemmelse med lov om særlige ](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1959-09-11-5036.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1959-09-11-5036) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1959-09-11-5036.md) |
| [Vedtak om Beredskapssystem for Forsvaret (BFF). Delegering av myndighet.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1999-12-17-1347.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1999-12-17-1347) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1999-12-17-1347.md) |
| [Vedtak om dispensasjon fra kravet om diplomatisk klarering for forskningsfartøye](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2009-06-05-617.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2009-06-05-617) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2009-06-05-617.md) |
