# Kommunal- og distriktsdepartementet

*92 forskrifter*

| Forskrift | Lovdata | Historikk |
|-----------|---------|-----------|
| [Forskrift for produksjons- og hjelpesystemer på produksjonsanlegg m.v. for utvin](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1978-04-03-9460.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1978-04-03-9460) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1978-04-03-9460.md) |
| [Forskrift om Husleietvistutvalget](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2016-06-21-765.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2016-06-21-765) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2016-06-21-765.md) |
| [Forskrift om IT-standarder i offentlig forvaltning](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2013-04-05-959.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-04-05-959) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-04-05-959.md) |
| [Forskrift om Kommunal- og distriktsdepartementets tilskot til kompetanse og arbe](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-04-02-576.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-04-02-576) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-04-02-576.md) |
| [Forskrift om Kommunal- og distriktsdepartementets tilskudd til FoU-program innen](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2023-02-20-222.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-02-20-222) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-02-20-222.md) |
| [Forskrift om Kommunal- og distriktsdepartementets tilskudd til Forskningsbasert ](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2022-02-11-250.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-02-11-250) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-02-11-250.md) |
| [Forskrift om Kommunal- og distriktsdepartementets tilskuddsmidler til Arktis 203](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2019-12-19-2112.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-12-19-2112) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-12-19-2112.md) |
| [Forskrift om Kommunal- og moderniseringsdepartementets distrikts- og regionalpol](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2018-05-23-747.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2018-05-23-747) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2018-05-23-747.md) |
| [Forskrift om behandling av personopplysninger på det boligsosiale feltet](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2023-08-17-1330.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-08-17-1330) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-08-17-1330.md) |
| [Forskrift om behandling av private forslag til detaljregulering etter plan- og b](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2017-12-08-1950.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-12-08-1950) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-12-08-1950.md) |
| [Forskrift om beregning av samlet selvkost for kommunale og fylkeskommunale gebyr](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2019-12-11-1731.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-12-11-1731) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-12-11-1731.md) |
| [Forskrift om bruk av det samiske flagget](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2004-05-27-1087.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2004-05-27-1087) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2004-05-27-1087.md) |
| [Forskrift om bruk av standardisert søknad om seksjonering](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2017-12-17-2119.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-12-17-2119) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-12-17-2119.md) |
| [Forskrift om bustøtte](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2012-11-29-1283.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2012-11-29-1283) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2012-11-29-1283.md) |
| [Forskrift om byggesak (byggesaksforskriften)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2010-03-26-488.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2010-03-26-488) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2010-03-26-488.md) |
| [Forskrift om direkte valg til kommunedelsutvalg.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2003-01-03-8.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2003-01-03-8) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2003-01-03-8.md) |
| [Forskrift om driftstilskudd til organisasjoner for nasjonale minoriteter](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2022-06-21-1137.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-06-21-1137) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-06-21-1137.md) |
| [Forskrift om eiendomsregistrering (matrikkelforskriften)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2009-06-26-864.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2009-06-26-864) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2009-06-26-864.md) |
| [Forskrift om eiendomsregistrering på Svalbard](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-12-17-3633.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-12-17-3633) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-12-17-3633.md) |
| [Forskrift om elektronisk faktura i offentlige anskaffelser](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2019-04-01-444.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-04-01-444) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-04-01-444.md) |
| [Forskrift om elektronisk kommunikasjon ved tinglysing av salgspant og leasing av](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2017-05-04-536.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-05-04-536) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-05-04-536.md) |
| [Forskrift om endring i forskrift om bustøtte](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2022-12-22-2501.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-12-22-2501) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-12-22-2501.md) |
| [Forskrift om endringer i personopplysningsforskriften](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2013-08-09-970.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-08-09-970) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-08-09-970.md) |
| [Forskrift om forbud mot vilkår om sosial infrastruktur i utbyggingsavtaler.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2006-04-20-453.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2006-04-20-453) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2006-04-20-453.md) |
| [Forskrift om forvaltningsområdet for samiske språk](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2005-06-17-657.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2005-06-17-657) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2005-06-17-657.md) |
| [Forskrift om garantier og finans- og gjeldsforvaltning i kommuner og fylkeskommu](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2019-11-18-1520.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-11-18-1520) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-11-18-1520.md) |
| [Forskrift om gebyr for tinglysing, registrering eller anmerkning i grunnboken og](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2013-12-18-1634.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-12-18-1634) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-12-18-1634.md) |
| [Forskrift om gebyrregulativ for sentral godkjenning av foretak for ansvarsrett e](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2010-06-29-989.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2010-06-29-989) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2010-06-29-989.md) |
| [Forskrift om hvilke kostnader som skal inn i et borettslags driftsbudsjett](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2011-03-31-416.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2011-03-31-416) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2011-03-31-416.md) |
| [Forskrift om hvilke opplysninger som skal gis i melding om salg av leiegård.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1993-01-15-30.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1993-01-15-30) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1993-01-15-30.md) |
| [Forskrift om infrastruktur for geografisk informasjon (geodataforskriften)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2012-08-08-797.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2012-08-08-797) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2012-08-08-797.md) |
| [Forskrift om innmåling, dokumentasjon og utlevering av geografisk informasjon om](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2020-12-18-2986.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-12-18-2986) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-12-18-2986.md) |
| [Forskrift om iverksetting av matrikkelen](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2007-02-09-151.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2007-02-09-151) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2007-02-09-151.md) |
| [Forskrift om kart, stedfestet informasjon, arealformål og kommunalt planregister](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-01-20-52.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-01-20-52) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-01-20-52.md) |
| [Forskrift om klagenemnd for Husbanken](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2012-10-31-1182.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2012-10-31-1182) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2012-10-31-1182.md) |
| [Forskrift om kommunale og fylkeskommunale budsjetter og regnskaper.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1990-03-01-715.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1990-03-01-715) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1990-03-01-715.md) |
| [Forskrift om kommunale og fylkeskommunale råd for eldre, personer med funksjonsn](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2019-06-17-727.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-06-17-727) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-06-17-727.md) |
| [Forskrift om kommunalt rapporteringsregister (KOR-forskriften)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2019-11-18-1521.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-11-18-1521) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-11-18-1521.md) |
| [Forskrift om kompetansetilskudd til bærekraftig bolig- og byggkvalitet fra Husba](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2011-02-23-194.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2011-02-23-194) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2011-02-23-194.md) |
| [Forskrift om konsekvensutredninger](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2017-06-21-854.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-06-21-854) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-06-21-854.md) |
| [Forskrift om kontrollutvalg og revisjon](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2019-06-17-904.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-06-17-904) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-06-17-904.md) |
| [Forskrift om lån fra Husbanken](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2019-11-18-1546.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-11-18-1546) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-11-18-1546.md) |
| [Forskrift om lån til omsorgsboliger, sykehjemsplasser og lokaler for omsorgstilt](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2003-07-10-957.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2003-07-10-957) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2003-07-10-957.md) |
| [Forskrift om minimumsavdrag på lån for kommuner, fylkeskommuner, kommunale og fy](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2024-09-27-2348.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-09-27-2348) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-09-27-2348.md) |
| [Forskrift om minstekrav til sikringsordningar i burettslag](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2010-12-15-1694.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2010-12-15-1694) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2010-12-15-1694.md) |
| [Forskrift om omsetning og dokumentasjon av heiser og sikkerhetskomponenter for h](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2016-04-13-373.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2016-04-13-373) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2016-04-13-373.md) |
| [Forskrift om omsetning og dokumentasjon av produkter til byggverk](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2013-12-17-1579.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-12-17-1579) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-12-17-1579.md) |
| [Forskrift om oppheving av forskrift om arealtilskott til privateide skoler, kirk](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1987-02-06-71.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1987-02-06-71) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1987-02-06-71.md) |
| [Forskrift om ordningen for kollektiv oppreisning til romanifolket/taterne](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2019-09-27-1277.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-09-27-1277) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-09-27-1277.md) |
| [Forskrift om overgangsbestemmelser for gjennomføring av lov om endringar i parti](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2013-02-01-129.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-02-01-129) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-02-01-129.md) |
| [Forskrift om overgangsbestemmelser til ny kommunelov](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2019-06-27-937.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-06-27-937) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-06-27-937.md) |
| [Forskrift om pensjonsordning for sametingsrepresentanter](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2013-08-23-1006.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-08-23-1006) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-08-23-1006.md) |
| [Forskrift om prosjekttilskudd til nasjonale minoriteter](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2020-01-13-40.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-01-13-40) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-01-13-40.md) |
| [Forskrift om rapportering fra kommuner og fylkeskommuner mv. (KOSTRA-forskriften](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2019-10-18-1412.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-10-18-1412) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-10-18-1412.md) |
| [Forskrift om registrering av beslutninger om utlegg i Løsøreregisteret (utleggsr](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-08-08-1616.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-08-08-1616) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-08-08-1616.md) |
| [Forskrift om registrering av regjeringsmedlemmers, statssekretærers og politiske](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2012-11-30-1114.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2012-11-30-1114) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2012-11-30-1114.md) |
| [Forskrift om rett til å kreve seksjonering etter eierseksjonsloven § 9](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2018-06-18-921.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2018-06-18-921) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2018-06-18-921.md) |
| [Forskrift om samvirke mellom bestemmelsen i plan- og bygningsloven 14. juni 1985](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2009-06-15-669.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2009-06-15-669) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2009-06-15-669.md) |
| [Forskrift om tekniske krav til byggverk (Byggteknisk forskrift)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2017-06-19-840.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-06-19-840) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-06-19-840.md) |
| [Forskrift om tidsfrist for krav om lovlighetskontroll.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1993-01-13-4041.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1993-01-13-4041) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1993-01-13-4041.md) |
| [Forskrift om tilskot frå Merkur-programmet (Merkur-forskrifta)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2024-11-21-2989.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-11-21-2989) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-11-21-2989.md) |
| [Forskrift om tilskudd til boligtiltak](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2026-03-26-506.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2026-03-26-506) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2026-03-26-506.md) |
| [Forskrift om tilskudd til etablering og tilpasning i distriktskommuner](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-04-29-709.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-04-29-709) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-04-29-709.md) |
| [Forskrift om tilskudd til forsøk med nye boligmodeller fra Husbanken](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-12-20-3779.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-12-20-3779) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-12-20-3779.md) |
| [Forskrift om tilskudd til informasjonstiltak ved valg til Stortinget, Sametinget](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2020-10-13-2034.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-10-13-2034) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-10-13-2034.md) |
| [Forskrift om tilskudd til kompetansetiltak innen kart, plan og geodata](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-04-08-633.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-04-08-633) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-04-08-633.md) |
| [Forskrift om tilskudd til kvensk språk og kvensk og norskfinsk kultur](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2019-11-22-1570.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-11-22-1570) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-11-22-1570.md) |
| [Forskrift om tilskudd til utleieboliger fra Husbanken](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2017-12-18-2235.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-12-18-2235) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-12-18-2235.md) |
| [Forskrift om tilskuddsordning forvaltet av Barentssekretariatet IKS](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2024-02-07-234.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-02-07-234) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-02-07-234.md) |
| [Forskrift om tilskuddsordninger til omstilling og utvikling i områder med særlig](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2024-04-03-556.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-04-03-556) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-04-03-556.md) |
| [Forskrift om tinglysing](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1995-11-03-875.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1995-11-03-875) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1995-11-03-875.md) |
| [Forskrift om universell utforming av informasjons- og kommunikasjonsteknologiske](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2013-06-21-732.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-06-21-732) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-06-21-732.md) |
| [Forskrift om unntak fra husleieloven § 3-5](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2009-06-02-628.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2009-06-02-628) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2009-06-02-628.md) |
| [Forskrift om utlevering, viderebruk og annen behandling av opplysninger fra grun](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2013-12-18-1599.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-12-18-1599) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-12-18-1599.md) |
| [Forskrift om valg til Sametinget](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2008-12-19-1480.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2008-12-19-1480) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2008-12-19-1480.md) |
| [Forskrift om valg til Stortinget, fylkesting og kommunestyrer (valgforskriften)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2024-11-05-2662.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-11-05-2662) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-11-05-2662.md) |
| [Forskrift om virkeområdet for distriktsrettet investeringsstøtte](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-12-14-3661.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-12-14-3661) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-12-14-3661.md) |
| [Forskrift om visse forhold vedrørende de politiske partiene (partilovforskriften](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2014-02-05-107.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2014-02-05-107) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2014-02-05-107.md) |
| [Forskrift om økonomiplan, årsbudsjett, årsregnskap og årsberetning for interkomm](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2023-08-16-1327.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-08-16-1327) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-08-16-1327.md) |
| [Forskrift om økonomiplan, årsbudsjett, årsregnskap og årsberetning for kommuner ](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2019-06-07-714.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-06-07-714) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-06-07-714.md) |
| [Forskrift til avhendingslova (tryggere bolighandel)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-06-08-1850.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-06-08-1850) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-06-08-1850.md) |
| [Forskrift til samelovens språkregler](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2003-01-07-13.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2003-01-07-13) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2003-01-07-13.md) |
| [Midlertidig forskrift for elektriske anlegg på innretninger som anvendes til und](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1985-07-26-1565.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1985-07-26-1565) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1985-07-26-1565.md) |
| [Midlertidig forskrift om tilskudd til kommunale næringsfond som følge av covid-1](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2020-06-30-1437.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-06-30-1437) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-06-30-1437.md) |
| [Midlertidig forskrift om unntak fra plan- og bygningsloven for å håndtere høye a](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2022-06-08-991.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-06-08-991) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-06-08-991.md) |
| [Refusjon av merutgifter og tap som følge av hevnaksjoner, som har sammenheng med](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2020-12-11-2711.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-12-11-2711) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-12-11-2711.md) |
| [Rikspolitiske retningslinjer for barn og planlegging](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1995-09-20-4146.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1995-09-20-4146) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1995-09-20-4146.md) |
| [Rikspolitiske retningslinjer for vernede vassdrag](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1994-11-10-1001.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1994-11-10-1001) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1994-11-10-1001.md) |
| [Statlige planretningslinjer for arealbruk og mobilitet](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-01-24-69.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-01-24-69) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-01-24-69.md) |
| [Statlige planretningslinjer for differensiert forvaltning av strandsonen langs s](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-05-28-1666.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-05-28-1666) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-05-28-1666.md) |
| [Statlige planretningslinjer for klima og energi](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2024-12-20-3359.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-12-20-3359) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-12-20-3359.md) |
| [Vedtak om innføring av matrikkelsystem](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2009-04-25-975.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2009-04-25-975) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2009-04-25-975.md) |
