# Utenriksdepartementet

*65 forskrifter*

| Forskrift | Lovdata | Historikk |
|-----------|---------|-----------|
| [Anerkjennelse av Norges Røde Kors' rett til til bruk av navn og emblem som Norge](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2009-08-21-1148.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2009-08-21-1148) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2009-08-21-1148.md) |
| [Forskrift angående bruk av Rikets segl og Riksvåbenet.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1927-05-20-3729.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1927-05-20-3729) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1927-05-20-3729.md) |
| [Forskrift angående bruk av statsflagget og handelsflagget.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1927-10-21-9733.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1927-10-21-9733) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1927-10-21-9733.md) |
| [Forskrift om adgang til i særlige tilfelle å benytte fremmed lands flagg ved sid](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1933-07-06-3.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1933-07-06-3) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1933-07-06-3.md) |
| [Forskrift om anvendelse av lov om oppdrett av fisk, skalldyr mv. i Norges økonom](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1988-04-29-314.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1988-04-29-314) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1988-04-29-314.md) |
| [Forskrift om eksport av forsvarsmateriell, flerbruksvarer, teknologi og tjeneste](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2013-06-19-718.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-06-19-718) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-06-19-718.md) |
| [Forskrift om endring i forskrift om sanksjoner i lys av situasjonen i Somalia](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2024-12-09-3030.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-12-09-3030) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-12-09-3030.md) |
| [Forskrift om fiskevernsone ved Svalbard.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1977-06-03-6.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1977-06-03-6) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1977-06-03-6.md) |
| [Forskrift om gebyr ved Norges utenriksstasjoner](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2014-06-20-780.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2014-06-20-780) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2014-06-20-780.md) |
| [Forskrift om gjennomføring av De Forente Nasjoners Sikkerhetsråds resolusjoner o](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1990-08-09-635.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1990-08-09-635) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1990-08-09-635.md) |
| [Forskrift om gjennomføring av Kimberley-prosessens sertifiseringsordning for han](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2004-02-24-470.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2004-02-24-470) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2004-02-24-470.md) |
| [Forskrift om gjennomføring av innførselsreguleringen.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1998-08-18-818.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1998-08-18-818) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1998-08-18-818.md) |
| [Forskrift om gjennomføring av konvensjon av 13. januar 1993 om forbud mot kjemis](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1997-05-16-477.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1997-05-16-477) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1997-05-16-477.md) |
| [Forskrift om grensen for det norske sjøterritorium ved Jan Mayen.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2002-08-30-943.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2002-08-30-943) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2002-08-30-943.md) |
| [Forskrift om grunnlinjen for sjøterritoriet ved Bouvetøya.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2005-02-25-174.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2005-02-25-174) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2005-02-25-174.md) |
| [Forskrift om grunnlinjene for sjøterritoriet rundt Fastlands-Norge.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2002-06-14-625.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2002-06-14-625) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2002-06-14-625.md) |
| [Forskrift om grunnlinjene for sjøterritoriet ved Svalbard.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2001-06-01-556.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2001-06-01-556) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2001-06-01-556.md) |
| [Forskrift om immunitet og privilegier for Western European Armaments Organisatio](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1997-02-14-131.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1997-02-14-131) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1997-02-14-131.md) |
| [Forskrift om immunitet og privilegier mv. for personer, eiendom og aktiva tilkny](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2000-01-07-14.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2000-01-07-14) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2000-01-07-14.md) |
| [Forskrift om iverksettelse av Norges økonomiske sone. Delegering av fullmakt.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1976-12-17-15.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1976-12-17-15) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1976-12-17-15.md) |
| [Forskrift om oppkreving av eksportavgift.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1981-06-05-8828.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1981-06-05-8828) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1981-06-05-8828.md) |
| [Forskrift om opprettelse av fiskerisone ved Jan Mayen. Delegering av fullmakt.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1980-05-23-4.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1980-05-23-4) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1980-05-23-4.md) |
| [Forskrift om rekruttering og forflytning i utenrikstjenesten](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2023-10-20-1669.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-10-20-1669) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-10-20-1669.md) |
| [Forskrift om restriktive tiltak i lys av Russlands destabiliserende aktiviteter](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-03-14-466.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-03-14-466) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-03-14-466.md) |
| [Forskrift om restriktive tiltak i lys av handlinger som destabiliserer Republikk](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2023-06-20-993.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-06-20-993) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-06-20-993.md) |
| [Forskrift om restriktive tiltak i lys av situasjonen i Belarus og Belarus' medvi](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2006-09-08-1041.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2006-09-08-1041) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2006-09-08-1041.md) |
| [Forskrift om restriktive tiltak i lys av situasjonen i Burundi](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2016-02-05-104.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2016-02-05-104) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2016-02-05-104.md) |
| [Forskrift om restriktive tiltak i lys av situasjonen i Mali](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2020-05-07-955.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-05-07-955) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-05-07-955.md) |
| [Forskrift om restriktive tiltak i lys av situasjonen i Myanmar/Burma](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2003-07-04-895.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2003-07-04-895) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2003-07-04-895.md) |
| [Forskrift om restriktive tiltak i lys av situasjonen i Nicaragua](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2020-06-23-1283.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-06-23-1283) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-06-23-1283.md) |
| [Forskrift om restriktive tiltak i lys av situasjonen i Niger](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-08-15-1655.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-08-15-1655) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-08-15-1655.md) |
| [Forskrift om restriktive tiltak i lys av situasjonen i Russland](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-03-14-472.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-03-14-472) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-03-14-472.md) |
| [Forskrift om restriktive tiltak i lys av situasjonen i Sudan](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2006-06-02-573.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2006-06-02-573) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2006-06-02-573.md) |
| [Forskrift om restriktive tiltak mot Republikken Guinea](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2014-05-09-626.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2014-05-09-626) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2014-05-09-626.md) |
| [Forskrift om restriktive tiltak mot Republikken Zimbabwe](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2003-08-15-1050.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2003-08-15-1050) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2003-08-15-1050.md) |
| [Forskrift om restriktive tiltak mot Syria](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2011-09-02-902.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2011-09-02-902) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2011-09-02-902.md) |
| [Forskrift om restriktive tiltak mot alvorlige menneskerettsbrudd og -overgrep](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-05-11-1458.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-05-11-1458) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-05-11-1458.md) |
| [Forskrift om restriktive tiltak mot cyberangrep](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-05-11-1459.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-05-11-1459) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-05-11-1459.md) |
| [Forskrift om restriktive tiltak mot personer som anses ansvarlige for underslag ](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2014-05-09-612.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2014-05-09-612) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2014-05-09-612.md) |
| [Forskrift om restriktive tiltak mot spredning og bruk av kjemiske våpen](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-05-11-1456.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-05-11-1456) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-05-11-1456.md) |
| [Forskrift om restriktive tiltak mot visse personer i lys av situasjonen i Tunisi](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2015-12-11-1436.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-12-11-1436) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-12-11-1436.md) |
| [Forskrift om restriktive tiltak vedrørende handlinger som undergraver eller true](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2014-08-15-1076.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2014-08-15-1076) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2014-08-15-1076.md) |
| [Forskrift om restriktive tiltak vedrørende situasjonen i Guinea-Bissau](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2015-12-11-1434.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-12-11-1434) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-12-11-1434.md) |
| [Forskrift om restriktive tiltak vedrørende situasjonen i Venezuela](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2017-12-15-2103.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-12-15-2103) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-12-15-2103.md) |
| [Forskrift om sanksjoner i lys av situasjonen i Haiti](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2023-03-24-404.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-03-24-404) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-03-24-404.md) |
| [Forskrift om sanksjoner i lys av situasjonen i Somalia](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1992-02-07-77.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1992-02-07-77) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1992-02-07-77.md) |
| [Forskrift om sanksjoner mot ISIL (Da'esh) og Al-Qaida](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1999-12-22-1374.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1999-12-22-1374) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1999-12-22-1374.md) |
| [Forskrift om sanksjoner mot Taliban](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2013-11-08-1294.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-11-08-1294) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-11-08-1294.md) |
| [Forskrift om sanksjoner mot ikke-statlige aktører i Libanon.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2006-09-08-1040.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2006-09-08-1040) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2006-09-08-1040.md) |
| [Forskrift om sanksjoner mot visse personer og aktører i Jemen](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2015-06-19-663.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-06-19-663) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-06-19-663.md) |
| [Forskrift om sanksjoner og restriktive tiltak i lys av situasjonen i Den demokra](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2003-10-10-1221.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2003-10-10-1221) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2003-10-10-1221.md) |
| [Forskrift om sanksjoner og restriktive tiltak i lys av situasjonen i Sør-Sudan](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2015-12-11-1435.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-12-11-1435) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-12-11-1435.md) |
| [Forskrift om sanksjoner og restriktive tiltak mot Libya](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2011-03-11-265.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2011-03-11-265) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2011-03-11-265.md) |
| [Forskrift om sanksjoner og restriktive tiltak mot Nord-Korea](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2006-12-15-1405.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2006-12-15-1405) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2006-12-15-1405.md) |
| [Forskrift om sanksjoner og restriktive tiltak vedrørende situasjonen i Den sentr](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2015-09-18-1061.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-09-18-1061) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-09-18-1061.md) |
| [Forskrift om sanksjoner og tiltak mot Iran](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2007-02-09-149.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2007-02-09-149) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2007-02-09-149.md) |
| [Forskrift om utenlandsk vitenskapelig havforskning i Norges indre farvann, sjøte](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2001-03-30-360.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2001-03-30-360) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2001-03-30-360.md) |
| [Forskrift om vigsel ved utsendt utenrikstjenesteansatt](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-04-11-731.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-04-11-731) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-04-11-731.md) |
| [Forskrift til gjennomføring av den alminnelige utførselsregulering.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1989-01-10-52.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1989-01-10-52) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1989-01-10-52.md) |
| [Res. angående flagg for Kronprinsen og Kronprinsessen](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1924-09-26-4.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1924-09-26-4) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1924-09-26-4.md) |
| [Res. om Kongeflaget m.v.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1905-11-15-2.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1905-11-15-2) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1905-11-15-2.md) |
| [Res. om Kongevaabenet.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1905-12-30-1.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1905-12-30-1) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1905-12-30-1.md) |
| [Res. om Noregs riksvåpen](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1937-03-19-3728.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1937-03-19-3728) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1937-03-19-3728.md) |
| [Res. om fastsættelse af en kongevimpel.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1906-01-27-2.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1906-01-27-2) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1906-01-27-2.md) |
| [Resolusjon om at øen Jan Mayen inndras under norsk høihetsrett.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1929-05-08-3426.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1929-05-08-3426) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1929-05-08-3426.md) |
