# Kunnskapsdepartementet

*330 forskrifter*

| Forskrift | Lovdata | Historikk |
|-----------|---------|-----------|
| [Eksamensreglement for Høgskulen for landbruk og bygdenæringar BA](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2007-08-31-1133.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2007-08-31-1133) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2007-08-31-1133.md) |
| [Forskrift for Fagskolen AOF Hordaland – Sogn og Fjordane](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2017-12-14-2471.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-12-14-2471) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-12-14-2471.md) |
| [Forskrift for OSM Aviation Academy](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2023-11-13-2011.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-11-13-2011) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-11-13-2011.md) |
| [Forskrift for bachelorstudiet Bevegelige bilder ved Nordland kunst- og filmfagsk](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2017-02-15-2466.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-02-15-2466) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-02-15-2466.md) |
| [Forskrift for fagskolestudier ved Fagskolen TLA AS](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2017-09-01-1416.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-09-01-1416) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-09-01-1416.md) |
| [Forskrift for fagskoleutdanning i yrkesdykking ved Høgskulen på Vestlandet](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2017-06-15-1044.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-06-15-1044) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-06-15-1044.md) |
| [Forskrift for forskerlinjen i medisin ved Norges teknisk-naturvitenskapelige uni](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2023-11-29-1935.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-11-29-1935) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-11-29-1935.md) |
| [Forskrift for graden doctor philosophiae (dr.philos.) ved Nord universitet](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-05-08-862.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-05-08-862) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-05-08-862.md) |
| [Forskrift for graden doctor philosophiae (dr.philos.) ved Norges miljø- og biovi](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2024-11-13-2941.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-11-13-2941) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-11-13-2941.md) |
| [Forskrift for graden doctor philosophiae (dr.philos.) ved Norges teknisk-naturvi](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2026-02-03-425.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2026-02-03-425) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2026-02-03-425.md) |
| [Forskrift for graden doctor philosophiae (dr.philos.) ved Universitetet i Bergen](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-02-13-284.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-02-13-284) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-02-13-284.md) |
| [Forskrift for graden doctor philosophiae (dr.philos.) ved Universitetet i Oslo](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2011-01-05-841.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2011-01-05-841) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2011-01-05-841.md) |
| [Forskrift for graden doctor philosophiae (dr.philos.) ved Universitetet i Sørøst](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2019-11-21-2304.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-11-21-2304) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-11-21-2304.md) |
| [Forskrift for graden doctor philosophiae (dr.philos.) ved VID vitenskapelige høg](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2026-03-11-448.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2026-03-11-448) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2026-03-11-448.md) |
| [Forskrift for graden dr.philos. ved MF vitenskapelig høyskole](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2018-08-30-1682.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2018-08-30-1682) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2018-08-30-1682.md) |
| [Forskrift for graden dr.philos. ved Universitetet i Stavanger](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2019-06-13-1472.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-06-13-1472) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-06-13-1472.md) |
| [Forskrift for graden philosophiae doctor (Ph.D.) – med utfyllende bestemmelser f](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2003-12-16-4680.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2003-12-16-4680) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2003-12-16-4680.md) |
| [Forskrift for graden philosophiae doctor (ph.d.) i kunstnerisk utviklingsarbeid ](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-09-15-4051.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-09-15-4051) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-09-15-4051.md) |
| [Forskrift for graden philosophiae doctor (ph.d.) i kunstnerisk utviklingsarbeid ](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-02-13-283.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-02-13-283) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-02-13-283.md) |
| [Forskrift for graden philosophiae doctor (ph.d.) i kunstnerisk utviklingsarbeid ](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2022-08-29-1598.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-08-29-1598) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-08-29-1598.md) |
| [Forskrift for graden philosophiae doctor (ph.d.) i kunstnerisk utviklingsarbeid ](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-06-12-1280.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-06-12-1280) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-06-12-1280.md) |
| [Forskrift for graden philosophiae doctor (ph.d.) ved Arkitektur- og designhøgsko](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2016-10-26-1442.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2016-10-26-1442) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2016-10-26-1442.md) |
| [Forskrift for graden philosophiae doctor (ph.d.) ved Høgskolen i Molde, Vitenska](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2026-01-28-149.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2026-01-28-149) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2026-01-28-149.md) |
| [Forskrift for graden philosophiae doctor (ph.d.) ved Høgskolen i Østfold](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2024-09-17-3171.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-09-17-3171) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-09-17-3171.md) |
| [Forskrift for graden philosophiae doctor (ph.d.) ved Høyskolen Kristiania](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-03-11-440.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-03-11-440) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-03-11-440.md) |
| [Forskrift for graden philosophiae doctor (ph.d.) ved MF vitenskapelig høyskole](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2012-06-05-645.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2012-06-05-645) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2012-06-05-645.md) |
| [Forskrift for graden philosophiae doctor (ph.d.) ved Nord universitet](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-05-08-892.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-05-08-892) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-05-08-892.md) |
| [Forskrift for graden philosophiae doctor (ph.d.) ved Norges Handelshøyskole](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-01-29-126.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-01-29-126) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-01-29-126.md) |
| [Forskrift for graden philosophiae doctor (ph.d.) ved Norges miljø- og biovitensk](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2024-11-13-3024.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-11-13-3024) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-11-13-3024.md) |
| [Forskrift for graden philosophiae doctor (ph.d.) ved Universitetet i Agder](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2022-02-01-1149.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-02-01-1149) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-02-01-1149.md) |
| [Forskrift for graden philosophiae doctor (ph.d.) ved Universitetet i Bergen](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-02-13-282.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-02-13-282) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-02-13-282.md) |
| [Forskrift for graden philosophiae doctor (ph.d.) ved Universitetet i Innlandet](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2017-12-19-2396.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-12-19-2396) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-12-19-2396.md) |
| [Forskrift for graden philosophiae doctor (ph.d.) ved Universitetet i Oslo](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2010-06-22-4998.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2010-06-22-4998) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2010-06-22-4998.md) |
| [Forskrift for graden philosophiae doctor (ph.d.) ved Universitetet i Stavanger](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-06-12-1279.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-06-12-1279) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-06-12-1279.md) |
| [Forskrift for gradene philosophiae doctor (ph.d.) og philosophiae doctor i kunst](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2026-02-03-387.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2026-02-03-387) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2026-02-03-387.md) |
| [Forskrift for integrert ph.d.-utdanning ved Universitetet i Agder (UiA)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2017-06-22-1145.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-06-22-1145) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-06-22-1145.md) |
| [Forskrift for masterstudiet ved Bergen Arkitekthøgskole](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2019-03-04-179.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-03-04-179) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-03-04-179.md) |
| [Forskrift for medisinsk embetseksamen og medisinsk eksamen ved Universitetet i T](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1976-03-22-8875.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1976-03-22-8875) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1976-03-22-8875.md) |
| [Forskrift for opptak, gjennomføring av studier, eksamen og klageregler for fagsk](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2017-09-18-1634.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-09-18-1634) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-09-18-1634.md) |
| [Forskrift for opptak, studier og eksamen ved Høyskolen for yrkesfag AS](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2020-01-08-906.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-01-08-906) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-01-08-906.md) |
| [Forskrift for opptak, studier og eksamen ved Imageakademiet](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2020-02-14-146.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-02-14-146) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-02-14-146.md) |
| [Forskrift for studier og eksamen ved Lillehammer Institute of Music Production a](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2016-07-04-1634.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2016-07-04-1634) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2016-07-04-1634.md) |
| [Forskrift om Nasjonalt kvalifikasjonsrammeverk for livslang læring og om henvisn](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2017-11-08-1846.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-11-08-1846) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-11-08-1846.md) |
| [Forskrift om akkreditering av og tilsyn med høyere yrkesfaglig utdanning (fagsko](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2020-04-23-853.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-04-23-853) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-04-23-853.md) |
| [Forskrift om ansvar for spesialpedagogisk hjelp for barn under opplæringspliktig](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2017-06-22-1050.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-06-22-1050) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-06-22-1050.md) |
| [Forskrift om autorisasjonsprøven ved Norges Handelshøyskole for å bli statsautor](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-06-17-2044.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-06-17-2044) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-06-17-2044.md) |
| [Forskrift om bachelorgrad ved Atlantis Medisinske Høgskole](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2013-05-24-548.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-05-24-548) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-05-24-548.md) |
| [Forskrift om bachelorgrad ved Høgskolen i Buskerud](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2006-06-21-1718.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2006-06-21-1718) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2006-06-21-1718.md) |
| [Forskrift om bachelorgrad ved Samisk høgskole](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2015-05-27-890.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-05-27-890) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-05-27-890.md) |
| [Forskrift om barnehagevirksomhet i Longyearbyen](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2022-06-17-1219.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-06-17-1219) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-06-17-1219.md) |
| [Forskrift om behandling av personopplysninger i Lånekassen](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-12-17-3713.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-12-17-3713) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-12-17-3713.md) |
| [Forskrift om behandling av personopplysninger i barnehagesektoren](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2018-09-28-1479.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2018-09-28-1479) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2018-09-28-1479.md) |
| [Forskrift om de regionale forskningsfondene](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2019-12-18-2110.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-12-18-2110) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-12-18-2110.md) |
| [Forskrift om delvis innlemming av Forsvarets etterretningshøgskole under lov 1. ](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2005-12-16-1575.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2005-12-16-1575) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2005-12-16-1575.md) |
| [Forskrift om delvis innlemming av Kriminalomsorgens høgskole og utdanningssenter](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2012-10-26-993.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2012-10-26-993) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2012-10-26-993.md) |
| [Forskrift om delvis innlemming av Politihøgskolen under lov 1. april 2005 nr. 15](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2005-12-16-1576.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2005-12-16-1576) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2005-12-16-1576.md) |
| [Forskrift om eksamen og sluttvurdering ved Samisk høgskole](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2011-02-15-460.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2011-02-15-460) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2011-02-15-460.md) |
| [Forskrift om eksamen ved Atlantis Medisinske Høgskole](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2013-05-24-547.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-05-24-547) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-05-24-547.md) |
| [Forskrift om eksamen ved Norges Informasjonsteknologiske Høgskole](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2005-12-16-1620.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2005-12-16-1620) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2005-12-16-1620.md) |
| [Forskrift om eksamen, studierett og grader ved Høgskolen i Østfold](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2024-09-17-2231.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-09-17-2231) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-09-17-2231.md) |
| [Forskrift om endring i forskrift om graden philosophiae doctor (ph.d.) ved Hande](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2026-03-11-396.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2026-03-11-396) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2026-03-11-396.md) |
| [Forskrift om endring i forskrift om grunnskoleopplæringa og den vidaregåande opp](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2026-01-28-107.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2026-01-28-107) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2026-01-28-107.md) |
| [Forskrift om endring i forskrift om grunnskoleopplæringa og den vidaregåande opp](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2026-03-20-443.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2026-03-20-443) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2026-03-20-443.md) |
| [Forskrift om endring i forskrift om grunnskoleopplæringa og den vidaregåande opp](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2026-02-18-235.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2026-02-18-235) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2026-02-18-235.md) |
| [Forskrift om endring i forskrift om høyere yrkesfaglig utdanning](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-06-12-1016.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-06-12-1016) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-06-12-1016.md) |
| [Forskrift om endring i forskrift om nasjonal retningslinje for sykepleierutdanni](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-12-18-2985.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-12-18-2985) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-12-18-2985.md) |
| [Forskrift om endring i forskrift om nasjonal retningslinje for sykepleierutdanni](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2026-01-23-81.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2026-01-23-81) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2026-01-23-81.md) |
| [Forskrift om endring i forskrift om nasjonal retningslinje for sykepleierutdanni](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2026-02-23-264.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2026-02-23-264) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2026-02-23-264.md) |
| [Forskrift om endring i forskrift om opptak, studier og eksamen ved Handelshøysko](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2026-04-28-737.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2026-04-28-737) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2026-04-28-737.md) |
| [Forskrift om endring i forskrift om studier ved Dronning Mauds Minne Høgskole fo](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2023-10-19-1685.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-10-19-1685) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-10-19-1685.md) |
| [Forskrift om enkelte klagenemnder på Kunnskapsdepartementets område](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-07-02-1462.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-07-02-1462) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-07-02-1462.md) |
| [Forskrift om fagskoleutdanning ved AOF Østlandet](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-06-24-2981.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-06-24-2981) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-06-24-2981.md) |
| [Forskrift om fagskoleutdanning ved Fredrikstad FagAkademi](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2017-10-17-1637.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-10-17-1637) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-10-17-1637.md) |
| [Forskrift om fagskoleutdanning ved Medlearn AS](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-11-24-3371.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-11-24-3371) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-11-24-3371.md) |
| [Forskrift om fagskoleutdanning ved NKI](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2017-08-01-1230.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-08-01-1230) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-08-01-1230.md) |
| [Forskrift om fagskoleutdanning ved Treider Fagskoler](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2017-06-16-1124.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-06-16-1124) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-06-16-1124.md) |
| [Forskrift om fagskoleutdanning ved fagskolen AOF Norge](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2017-04-04-446.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-04-04-446) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-04-04-446.md) |
| [Forskrift om familiebarnehager](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2005-12-16-1555.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2005-12-16-1555) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2005-12-16-1555.md) |
| [Forskrift om felles rammeplan for helse- og sosialfagutdanninger](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-07-04-1478.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-07-04-1478) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-07-04-1478.md) |
| [Forskrift om finansiering av private barnehager (finansieringsforskriften)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2026-03-23-454.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2026-03-23-454) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2026-03-23-454.md) |
| [Forskrift om foreldrebetaling i barnehager](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2005-12-16-1478.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2005-12-16-1478) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2005-12-16-1478.md) |
| [Forskrift om forskningsetiske komiteer og utvalg (forskningsetikkforskriften)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2018-03-05-321.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2018-03-05-321) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2018-03-05-321.md) |
| [Forskrift om forsterkning av gaver til forskning (gaveforsterkningsforskriften)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2013-12-20-1662.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-12-20-1662) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-12-20-1662.md) |
| [Forskrift om frister for sensur av eksamen ved Det juridiske fakultet ved Univer](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2018-11-29-2298.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2018-11-29-2298) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2018-11-29-2298.md) |
| [Forskrift om fulltidsstudiene ved Norges Handelshøyskole, NHH](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2024-06-18-1108.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-06-18-1108) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-06-18-1108.md) |
| [Forskrift om føring av register til bruk i forbindelse med kontroll av beregning](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2005-12-16-1510.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2005-12-16-1510) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2005-12-16-1510.md) |
| [Forskrift om generell godkjenning av utenlandsk høyere utdanning](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2024-05-21-789.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-05-21-789) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-05-21-789.md) |
| [Forskrift om godkjenning av yrkeskvalifikasjoner](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2017-12-22-2384.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-12-22-2384) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-12-22-2384.md) |
| [Forskrift om godkjenning av yrkeskvalifikasjoner for styrer og pedagogisk leder ](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2008-09-12-1071.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2008-09-12-1071) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2008-09-12-1071.md) |
| [Forskrift om godkjenning for utdanningsstøtte av utvekslingsorganisasjoner og ut](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2019-06-14-734.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-06-14-734) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-06-14-734.md) |
| [Forskrift om godkjenning for utdanningsstøtte i Norge](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2020-03-27-562.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-03-27-562) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-03-27-562.md) |
| [Forskrift om graden doctor philosophiae (dr.philos.) ved Norges Handelshøyskole](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2024-03-05-415.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-03-05-415) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-03-05-415.md) |
| [Forskrift om graden doctor philosophiae (dr.philos.) ved Norges musikkhøgskole](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-06-10-1861.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-06-10-1861) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-06-10-1861.md) |
| [Forskrift om graden doctor philosophiae (dr.philos.) ved Universitetet i Agder](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-09-15-3067.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-09-15-3067) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-09-15-3067.md) |
| [Forskrift om graden doctor philosophiae (dr.philos.) ved Universitetet i Tromsø ](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2018-06-19-1186.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2018-06-19-1186) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2018-06-19-1186.md) |
| [Forskrift om graden philosophiae doctor (ph.d.) i kunstnerisk utviklingsarbeid v](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2018-02-06-177.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2018-02-06-177) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2018-02-06-177.md) |
| [Forskrift om graden philosophiae doctor (ph.d.) i kunstnerisk utviklingsarbeid v](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2024-06-06-1106.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-06-06-1106) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-06-06-1106.md) |
| [Forskrift om graden philosophiae doctor (ph.d.) ved Handelshøyskolen BI](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2015-06-11-924.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-06-11-924) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-06-11-924.md) |
| [Forskrift om graden philosophiae doctor (ph.d.) ved Høgskulen i Volda](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2024-09-05-2677.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-09-05-2677) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-09-05-2677.md) |
| [Forskrift om graden philosophiae doctor (ph.d.) ved Høgskulen på Vestlandet](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2024-06-24-1859.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-06-24-1859) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-06-24-1859.md) |
| [Forskrift om graden philosophiae doctor (ph.d.) ved Norges musikkhøgskole](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2024-06-06-969.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-06-06-969) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-06-06-969.md) |
| [Forskrift om graden philosophiae doctor (ph.d.) ved OsloMet – storbyuniversitete](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2024-09-17-2297.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-09-17-2297) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-09-17-2297.md) |
| [Forskrift om graden philosophiae doctor (ph.d.) ved Universitetet i Sørøst-Norge](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2017-12-14-2411.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-12-14-2411) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-12-14-2411.md) |
| [Forskrift om graden philosophiae doctor (ph.d.) ved VID vitenskapelige høgskole](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2015-12-11-1666.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-12-11-1666) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-12-11-1666.md) |
| [Forskrift om graden philosophiae doctor ved Samisk høgskole](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2019-11-12-2240.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-11-12-2240) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-11-12-2240.md) |
| [Forskrift om gradene philosophiae doctor (ph.d.) og philosophiae doctor (ph.d.) ](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2022-12-01-2087.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-12-01-2087) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-12-01-2087.md) |
| [Forskrift om grader ved Kunsthøgskolen i Bergen.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2003-06-25-1236.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2003-06-25-1236) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2003-06-25-1236.md) |
| [Forskrift om grader, opptak, studier og eksamen ved VID vitenskapelige høgskole](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2024-06-04-1483.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-06-04-1483) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-06-04-1483.md) |
| [Forskrift om grunnskoleopplæring og vidaregåande opplæring i Longyearbyen](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2024-06-21-1103.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-06-21-1103) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-06-21-1103.md) |
| [Forskrift om grunnskoleopplæringa og den vidaregåande opplæringa (opplæringsfors](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2024-06-03-900.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-06-03-900) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-06-03-900.md) |
| [Forskrift om grunntilskudd til organisasjoner på grunnopplæringsområdet](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2023-12-19-2176.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-12-19-2176) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-12-19-2176.md) |
| [Forskrift om høyere yrkesfaglig utdanning (fagskoleforskriften)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2019-07-11-1005.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-07-11-1005) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-07-11-1005.md) |
| [Forskrift om høyere yrkesfaglig utdanning for Fagskolen i Agder (Forskrift for F](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2024-04-30-783.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-04-30-783) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-04-30-783.md) |
| [Forskrift om høyere yrkesfaglig utdanning for TISIP fagskole](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2020-10-12-2054.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-10-12-2054) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-10-12-2054.md) |
| [Forskrift om høyere yrkesfaglig utdanning ved Fagskolen Innlandet](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2023-12-04-2342.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-12-04-2342) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-12-04-2342.md) |
| [Forskrift om høyere yrkesfaglig utdanning ved Fagskolen Tirna](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-09-15-1843.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-09-15-1843) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-09-15-1843.md) |
| [Forskrift om høyere yrkesfaglig utdanning ved Fagskolen Vestfold og Telemark](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-06-26-1539.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-06-26-1539) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-06-26-1539.md) |
| [Forskrift om høyere yrkesfaglig utdanning ved Fagskolen i Finnmark](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2024-01-05-300.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-01-05-300) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-01-05-300.md) |
| [Forskrift om høyere yrkesfaglig utdanning ved Fagskolen i Nord](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-06-24-1413.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-06-24-1413) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-06-24-1413.md) |
| [Forskrift om høyere yrkesfaglig utdanning ved KRM Tekniske Fagskole](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2020-11-26-3304.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-11-26-3304) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-11-26-3304.md) |
| [Forskrift om høyere yrkesfaglig utdanning ved NKI Fagskoler AS](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2019-11-18-2264.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-11-18-2264) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-11-18-2264.md) |
| [Forskrift om høyere yrkesfaglig utdanning ved Nordland fagskole](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-12-16-3020.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-12-16-3020) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-12-16-3020.md) |
| [Forskrift om høyere yrkesfaglig utdanning ved Norges Fagakademi](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2019-12-11-2093.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-12-11-2093) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-12-11-2093.md) |
| [Forskrift om høyere yrkesfaglig utdanning ved Norges grønne fagskole – Vea](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2024-06-12-1347.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-06-12-1347) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-06-12-1347.md) |
| [Forskrift om høyere yrkesfaglig utdanning ved Noroff fagskole](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-08-06-1713.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-08-06-1713) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-08-06-1713.md) |
| [Forskrift om høyere yrkesfaglig utdanning ved Trøndelag høyere yrkesfagskole](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-06-24-1643.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-06-24-1643) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-06-24-1643.md) |
| [Forskrift om inntak til videregående opplæring i Longyearbyen, Longyearbyen loka](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-11-04-2265.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-11-04-2265) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-11-04-2265.md) |
| [Forskrift om kompensasjon for renteutgifter til investering i læringsarenaer, ut](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2024-06-14-1054.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-06-14-1054) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-06-14-1054.md) |
| [Forskrift om kompensasjon for utgifter til investering i skole- og svømmeanlegg ](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2014-12-11-1583.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2014-12-11-1583) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2014-12-11-1583.md) |
| [Forskrift om krav til bachelorgrad ved Høgskolen i Vestfold](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2011-06-23-724.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2011-06-23-724) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2011-06-23-724.md) |
| [Forskrift om krav til bachelorgrad ved Høgskulen for landbruk og bygdenæringar](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2010-05-27-1897.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2010-05-27-1897) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2010-05-27-1897.md) |
| [Forskrift om lokale opptak til Universitetet i Oslo](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2014-02-12-130.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2014-02-12-130) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2014-02-12-130.md) |
| [Forskrift om masterstudiene ved Arkitektur- og designhøgskolen i Oslo](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2010-05-28-1888.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2010-05-28-1888) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2010-05-28-1888.md) |
| [Forskrift om midlertidige opptaksregler ved Statens kunstakademi.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1991-01-21-54.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1991-01-21-54) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1991-01-21-54.md) |
| [Forskrift om nasjonal retningslinje for anestesisykepleierutdanning](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-09-05-1833.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-09-05-1833) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-09-05-1833.md) |
| [Forskrift om nasjonal retningslinje for audiografutdanning](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-07-04-1471.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-07-04-1471) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-07-04-1471.md) |
| [Forskrift om nasjonal retningslinje for barnesykepleierutdanning](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-09-05-1832.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-09-05-1832) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-09-05-1832.md) |
| [Forskrift om nasjonal retningslinje for barnevernspedagogutdanning](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-09-04-1828.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-09-04-1828) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-09-04-1828.md) |
| [Forskrift om nasjonal retningslinje for bioingeniørutdanning](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-07-04-1486.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-07-04-1486) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-07-04-1486.md) |
| [Forskrift om nasjonal retningslinje for ergoterapeututdanning](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-07-04-1484.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-07-04-1484) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-07-04-1484.md) |
| [Forskrift om nasjonal retningslinje for farmasøytutdanningene, bachelor- og mast](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-07-04-1474.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-07-04-1474) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-07-04-1474.md) |
| [Forskrift om nasjonal retningslinje for fysioterapeututdanning](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-07-04-1485.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-07-04-1485) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-07-04-1485.md) |
| [Forskrift om nasjonal retningslinje for helsesykepleierutdanning](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-07-04-1458.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-07-04-1458) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-07-04-1458.md) |
| [Forskrift om nasjonal retningslinje for intensivsykepleierutdanning](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-09-05-1834.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-09-05-1834) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-09-05-1834.md) |
| [Forskrift om nasjonal retningslinje for jordmorutdanning](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-09-05-1829.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-09-05-1829) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-09-05-1829.md) |
| [Forskrift om nasjonal retningslinje for klinisk ernæringsfysiologutdanning](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-07-04-1473.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-07-04-1473) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-07-04-1473.md) |
| [Forskrift om nasjonal retningslinje for kreftsykepleierutdanning](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-09-05-1831.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-09-05-1831) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-09-05-1831.md) |
| [Forskrift om nasjonal retningslinje for masterutdanning i avansert klinisk allme](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-07-04-1454.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-07-04-1454) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-07-04-1454.md) |
| [Forskrift om nasjonal retningslinje for masterutdanning i barnevern](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-07-04-1456.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-07-04-1456) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-07-04-1456.md) |
| [Forskrift om nasjonal retningslinje for masterutdanning i barnevernsarbeid](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-07-04-1455.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-07-04-1455) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-07-04-1455.md) |
| [Forskrift om nasjonal retningslinje for masterutdanning i sykepleie innen psykis](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-07-04-1916.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-07-04-1916) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-07-04-1916.md) |
| [Forskrift om nasjonal retningslinje for medisinutdanning](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-07-04-1472.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-07-04-1472) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-07-04-1472.md) |
| [Forskrift om nasjonal retningslinje for operasjonssykepleierutdanning](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-09-05-1830.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-09-05-1830) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-09-05-1830.md) |
| [Forskrift om nasjonal retningslinje for optikerutdanning](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-07-04-1470.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-07-04-1470) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-07-04-1470.md) |
| [Forskrift om nasjonal retningslinje for ortopediingeniørutdanning](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-07-04-1469.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-07-04-1469) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-07-04-1469.md) |
| [Forskrift om nasjonal retningslinje for paramedisinutdanning](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-07-04-1487.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-07-04-1487) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-07-04-1487.md) |
| [Forskrift om nasjonal retningslinje for psykologutdanning](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-07-04-1468.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-07-04-1468) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-07-04-1468.md) |
| [Forskrift om nasjonal retningslinje for radiografutdanning](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-07-04-1483.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-07-04-1483) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-07-04-1483.md) |
| [Forskrift om nasjonal retningslinje for samisk sykepleierutdanning](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-07-04-1475.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-07-04-1475) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-07-04-1475.md) |
| [Forskrift om nasjonal retningslinje for sosionomutdanning](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-07-04-1465.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-07-04-1465) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-07-04-1465.md) |
| [Forskrift om nasjonal retningslinje for sykepleierutdanning](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-07-04-1477.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-07-04-1477) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-07-04-1477.md) |
| [Forskrift om nasjonal retningslinje for tannlegeutdanning](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-07-04-1467.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-07-04-1467) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-07-04-1467.md) |
| [Forskrift om nasjonal retningslinje for tannpleierutdanning](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-07-04-1466.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-07-04-1466) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-07-04-1466.md) |
| [Forskrift om nasjonal retningslinje for tannteknikerutdanning](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-07-04-1482.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-07-04-1482) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-07-04-1482.md) |
| [Forskrift om nasjonal retningslinje for tverrfaglig videreutdanning i psykisk he](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-07-04-1457.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-07-04-1457) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-07-04-1457.md) |
| [Forskrift om nasjonal retningslinje for tverrfaglig videreutdanning i psykososia](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-03-18-523.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-03-18-523) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-03-18-523.md) |
| [Forskrift om nasjonal retningslinje for vernepleierutdanning](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-07-04-1476.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-07-04-1476) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-07-04-1476.md) |
| [Forskrift om opptak og eksamen for Astrologiskolen Herkules](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2019-05-15-635.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-05-15-635) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-05-15-635.md) |
| [Forskrift om opptak og eksamen ved Eccera IT Academy](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2020-10-15-2116.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-10-15-2116) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-10-15-2116.md) |
| [Forskrift om opptak og eksamen ved Fagskolen Aldring og helse](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2019-12-13-1794.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-12-13-1794) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-12-13-1794.md) |
| [Forskrift om opptak til Høgskulen på Vestlandet](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2024-06-24-1858.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-06-24-1858) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-06-24-1858.md) |
| [Forskrift om opptak til Universitetet i Bergen](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2018-11-27-1907.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2018-11-27-1907) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2018-11-27-1907.md) |
| [Forskrift om opptak til Universitetet i Tromsø – Norges arktiske universitet](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2020-09-15-1794.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-09-15-1794) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-09-15-1794.md) |
| [Forskrift om opptak til høgare utdanning](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2017-01-06-13.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-01-06-13) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-01-06-13.md) |
| [Forskrift om opptak til høgare utdanning (opptaksforskrifta)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-09-11-1850.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-09-11-1850) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-09-11-1850.md) |
| [Forskrift om opptak til høyere yrkesfaglig utdanning ved Fagskolen Rogaland (opp](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2024-09-19-2344.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-09-19-2344) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-09-19-2344.md) |
| [Forskrift om opptak til masterstudier ved Politihøgskolen](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2017-04-19-674.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-04-19-674) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-04-19-674.md) |
| [Forskrift om opptak til masterutdanning ved Høgskolen i Buskerud](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2006-06-21-1719.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2006-06-21-1719) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2006-06-21-1719.md) |
| [Forskrift om opptak til studier og emner ved Universitetet i Agder](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-11-24-3370.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-11-24-3370) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-11-24-3370.md) |
| [Forskrift om opptak til studier og emner ved Universitetet i Stavanger](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2018-10-18-1671.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2018-10-18-1671) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2018-10-18-1671.md) |
| [Forskrift om opptak til studier ved Høgskolen i Østfold](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-12-15-2610.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-12-15-2610) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-12-15-2610.md) |
| [Forskrift om opptak til studier ved Norges teknisk-naturvitenskapelige universit](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-03-06-376.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-03-06-376) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-03-06-376.md) |
| [Forskrift om opptak til studier ved OsloMet – storbyuniversitetet](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2015-12-15-1681.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-12-15-1681) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-12-15-1681.md) |
| [Forskrift om opptak ved Fagskulen Vestland](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-09-17-2913.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-09-17-2913) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-09-17-2913.md) |
| [Forskrift om opptak ved Lovisenberg diakonale høgskole](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-12-16-2962.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-12-16-2962) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-12-16-2962.md) |
| [Forskrift om opptak ved Universitetet i Sørøst-Norge](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2023-12-13-2111.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-12-13-2111) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-12-13-2111.md) |
| [Forskrift om opptak, disiplinære sanksjoner, klagebestemmelser og eksamen ved Fa](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2023-01-02-96.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-01-02-96) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-01-02-96.md) |
| [Forskrift om opptak, disiplinære sanksjoner, klagebestemmelser og eksamen ved Lu](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2024-10-24-3634.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-10-24-3634) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-10-24-3634.md) |
| [Forskrift om opptak, disiplinære sanksjoner, klagebestemmelser og eksamen ved fa](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2020-03-24-500.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-03-24-500) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-03-24-500.md) |
| [Forskrift om opptak, disiplinære sanksjoner, klagebestemmelser og eksamen ved fa](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-08-04-1620.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-08-04-1620) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-08-04-1620.md) |
| [Forskrift om opptak, disiplinære sanksjoner, klagebestemmelser og eksamen ved fa](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-06-22-2204.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-06-22-2204) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-06-22-2204.md) |
| [Forskrift om opptak, disiplinære sanksjoner, klagebestemmelser og eksamen ved fa](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-12-01-2991.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-12-01-2991) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-12-01-2991.md) |
| [Forskrift om opptak, disiplinære sanksjoner, klagebestemmelser og eksamen ved fa](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-08-01-4016.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-08-01-4016) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-08-01-4016.md) |
| [Forskrift om opptak, disiplinære sanksjoner, klagebestemmelser og eksamen ved fa](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2017-09-20-1444.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-09-20-1444) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-09-20-1444.md) |
| [Forskrift om opptak, disiplinære sanksjoner, klagebestemmelser og eksamen ved fa](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2022-01-17-2725.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-01-17-2725) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-01-17-2725.md) |
| [Forskrift om opptak, disiplinære sanksjoner, klagebestemmelser og eksamen ved fa](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2023-08-30-2528.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-08-30-2528) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-08-30-2528.md) |
| [Forskrift om opptak, disiplinære sanksjoner, klagebestemmelser og eksamen ved fa](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-04-23-746.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-04-23-746) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-04-23-746.md) |
| [Forskrift om opptak, disiplinære sanksjoner, klagebestemmelser og eksamen ved fa](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2019-08-22-1094.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-08-22-1094) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-08-22-1094.md) |
| [Forskrift om opptak, eksamen og sensur for Fagskolen Møre og Romsdal](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2020-10-20-2103.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-10-20-2103) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-10-20-2103.md) |
| [Forskrift om opptak, eksamen, disiplinære sanksjoner og klagehåndtering for Lofo](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2017-10-30-2479.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-10-30-2479) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-10-30-2479.md) |
| [Forskrift om opptak, gjennomføring av studier, eksamen og klageregler ved Fagsko](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-03-06-396.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-03-06-396) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-03-06-396.md) |
| [Forskrift om opptak, gjennomføring av studier, eksamen og klageregler ved Tunsbe](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2020-12-03-2662.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-12-03-2662) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-12-03-2662.md) |
| [Forskrift om opptak, gjennomføring av studier, eksamen, klageregler og skikkethe](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2019-12-20-2136.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-12-20-2136) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-12-20-2136.md) |
| [Forskrift om opptak, gjennomføring av studier, sluttvurdering, klageregler og sk](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2023-09-05-2500.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-09-05-2500) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-09-05-2500.md) |
| [Forskrift om opptak, gjennomføring og eksamen for Lokomotivførerutdanningen ved ](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2017-04-27-636.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-04-27-636) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-04-27-636.md) |
| [Forskrift om opptak, skikkethet, eksamen og klagebehandling ved Sjøforsvarets fa](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2022-08-01-1410.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-08-01-1410) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-08-01-1410.md) |
| [Forskrift om opptak, studier og eksamen for Einar Granum Kunstfagskole](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2019-12-05-2158.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-12-05-2158) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-12-05-2158.md) |
| [Forskrift om opptak, studier og eksamen for Kunstfagskolen i Bergen](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2022-10-19-2084.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-10-19-2084) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-10-19-2084.md) |
| [Forskrift om opptak, studier og eksamen ved Agder Kunstfagskole](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2019-08-31-2291.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-08-31-2291) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-08-31-2291.md) |
| [Forskrift om opptak, studier og eksamen ved Ansgar høyskole](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2024-12-11-3175.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-12-11-3175) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-12-11-3175.md) |
| [Forskrift om opptak, studier og eksamen ved Arkitektur- og designhøgskolen i Osl](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-12-17-2645.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-12-17-2645) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-12-17-2645.md) |
| [Forskrift om opptak, studier og eksamen ved Den norske Eurytmihøyskole (DnE).](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2005-12-09-1716.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2005-12-09-1716) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2005-12-09-1716.md) |
| [Forskrift om opptak, studier og eksamen ved Designinstituttet](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2020-06-09-1167.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-06-09-1167) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-06-09-1167.md) |
| [Forskrift om opptak, studier og eksamen ved Fagskolen Aldring og helse](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2017-05-22-661.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-05-22-661) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-05-22-661.md) |
| [Forskrift om opptak, studier og eksamen ved Fagskolen Kristiania](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2023-06-20-1072.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-06-20-1072) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-06-20-1072.md) |
| [Forskrift om opptak, studier og eksamen ved Fagskolen Viken](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-06-14-1978.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-06-14-1978) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-06-14-1978.md) |
| [Forskrift om opptak, studier og eksamen ved Fagskolen for bokbransjen](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2017-05-15-1139.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-05-15-1139) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-05-15-1139.md) |
| [Forskrift om opptak, studier og eksamen ved Fjellhaug Internasjonale Høgskole](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2024-11-27-3659.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-11-27-3659) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-11-27-3659.md) |
| [Forskrift om opptak, studier og eksamen ved Handelshøyskolen BI](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2018-06-01-1546.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2018-06-01-1546) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2018-06-01-1546.md) |
| [Forskrift om opptak, studier og eksamen ved Høgskolen i Molde – Vitenskapelig hø](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2015-05-07-540.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-05-07-540) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-05-07-540.md) |
| [Forskrift om opptak, studier og eksamen ved Høyskolen for Ledelse og Teologi](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2019-09-23-1468.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-09-23-1468) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-09-23-1468.md) |
| [Forskrift om opptak, studier og eksamen ved International Stunt Academy](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-02-16-530.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-02-16-530) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-02-16-530.md) |
| [Forskrift om opptak, studier og eksamen ved Jusutdanning AS](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-07-28-2462.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-07-28-2462) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-07-28-2462.md) |
| [Forskrift om opptak, studier og eksamen ved KBT fagskole](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2022-04-08-2655.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-04-08-2655) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-04-08-2655.md) |
| [Forskrift om opptak, studier og eksamen ved MF vitenskapelig høyskole](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2005-11-02-1367.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2005-11-02-1367) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2005-11-02-1367.md) |
| [Forskrift om opptak, studier og eksamen ved NSKI Høyskole](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2017-06-27-1229.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-06-27-1229) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-06-27-1229.md) |
| [Forskrift om opptak, studier og eksamen ved Norges Dansehøyskole, NDH (tidligere](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2005-08-24-1037.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2005-08-24-1037) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2005-08-24-1037.md) |
| [Forskrift om opptak, studier og eksamen ved Norges idrettshøgskole](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2005-05-26-1811.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2005-05-26-1811) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2005-05-26-1811.md) |
| [Forskrift om opptak, studier og eksamen ved Norsk Fotofagskole](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-01-22-176.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-01-22-176) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-01-22-176.md) |
| [Forskrift om opptak, studier og eksamen ved Norsk Gestaltinstitutt Høyskole](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-06-16-1701.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-06-16-1701) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-06-16-1701.md) |
| [Forskrift om opptak, studier og eksamen ved Norsk barnebokinstitutt](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2020-02-13-688.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-02-13-688) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-02-13-688.md) |
| [Forskrift om opptak, studier og eksamen ved Nortrain fagskole](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2017-05-10-596.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-05-10-596) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-05-10-596.md) |
| [Forskrift om opptak, studier og eksamen ved Oslo Nye Fagskole](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2024-03-15-478.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-03-15-478) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-03-15-478.md) |
| [Forskrift om opptak, studier og eksamen ved Oslo Nye Høyskole](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2019-03-01-1082.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-03-01-1082) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-03-01-1082.md) |
| [Forskrift om opptak, studier og eksamen ved Steinerhøyskolen](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2006-03-07-563.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2006-03-07-563) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2006-03-07-563.md) |
| [Forskrift om opptak, studier og eksamen ved Stiftelsen Norsk Hestesenter](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2020-10-21-2137.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-10-21-2137) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-10-21-2137.md) |
| [Forskrift om opptak, studier og eksamen ved Universitetet i Innlandet](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2024-06-19-1221.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-06-19-1221) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-06-19-1221.md) |
| [Forskrift om opptak, studier og eksamener ved Universitetssenteret på Svalbard A](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2019-09-27-1441.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-09-27-1441) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-09-27-1441.md) |
| [Forskrift om opptak, studier, eksamen og klagebehandling for Fabrikken Asker Kun](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2019-12-17-2134.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-12-17-2134) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-12-17-2134.md) |
| [Forskrift om opptak, studier, eksamen og klagebehandling for Kunstskolen i Stava](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2019-12-09-2189.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-12-09-2189) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-12-09-2189.md) |
| [Forskrift om opptak, studier, eksamen og klagebehandling for Ytre kunstfagskole](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2020-01-16-54.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-01-16-54) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-01-16-54.md) |
| [Forskrift om opptak, studier, eksamen og klagebehandling ved Campus BLÅ Fagskole](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2019-02-15-223.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-02-15-223) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-02-15-223.md) |
| [Forskrift om opptak, studier, grader og eksamen ved Høyskolen Kristiania](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2024-12-12-3309.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-12-12-3309) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-12-12-3309.md) |
| [Forskrift om opptak, studier, grader og eksamen ved Noroff University College AS](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2024-10-11-3715.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-10-11-3715) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-10-11-3715.md) |
| [Forskrift om opptak, studium og eksamen ved Høgskulen i Volda](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-07-03-1481.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-07-03-1481) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-07-03-1481.md) |
| [Forskrift om opptak, studium og eksamen ved Skrivekunstakademiet i Hordaland](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2017-03-14-324.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-03-14-324) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-03-14-324.md) |
| [Forskrift om opptak, utdanninger og eksamen ved Fagskolen Diakonova](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-01-09-20.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-01-09-20) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-01-09-20.md) |
| [Forskrift om overføring av forhandlingsansvaret for undervisningspersonale til k](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2003-01-31-90.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2003-01-31-90) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2003-01-31-90.md) |
| [Forskrift om overgangsregler for Høgskolen i Oslo og Akershus](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2011-09-01-948.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2011-09-01-948) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2011-09-01-948.md) |
| [Forskrift om overgangsregler for NLA Høgskolen](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2012-12-13-1432.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2012-12-13-1432) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2012-12-13-1432.md) |
| [Forskrift om overgangsregler til barnehageloven – overføring av ansvaret for å f](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-10-06-3079.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-10-06-3079) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-10-06-3079.md) |
| [Forskrift om pedagogisk bemanning og dispensasjon i barnehager](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2017-06-22-1049.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-06-22-1049) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-06-22-1049.md) |
| [Forskrift om plikt til å stille krav om bruk av lærlinger i offentlige kontrakte](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2016-12-17-1708.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2016-12-17-1708) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2016-12-17-1708.md) |
| [Forskrift om politiattest i barnehager](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2015-11-11-1285.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-11-11-1285) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-11-11-1285.md) |
| [Forskrift om private universiteter, høyskoler og fagskoler – krav til regnskap m](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2017-12-21-2383.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-12-21-2383) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-12-21-2383.md) |
| [Forskrift om rammeplan for bachelor i regnskap og revisjon](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2012-06-27-687.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2012-06-27-687) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2012-06-27-687.md) |
| [Forskrift om rammeplan for barnehagelærerutdanning](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-07-04-1447.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-07-04-1447) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-07-04-1447.md) |
| [Forskrift om rammeplan for barnehagens innhold og oppgaver](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2017-04-24-487.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-04-24-487) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-04-24-487.md) |
| [Forskrift om rammeplan for grunnskolelærerutdanning for trinn 1–7](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-07-04-1442.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-07-04-1442) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-07-04-1442.md) |
| [Forskrift om rammeplan for grunnskolelærerutdanning for trinn 5–10](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-07-04-1444.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-07-04-1444) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-07-04-1444.md) |
| [Forskrift om rammeplan for ingeniørutdanning](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2018-05-18-870.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2018-05-18-870) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2018-05-18-870.md) |
| [Forskrift om rammeplan for lektorutdanning for trinn 8–13](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-07-04-1446.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-07-04-1446) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-07-04-1446.md) |
| [Forskrift om rammeplan for lærerutdanning i praktiske og estetiske fag for trinn](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-07-04-1451.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-07-04-1451) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-07-04-1451.md) |
| [Forskrift om rammeplan for praktisk-pedagogisk utdanning](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-07-04-1449.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-07-04-1449) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-07-04-1449.md) |
| [Forskrift om rammeplan for praktisk-pedagogisk utdanning for yrkesfag for trinn ](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-07-04-1450.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-07-04-1450) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-07-04-1450.md) |
| [Forskrift om rammeplan for samisk barnehagelærerutdanning](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-07-04-1448.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-07-04-1448) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-07-04-1448.md) |
| [Forskrift om rammeplan for samisk grunnskolelærerutdanning for trinn 1–7](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-07-04-1443.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-07-04-1443) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-07-04-1443.md) |
| [Forskrift om rammeplan for samisk grunnskolelærerutdanning for trinn 5–10](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-07-04-1445.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-07-04-1445) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-07-04-1445.md) |
| [Forskrift om rammeplan for skolefritidsordningen](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-05-31-1825.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-05-31-1825) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-05-31-1825.md) |
| [Forskrift om rammeplan for yrkesfaglærerutdanning for trinn 8–13](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-07-04-1453.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-07-04-1453) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-07-04-1453.md) |
| [Forskrift om regler for utdanningsstøtte for 2019–2020 som følge av utbruddet av](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2020-04-03-569.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-04-03-569) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-04-03-569.md) |
| [Forskrift om regnskapsplikt mv. for private barnehager (økonomiforskrift til bar](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2022-12-16-2322.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-12-16-2322) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-12-16-2322.md) |
| [Forskrift om rett til eksamen som privatist ved Universitetet i Stavanger (priva](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-10-14-2123.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-10-14-2123) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-10-14-2123.md) |
| [Forskrift om rett til opplæring i samisk](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1992-03-31-204.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1992-03-31-204) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1992-03-31-204.md) |
| [Forskrift om saksbehandlingsregler ved opptak i barnehage](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2005-12-16-1477.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2005-12-16-1477) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2005-12-16-1477.md) |
| [Forskrift om skole- og feriedager (skoleruta) (2025–2026), Samisk videregående s](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-06-20-1157.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-06-20-1157) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-06-20-1157.md) |
| [Forskrift om skole- og feriedager (skoleruta) (2025–2026), Samisk videregående s](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-06-20-1158.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-06-20-1158) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-06-20-1158.md) |
| [Forskrift om skoleregler for Samisk videregående skole, Karasjok og Samisk vider](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-06-20-1156.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-06-20-1156) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-06-20-1156.md) |
| [Forskrift om studentsamskipnader](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2008-07-22-828.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2008-07-22-828) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2008-07-22-828.md) |
| [Forskrift om studieforbund godkjent av Kunnskapsdepartementet](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2020-12-15-2874.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-12-15-2874) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-12-15-2874.md) |
| [Forskrift om studiene ved Kunsthøgskolen i Oslo](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2024-06-11-1304.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-06-11-1304) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-06-11-1304.md) |
| [Forskrift om studiene ved Musikkteaterhøyskolen](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2012-08-03-1479.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2012-08-03-1479) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2012-08-03-1479.md) |
| [Forskrift om studiene ved Norges musikkhøgskole](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2005-12-16-1559.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2005-12-16-1559) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2005-12-16-1559.md) |
| [Forskrift om studiene ved etter- og videreutdanningen ved Norges Handelshøyskole](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2024-06-18-1057.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-06-18-1057) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-06-18-1057.md) |
| [Forskrift om studier og eksamen ved Lovisenberg diakonale høgskole](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2024-12-03-3571.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-12-03-3571) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-12-03-3571.md) |
| [Forskrift om studier og eksamen ved Nord universitet](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2024-06-19-1643.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-06-19-1643) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-06-19-1643.md) |
| [Forskrift om studier og eksamen ved OsloMet – storbyuniversitetet (OsloMet)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2023-06-15-1310.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-06-15-1310) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-06-15-1310.md) |
| [Forskrift om studier og eksamen ved Universitetet i Agder](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2005-06-22-833.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2005-06-22-833) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2005-06-22-833.md) |
| [Forskrift om studier og eksamen ved Universitetet i Stavanger](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-06-12-1278.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-06-12-1278) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-06-12-1278.md) |
| [Forskrift om studier og eksamen ved Universitetet i Sørøst-Norge (USN)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2024-06-19-1376.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-06-19-1376) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-06-19-1376.md) |
| [Forskrift om studier og eksamener ved Universitetet i Oslo](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2005-12-20-1798.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2005-12-20-1798) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2005-12-20-1798.md) |
| [Forskrift om studier og eksamener ved Universitetet i Tromsø – Norges arktiske u](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2020-06-26-1617.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-06-26-1617) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-06-26-1617.md) |
| [Forskrift om studier ved Dronning Mauds Minne Høgskole for barnehagelærerutdanni](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-06-05-1370.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-06-05-1370) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-06-05-1370.md) |
| [Forskrift om studier ved NLA Høgskolen](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2024-06-05-1822.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-06-05-1822) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-06-05-1822.md) |
| [Forskrift om studier ved Norges miljø- og biovitenskapelige universitet](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2023-03-09-322.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-03-09-322) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-03-09-322.md) |
| [Forskrift om studier ved Norges teknisk-naturvitenskapelige universitet (NTNU)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-03-06-384.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-03-06-384) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-03-06-384.md) |
| [Forskrift om studium og eksamen ved Høgskulen på Vestlandet](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-06-12-1547.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-06-12-1547) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-06-12-1547.md) |
| [Forskrift om studium ved Fagskulen Vestland](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-03-07-529.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-03-07-529) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-03-07-529.md) |
| [Forskrift om studium ved Universitetet i Bergen](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2023-06-15-1359.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-06-15-1359) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-06-15-1359.md) |
| [Forskrift om tilbakebetaling av utdanningslån](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2022-12-15-2259.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-12-15-2259) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-12-15-2259.md) |
| [Forskrift om tilbakebetaling av utdanningslån 2020](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2019-12-17-1872.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-12-17-1872) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-12-17-1872.md) |
| [Forskrift om tilbakebetaling av utdanningslån 2021](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2020-12-17-3022.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-12-17-3022) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-12-17-3022.md) |
| [Forskrift om tilbakebetaling av utdanningslån 2022](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-12-15-3636.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-12-15-3636) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-12-15-3636.md) |
| [Forskrift om tildeling av tilskudd til private barnehager](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2015-10-09-1166.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-10-09-1166) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-10-09-1166.md) |
| [Forskrift om tildeling av utdanningsstøtte for undervisningsåret 2019–2020](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2019-03-15-254.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-03-15-254) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-03-15-254.md) |
| [Forskrift om tilpasning til universitets- og høyskoleloven for Høgskolen for kri](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2026-04-17-602.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2026-04-17-602) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2026-04-17-602.md) |
| [Forskrift om tilskudd til dekning av skolepenger til elever ved utenlandske elle](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2003-02-13-224.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2003-02-13-224) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2003-02-13-224.md) |
| [Forskrift om tilskudd til kollektiv kompetanseutvikling i barnehage og grunnskol](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2026-01-12-23.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2026-01-12-23) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2026-01-12-23.md) |
| [Forskrift om tilskudd til kollektiv kompetanseutvikling i videregående opplæring](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2026-01-12-25.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2026-01-12-25) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2026-01-12-25.md) |
| [Forskrift om tilskudd til studentboliger](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2004-01-28-424.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2004-01-28-424) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2004-01-28-424.md) |
| [Forskrift om tilskudd til videreutdanning i barnehage, grunnskole og videregåend](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2026-01-12-24.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2026-01-12-24) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2026-01-12-24.md) |
| [Forskrift om trafikkflyger fagskoleutdanning CAE Oslo Aviation Academy](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2019-11-13-2285.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-11-13-2285) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-11-13-2285.md) |
| [Forskrift om trafikkflyger fagskoleutdanning European Helicopter Center](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2023-12-27-2428.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-12-27-2428) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-12-27-2428.md) |
| [Forskrift om unntak fra rett og plikt til deltagelse i opplæring i norsk og samf](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2020-12-18-2830.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-12-18-2830) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-12-18-2830.md) |
| [Forskrift om utanrettslege gjeldsordningar og ettergiving av fordringar som er u](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2001-10-31-1274.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2001-10-31-1274) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2001-10-31-1274.md) |
| [Forskrift om utdanning ved Fagskolen Rogaland (utdanningsforskrift for Fagskolen](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2024-09-19-2345.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-09-19-2345) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-09-19-2345.md) |
| [Forskrift om utdanningsstøtte](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2020-04-15-798.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-04-15-798) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-04-15-798.md) |
| [Forskrift om utfylling av dei overordna måla og prinsippa for opplæringa i grunn](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2017-09-01-1332.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-09-01-1332) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-09-01-1332.md) |
| [Forskrift om utvidet sensurfrist for fjernundervisningsemner ved Høgskolen i Sør](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2005-11-16-1340.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2005-11-16-1340) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2005-11-16-1340.md) |
| [Forskrift til folkehøgskoleloven (folkehøgskoleforskriften)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-08-21-1693.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-08-21-1693) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-08-21-1693.md) |
| [Forskrift til privatskolelova (privatskoleforskrifta)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2024-06-03-901.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-06-03-901) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-06-03-901.md) |
| [Forskrift til privatskolelova kapittel 6A](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2020-11-23-2476.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-11-23-2476) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-11-23-2476.md) |
| [Forskrift til rammeplan for videreutdanning i aldring og eldreomsorg](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2005-12-01-1383.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2005-12-01-1383) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2005-12-01-1383.md) |
| [Forskrift til rammeplan for videreutdanning i helsefremmende og forebyggende arb](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2005-12-01-1382.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2005-12-01-1382) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2005-12-01-1382.md) |
| [Forskrift til universitets- og høyskoleloven (universitets- og høyskoleforskrift](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2024-06-28-1392.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-06-28-1392) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-06-28-1392.md) |
| [Grunnregler for skoler til utdanning av vernepleiere (grunnregler i vernepleie)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1980-06-17-8756.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1980-06-17-8756) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1980-06-17-8756.md) |
| [Mellombels forskrift om sensurfristar ved Norges Handelshøyskole (NHH)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-12-16-3961.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-12-16-3961) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-12-16-3961.md) |
| [Mellombels forskrift om sensurfristar ved Norges Handelshøyskole (NHH)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2023-12-12-2083.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-12-12-2083) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-12-12-2083.md) |
| [Midlertidig forskrift om midlertidig godkjenning av ordinære barnehager og midle](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2023-06-27-1136.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-06-27-1136) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-06-27-1136.md) |
| [Økonomiforskrift til privatskolelova](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2018-09-01-1295.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2018-09-01-1295) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2018-09-01-1295.md) |
