# Barne- og familiedepartementet

*94 forskrifter*

| Forskrift | Lovdata | Historikk |
|-----------|---------|-----------|
| [Forskrift om Barne-, ungdoms- og familieetatens rett til å kreve egenbetaling fr](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2003-11-26-1397.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2003-11-26-1397) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2003-11-26-1397.md) |
| [Forskrift om Barnesakkyndig kommisjon](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2022-08-12-1430.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-08-12-1430) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-08-12-1430.md) |
| [Forskrift om Den norske kirkes medlemsregister](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-11-14-3326.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-11-14-3326) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-11-14-3326.md) |
| [Forskrift om Digital gravferdsmelding](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2024-06-05-940.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-06-05-940) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-06-05-940.md) |
| [Forskrift om Forbrukertilsynets og Markedsrådets saksbehandling mv.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2017-11-21-1817.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-11-21-1817) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-11-21-1817.md) |
| [Forskrift om Reservasjonsregisteret](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2009-06-05-598.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2009-06-05-598) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2009-06-05-598.md) |
| [Forskrift om adopsjon](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2018-06-22-959.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2018-06-22-959) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2018-06-22-959.md) |
| [Forskrift om anvendelse av familievernkontorloven på Svalbard](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2008-05-23-479.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2008-05-23-479) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2008-05-23-479.md) |
| [Forskrift om barnevernslovens anvendelse på Svalbard](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1995-09-01-772.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1995-09-01-772) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1995-09-01-772.md) |
| [Forskrift om barnevernstjenestens oppfølging av barn på barnevernsinstitusjon (o](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2022-12-15-2240.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-12-15-2240) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-12-15-2240.md) |
| [Forskrift om barns medvirkning i barnevernet](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2023-10-12-1631.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-10-12-1631) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-10-12-1631.md) |
| [Forskrift om barns rettigheter i barnevernsinstitusjon](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2022-12-20-2358.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-12-20-2358) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-12-20-2358.md) |
| [Forskrift om behandling av begjæringer om anerkjennelse av ekteskap etter ektesk](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2024-12-20-3300.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-12-20-3300) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-12-20-3300.md) |
| [Forskrift om behandling av forbrukerklager i Forbrukertilsynet og Forbrukerklage](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2020-12-21-3084.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-12-21-3084) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-12-21-3084.md) |
| [Forskrift om behandling av opplysninger i kredittopplysningsvirksomhet (kreditto](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2022-05-20-883.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-05-20-883) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-05-20-883.md) |
| [Forskrift om behandling av personopplysninger i programmet Sammen på vei](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2024-06-13-1053.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-06-13-1053) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-06-13-1053.md) |
| [Forskrift om ettergjeving.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1992-10-13-762.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1992-10-13-762) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1992-10-13-762.md) |
| [Forskrift om fastsetjing av medmorskap](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2008-12-15-1362.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2008-12-15-1362) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2008-12-15-1362.md) |
| [Forskrift om fastsetjing og endring av fostringstilskot](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2003-01-15-123.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2003-01-15-123) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2003-01-15-123.md) |
| [Forskrift om fastsetting og endring av oppfostringsbidrag etter lov om barnevern](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2006-06-23-723.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2006-06-23-723) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2006-06-23-723.md) |
| [Forskrift om forvaltning av kulturhistorisk verdifulle kirker (kirkebyggforskrif](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2020-12-18-2827.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-12-18-2827) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-12-18-2827.md) |
| [Forskrift om fosterhjem](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2023-10-13-1632.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-10-13-1632) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-10-13-1632.md) |
| [Forskrift om frivillig merking av lydnivå ved husholdningsapparater](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1996-05-29-566.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1996-05-29-566) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1996-05-29-566.md) |
| [Forskrift om fysisk sikkerheit i krisesentertilbodet](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2017-03-07-282.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-03-07-282) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-03-07-282.md) |
| [Forskrift om føring av klientjournal og meklingsprotokoll ved familievernkontore](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2007-12-20-1763.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2007-12-20-1763) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2007-12-20-1763.md) |
| [Forskrift om gebyr for offentlig fastsettelse av barnebidrag](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2001-11-04-1250.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2001-11-04-1250) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2001-11-04-1250.md) |
| [Forskrift om gjennomføringen av bestemmelsene om inntektsprøving av forskott](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2003-02-06-125.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2003-02-06-125) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2003-02-06-125.md) |
| [Forskrift om godtgjering til andre som gjer teneste etter barnelova § 61 første ](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2004-03-10-516.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2004-03-10-516) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2004-03-10-516.md) |
| [Forskrift om i hvilke tilfelle bidragsfogden skal fastsette eller endre bidrag a](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1994-08-09-797.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1994-08-09-797) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1994-08-09-797.md) |
| [Forskrift om i hvilke tilfelle det kan ytes bidragsforskott til barn som har del](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2003-09-25-1181.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2003-09-25-1181) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2003-09-25-1181.md) |
| [Forskrift om i hvilke tilfelle vilkåret i forskotteringsloven om bosted og oppho](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1989-06-21-518.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1989-06-21-518) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1989-06-21-518.md) |
| [Forskrift om individuell plan ved ytelse av velferdstjenester](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2022-06-22-1110.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-06-22-1110) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-06-22-1110.md) |
| [Forskrift om innlemmelse av forordning (EU) nr. 1007/2011 om tekstilfibernavn og](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2012-10-25-990.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2012-10-25-990) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2012-10-25-990.md) |
| [Forskrift om klageorganer for forbrukersaker](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2016-06-20-733.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2016-06-20-733) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2016-06-20-733.md) |
| [Forskrift om kommunale vigsler](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2017-09-18-1421.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-09-18-1421) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-09-18-1421.md) |
| [Forskrift om krav til kvalitet og godkjenning av barnevernsinstitusjoner (kvalit](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2022-12-22-2474.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-12-22-2474) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-12-22-2474.md) |
| [Forskrift om krystallglass](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1997-07-03-773.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1997-07-03-773) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1997-07-03-773.md) |
| [Forskrift om livsoppholdssatser ved utleggstrekk og gjeldsordning](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2014-06-13-724.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2014-06-13-724) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2014-06-13-724.md) |
| [Forskrift om mekling etter ekteskapsloven og barneloven.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2006-12-18-1478.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2006-12-18-1478) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2006-12-18-1478.md) |
| [Forskrift om merking av fottøy](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1996-01-08-13.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1996-01-08-13) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1996-01-08-13.md) |
| [Forskrift om merking av retusjert reklame](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2022-06-17-1114.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-06-17-1114) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-06-17-1114.md) |
| [Forskrift om når en utenlandsk statsborger skal anses å være fast bosatt i Norge](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1992-11-05-979.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1992-11-05-979) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1992-11-05-979.md) |
| [Forskrift om opplysningsplikt og angrerett mv.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2014-06-20-777.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2014-06-20-777) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2014-06-20-777.md) |
| [Forskrift om oppnevnelse av og godtgjørelse til medhjelper under gjeldsforhandli](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1992-12-04-885.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1992-12-04-885) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1992-12-04-885.md) |
| [Forskrift om overgangsbestemmelser til lov av 10. januar 2003 nr. 1 om endringer](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2003-04-04-432.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2003-04-04-432) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2003-04-04-432.md) |
| [Forskrift om overgangsreglar i samband med nye reglar om fastsetjing av fostring](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2003-01-15-119.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2003-01-15-119) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2003-01-15-119.md) |
| [Forskrift om overgangsreglar til lov 20. juni 2003 nr. 40 om endringer i barnelo](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2004-02-24-471.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2004-02-24-471) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2004-02-24-471.md) |
| [Forskrift om overgangsregler for det økonomiske ansvaret for hjelpetiltak i sent](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-12-07-3419.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-12-07-3419) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-12-07-3419.md) |
| [Forskrift om overgangsregler til endringer i lov 8. mars 2002 nr. 4 om barnetryg](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2024-06-26-1360.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-06-26-1360) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-06-26-1360.md) |
| [Forskrift om overgangsregler til lov 18. juni 2021 nr. 97 om barnevern (barnever](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2022-12-15-2264.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-12-15-2264) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-12-15-2264.md) |
| [Forskrift om pakkereiselovens anvendelse for Svalbard](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2022-11-25-2021.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-11-25-2021) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-11-25-2021.md) |
| [Forskrift om pakkereiser og reisegaranti mv. (pakkereiseforskriften)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2018-06-22-954.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2018-06-22-954) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2018-06-22-954.md) |
| [Forskrift om politiattest etter barnevernsloven](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2022-12-20-2359.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-12-20-2359) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-12-20-2359.md) |
| [Forskrift om prisopplysninger mv. for varer og tjenester](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2012-11-14-1066.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2012-11-14-1066) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2012-11-14-1066.md) |
| [Forskrift om registrering av og tilskudd til tros- og livssynssamfunn (trossamfu](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2020-12-18-2825.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-12-18-2825) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-12-18-2825.md) |
| [Forskrift om registrering og melding av vigsel](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1992-11-20-854.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1992-11-20-854) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1992-11-20-854.md) |
| [Forskrift om rekneskapsføring av pensjonsutgifter for Den norske kyrkja (rettssu](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-01-19-193.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-01-19-193) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-01-19-193.md) |
| [Forskrift om saksbehandlingen for statsforvalteren ved separasjon og skilsmisse ](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1992-11-18-981.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1992-11-18-981) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1992-11-18-981.md) |
| [Forskrift om samla fastsetjing av tilskot i visse tilfelle.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2003-01-15-122.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2003-01-15-122) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2003-01-15-122.md) |
| [Forskrift om sammenlignende reklame](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2000-12-19-1653.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2000-12-19-1653) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2000-12-19-1653.md) |
| [Forskrift om samtaleprosess i barneverns- og helsenemnda (samtaleprosessforskrif](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2023-01-27-106.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-01-27-106) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-01-27-106.md) |
| [Forskrift om samvær med tilsyn etter barnelova](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2013-12-19-1636.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-12-19-1636) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-12-19-1636.md) |
| [Forskrift om sentre for foreldre og barn](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2022-12-22-2509.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-12-22-2509) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-12-22-2509.md) |
| [Forskrift om standard opplysningsskjemaer etter lov om avtaler om deltidsbruksre](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2012-07-03-766.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2012-07-03-766) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2012-07-03-766.md) |
| [Forskrift om stans i utbetalinga av offentlege ytingar og barnebidrag når ein av](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2015-07-01-847.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-07-01-847) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-07-01-847.md) |
| [Forskrift om statlig refusjon av utgifter til kommunale presteboliger.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2007-06-01-570.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2007-06-01-570) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2007-06-01-570.md) |
| [Forskrift om statsforvalterens adgang til å ilegge kommuner mulkt ved oversittel](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1992-12-16-1243.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1992-12-16-1243) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1992-12-16-1243.md) |
| [Forskrift om særtilskot](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2003-01-15-121.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2003-01-15-121) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2003-01-15-121.md) |
| [Forskrift om tildeling og tilbaketrekning av vigselsrett i tros- og livssynssamf](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2020-12-18-2826.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-12-18-2826) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-12-18-2826.md) |
| [Forskrift om tilskudd til barnevernsfaglig videreutdanning](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2022-12-20-2541.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-12-20-2541) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-12-20-2541.md) |
| [Forskrift om tilskudd til dialog, debatt, samarbeid og kunnskapsutvikling på tro](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2022-03-16-435.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-03-16-435) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-03-16-435.md) |
| [Forskrift om tilskudd til frivillige barne- og ungdomsorganisasjoner](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2022-01-18-90.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-01-18-90) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-01-18-90.md) |
| [Forskrift om tilskudd til inkludering av barn og unge](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-11-23-3261.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-11-23-3261) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-11-23-3261.md) |
| [Forskrift om tilskudd til kulturhistorisk verdifulle kirkebygg](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2024-06-23-1309.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-06-23-1309) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-06-23-1309.md) |
| [Forskrift om tilskudd til organisasjoner i barnevernet](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2022-11-24-2046.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-11-24-2046) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-11-24-2046.md) |
| [Forskrift om tilskudd til tiltak mot vold og overgrep](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-11-24-3297.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-11-24-3297) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-11-24-3297.md) |
| [Forskrift om tilskudd til utviklings- og samhandlingsprosjekter i barnevernet](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2022-11-22-2034.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-11-22-2034) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-11-22-2034.md) |
| [Forskrift om tilsyn med tjenester og tiltak til barn i barnevernsinstitusjoner m](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2022-12-16-2272.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-12-16-2272) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-12-16-2272.md) |
| [Forskrift om urimelig handelspraksis](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2009-06-01-565.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2009-06-01-565) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2009-06-01-565.md) |
| [Forskrift om utmåling av tvangsmulkt og overtredelsesgebyr](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2023-02-14-193.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-02-14-193) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-02-14-193.md) |
| [Forskrift om vedlikeholdsmerking av tekstilprodukter mv.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2004-10-01-1340.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2004-10-01-1340) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2004-10-01-1340.md) |
| [Forskrift om vilkår for rett til kontantstøtte til småbarnsforeldre – forholdet ](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2000-10-03-984.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2000-10-03-984) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2000-10-03-984.md) |
| [Forskrift om virksomhet etter gjeldsinformasjonsloven (gjeldsinformasjonsforskri](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2017-10-31-1691.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-10-31-1691) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-10-31-1691.md) |
| [Forskrift om å klargjere morskap](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2013-12-17-1592.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-12-17-1592) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-12-17-1592.md) |
| [Forskrift om økonomiforvaltningen i sokn i Den norske kirke](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2020-12-08-2646.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-12-08-2646) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-12-08-2646.md) |
| [Forskrift til lov om Haagkonvensjonen 1996 om sentralmyndigheten mv.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2016-06-07-604.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2016-06-07-604) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2016-06-07-604.md) |
| [Forskrift til lov om gravplasser, kremasjon og gravferd (gravplassforskriften)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1997-01-10-16.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1997-01-10-16) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1997-01-10-16.md) |
| [Forskrifter om adgangen til kirkelig vigsel for medlemmer av The Evangelical Lut](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1952-05-08-6.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1952-05-08-6) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1952-05-08-6.md) |
| [Forskrifter om anerkjennelse av nordiske farskapsavgjørelser.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1981-11-20-8950.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1981-11-20-8950) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1981-11-20-8950.md) |
| [Forskrifter om indeksregulering av underholdsbidrag til barn.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1981-11-20-8986.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1981-11-20-8986) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1981-11-20-8986.md) |
| [Kirkeordning for Den norske kirke](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2019-03-30-2307.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-03-30-2307) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-03-30-2307.md) |
| [Midlertidig forskrift om endring i forskrifter etter barnevernloven for å håndte](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2022-06-20-1116.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-06-20-1116) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-06-20-1116.md) |
| [Overgangsregler til lov om klageorganer for forbrukersaker (gjennomføring av dir](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2016-06-20-735.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2016-06-20-735) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2016-06-20-735.md) |
| [Vedtak om borgerlig vigselsformular](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1996-01-19-4263.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1996-01-19-4263) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1996-01-19-4263.md) |
