# Finansdepartementet

*310 forskrifter*

| Forskrift | Lovdata | Historikk |
|-----------|---------|-----------|
| [Forskrift fastsatt av Skattedirektoratet om satser mv. til bruk for forskudd og ](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2022-11-22-2002.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-11-22-2002) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-11-22-2002.md) |
| [Forskrift fastsatt av Skattedirektoratet til utfylling og gjennomføring mv. av s](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1999-11-22-1160.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1999-11-22-1160) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1999-11-22-1160.md) |
| [Forskrift for Norges Kommunalbank.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1967-01-20-4129.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1967-01-20-4129) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1967-01-20-4129.md) |
| [Forskrift for skattemessig behandling av deltakere i samordning og omfordeling a](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1988-12-02-998.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1988-12-02-998) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1988-12-02-998.md) |
| [Forskrift for statlige, kommunale og fylkeskommunale etater og institusjoner om ](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1964-11-20-3.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1964-11-20-3) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1964-11-20-3.md) |
| [Forskrift for virksomheten til Statens Banksikringsfond.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1991-11-29-763.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1991-11-29-763) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1991-11-29-763.md) |
| [Forskrift om Arbeids- og velferdsetatens kompetanse til å fastsette pensjonsgive](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2013-04-29-422.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-04-29-422) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-04-29-422.md) |
| [Forskrift om EU-gjødselvarer (EU-gjødselvareforskriften)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2024-03-06-538.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-03-06-538) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-03-06-538.md) |
| [Forskrift om Etikkrådets og Norges Banks behandling av personopplysninger](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2019-06-27-924.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-06-27-924) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-06-27-924.md) |
| [Forskrift om Statens finansfond](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2009-05-08-495.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2009-05-08-495) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2009-05-08-495.md) |
| [Forskrift om adgang for visse foretak etablert i Det Forente Kongeriket Storbrit](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-11-30-3303.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-11-30-3303) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-11-30-3303.md) |
| [Forskrift om adgang til lån og innskudd i Norges Bank](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2019-12-18-2025.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-12-18-2025) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-12-18-2025.md) |
| [Forskrift om arbeidsgivers innrapportering av ansettelses- og inntektsforhold me](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2014-06-24-857.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2014-06-24-857) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2014-06-24-857.md) |
| [Forskrift om avgrensning av arbeidsgiveravgiftsfritaket etter folketrygdloven § ](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1997-11-19-1173.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1997-11-19-1173) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1997-11-19-1173.md) |
| [Forskrift om avgrensning av eiendomsskatt på statlige eiendommer](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1992-11-18-850.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1992-11-18-850) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1992-11-18-850.md) |
| [Forskrift om avgrensning av tvungne betalingsmidler](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-12-17-3771.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-12-17-3771) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-12-17-3771.md) |
| [Forskrift om avsetning til reservefond for filialer m.v. av selskaper hjemmehøre](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1983-04-29-916.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1983-04-29-916) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1983-04-29-916.md) |
| [Forskrift om behandling av godtgjørelse til fiskere i forhold til lov om obligat](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2006-12-20-1521.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2006-12-20-1521) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2006-12-20-1521.md) |
| [Forskrift om beregning av ansvarlig kapital for banker, kredittforetak, finansie](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1990-06-01-435.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1990-06-01-435) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1990-06-01-435.md) |
| [Forskrift om beregning av foretaksspesifikke satser for kapitalbufferkrav](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2022-01-12-59.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-01-12-59) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-01-12-59.md) |
| [Forskrift om beregning av kapitalavkastning i livsforsikrings- og pensjonsforeta](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2017-01-06-10.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-01-06-10) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-01-06-10.md) |
| [Forskrift om beregning av underskudd og gjennomføring av fradrag i toppskattegru](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1989-12-22-1351.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1989-12-22-1351) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1989-12-22-1351.md) |
| [Forskrift om beregning av underskudd og gjennomføring av fradrag i toppskattegru](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1990-12-21-1016.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1990-12-21-1016) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1990-12-21-1016.md) |
| [Forskrift om beregning av underskudd og gjennomføring av fradrag i toppskattegru](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1991-12-20-849.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1991-12-20-849) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1991-12-20-849.md) |
| [Forskrift om beregning og fastsetting m.v. av arbeidsgiveravgift til folketrygde](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1997-12-02-1385.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1997-12-02-1385) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1997-12-02-1385.md) |
| [Forskrift om bokføring](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2004-12-01-1558.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2004-12-01-1558) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2004-12-01-1558.md) |
| [Forskrift om bruk av informasjons- og kommunikasjonsteknologi (IKT)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2003-05-21-630.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2003-05-21-630) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2003-05-21-630.md) |
| [Forskrift om bruk av normpris ved skattefastsettingen (Undersjøiske naturforekom](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1976-12-17-7.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1976-12-17-7) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1976-12-17-7.md) |
| [Forskrift om digital operasjonell motstandsdyktighet i finanssektoren (DORA-fors](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-06-24-1296.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-06-24-1296) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-06-24-1296.md) |
| [Forskrift om dokumentavgift.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1975-12-16-1.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1975-12-16-1) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1975-12-16-1.md) |
| [Forskrift om eiendomsmegling](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2007-11-23-1318.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2007-11-23-1318) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2007-11-23-1318.md) |
| [Forskrift om endring av motorvogners avgiftsmessige status](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2015-12-16-1685.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-12-16-1685) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-12-16-1685.md) |
| [Forskrift om endring i forordning om Den europeiske banktilsynsmyndighet om loka](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-07-02-2339.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-07-02-2339) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-07-02-2339.md) |
| [Forskrift om endring i forskrift om inn- og utførsel av varer (vareførselsforskr](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2023-11-22-1915.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-11-22-1915) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-11-22-1915.md) |
| [Forskrift om endring i forskrift om inn- og utførsel av varer (vareførselsforskr](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-02-04-156.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-02-04-156) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-02-04-156.md) |
| [Forskrift om endring i forskrift om inn- og utførsel av varer (vareførselsforskr](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-04-30-725.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-04-30-725) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-04-30-725.md) |
| [Forskrift om endring i forskrift om inn- og utførsel av varer (vareførselsforskr](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-06-30-1375.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-06-30-1375) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-06-30-1375.md) |
| [Forskrift om endring i forskrift om inn- og utførsel av varer (vareførselsforskr](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2026-02-26-296.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2026-02-26-296) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2026-02-26-296.md) |
| [Forskrift om endring i forskrift om inn- og utførsel av varer (vareførselsforskr](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2026-05-05-749.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2026-05-05-749) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2026-05-05-749.md) |
| [Forskrift om endring i forskrift om nedsettelse av pensjonsgivende inntekt, pens](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-06-13-1017.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-06-13-1017) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-06-13-1017.md) |
| [Forskrift om endring i forskrift om prospekt for verdipapirfond.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2003-08-13-1046.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2003-08-13-1046) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2003-08-13-1046.md) |
| [Forskrift om endring i forskrift til utfylling og gjennomføring mv. av skattelov](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2014-12-19-1890.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2014-12-19-1890) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2014-12-19-1890.md) |
| [Forskrift om engangsavgift på motorvogner](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2001-03-19-268.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2001-03-19-268) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2001-03-19-268.md) |
| [Forskrift om erstatning for sterkt skadde eller bortkomne sedler og mynter](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-12-17-3772.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-12-17-3772) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-12-17-3772.md) |
| [Forskrift om fakturering av kredittkortgjeld mv.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2017-04-04-427.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-04-04-427) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-04-04-427.md) |
| [Forskrift om fastsettelse av rente på grunnkjøpsobligasjoner](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1969-10-17-8569.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1969-10-17-8569) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1969-10-17-8569.md) |
| [Forskrift om fastsettelse av rente på statens grunnkjøpsobligasjoner](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1977-12-23-8568.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1977-12-23-8568) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1977-12-23-8568.md) |
| [Forskrift om fastsettelse av renten på statens grunnkjøpsobligasjoner og grunnkj](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1981-04-10-8565.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1981-04-10-8565) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1981-04-10-8565.md) |
| [Forskrift om fastsettelse av renten på statens grunnkjøpsobligasjoner.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1980-01-11-8567.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1980-01-11-8567) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1980-01-11-8567.md) |
| [Forskrift om fastsettelse av skattemessige inngangsverdier pr. 1. januar 1997 fo](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1997-01-20-79.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1997-01-20-79) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1997-01-20-79.md) |
| [Forskrift om fastsettelse av tidligere ervervsinntekt som nevnt i § 7-10 nr. 1 i](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1972-09-22-3.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1972-09-22-3) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1972-09-22-3.md) |
| [Forskrift om fastsettelse av vilkår for statens grunnkjøpsobligasjoner](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1965-07-09-8570.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1965-07-09-8570) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1965-07-09-8570.md) |
| [Forskrift om fastsettelse og innkreving av avgifter til folketrygden for persone](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1997-12-22-1432.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1997-12-22-1432) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1997-12-22-1432.md) |
| [Forskrift om finansforetak og finanskonsern (finansforetaksforskriften)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2016-12-09-1502.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2016-12-09-1502) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2016-12-09-1502.md) |
| [Forskrift om finansforetakenes utlånspraksis (utlånsforskriften)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2020-12-09-2648.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-12-09-2648) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-12-09-2648.md) |
| [Forskrift om forbud mot markedsføring, distribusjon og salg av binære opsjoner t](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2020-02-04-107.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-02-04-107) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-02-04-107.md) |
| [Forskrift om forenklet anvendelse av internasjonale regnskapsstandarder](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2022-02-07-182.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-02-07-182) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-02-07-182.md) |
| [Forskrift om forenklet oppgjør for arbeidsgiveravgift fra statens forvaltningsvi](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2003-11-27-1398.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2003-11-27-1398) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2003-11-27-1398.md) |
| [Forskrift om formidlere omfattet av verdipapirsentralloven § 4-5](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2022-09-01-1523.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-09-01-1523) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-09-01-1523.md) |
| [Forskrift om formidlingsgebyr i kortordninger mv.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2019-12-16-1843.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-12-16-1843) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-12-16-1843.md) |
| [Forskrift om forsikringsformidling (forsikringsformidlingsforskriften)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-12-22-3872.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-12-22-3872) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-12-22-3872.md) |
| [Forskrift om forsinkelsesrente og kompensasjon for inndrivelseskostnader](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-12-18-2658.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-12-18-2658) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-12-18-2658.md) |
| [Forskrift om forvaltning og bruk av midler i premiefond og innskuddsfond](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1989-11-21-1170.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1989-11-21-1170) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1989-11-21-1170.md) |
| [Forskrift om fradrag i inntekt om bord ved beregning av sjømannsskatt fra og med](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1982-09-16-1431.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1982-09-16-1431) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1982-09-16-1431.md) |
| [Forskrift om frådrag i inntekt om bord ved utrekning av sjømannsskatt frå og med](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1983-10-13-1571.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1983-10-13-1571) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1983-10-13-1571.md) |
| [Forskrift om frådrag i inntekt om bord ved utrekning av sjømannsskatt frå og med](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1984-10-09-1752.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1984-10-09-1752) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1984-10-09-1752.md) |
| [Forskrift om frådrag i inntekt om bord ved utrekning av sjømannsskatt frå og med](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1985-10-08-1806.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1985-10-08-1806) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1985-10-08-1806.md) |
| [Forskrift om frådrag i sjømannsskatt ved aksjesparing.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1982-12-15-1787.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1982-12-15-1787) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1982-12-15-1787.md) |
| [Forskrift om gebyr når kommunene utøver namskompetanse etter tvangsfullbyrdelses](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-07-01-1397.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-07-01-1397) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-07-01-1397.md) |
| [Forskrift om gjennomføring av EØS-regler om vedtatte internasjonale regnskapssta](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2004-12-17-1852.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2004-12-17-1852) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2004-12-17-1852.md) |
| [Forskrift om gjennomføring av EØS-rettsakter om europeisk statistikk](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2020-12-11-2745.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-12-11-2745) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-12-11-2745.md) |
| [Forskrift om gjennomføring av lov av 16. juni 1972 om fradrag ved inntektslignin](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1972-07-17-3.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1972-07-17-3) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1972-07-17-3.md) |
| [Forskrift om gjennomføring av nedsettelse av pensjonsgivende inntekt, pensjonsop](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1997-12-19-1421.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1997-12-19-1421) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1997-12-19-1421.md) |
| [Forskrift om gjennomføring av opplysningsplikt etter § 5-3 i sentralbankloven](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2020-01-16-53.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-01-16-53) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-01-16-53.md) |
| [Forskrift om gjennomføring av skatte- og avgiftskontroll](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2013-03-08-258.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-03-08-258) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-03-08-258.md) |
| [Forskrift om gjennomføring av verdipapir- og interbankoppgjør i insolvenssituasj](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2016-09-22-1095.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2016-09-22-1095) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2016-09-22-1095.md) |
| [Forskrift om gjennomføringen av fordeling av skatt mv. mellom skattekreditorene](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2012-06-20-627.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2012-06-20-627) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2012-06-20-627.md) |
| [Forskrift om godkjenning av denaturering av teknisk etanol og etanolholdige prep](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2015-12-16-1686.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-12-16-1686) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-12-16-1686.md) |
| [Forskrift om gradvis anvendelse av nytt regelverk om utlegg mv. (utrullingsforsk](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-12-12-2508.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-12-12-2508) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-12-12-2508.md) |
| [Forskrift om hvad der skal henføres til skattepliktig formue og inntekt samt bes](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1925-12-18-9838.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1925-12-18-9838) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1925-12-18-9838.md) |
| [Forskrift om ikke-samarbeidsvillige jurisdiksjoner for skatteformål](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-07-01-1379.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-07-01-1379) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-07-01-1379.md) |
| [Forskrift om ikraftsetting av lov 27. juni 2008 nr. 63 om endringer i lov 12. ju](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2010-03-26-466.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2010-03-26-466) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2010-03-26-466.md) |
| [Forskrift om inn- og utførsel av varer (vareførselsforskriften)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2022-10-27-1901.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-10-27-1901) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-10-27-1901.md) |
| [Forskrift om innhenting av opplysninger ved fastsettelse av bunnfradrag.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1993-02-11-107.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1993-02-11-107) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1993-02-11-107.md) |
| [Forskrift om innkreving av statlige krav mv. (innkrevingsforskriften)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-07-01-1396.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-07-01-1396) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-07-01-1396.md) |
| [Forskrift om innsendelse og offentliggjøring i forbindelse med flaggepliktig ver](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2007-12-06-1359.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2007-12-06-1359) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2007-12-06-1359.md) |
| [Forskrift om innskuddspensjonsordninger som skal oppfylle minstekravene i lov om](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2006-06-30-870.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2006-06-30-870) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2006-06-30-870.md) |
| [Forskrift om kapitalkrav for utenlandske livsforsikringsselskaper med filial i N](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1989-11-21-1173.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1989-11-21-1173) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1989-11-21-1173.md) |
| [Forskrift om kapitalkrav for utenlandske skadeforsikringsselskaper med filial i ](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1989-11-21-1172.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1989-11-21-1172) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1989-11-21-1172.md) |
| [Forskrift om kapitalkrav og gjennomføring av CRR/CRD-regelverket (CRR/CRD-forskr](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2014-08-22-1097.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2014-08-22-1097) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2014-08-22-1097.md) |
| [Forskrift om klassifisering av varer (tolltariffen)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-12-16-2594.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-12-16-2594) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-12-16-2594.md) |
| [Forskrift om kommunefordeling av grunnlaget for eigedomsskatt for kraftanlegg.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2000-12-20-1393.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2000-12-20-1393) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2000-12-20-1393.md) |
| [Forskrift om kompensasjon av merverdiavgift til kommuner, fylkeskommuner mv.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2003-12-12-1566.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2003-12-12-1566) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2003-12-12-1566.md) |
| [Forskrift om konsolidering mv. i tverrsektorielle grupper](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2015-12-18-1764.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-12-18-1764) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-12-18-1764.md) |
| [Forskrift om kontrollkomité for verdipapirregistre](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2003-01-31-86.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2003-01-31-86) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2003-01-31-86.md) |
| [Forskrift om krav til kassasystem (kassasystemforskrifta)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2015-12-18-1616.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-12-18-1616) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-12-18-1616.md) |
| [Forskrift om krav til rapportering av opplysninger om innskytere og innskudd til](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2019-12-02-1640.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-12-02-1640) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-12-02-1640.md) |
| [Forskrift om kredittvurderingsbyråer](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2016-10-03-1174.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2016-10-03-1174) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2016-10-03-1174.md) |
| [Forskrift om land-for-land-rapportering](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2013-12-20-1682.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-12-20-1682) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-12-20-1682.md) |
| [Forskrift om likeverdighetsvurderinger etter EMIR](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2017-06-30-1085.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-06-30-1085) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-06-30-1085.md) |
| [Forskrift om likeverdsvurderingar etter kredittvurderingsbyråforordningen](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2019-12-17-1882.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-12-17-1882) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-12-17-1882.md) |
| [Forskrift om likeverdsvurderingar etter verdipapirmarkedsdirektivet og -forordni](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2019-12-18-1991.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-12-18-1991) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-12-18-1991.md) |
| [Forskrift om lovpålagte forsikringer mv. som er tegnet i britiske foretak og adg](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2020-12-18-2858.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-12-18-2858) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-12-18-2858.md) |
| [Forskrift om låneformidling (låneformidlingsforskriften)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2023-06-28-1154.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-06-28-1154) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-06-28-1154.md) |
| [Forskrift om medlemskap i pensjonsordning for personer som ikke er pliktig medle](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2006-03-16-311.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2006-03-16-311) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2006-03-16-311.md) |
| [Forskrift om meldeplikt ved utkontraktering av virksomhet mv.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-09-15-2777.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-09-15-2777) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-09-15-2777.md) |
| [Forskrift om midlertidig bruk av utenlandsregistrert motorvogn i Norge](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1991-06-20-381.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1991-06-20-381) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1991-06-20-381.md) |
| [Forskrift om midlertidig tilskuddsordning for foretak med stort omsetningsfall p](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2020-04-17-810.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-04-17-810) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-04-17-810.md) |
| [Forskrift om midlertidig unntak fra prioritetsreglene under rekonstruksjon etter](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2020-05-11-974.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-05-11-974) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-05-11-974.md) |
| [Forskrift om nedsettelse av pensjonsgivende inntekt, pensjonsopptjening og avgif](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1997-12-18-1408.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1997-12-18-1408) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1997-12-18-1408.md) |
| [Forskrift om nedsettelse av renter ved klage- og domstolsbehandling av tilleggss](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2016-06-17-713.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2016-06-17-713) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2016-06-17-713.md) |
| [Forskrift om normalvedtekt for ymsesidige sjøtrygdelag etter lov av 3. juli 1953](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1956-11-09-9388.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1956-11-09-9388) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1956-11-09-9388.md) |
| [Forskrift om normalvedtekter for gjensidige sjøtrygdelag ifølge lov av 3. juli 1](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1956-11-09-8632.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1956-11-09-8632) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1956-11-09-8632.md) |
| [Forskrift om omdannelse av Verdipapirsentralen](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2002-12-20-1726.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2002-12-20-1726) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2002-12-20-1726.md) |
| [Forskrift om omregistreringsavgift](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1986-07-02-1430.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1986-07-02-1430) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1986-07-02-1430.md) |
| [Forskrift om oppheving av forskrift om valutaregulering. Delegering av myndighet](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1990-06-22-589.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1990-06-22-589) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1990-06-22-589.md) |
| [Forskrift om opplysningsplikt til den offisielle lønnsstatistikken ved rapporter](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2020-12-14-2753.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-12-14-2753) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-12-14-2753.md) |
| [Forskrift om overføring av fødselsregistreringen til folkeregistrerene.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1982-10-22-3421.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1982-10-22-3421) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1982-10-22-3421.md) |
| [Forskrift om overgangsregler for innkrevingsloven og endringer i andre lover](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-07-01-1418.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-07-01-1418) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-07-01-1418.md) |
| [Forskrift om overgangsregler for private tjenestepensjonsordninger etter skattel](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2000-12-22-1412.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2000-12-22-1412) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2000-12-22-1412.md) |
| [Forskrift om overgangsregler for veterinærer som etter søknad har oppgavefritak ](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2011-08-31-892.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2011-08-31-892) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2011-08-31-892.md) |
| [Forskrift om overgangsregler mv. til lov 10. april 2015 nr. 17 om finansforetak ](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2015-12-21-1794.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-12-21-1794) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-12-21-1794.md) |
| [Forskrift om overgangsregler mv. til lov 25. juni 2010 nr. 33 om endringer i reg](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2010-07-01-1048.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2010-07-01-1048) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2010-07-01-1048.md) |
| [Forskrift om overgangsregler til forskrift om årsregnskap m.m. for forsikringsse](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1998-12-16-1242.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1998-12-16-1242) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1998-12-16-1242.md) |
| [Forskrift om overgangsregler til kryptoeiendelsloven](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-12-18-2854.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-12-18-2854) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-12-18-2854.md) |
| [Forskrift om overgangsregler til lov 15. juni 2007 nr. 28 om endringer i foretak](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2007-06-29-743.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2007-06-29-743) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2007-06-29-743.md) |
| [Forskrift om overgangsregler til lov 15. mars 2019 nr. 6 om verdipapirsentraler ](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2019-12-20-2065.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-12-20-2065) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-12-20-2065.md) |
| [Forskrift om overgangsregler til lov 19. april 2013 nr. 15 om endringer i regnsk](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2013-06-03-568.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-06-03-568) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-06-03-568.md) |
| [Forskrift om overgangsregler til lov 19. juni 2009 nr. 48 om endringer i lov 12.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2009-06-26-908.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2009-06-26-908) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2009-06-26-908.md) |
| [Forskrift om overgangsregler til lov 21. juni 2019 nr. 41 om endringer i verdipa](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-02-24-540.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-02-24-540) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-02-24-540.md) |
| [Forskrift om overgangsregler til lov 22. juni 2012 nr. 35 om endringer i bokføri](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2012-06-22-568.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2012-06-22-568) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2012-06-22-568.md) |
| [Forskrift om overgangsregler til lov 29. juni 2007 nr. 73 om eiendomsmegling](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2007-11-23-1282.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2007-11-23-1282) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2007-11-23-1282.md) |
| [Forskrift om overgangsregler til lov 29. juni 2007 nr. 74 om regulerte markeder ](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2007-06-29-750.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2007-06-29-750) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2007-06-29-750.md) |
| [Forskrift om overgangsregler til lov 3. mai 2019 nr. 14 om endringer i innskudds](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2020-11-06-2272.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-11-06-2272) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-11-06-2272.md) |
| [Forskrift om overgangsregler til lov om endringer i pensjonslovgivningen mv. (pe](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-12-22-3856.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-12-22-3856) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-12-22-3856.md) |
| [Forskrift om overgangsregler til lov om endringer i revisorloven og enkelte andr](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2011-04-15-401.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2011-04-15-401) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2011-04-15-401.md) |
| [Forskrift om overgangsregler til regler om ettergivelse og tvangsinnkreving av f](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2001-10-02-1132.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2001-10-02-1132) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2001-10-02-1132.md) |
| [Forskrift om overgangsregler ved avviklingen av de særlige reglene om nettoligni](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2005-09-09-1043.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2005-09-09-1043) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2005-09-09-1043.md) |
| [Forskrift om pensjonsforetak](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2016-12-09-1503.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2016-12-09-1503) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2016-12-09-1503.md) |
| [Forskrift om plikt for innehavere av inkassobevillinger til å holde tilsynsmyndi](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1990-03-12-213.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1990-03-12-213) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1990-03-12-213.md) |
| [Forskrift om politiattest ved arbeid eller tjeneste for Norges Bank](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2019-12-17-1880.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-12-17-1880) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-12-17-1880.md) |
| [Forskrift om rapportering for forsikringsformidlingsforetak](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2022-11-29-2044.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-11-29-2044) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-11-29-2044.md) |
| [Forskrift om rapportering om faktiske eller mulige overtredelser av markedsmisbr](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2022-08-23-1467.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-08-23-1467) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-08-23-1467.md) |
| [Forskrift om rapporteringsplikt for foretak som driver inkassovirksomhet](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2007-11-29-1332.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2007-11-29-1332) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2007-11-29-1332.md) |
| [Forskrift om rebalanserende tiltak i form av visse tolløkninger på enkelte varer](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2003-11-21-1363.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2003-11-21-1363) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2003-11-21-1363.md) |
| [Forskrift om register over opplysninger om valutaveksling og overføring av betal](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2004-12-06-1573.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2004-12-06-1573) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2004-12-06-1573.md) |
| [Forskrift om regnskap for skattepliktige som driver petroleumsutvinning og rørle](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1976-12-17-8.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1976-12-17-8) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1976-12-17-8.md) |
| [Forskrift om rentegodtgjersle når eigedomsskatt vert innbetalt for seint eller b](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1987-12-18-977.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1987-12-18-977) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1987-12-18-977.md) |
| [Forskrift om rentegodtgjørelse ved tilbakebetaling av sjømannsskatt.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1986-12-12-2192.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1986-12-12-2192) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1986-12-12-2192.md) |
| [Forskrift om renten på kontolån til statskassen. Særavtaler.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1980-01-04-8566.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1980-01-04-8566) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1980-01-04-8566.md) |
| [Forskrift om renter ved tilbakebetaling av for meget innbetalt CO2-avgift.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1998-06-12-577.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1998-06-12-577) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1998-06-12-577.md) |
| [Forskrift om revisjon og revisorer](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2020-12-18-2988.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-12-18-2988) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-12-18-2988.md) |
| [Forskrift om risikostyring og internkontroll](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2008-09-22-1080.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2008-09-22-1080) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2008-09-22-1080.md) |
| [Forskrift om saksbehandlingsfrister ved erverv av betydelig eierandel i verdipap](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2016-11-09-1306.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2016-11-09-1306) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2016-11-09-1306.md) |
| [Forskrift om samtykke til overdragelse av tillatelse og interesseoverføring ette](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2009-07-01-956.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2009-07-01-956) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2009-07-01-956.md) |
| [Forskrift om satser mv. til bruk for forskudd og skattefastsetting for 2021](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2020-11-26-2480.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-11-26-2480) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-11-26-2480.md) |
| [Forskrift om satser mv. til bruk for forskudd og skattefastsetting for 2022](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-11-23-3287.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-11-23-3287) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-11-23-3287.md) |
| [Forskrift om satser mv. til bruk for forskudd og skattefastsetting for 2024](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2023-11-24-1905.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-11-24-1905) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-11-24-1905.md) |
| [Forskrift om satser mv. til bruk for forskudd og skattefastsetting for 2025](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2024-11-27-2889.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-11-27-2889) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-11-27-2889.md) |
| [Forskrift om satser mv. til bruk for forskudd og skattefastsetting for 2026](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-11-07-2216.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-11-07-2216) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-11-07-2216.md) |
| [Forskrift om skatt til Svalbard](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1997-12-15-1305.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1997-12-15-1305) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1997-12-15-1305.md) |
| [Forskrift om skattefradrag for uføre](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2014-12-19-1860.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2014-12-19-1860) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2014-12-19-1860.md) |
| [Forskrift om skattefrie fondsavsetninger m.v.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1975-12-19-26.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1975-12-19-26) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1975-12-19-26.md) |
| [Forskrift om skattefrie fondsavsetninger til bedring av arbeidsmiljø.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1976-05-14-1.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1976-05-14-1) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1976-05-14-1.md) |
| [Forskrift om skattefrie fondsavsetninger til miljøverntiltak.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1981-11-25-1.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1981-11-25-1) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1981-11-25-1.md) |
| [Forskrift om skattefrie fondsavsetninger.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1963-01-18-8.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1963-01-18-8) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1963-01-18-8.md) |
| [Forskrift om skattefrie fondsavsetninger. Delegering av myndighet.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1983-03-25-728.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1983-03-25-728) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1983-03-25-728.md) |
| [Forskrift om skattlegging av inntekt vunnet ved utvinning og rørledningstranspor](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1993-04-30-316.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1993-04-30-316) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1993-04-30-316.md) |
| [Forskrift om standarder for bærekraftsrapportering](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2024-12-20-3325.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-12-20-3325) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-12-20-3325.md) |
| [Forskrift om systemer for betalingstjenester](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2019-02-15-152.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-02-15-152) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-02-15-152.md) |
| [Forskrift om særavgifter](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2001-12-11-1451.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2001-12-11-1451) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2001-12-11-1451.md) |
| [Forskrift om særlige skatteregler for Nord-Norge.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1954-10-15-9888.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1954-10-15-9888) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1954-10-15-9888.md) |
| [Forskrift om særskilt takst på ikke forsikret bygg eller anlegg som blir skadet ](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1972-12-08-15.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1972-12-08-15) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1972-12-08-15.md) |
| [Forskrift om taksering av formues-, inntekts og fradragsposter mv. som må fastse](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-12-01-2404.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-12-01-2404) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-12-01-2404.md) |
| [Forskrift om takseringsregler til bruk ved beskatning ved trekk i lønn mv. (lønn](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-12-15-2559.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-12-15-2559) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-12-15-2559.md) |
| [Forskrift om takseringsregler til bruk ved beskatningen av utenlandske artister ](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-12-15-2562.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-12-15-2562) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-12-15-2562.md) |
| [Forskrift om tilbaketrekking av 50-øremynt som gyldig betalingsmiddel](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2011-03-16-294.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2011-03-16-294) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2011-03-16-294.md) |
| [Forskrift om tilbaketrekking av betalingsmidler](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2017-04-05-450.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-04-05-450) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-04-05-450.md) |
| [Forskrift om tilbaketrekking av betalingsmidler 1000-kroneseddelen](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2019-11-01-1469.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-11-01-1469) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-11-01-1469.md) |
| [Forskrift om tilbaketrekking av betalingsmidler 50- og 500-kroneseddelen](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2018-09-12-1688.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2018-09-12-1688) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2018-09-12-1688.md) |
| [Forskrift om tilsyn med finansforetak og forvaltningsselskap som har hovedsete i](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1993-12-28-1257.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1993-12-28-1257) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1993-12-28-1257.md) |
| [Forskrift om tiltak mot hvitvasking og terrorfinansiering (hvitvaskingsforskrift](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2018-09-14-1324.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2018-09-14-1324) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2018-09-14-1324.md) |
| [Forskrift om tollavgift (tollavgiftsforskriften)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2022-10-27-1938.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-10-27-1938) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-10-27-1938.md) |
| [Forskrift om tvangsmulkt etter OTP-loven](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-06-24-2196.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-06-24-2196) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-06-24-2196.md) |
| [Forskrift om unntak fra CRR-forordningen (EU) nr. 575/2013](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2022-10-18-1759.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-10-18-1759) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-10-18-1759.md) |
| [Forskrift om unntak fra finansforetaksloven for avtaler inngått av amerikanske s](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2022-06-29-1247.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-06-29-1247) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-06-29-1247.md) |
| [Forskrift om unntak fra forvaltningslovens klageregler for vedtak fattet av Fina](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2004-12-17-1716.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2004-12-17-1716) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2004-12-17-1716.md) |
| [Forskrift om unntak fra lov av 5. april 1974 nr. 11 om aksjeemisjoner.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1974-11-15-7.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1974-11-15-7) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1974-11-15-7.md) |
| [Forskrift om unntak fra registreringsplikt for ihendehaverobligasjoner.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2003-02-06-139.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2003-02-06-139) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2003-02-06-139.md) |
| [Forskrift om unntak fra taushetsplikt ved rapportering til transaksjonsregister](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2020-03-19-351.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-03-19-351) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-03-19-351.md) |
| [Forskrift om utfasing av særfradraget for store sykdomsutgifter](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2012-03-30-270.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2012-03-30-270) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2012-03-30-270.md) |
| [Forskrift om utfyllende regler til det forenklede solvenskapitalkravet for pensj](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2018-11-09-1689.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2018-11-09-1689) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2018-11-09-1689.md) |
| [Forskrift om utfylling og gjennomføring av overgangsregel i lov 21. juni 2013 nr](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2014-04-25-576.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2014-04-25-576) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2014-04-25-576.md) |
| [Forskrift om utsettelse av skatteinnbetalinger mv. for å avhjelpe konsekvensene ](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2020-04-07-764.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-04-07-764) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-04-07-764.md) |
| [Forskrift om utskriving, betaling og avregning av terminskatt m.v.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1980-09-05-4.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1980-09-05-4) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1980-09-05-4.md) |
| [Forskrift om vareførselskontroll på Svalbard](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2022-12-13-2193.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-12-13-2193) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-12-13-2193.md) |
| [Forskrift om vektårsavgift](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2000-06-29-688.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2000-06-29-688) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2000-06-29-688.md) |
| [Forskrift om verdipapirsentraler og verdipapiroppgjør (verdipapirsentralforskrif](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2019-12-18-1900.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-12-18-1900) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-12-18-1900.md) |
| [Forskrift om årsavgift for motorvogn](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1986-07-04-1433.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1986-07-04-1433) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1986-07-04-1433.md) |
| [Forskrift om årsregnskap for banker, kredittforetak og finansieringsforetak](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1998-12-16-1240.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1998-12-16-1240) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1998-12-16-1240.md) |
| [Forskrift om årsregnskap for livsforsikringsforetak](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2015-12-18-1824.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-12-18-1824) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-12-18-1824.md) |
| [Forskrift om årsregnskap for pensjonsforetak](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2011-12-20-1457.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2011-12-20-1457) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2011-12-20-1457.md) |
| [Forskrift om årsregnskap for skadeforsikringsforetak](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2015-12-18-1775.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-12-18-1775) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-12-18-1775.md) |
| [Forskrift om årsregnskap m.m. for eiendomsmeglere.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1999-10-14-1084.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1999-10-14-1084) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1999-10-14-1084.md) |
| [Forskrift om årsregnskap m.m. for inkassovirksomhet.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1999-05-28-655.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1999-05-28-655) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1999-05-28-655.md) |
| [Forskrift om årsregnskap m.m. for verdipapirfond](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1999-05-28-654.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1999-05-28-654) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1999-05-28-654.md) |
| [Forskrift om årsregnskap m.m. for verdipapirforetak, forvaltningsselskap og AIF-](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1999-08-23-957.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1999-08-23-957) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1999-08-23-957.md) |
| [Forskrift om årsregnskap og årsberetning for borettslag](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2005-06-30-745.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2005-06-30-745) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2005-06-30-745.md) |
| [Forskrift til a-opplysningsloven § 12a om tilpasset innføring av a-ordningen](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2014-10-29-1364.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2014-10-29-1364) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2014-10-29-1364.md) |
| [Forskrift til finansforetaksloven om gjennomføring av Solvens II-direktivet (Sol](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2015-08-25-999.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-08-25-999) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-08-25-999.md) |
| [Forskrift til finanstilsynsloven (finanstilsynsforskriften)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-03-27-543.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-03-27-543) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-03-27-543.md) |
| [Forskrift til folkeregisterloven (folkeregisterforskriften)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2017-07-14-1201.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-07-14-1201) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-07-14-1201.md) |
| [Forskrift til forsikringsvirksomhetsloven (livsforsikring mv.)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2006-06-30-869.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2006-06-30-869) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2006-06-30-869.md) |
| [Forskrift til lov av 24. mars 2000 nr. 16 om foretakspensjon](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2000-12-01-1212.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2000-12-01-1212) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2000-12-01-1212.md) |
| [Forskrift til lov av 24. november 2000 nr. 81 om innskuddspensjon i arbeidsforho](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2000-12-22-1413.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2000-12-22-1413) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2000-12-22-1413.md) |
| [Forskrift til lov om Bankenes sikringsfond](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2018-12-19-2145.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2018-12-19-2145) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2018-12-19-2145.md) |
| [Forskrift til lov om beskyttelse av supplerende pensjonsrettigheter for arbeidst](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2023-06-28-1157.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-06-28-1157) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-06-28-1157.md) |
| [Forskrift til lov om finansieringsvirksomhet.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1985-03-08-530.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1985-03-08-530) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1985-03-08-530.md) |
| [Forskrift til lov om forvaltning av alternative investeringsfond](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2014-06-26-877.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2014-06-26-877) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2014-06-26-877.md) |
| [Forskrift til lov om kryptoeiendeler (kryptoeiendelsforskriften)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-06-25-1311.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-06-25-1311) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-06-25-1311.md) |
| [Forskrift til lov om nøkkelinformasjon om sammensatte og forsikringsbaserte inve](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2024-09-16-2162.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-09-16-2162) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-09-16-2162.md) |
| [Forskrift til lov om offentliggjøring av bærekraftsinformasjon i finanssektoren ](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2022-12-20-2354.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-12-20-2354) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-12-20-2354.md) |
| [Forskrift til lov om register over reelle rettighetshavere](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-06-21-2056.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-06-21-2056) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-06-21-2056.md) |
| [Forskrift til lov om regnskapsførere (regnskapsførerforskriften)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2022-12-16-2270.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-12-16-2270) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-12-16-2270.md) |
| [Forskrift til merverdiavgiftsloven (merverdiavgiftsforskriften)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2009-12-15-1540.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2009-12-15-1540) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2009-12-15-1540.md) |
| [Forskrift til referanseverdiloven (referanseverdiforskriften)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2019-12-18-1989.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-12-18-1989) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-12-18-1989.md) |
| [Forskrift til skatteforvaltningsloven (skatteforvaltningsforskriften)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2016-11-23-1360.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2016-11-23-1360) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2016-11-23-1360.md) |
| [Forskrift til statistikkloven (statistikkforskriften)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2020-12-11-2731.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-12-11-2731) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-12-11-2731.md) |
| [Forskrift til tjenestepensjonsloven](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2014-06-27-885.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2014-06-27-885) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2014-06-27-885.md) |
| [Forskrift til utfylling og gjennomføring av lov om lønnsstøtte (økonomiske tilta](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2022-02-04-167.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-02-04-167) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-02-04-167.md) |
| [Forskrift til utfylling og gjennomføring av lov om midlertidig kompensasjonsordn](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2020-06-30-1453.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-06-30-1453) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-06-30-1453.md) |
| [Forskrift til utfylling og gjennomføring av lov om midlertidig tilskuddsordning ](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2020-04-17-820.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-04-17-820) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-04-17-820.md) |
| [Forskrift til utfylling og gjennomføring av lov om tilskudd ved avbrutt permitte](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2020-06-29-1420.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-06-29-1420) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-06-29-1420.md) |
| [Forskrift til utfylling og gjennomføring av reglene i lov om skatt på honorar ti](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1997-12-17-1400.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1997-12-17-1400) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1997-12-17-1400.md) |
| [Forskrift til utfylling og gjennomføring mv. av regnskapsloven av 17. juli 1998 ](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2006-09-07-1062.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2006-09-07-1062) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2006-09-07-1062.md) |
| [Forskrift til utfylling og gjennomføring mv. av skattebetalingsloven (skattebeta](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2007-12-21-1766.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2007-12-21-1766) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2007-12-21-1766.md) |
| [Forskrift til utfylling og gjennomføring mv. av skatteloven av 26. mars 1999 nr.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1999-11-19-1158.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1999-11-19-1158) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1999-11-19-1158.md) |
| [Forskrift til utfylling og gjennomføring mv. av suppleringsskatteloven av 12. ja](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2024-03-26-541.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-03-26-541) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-03-26-541.md) |
| [Forskrift til verdipapirfondloven](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2011-12-21-1467.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2011-12-21-1467) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2011-12-21-1467.md) |
| [Forskrift til verdipapirhandelloven (verdipapirforskriften)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2007-06-29-876.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2007-06-29-876) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2007-06-29-876.md) |
| [Forskrift vedrørende systemet med generelle tollpreferanser for import av varer ](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1971-09-03-3.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1971-09-03-3) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1971-09-03-3.md) |
| [Forskrifter etter lov om skattefrie fondsavsetninger – avsetninger til miljøvern](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1978-12-08-1.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1978-12-08-1) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1978-12-08-1.md) |
| [Forskrifter etter lov om særlige skatteregler til fremme av distriktsutbygging. ](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1979-09-25-1.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1979-09-25-1) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1979-09-25-1.md) |
| [Forskrifter om frist for anvendelse av midler avsatt til premiefond til folketry](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1977-04-22-9891.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1977-04-22-9891) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1977-04-22-9891.md) |
| [Forskrifter om hvilken fart som skal regnes som fjernfart ved skattlegging av sj](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1972-12-04-2.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1972-12-04-2) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1972-12-04-2.md) |
| [Forskrifter om sjømenns fradrag for foreningskontingent ved beregning og trekk a](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1977-11-24-1.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1977-11-24-1) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1977-11-24-1.md) |
| [Forskrifter om skattefrie fondsavsetninger til energiøkonomisering.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1978-07-14-2.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1978-07-14-2) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1978-07-14-2.md) |
| [Forskrifter om skattefrie fondsavsetninger, avsetninger til miljøverntiltak.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1977-12-02-3.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1977-12-02-3) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1977-12-02-3.md) |
| [Forskrifter om skattefrie fondsavsetninger, avsetninger til miljøverntiltak.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1979-12-14-3.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1979-12-14-3) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1979-12-14-3.md) |
| [Forskrifter om skattefrie fondsavsetninger, avsetninger til miljøverntiltak.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1980-12-19-5.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1980-12-19-5) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1980-12-19-5.md) |
| [Forskrifter om skattefrie fondsavsetninger, avsetninger til miljøverntiltak.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1981-12-11-8965.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1981-12-11-8965) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1981-12-11-8965.md) |
| [Forskrifter om skattefrie fondsavsetninger.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1972-04-28-4.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1972-04-28-4) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1972-04-28-4.md) |
| [Forskrifter om skattefrie fondsavsetninger. Avsetninger til miljøverntiltak.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1976-12-03-1.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1976-12-03-1) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1976-12-03-1.md) |
| [Forskrifter om stiftelse og organisasjon av gjensidige sjøtrygdelag.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1956-11-09-5.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1956-11-09-5) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1956-11-09-5.md) |
| [Kunngjøring av normrentesats for inntektsåret 2012 til bruk ved anvendelse av fo](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2013-01-25-69.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-01-25-69) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-01-25-69.md) |
| [Kunngjøring av normrentesats for inntektsåret 2013 til bruk ved anvendelse av fo](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2014-01-29-73.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2014-01-29-73) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2014-01-29-73.md) |
| [Kunngjøring av normrentesats for inntektsåret 2014 i henhold til forskrift 18. a](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2015-02-06-86.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-02-06-86) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-02-06-86.md) |
| [Kunngjøring av normrentesats for inntektsåret 2015 i henhold til forskrift 18. a](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2016-02-04-94.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2016-02-04-94) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2016-02-04-94.md) |
| [Kunngjøring av normrentesats for inntektsåret 2016 etter forskrift 18. august 19](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2017-01-30-101.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-01-30-101) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-01-30-101.md) |
| [Kunngjøring av normrentesats for inntektsåret 2017 etter forskrift 18. august 19](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2018-01-26-106.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2018-01-26-106) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2018-01-26-106.md) |
| [Kunngjøring av normrentesats for inntektsåret 2018 etter forskrift 18. august 19](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2019-02-15-122.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-02-15-122) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-02-15-122.md) |
| [Kunngjøring av normrentesats for inntektsåret 2019 etter forskrift 18. august 19](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2020-01-22-59.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-01-22-59) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-01-22-59.md) |
| [Kunngjøring av normrentesats for inntektsåret 2020 etter forskrift 18. august 19](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-01-07-48.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-01-07-48) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-01-07-48.md) |
| [Kunngjøring av normrentesats for inntektsåret 2021 etter forskrift 18. august 19](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2022-01-19-84.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-01-19-84) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-01-19-84.md) |
| [Kunngjøring av rentesats for inntektsåret 2012 til bruk ved fremføring av unders](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2013-01-25-70.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-01-25-70) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-01-25-70.md) |
| [Kunngjøring av rentesats for inntektsåret 2013 til bruk ved fremføring av unders](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2014-01-29-72.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2014-01-29-72) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2014-01-29-72.md) |
| [Kunngjøring av rentesats for inntektsåret 2014 til bruk ved framføring av unders](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2015-02-06-87.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-02-06-87) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-02-06-87.md) |
| [Kunngjøring av rentesats for inntektsåret 2015 til bruk ved fremføring av unders](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2016-02-04-95.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2016-02-04-95) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2016-02-04-95.md) |
| [Kunngjøring av rentesats for inntektsåret 2016 til bruk ved fremføring av unders](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2017-01-30-102.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-01-30-102) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-01-30-102.md) |
| [Kunngjøring av rentesats for inntektsåret 2017 til bruk ved fremføring av unders](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2018-01-26-105.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2018-01-26-105) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2018-01-26-105.md) |
| [Kunngjøring av rentesats for inntektsåret 2018 til bruk ved fremføring av unders](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2019-02-15-121.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-02-15-121) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-02-15-121.md) |
| [Kunngjøring av rentesats for inntektsåret 2019 til bruk ved fremføring av unders](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2020-01-22-58.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-01-22-58) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-01-22-58.md) |
| [Kunngjøring av rentesats for inntektsåret 2020 til bruk ved fremføring av unders](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-01-07-47.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-01-07-47) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-01-07-47.md) |
| [Kunngjøring av rentesats for inntektsåret 2021 til bruk ved fremføring av unders](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2022-01-19-83.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-01-19-83) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-01-19-83.md) |
| [Midlertidig forskrift om fastsettelse av pris ved pliktig tilbud](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2020-05-20-1030.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-05-20-1030) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-05-20-1030.md) |
| [Midlertidig forskrift om unntak fra autorisasjonsplikten etter regnskapsførerlov](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2011-11-24-1134.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2011-11-24-1134) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2011-11-24-1134.md) |
| [Midlertidig forskrift til skattelovens regler om avskrivning på driftsmidler og ](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1982-10-12-1449.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1982-10-12-1449) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1982-10-12-1449.md) |
| [Overgangsregler om forsikringsformidling](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-12-22-3873.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-12-22-3873) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-12-22-3873.md) |
| [Overgangsregler til lov 10. april 2025 nr. 10 om endringer i eiendomsmeglingslov](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-11-13-2263.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-11-13-2263) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-11-13-2263.md) |
| [Overgangsregler til lov 11. april 2014 nr. 12 om endringer i finansieringsvirkso](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2014-05-06-608.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2014-05-06-608) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2014-05-06-608.md) |
| [Overgangsregler til lov 19. juni 2009 nr. 60 om endringer i revisorloven og enke](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2009-06-19-707.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2009-06-19-707) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2009-06-19-707.md) |
| [Overgangsregler til lov 21. juni 2024 nr. 42 om endringer i regnskapsloven mv. (](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2024-10-11-2477.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-10-11-2477) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-10-11-2477.md) |
| [Overgangsregler til lov 22. juni 2022 nr. 80 om endringer i verdipapirhandellove](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2022-06-27-1205.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-06-27-1205) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-06-27-1205.md) |
| [Overgangsregler til lov 30. april 2021 nr. 26 om endringer i verdipapirhandellov](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-06-24-2176.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-06-24-2176) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-06-24-2176.md) |
| [Retningsliner om grunnlag for og berekning av kommunefordelingsnøklar for grunnl](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2000-12-20-1394.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2000-12-20-1394) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2000-12-20-1394.md) |
| [Rundskriv om filialetablering og fusjoner.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1984-02-16-3908.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1984-02-16-3908) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1984-02-16-3908.md) |
| [Vedtak om fastsettelse av alternativ instrumentidentifikator](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2009-03-24-352.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2009-03-24-352) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2009-03-24-352.md) |
| [Vedtak om fastsettelse av rente for skattlegging av havbruksvirksomhet for innte](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-01-24-66.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-01-24-66) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-01-24-66.md) |
| [Vedtak om fastsettelse av renter for beskatning av kraftforetak for inntektsåret](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2015-01-22-54.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-01-22-54) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-01-22-54.md) |
| [Vedtak om fastsettelse av renter for beskatning av kraftforetak for inntektsåret](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2016-01-26-59.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2016-01-26-59) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2016-01-26-59.md) |
| [Vedtak om fastsettelse av renter for beskatning av kraftforetak for inntektsåret](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2017-01-18-43.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-01-18-43) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-01-18-43.md) |
| [Vedtak om fastsettelse av renter for beskatning av kraftforetak for inntektsåret](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2018-01-09-17.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2018-01-09-17) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2018-01-09-17.md) |
| [Vedtak om fastsettelse av renter for beskatning av kraftforetak for inntektsåret](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2019-01-11-18.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-01-11-18) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-01-11-18.md) |
| [Vedtak om fastsettelse av renter for beskatning av kraftforetak for inntektsåret](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2020-01-23-72.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-01-23-72) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-01-23-72.md) |
| [Vedtak om fastsettelse av renter for beskatning av kraftforetak for inntektsåret](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-01-25-197.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-01-25-197) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-01-25-197.md) |
| [Vedtak om fastsettelse av renter for beskatning av kraftforetak for inntektsåret](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2022-01-19-82.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-01-19-82) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-01-19-82.md) |
| [Vedtak om fastsettelse av renter for beskatning av kraftforetak for inntektsåret](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2023-01-30-114.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-01-30-114) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-01-30-114.md) |
| [Vedtak om fastsettelse av renter for beskatning av kraftforetak for inntektsåret](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2024-01-30-145.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-01-30-145) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-01-30-145.md) |
| [Vedtak om fastsettelse av renter for beskatning av vannkraftverk for inntektsåre](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-01-24-67.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-01-24-67) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-01-24-67.md) |
| [Vedtak om fastsettelse av renter for skattlegging av havbruksvirksomhet for innt](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2024-02-09-229.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-02-09-229) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-02-09-229.md) |
| [Vedtak om opphevelse av rundskriv vedrørende unntak for beregning av forsinkelse](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2006-06-01-572.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2006-06-01-572) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2006-06-01-572.md) |
| [Vedtak om pris på kraft ved interne leveranser etter skatteloven § 18-3 andre le](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2012-01-16-54.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2012-01-16-54) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2012-01-16-54.md) |
| [Vedtak om pris på kraft ved interne leveranser etter skatteloven § 18-3 annet le](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2009-01-26-70.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2009-01-26-70) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2009-01-26-70.md) |
| [Vedtak om pris på kraft ved interne leveranser etter skatteloven § 18-3 annet le](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2010-01-29-80.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2010-01-29-80) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2010-01-29-80.md) |
| [Vedtak om pris på kraft ved interne leveranser etter skatteloven § 18-3 annet le](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2011-01-26-92.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2011-01-26-92) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2011-01-26-92.md) |
| [Vedtak om pris på kraft ved interne leveranser etter skatteloven § 18-3 annet le](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2013-01-28-115.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-01-28-115) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-01-28-115.md) |
| [Vedtak om pris på kraft ved interne leveranser etter skatteloven § 18-3 annet le](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2014-01-30-80.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2014-01-30-80) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2014-01-30-80.md) |
| [Vedtak om pris på kraft ved interne leveranser etter skatteloven § 18-3 annet le](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2015-01-22-53.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-01-22-53) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-01-22-53.md) |
| [Vedtak om pris på kraft ved interne leveranser etter skatteloven § 18-3 annet le](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2016-01-26-60.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2016-01-26-60) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2016-01-26-60.md) |
| [Vedtak om retningslinjer ved forvaltningen av kompensasjonsordningen](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2002-07-09-1116.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2002-07-09-1116) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2002-07-09-1116.md) |
