# Kultur- og likestillingsdepartementet

*89 forskrifter*

| Forskrift | Lovdata | Historikk |
|-----------|---------|-----------|
| [Endringer i 1) rettskrivningen og læreboknormalen for bokmål og 2) bruksområdet ](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1981-07-24-4940.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1981-07-24-4940) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1981-07-24-4940.md) |
| [Forskrift for strømstøtteordningen for frivillig sektor](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2022-07-01-1283.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-07-01-1283) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-07-01-1283.md) |
| [Forskrift for tilbakelån av arkivsaker fra arkivverket til avleverende institusj](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1980-05-19-3564.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1980-05-19-3564) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1980-05-19-3564.md) |
| [Forskrift for vigsel ved sjømannsprest utsendt av Den norske Sjømannsmisjon.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1956-09-14-3.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1956-09-14-3) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1956-09-14-3.md) |
| [Forskrift om Fond for lyd og bilde](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-12-19-2845.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-12-19-2845) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-12-19-2845.md) |
| [Forskrift om aspirantordning for kunstnere i etableringsfasen](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1998-10-01-1031.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1998-10-01-1031) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1998-10-01-1031.md) |
| [Forskrift om avleveringsplikt for allment tilgjengelege dokument](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2018-07-01-1139.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2018-07-01-1139) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2018-07-01-1139.md) |
| [Forskrift om beskyttelse av mindreårige mot skadelige bildeprogram](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2015-06-26-800.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-06-26-800) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-06-26-800.md) |
| [Forskrift om bibliotekstatistikk](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1987-01-05-2.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1987-01-05-2) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1987-01-05-2.md) |
| [Forskrift om dokumentasjon og arkiv (arkivforskrifta)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-12-17-2647.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-12-17-2647) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-12-17-2647.md) |
| [Forskrift om endring av rettskriving og læreboknormal](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1982-02-16-382.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1982-02-16-382) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1982-02-16-382.md) |
| [Forskrift om film og videogram.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1999-12-20-1515.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1999-12-20-1515) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1999-12-20-1515.md) |
| [Forskrift om fordeling av Norsk Tippings overskudd til idrettsformål](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2022-12-05-2122.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-12-05-2122) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-12-05-2122.md) |
| [Forskrift om fordeling av Norsk Tippings overskudd til kulturformål](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2026-04-17-615.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2026-04-17-615) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2026-04-17-615.md) |
| [Forskrift om fordeling av formue til frivillig virksomhet til fordel for barn og](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2023-10-27-1706.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-10-27-1706) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-10-27-1706.md) |
| [Forskrift om fortsatt bevilling til TONO og NCB til å drive virksomhet i Norge.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1971-06-25-3800.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1971-06-25-3800) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1971-06-25-3800.md) |
| [Forskrift om forvaltning av Fond for utøvende kunstnere og om fastsetting av avg](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2001-12-21-1559.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2001-12-21-1559) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2001-12-21-1559.md) |
| [Forskrift om grasrotandel](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2022-12-05-2124.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-12-05-2124) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-12-05-2124.md) |
| [Forskrift om helseføretak som statsorgan etter lov om målbruk i offentleg tenest](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2004-03-18-532.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2004-03-18-532) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2004-03-18-532.md) |
| [Forskrift om innovasjons- og utviklingstilskudd til nyhets- og aktualitetsmedier](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2018-06-26-1033.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2018-06-26-1033) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2018-06-26-1033.md) |
| [Forskrift om insentivordning for film- og serieproduksjoner](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2015-12-16-1684.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-12-16-1684) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-12-16-1684.md) |
| [Forskrift om insentivordning for ny dramatikk](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2024-11-25-2837.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-11-25-2837) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-11-25-2837.md) |
| [Forskrift om kompensasjon for portoutgifter i avisene.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2006-11-20-1267.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2006-11-20-1267) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2006-11-20-1267.md) |
| [Forskrift om kompensasjon for utgifter til renter til investeringer for istandse](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2014-09-01-1139.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2014-09-01-1139) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2014-09-01-1139.md) |
| [Forskrift om konsesjonsområder for lokalradio.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2000-10-10-1004.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2000-10-10-1004) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2000-10-10-1004.md) |
| [Forskrift om krigsgraver](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2015-04-13-370.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-04-13-370) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-04-13-370.md) |
| [Forskrift om kringkasting og audiovisuelle bestillingstjenester mv. (kringkastin](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1997-02-28-153.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1997-02-28-153) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1997-02-28-153.md) |
| [Forskrift om kva dokumentasjon som skal takast vare på for ettertida (bevaringsf](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-12-19-2729.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-12-19-2729) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-12-19-2729.md) |
| [Forskrift om kvalifikasjonskrav for ansatte i folkebibliotek](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2013-12-20-1656.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-12-20-1656) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-12-20-1656.md) |
| [Forskrift om medieregioner.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2005-07-01-754.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2005-07-01-754) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2005-07-01-754.md) |
| [Forskrift om merverdiavgiftskompensasjon for frivillige organisasjoner](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-12-18-2719.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-12-18-2719) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-12-18-2719.md) |
| [Forskrift om midlertidig kompensasjonsordning for arrangører i kultursektoren ve](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2020-04-03-677.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-04-03-677) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-04-03-677.md) |
| [Forskrift om midlertidig kompensasjonsordning for avlyste, stengte eller nedskal](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-05-26-1642.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-05-26-1642) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-05-26-1642.md) |
| [Forskrift om midlertidig kompensasjonsordning for avlyste, stengte eller nedskal](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-10-01-2923.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-10-01-2923) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-10-01-2923.md) |
| [Forskrift om midlertidig kompensasjonsordning for avlyste, stengte eller nedskal](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2022-03-08-345.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-03-08-345) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-03-08-345.md) |
| [Forskrift om midlertidig kompensasjonsordning for frivillighets- og idrettssekto](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2020-07-16-1581.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-07-16-1581) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-07-16-1581.md) |
| [Forskrift om midlertidig kompensasjonsordning for frivillighets- og idrettssekto](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2020-10-16-2084.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-10-16-2084) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-10-16-2084.md) |
| [Forskrift om midlertidig kompensasjonsordning for redaktørstyrte medier med fall](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2020-07-07-1521.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-07-07-1521) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-07-07-1521.md) |
| [Forskrift om midlertidig kompensasjonsordning i forbindelse med avlysning eller ](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2020-11-04-2245.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-11-04-2245) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-11-04-2245.md) |
| [Forskrift om midlertidig kompensasjonsordning i forbindelse med avlysning, steng](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2020-11-04-2250.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-11-04-2250) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-11-04-2250.md) |
| [Forskrift om midlertidig kompensasjonsordning i forbindelse med avlysning, steng](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2020-07-16-1568.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-07-16-1568) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-07-16-1568.md) |
| [Forskrift om midlertidig støtte til aktivitet for utøvende kunstnere rammet av o](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2020-07-01-1462.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-07-01-1462) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-07-01-1462.md) |
| [Forskrift om midlertidig tilskudd til kulturarrangementer fra juli 2021 som følg](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-05-14-1521.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-05-14-1521) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-05-14-1521.md) |
| [Forskrift om midlertidig tilskudd til kulturarrangementer første halvår 2021 som](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-01-28-273.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-01-28-273) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-01-28-273.md) |
| [Forskrift om midlertidig tilskudd til kulturarrangementer som følge av covid-19](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2020-10-19-2070.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-10-19-2070) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-10-19-2070.md) |
| [Forskrift om målbruk i offentleg teneste](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1980-12-05-4938.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1980-12-05-4938) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1980-12-05-4938.md) |
| [Forskrift om målform i eksamensoppgåver.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1987-07-07-4148.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1987-07-07-4148) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1987-07-07-4148.md) |
| [Forskrift om omsetning av bøker (bokforskriften)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2023-12-21-2268.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-12-21-2268) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-12-21-2268.md) |
| [Forskrift om organisasjon, oppgaver og saksbehandling for Diskrimineringsnemnda](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2017-12-20-2260.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-12-20-2260) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-12-20-2260.md) |
| [Forskrift om pengespill (pengespillforskriften)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2022-11-17-1978.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-11-17-1978) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-11-17-1978.md) |
| [Forskrift om produksjonstilskudd til nyhets- og aktualitetsmedier](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2022-12-08-2117.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-12-08-2117) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-12-08-2117.md) |
| [Forskrift om regionale kulturfond](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-06-10-985.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-06-10-985) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-06-10-985.md) |
| [Forskrift om representasjon av begge kjønn i statlige utvalg, styrer, råd, deleg](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1996-02-02-110.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1996-02-02-110) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1996-02-02-110.md) |
| [Forskrift om sikkerhetsbestemmelser til lov om organisert kampaktivitet som till](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2024-12-06-2944.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-12-06-2944) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-12-06-2944.md) |
| [Forskrift om språkvedtak i kommunar og fylkeskommunar (språkvedtaksforskrifta)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2019-12-20-2114.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-12-20-2114) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-12-20-2114.md) |
| [Forskrift om stadnamn](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2017-05-23-638.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-05-23-638) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-05-23-638.md) |
| [Forskrift om statens stipend og garantiinntekter for kunstnere](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1998-09-16-936.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1998-09-16-936) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1998-09-16-936.md) |
| [Forskrift om studieforbund godkjent av Kultur- og likestillingsdepartementet](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2020-12-08-2896.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-12-08-2896) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-12-08-2896.md) |
| [Forskrift om søknad, utbetaling og kontroll av tilskudd til manuskriptutvikling ](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2010-01-05-7.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2010-01-05-7) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2010-01-05-7.md) |
| [Forskrift om tilbakelevering av stjålne og ulovlig utførte kulturgjenstander](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2001-10-04-1179.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2001-10-04-1179) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2001-10-04-1179.md) |
| [Forskrift om tilskudd fra Norsk kulturfond](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2014-10-31-1387.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2014-10-31-1387) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2014-10-31-1387.md) |
| [Forskrift om tilskudd til arrangementer for idrett og fysisk aktivitet for perso](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2022-12-05-2602.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-12-05-2602) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-12-05-2602.md) |
| [Forskrift om tilskudd til audiovisuell produksjon](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2016-10-31-1264.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2016-10-31-1264) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2016-10-31-1264.md) |
| [Forskrift om tilskudd til filmformidling](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2016-10-12-1209.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2016-10-12-1209) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2016-10-12-1209.md) |
| [Forskrift om tilskudd til frivillige organisasjoner på familie- og likestillings](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2022-01-14-70.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-01-14-70) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-01-14-70.md) |
| [Forskrift om tilskudd til frivillige organisasjoner som arbeider med problematis](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2022-11-17-1980.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-11-17-1980) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-11-17-1980.md) |
| [Forskrift om tilskudd til frivilligsentraler](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2022-06-30-1272.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-06-30-1272) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-06-30-1272.md) |
| [Forskrift om tilskudd til funksjonshemmedes organisasjoner](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2023-01-01-122.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-01-01-122) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-01-01-122.md) |
| [Forskrift om tilskudd til informasjonsvirksomhet i politiske partier.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1999-02-08-199.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1999-02-08-199) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1999-02-08-199.md) |
| [Forskrift om tilskudd til lokale lyd- og bildemedier](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2016-02-19-166.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2016-02-19-166) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2016-02-19-166.md) |
| [Forskrift om tilskudd til minoritetsspråklige publikasjoner](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2003-10-22-1256.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2003-10-22-1256) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2003-10-22-1256.md) |
| [Forskrift om tilskudd til produksjon og formidling av audiovisuelle verk](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2016-10-07-1196.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2016-10-07-1196) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2016-10-07-1196.md) |
| [Forskrift om tilskudd til samfunnsnyttige og humanitære organisasjoner fra spill](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2022-12-05-2123.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-12-05-2123) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-12-05-2123.md) |
| [Forskrift om tilskudd til samiske nyhets- og aktualitetsmedier](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-12-10-2490.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-12-10-2490) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-12-10-2490.md) |
| [Forskrift om tilskudd til utvikling, lansering og formidling av dataspill](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-02-23-557.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-02-23-557) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-02-23-557.md) |
| [Forskrift om tilskudd til å styrke kjønns- og seksualitetsmangfold](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-10-13-3048.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-10-13-3048) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-10-13-3048.md) |
| [Forskrift om unntak fra adgangen til å klage over vedtak i Norsk kulturråd, Nors](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1987-11-20-924.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1987-11-20-924) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1987-11-20-924.md) |
| [Forskrift om utførsel og innførsel av kulturgjenstander](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2007-01-01-1.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2007-01-01-1) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2007-01-01-1.md) |
| [Forskrift om virksomheten i Norsk rikskringkasting under beredskap og i krig.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1989-10-06-4154.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1989-10-06-4154) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1989-10-06-4154.md) |
| [Forskrift til lov om avgift på omsetning av billedkunst](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1990-09-28-778.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1990-09-28-778) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1990-09-28-778.md) |
| [Forskrift til lov om kollektiv forvaltning av opphavsrett mv.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-08-09-2484.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-08-09-2484) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-08-09-2484.md) |
| [Forskrift til lov om register for frivillig virksomhet](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2008-10-15-1214.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2008-10-15-1214) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2008-10-15-1214.md) |
| [Forskrift til stiftelsesloven mv.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2004-12-21-1793.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2004-12-21-1793) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2004-12-21-1793.md) |
| [Forskrift til åndsverkloven](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-08-26-2608.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-08-26-2608) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-08-26-2608.md) |
| [Forskrifter for Statens barne- og ungdomsråd.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1985-01-25-3553.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1985-01-25-3553) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1985-01-25-3553.md) |
| [Forskrifter om fjernsynsmottakere](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1980-10-23-8798.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1980-10-23-8798) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1980-10-23-8798.md) |
| [Forskrifter om opplysningsplikt og om betaling av avgifter til Det norske kompon](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1966-10-18-9040.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1966-10-18-9040) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1966-10-18-9040.md) |
| [Kampaktivitetslisten](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2016-12-22-1924.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2016-12-22-1924) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2016-12-22-1924.md) |
| [Vedtak om utvidelse av det geografiske virkeområdet for lov om arkiv til også å ](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2001-03-09-192.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2001-03-09-192) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2001-03-09-192.md) |
