# Justis- og beredskapsdepartementet

*325 forskrifter*

| Forskrift | Lovdata | Historikk |
|-----------|---------|-----------|
| [Anerkjennelse av visse typer legitimasjonsdokumenter ved reise til Svalbard, jf.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-01-07-8.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-01-07-8) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-01-07-8.md) |
| [Bestemmelser for gjennomføring av nye tjenestetidsbestemmelser for mannskap som ](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2006-06-19-648.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2006-06-19-648) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2006-06-19-648.md) |
| [Byggeforskrift for Longyearbyen](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2016-11-15-1329.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2016-11-15-1329) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2016-11-15-1329.md) |
| [Delegering av myndighet til Direktoratet for brann- og eksplosjonsvern etter lov](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1996-08-20-811.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1996-08-20-811) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1996-08-20-811.md) |
| [Delegering av myndighet til Direktoratet for brann- og eksplosjonsvern til å fas](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2001-05-08-471.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2001-05-08-471) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2001-05-08-471.md) |
| [Delegering av myndighet til Direktoratet for brann- og elsikkerhet etter lov om ](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2003-06-26-868.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2003-06-26-868) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2003-06-26-868.md) |
| [Delegering av myndighet til å gi tillatelse til midlertidig oppbevaring av brann](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1998-01-19-38.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1998-01-19-38) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1998-01-19-38.md) |
| [Delegering av myndighet til å gi tillatelse til midlertidig oppbevaring av brann](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1998-05-29-564.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1998-05-29-564) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1998-05-29-564.md) |
| [Forskrift (disiplinærregler) for tjenestepliktige etter lov om fritaking for mil](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1968-02-01-3641.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1968-02-01-3641) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1968-02-01-3641.md) |
| [Forskrift etter rettsgebyrloven m.m. (rettsgebyrforskriften)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1983-02-15-86.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1983-02-15-86) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1983-02-15-86.md) |
| [Forskrift for bruk av skytevåpen i Longyearbyen og omegn, Pyramiden, Barentsburg](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1966-02-11-3449.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1966-02-11-3449) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1966-02-11-3449.md) |
| [Forskrift for oppnevnelse av stedfortredere for en del embets- og tjenestemenn v](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1954-07-08-3.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1954-07-08-3) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1954-07-08-3.md) |
| [Forskrift i medhold av oreigningslovens § 29](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1960-06-02-4.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1960-06-02-4) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1960-06-02-4.md) |
| [Forskrift i medhold av oreigningslovens § 3 om rett til å foreta eiendomsinngrep](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1960-06-02-2.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1960-06-02-2) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1960-06-02-2.md) |
| [Forskrift i medhold av oreigningslovens § 5 om rett til å gjøre vedtak om eller ](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1960-06-02-1.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1960-06-02-1) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1960-06-02-1.md) |
| [Forskrift om Bouvet-øya.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1930-09-19-3663.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1930-09-19-3663) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1930-09-19-3663.md) |
| [Forskrift om Den rettsmedisinske kommisjon](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2018-02-13-240.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2018-02-13-240) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2018-02-13-240.md) |
| [Forskrift om Finnmarkskommisjonen og Utmarksdomstolen for Finnmark](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2007-03-16-277.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2007-03-16-277) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2007-03-16-277.md) |
| [Forskrift om Lovdatas lov- og forskriftsdatabaser.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1994-06-21-644.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1994-06-21-644) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1994-06-21-644.md) |
| [Forskrift om Politiets utlendingsinternat (Utlendingsinternatforskriften)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2009-12-23-1890.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2009-12-23-1890) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2009-12-23-1890.md) |
| [Forskrift om Politihøgskolens styre, oppgaver og virksomhet.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2005-11-25-1330.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2005-11-25-1330) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2005-11-25-1330.md) |
| [Forskrift om Schengen informasjonssystem (SIS-forskriften)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2022-06-26-1194.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-06-26-1194) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-06-26-1194.md) |
| [Forskrift om York–Antwerpen-reglene 2016 som fravikelige regler for felleshavari](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2018-06-01-785.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2018-06-01-785) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2018-06-01-785.md) |
| [Forskrift om administrasjon av Jan Mayen](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1980-11-21-12.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1980-11-21-12) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1980-11-21-12.md) |
| [Forskrift om administrativ tilhørighet for sysselmannen på Svalbard.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1953-03-20-3454.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1953-03-20-3454) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1953-03-20-3454.md) |
| [Forskrift om advokater og andre som yter rettslig bistand (advokatforskriften)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2024-10-22-2546.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-10-22-2546) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-10-22-2546.md) |
| [Forskrift om advokatlovens anvendelse for Svalbard](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2024-10-11-2451.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-10-11-2451) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-10-11-2451.md) |
| [Forskrift om aerosolbeholdere](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1996-03-01-229.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1996-03-01-229) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1996-03-01-229.md) |
| [Forskrift om antennelighet av madrasser og stoppede møbler.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1999-04-16-525.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1999-04-16-525) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1999-04-16-525.md) |
| [Forskrift om anvendelse av lov 15. desember 1950 nr. 7 om særlige rådgjerder und](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2023-12-01-1943.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-12-01-1943) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-12-01-1943.md) |
| [Forskrift om anvendelse av straffeloven § 155 på lovbrudd mot annet lands offent](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1997-10-03-1077.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1997-10-03-1077) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1997-10-03-1077.md) |
| [Forskrift om aspiranter i kriminalomsorgen](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-04-05-619.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-04-05-619) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-04-05-619.md) |
| [Forskrift om at passlovens § 6 annet ledd og § 6a også skal omfatte diplomatpass](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2005-09-30-1113.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2005-09-30-1113) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2005-09-30-1113.md) |
| [Forskrift om autorisasjon av verksteder for reparasjon/ombygging m.v. av eksplos](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1987-11-20-1080.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1987-11-20-1080) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1987-11-20-1080.md) |
| [Forskrift om avgift på enkelte farlige stoffer, anlegg og innretninger som omfat](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1995-07-10-684.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1995-07-10-684) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1995-07-10-684.md) |
| [Forskrift om avhør av barn og andre særlig sårbare fornærmede og vitner (tilrett](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2015-09-24-1098.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-09-24-1098) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-09-24-1098.md) |
| [Forskrift om barnesikring av lightere og om forbud mot lightere med forvekslings](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2007-06-21-687.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2007-06-21-687) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2007-06-21-687.md) |
| [Forskrift om behandling av opplysninger i politiet og påtalemyndigheten (politir](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2013-09-20-1097.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-09-20-1097) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-09-20-1097.md) |
| [Forskrift om behandling av opplysninger om natur- og vannskader i Kunnskapsbanke](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2022-06-01-954.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-06-01-954) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-06-01-954.md) |
| [Forskrift om behandling av personopplysninger](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2018-06-15-876.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2018-06-15-876) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2018-06-15-876.md) |
| [Forskrift om behandling av personopplysninger i kriminalomsorgen](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2013-09-20-1099.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-09-20-1099) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-09-20-1099.md) |
| [Forskrift om behandling av saker om straff for personer mistenkt for piratvirkso](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2013-06-14-622.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-06-14-622) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-06-14-622.md) |
| [Forskrift om behandling av straffesaker når norske skip deltar i en Frontex-oper](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2015-06-05-582.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-06-05-582) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-06-05-582.md) |
| [Forskrift om bekreftelse av underskrift på eksigible gjeldsbrev.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1973-10-26-4.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1973-10-26-4) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1973-10-26-4.md) |
| [Forskrift om bekreftelse av underskrift på eksigible gjeldsbrev.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1992-12-04-896.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1992-12-04-896) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1992-12-04-896.md) |
| [Forskrift om bemyndigelse av funksjonærer etter tvangsfullbyrdelsesloven.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1992-12-04-893.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1992-12-04-893) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1992-12-04-893.md) |
| [Forskrift om bevisopptak i sivile saker i utlandet](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1950-04-28-3419.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1950-04-28-3419) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1950-04-28-3419.md) |
| [Forskrift om bortvisning og utvisning av personer fra Svalbard](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1995-02-03-96.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1995-02-03-96) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1995-02-03-96.md) |
| [Forskrift om bostyrerens sikkerhetsstillelse.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1985-09-20-1871.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1985-09-20-1871) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1985-09-20-1871.md) |
| [Forskrift om brannforebygging](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2015-12-17-1710.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-12-17-1710) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-12-17-1710.md) |
| [Forskrift om brannvern på Svalbard.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1993-08-20-815.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1993-08-20-815) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1993-08-20-815.md) |
| [Forskrift om bruk av politiarrest](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2006-06-30-749.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2006-06-30-749) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2006-06-30-749.md) |
| [Forskrift om bruk av sikringsmidler](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1961-12-01-2.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1961-12-01-2) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1961-12-01-2.md) |
| [Forskrift om deklarering av kjemikalier til produktregisteret (deklareringsforsk](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2015-05-19-541.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-05-19-541) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-05-19-541.md) |
| [Forskrift om deling av taushetsbelagte opplysninger og behandling av personopply](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2022-06-17-1045.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-06-17-1045) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-06-17-1045.md) |
| [Forskrift om den sentrale administrasjonsordning for Svalbard-saker og om oppret](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1965-01-06-3451.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1965-01-06-3451) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1965-01-06-3451.md) |
| [Forskrift om det lokale elektrisitetstilsyn og sakkyndige som utfører oppgaver f](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2007-06-29-830.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2007-06-29-830) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2007-06-29-830.md) |
| [Forskrift om digital sikkerhet (digitalsikkerhetsforskriften)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-06-20-1131.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-06-20-1131) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-06-20-1131.md) |
| [Forskrift om dispasjører](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2024-02-03-172.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-02-03-172) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-02-03-172.md) |
| [Forskrift om dommeres sidegjøremål.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2002-10-18-1133.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2002-10-18-1133) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2002-10-18-1133.md) |
| [Forskrift om domsmyndighet på Svalbard](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1985-03-08-532.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1985-03-08-532) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1985-03-08-532.md) |
| [Forskrift om driftsstøttetjenester til Nødnettutstyret ved brannvesenets nødalar](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2012-06-14-530.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2012-06-14-530) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2012-06-14-530.md) |
| [Forskrift om eksamen ved fengselsbetjentutdanningen](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2011-06-23-854.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2011-06-23-854) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2011-06-23-854.md) |
| [Forskrift om elektrisk utstyr](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2017-10-10-1598.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-10-10-1598) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-10-10-1598.md) |
| [Forskrift om elektriske forsyningsanlegg.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2005-12-20-1626.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2005-12-20-1626) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2005-12-20-1626.md) |
| [Forskrift om elektriske lavspenningsanlegg](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1998-11-06-1060.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1998-11-06-1060) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1998-11-06-1060.md) |
| [Forskrift om elektroforetak og kvalifikasjonskrav for arbeid knyttet til elektri](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2013-06-19-739.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-06-19-739) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-06-19-739.md) |
| [Forskrift om elektromagnetisk kompatibilitet](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2017-10-10-1597.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-10-10-1597) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-10-10-1597.md) |
| [Forskrift om elektronisk kommunikasjon med alminnelig namsmann og Innkrevingsmyn](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-07-09-1509.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-07-09-1509) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-07-09-1509.md) |
| [Forskrift om elektronisk kommunikasjon med domstolene](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2016-10-28-1258.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2016-10-28-1258) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2016-10-28-1258.md) |
| [Forskrift om en særskilt klagenemnd for behandling av klager over vedtak om erkj](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1999-08-06-885.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1999-08-06-885) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1999-08-06-885.md) |
| [Forskrift om endring i forskrift om fastsetting av inndeling i lensmanns- og pol](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2020-06-04-1135.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-06-04-1135) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-06-04-1135.md) |
| [Forskrift om endring i forskrift om fastsetting av inndeling i lensmanns- og pol](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-06-02-1774.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-06-02-1774) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-06-02-1774.md) |
| [Forskrift om endring i forskrift om fastsetting av inndeling i lensmanns- og pol](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-06-02-1789.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-06-02-1789) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-06-02-1789.md) |
| [Forskrift om endring i forskrift om håndtering av brannfarlig, reaksjonsfarlig o](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2026-02-04-140.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2026-02-04-140) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2026-02-04-140.md) |
| [Forskrift om endring i forskrift om sivil håndtering av eksplosjonsfarlige stoff](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2026-02-17-227.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2026-02-17-227) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2026-02-17-227.md) |
| [Forskrift om endring i rettsgebyrforskriften](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-12-17-2649.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-12-17-2649) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-12-17-2649.md) |
| [Forskrift om endringer i utlendingsforskriften (avvikling av au pair-ordningen)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2024-02-14-257.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-02-14-257) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-02-14-257.md) |
| [Forskrift om enkelte spørsmål knyttet til saksbehandlingen hos namsmannen](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-07-09-1510.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-07-09-1510) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-07-09-1510.md) |
| [Forskrift om enkle trykkbeholdere](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2017-02-10-171.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-02-10-171) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-02-10-171.md) |
| [Forskrift om erstatning etter politiloven § 23a](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2022-06-30-1279.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-06-30-1279) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-06-30-1279.md) |
| [Forskrift om erstatning ved atomulykker.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2001-12-14-1498.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2001-12-14-1498) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2001-12-14-1498.md) |
| [Forskrift om etablering av Direktoratet for brann og eksplosjonsvern og Statens ](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1984-12-14-2044.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1984-12-14-2044) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1984-12-14-2044.md) |
| [Forskrift om farlige næringsmiddelimitasjoner.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1992-05-26-420.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1992-05-26-420) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1992-05-26-420.md) |
| [Forskrift om faste forsvarere og bistandsadvokater](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2011-03-04-251.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2011-03-04-251) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2011-03-04-251.md) |
| [Forskrift om fastsettelse av utleggstrekk og fordeling av trekkbeløp](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-07-09-1507.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-07-09-1507) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-07-09-1507.md) |
| [Forskrift om fastsetting av inndeling i politistasjonsdistrikter og tjenestested](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2017-05-24-2480.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-05-24-2480) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-05-24-2480.md) |
| [Forskrift om felles faste dommerstillinger](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2015-09-28-1202.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-09-28-1202) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-09-28-1202.md) |
| [Forskrift om finansavtaler (finansavtaleforskriften)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2022-09-19-1612.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-09-19-1612) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-09-19-1612.md) |
| [Forskrift om fiske etter røye på Svalbard i 2026](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2026-01-07-12.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2026-01-07-12) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2026-01-07-12.md) |
| [Forskrift om fjernmøter og fjernavhør i straffesaker](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2011-08-12-835.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2011-08-12-835) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2011-08-12-835.md) |
| [Forskrift om flytting av det sentrale ektepaktregister fra Oslo byskriverembete,](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1980-06-27-7.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1980-06-27-7) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1980-06-27-7.md) |
| [Forskrift om forbud mot fallskjermhopping m.v. i Trolltindene.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1987-06-12-495.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1987-06-12-495) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1987-06-12-495.md) |
| [Forskrift om forbud mot svært brennbare tekstiler](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1984-02-13-427.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1984-02-13-427) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1984-02-13-427.md) |
| [Forskrift om fordelingen av sakene i domstolene](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-03-19-762.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-03-19-762) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-03-19-762.md) |
| [Forskrift om forenklet forelegg i fritids- og småbåtsaker](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2001-06-15-634.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2001-06-15-634) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2001-06-15-634.md) |
| [Forskrift om forsikringsavtaler (forsikringsavtaleforskriften)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2022-03-04-323.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-03-04-323) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-03-04-323.md) |
| [Forskrift om forsøksprosjekt om kartlegging av domfeltes behov for tiltak med si](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2011-09-30-978.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2011-09-30-978) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2011-09-30-978.md) |
| [Forskrift om fortegnelser over meddommere](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2018-09-25-1474.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2018-09-25-1474) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2018-09-25-1474.md) |
| [Forskrift om fortsatt anvendelse av Luganokonvensjonen 1988](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2009-10-16-1280.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2009-10-16-1280) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2009-10-16-1280.md) |
| [Forskrift om fotografering, filmopptak og opptak for radio eller fjernsyn under ](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1985-11-15-1910.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1985-11-15-1910) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1985-11-15-1910.md) |
| [Forskrift om fraktførerens ansvar for skade ved lufttransport av passasjerer, re](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2011-01-06-9.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2011-01-06-9) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2011-01-06-9.md) |
| [Forskrift om framgangsmåten ved tinglysing av melding om konkursåpning på grunnl](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1985-09-20-1872.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1985-09-20-1872) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1985-09-20-1872.md) |
| [Forskrift om fri rettshjelp (rettshjelpsforskriften)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-09-26-1961.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-09-26-1961) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-09-26-1961.md) |
| [Forskrift om fritak fra plikten til å sende inn regnskaper til Fylkesmannen for ](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1998-05-07-468.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1998-05-07-468) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1998-05-07-468.md) |
| [Forskrift om fullbyrding av nordiske dommer på straff m.v.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1963-12-12-1.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1963-12-12-1) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1963-12-12-1.md) |
| [Forskrift om føring av Løsøreregisteret og Regnskapsregisteret](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1987-12-18-985.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1987-12-18-985) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1987-12-18-985.md) |
| [Forskrift om gassapparater](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2018-06-26-1025.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2018-06-26-1025) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2018-06-26-1025.md) |
| [Forskrift om gjennomføring av særreaksjonen forvaring.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2004-03-05-481.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2004-03-05-481) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2004-03-05-481.md) |
| [Forskrift om gjennomføring av særreaksjonen tvungen omsorg](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2001-12-21-1523.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2001-12-21-1523) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2001-12-21-1523.md) |
| [Forskrift om gjennomføring i norsk rett av nordisk konvensjon 6. februar 1931 nr](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2008-05-26-507.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2008-05-26-507) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2008-05-26-507.md) |
| [Forskrift om grensetilsyn og grensekontroll av personer (grenseforskriften)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2022-04-29-665.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-04-29-665) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-04-29-665.md) |
| [Forskrift om gruppesøksmål](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2007-11-26-1325.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2007-11-26-1325) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2007-11-26-1325.md) |
| [Forskrift om hvilke domstoler forskrift om opptak i retten § 6 gjelder for](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2018-10-17-1577.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2018-10-17-1577) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2018-10-17-1577.md) |
| [Forskrift om håndtering av brannfarlig, reaksjonsfarlig og trykksatt stoff samt ](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2009-06-08-602.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2009-06-08-602) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2009-06-08-602.md) |
| [Forskrift om håndtering av eksplosjonsfarlig stoff](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2002-06-26-922.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2002-06-26-922) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2002-06-26-922.md) |
| [Forskrift om håndtering av medisinsk utstyr](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2013-11-29-1373.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-11-29-1373) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-11-29-1373.md) |
| [Forskrift om industrielt rettsvern på Svalbard og Jan Mayen](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2019-06-21-801.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-06-21-801) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-06-21-801.md) |
| [Forskrift om industrivern](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2011-12-20-1434.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2011-12-20-1434) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2011-12-20-1434.md) |
| [Forskrift om inndelingen av rettskretser og lagdømmer](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-01-22-163.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-01-22-163) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-01-22-163.md) |
| [Forskrift om innkalling og utsettelse ved fullbyrding av straff](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2010-03-19-408.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2010-03-19-408) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2010-03-19-408.md) |
| [Forskrift om internasjonalt samarbeid i straffesaker](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2012-12-14-1227.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2012-12-14-1227) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2012-12-14-1227.md) |
| [Forskrift om jordskiftedommerfullmektigers myndighet](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2015-12-07-1431.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-12-07-1431) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-12-07-1431.md) |
| [Forskrift om justering av årlige erstatninger fastsatt i medhold av oreigningslo](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1984-12-07-1957.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1984-12-07-1957) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1984-12-07-1957.md) |
| [Forskrift om justering av årlige vederlag fastsatt i medhold av lov om rettshøve](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1984-12-07-1958.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1984-12-07-1958) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1984-12-07-1958.md) |
| [Forskrift om kapitaliseringsrente etter skadeserstatningsloven](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2022-08-26-1482.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-08-26-1482) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-08-26-1482.md) |
| [Forskrift om kirkegårder i Longyearbyen og askespredning på Svalbard](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2008-02-15-153.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2008-02-15-153) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2008-02-15-153.md) |
| [Forskrift om kjøpers renteplikt ved betaling etter oppgjørsdagen, jf. tvangsfull](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2000-04-28-368.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2000-04-28-368) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2000-04-28-368.md) |
| [Forskrift om klageordning for kommuner som berøres av ny tjenestestedsstruktur i](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2016-06-22-815.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2016-06-22-815) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2016-06-22-815.md) |
| [Forskrift om klassifisering, merking og emballering av stoffer og stoffblandinge](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2012-06-16-622.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2012-06-16-622) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2012-06-16-622.md) |
| [Forskrift om kommunal beredskapsplikt](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2011-08-22-894.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2011-08-22-894) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2011-08-22-894.md) |
| [Forskrift om kommunal håndheving av politivedtekter](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2012-06-19-600.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2012-06-19-600) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2012-06-19-600.md) |
| [Forskrift om kommunikasjonskontroll, romavlytting og dataavlesing (kommunikasjon](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2016-09-09-1047.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2016-09-09-1047) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2016-09-09-1047.md) |
| [Forskrift om konfliktrådsbehandling](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2014-06-30-923.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2014-06-30-923) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2014-06-30-923.md) |
| [Forskrift om konkursregisteret og om kunngjøringer etter konkursloven](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1993-08-23-824.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1993-08-23-824) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1993-08-23-824.md) |
| [Forskrift om konstruksjon, utforming og produksjon av personlig verneutstyr (PVU](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2018-06-22-1019.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2018-06-22-1019) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2018-06-22-1019.md) |
| [Forskrift om kontroll av reisende til og fra Svalbard](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2022-04-29-643.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-04-29-643) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-04-29-643.md) |
| [Forskrift om kontroll med post- og telegramforsendelser.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1960-08-19-2.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1960-08-19-2) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1960-08-19-2.md) |
| [Forskrift om landtransport av farlig gods](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2009-04-01-384.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2009-04-01-384) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2009-04-01-384.md) |
| [Forskrift om lokal regulering av jakt på svalbardrype og svalbardrein på Svalbar](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2003-08-04-1005.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2003-08-04-1005) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2003-08-04-1005.md) |
| [Forskrift om lokalstyrevalg i Longyearbyen](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2007-05-14-506.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2007-05-14-506) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2007-05-14-506.md) |
| [Forskrift om maritime elektriske anlegg](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2001-12-04-1450.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2001-12-04-1450) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2001-12-04-1450.md) |
| [Forskrift om maskiner](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2009-05-20-544.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2009-05-20-544) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2009-05-20-544.md) |
| [Forskrift om mortifikasjon av skuldbrev](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2008-06-20-620.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2008-06-20-620) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2008-06-20-620.md) |
| [Forskrift om målingsmåten i lov om rettshøve mellom grannar 16. juni 1961 nr. 15](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1961-12-22-4.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1961-12-22-4) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1961-12-22-4.md) |
| [Forskrift om narkotikaprogram med domstolskontroll](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2017-10-20-1650.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-10-20-1650) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-10-20-1650.md) |
| [Forskrift om nasjonalt register for vaktvirksomhet](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2022-01-25-120.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-01-25-120) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-01-25-120.md) |
| [Forskrift om naturskadeforsikring (naturskadeforsikringsforskriften)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2024-01-26-111.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-01-26-111) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-01-26-111.md) |
| [Forskrift om notarius publicus](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2002-05-03-418.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2002-05-03-418) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2002-05-03-418.md) |
| [Forskrift om offentlighet i rettspleien.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2001-07-06-757.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2001-07-06-757) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2001-07-06-757.md) |
| [Forskrift om omsorgen for enslige mindreårige som bor i asylmottak](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-05-12-1520.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-05-12-1520) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-05-12-1520.md) |
| [Forskrift om oppbevaring ved domstolene av dokumenter i saker med anonym vitnefø](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2001-07-06-759.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2001-07-06-759) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2001-07-06-759.md) |
| [Forskrift om opphevelse av importøransvaret etter produktansvarsloven for import](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1993-11-12-1028.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1993-11-12-1028) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1993-11-12-1028.md) |
| [Forskrift om opptak i retten](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2018-09-28-1471.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2018-09-28-1471) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2018-09-28-1471.md) |
| [Forskrift om opptak til bachelorutdanningen ved Politihøgskolen](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2017-08-29-1592.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-08-29-1592) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-08-29-1592.md) |
| [Forskrift om opptak til masterstudier ved Politihøgskolen](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2017-04-19-674.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-04-19-674) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-04-19-674.md) |
| [Forskrift om opptak, studier og eksamen ved fagskolestudiet Brann, redning og sa](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2023-01-30-111.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-01-30-111) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-01-30-111.md) |
| [Forskrift om ordningen av påtalemyndigheten (Påtaleinstruksen)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1985-06-28-1679.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1985-06-28-1679) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1985-06-28-1679.md) |
| [Forskrift om organisering, bemanning og utrustning av brann- og redningsvesen og](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-09-15-2755.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-09-15-2755) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-09-15-2755.md) |
| [Forskrift om overgangsbestemmelser for gjennomføring av lov av 18. februar 1999 ](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1999-09-07-1048.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1999-09-07-1048) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1999-09-07-1048.md) |
| [Forskrift om overgangsbestemmelser til lov 15. desember 2006 nr. 88 om endringer](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2006-12-15-1433.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2006-12-15-1433) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2006-12-15-1433.md) |
| [Forskrift om overgangsbestemmelser til lov om endringer i forbrukerkjøpsloven (l](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2006-06-30-874.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2006-06-30-874) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2006-06-30-874.md) |
| [Forskrift om overgangsreglar ved ikraftsetjing av lov 2. juli 2004 nr. 63 om end](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2004-10-15-1338.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2004-10-15-1338) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2004-10-15-1338.md) |
| [Forskrift om overgangsreglar ved ikraftsetjing av lov 30. juni 2006 nr. 52 om en](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2006-06-30-729.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2006-06-30-729) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2006-06-30-729.md) |
| [Forskrift om overgangsreglar ved iverksetjing av lov 19. juni 2009 nr. 76 om end](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2009-09-04-1153.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2009-09-04-1153) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2009-09-04-1153.md) |
| [Forskrift om overgangsregler for behandling av arrestordre og anmodninger om gje](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2020-12-18-2868.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-12-18-2868) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-12-18-2868.md) |
| [Forskrift om overgangsregler om betaling av egenandeler i saker om fri rettshjel](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2003-08-01-988.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2003-08-01-988) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2003-08-01-988.md) |
| [Forskrift om overgangsregler til lov av 16. mars 2001 nr. 8 om endringer i inkas](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2001-12-21-1508.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2001-12-21-1508) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2001-12-21-1508.md) |
| [Forskrift om overgangsregler til tvangsfullbyrdelsesloven.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1992-12-04-891.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1992-12-04-891) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1992-12-04-891.md) |
| [Forskrift om pass og nasjonalt ID-kort (pass- og ID-kortforskriften)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2020-10-09-2012.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-10-09-2012) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-10-09-2012.md) |
| [Forskrift om plikt til å gi opplysninger til forvaltning og statistikk på Svalba](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2006-06-09-602.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2006-06-09-602) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2006-06-09-602.md) |
| [Forskrift om politidistrikt, namsmannsdistrikt, lagdømme og domssogn for utøvels](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1999-12-17-1391.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1999-12-17-1391) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1999-12-17-1391.md) |
| [Forskrift om postforkynning](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1985-10-11-1810.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1985-10-11-1810) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1985-10-11-1810.md) |
| [Forskrift om program mot ruspåvirket kjøring](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2008-10-10-1100.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2008-10-10-1100) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2008-10-10-1100.md) |
| [Forskrift om pyrotekniske artikler](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2013-10-03-1199.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-10-03-1199) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-10-03-1199.md) |
| [Forskrift om reduksjon av utslipp av bensindamp](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1999-02-10-206.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1999-02-10-206) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1999-02-10-206.md) |
| [Forskrift om register over befolkningen på Svalbard](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1994-02-04-111.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1994-02-04-111) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1994-02-04-111.md) |
| [Forskrift om registrering og merking av fartøyer i vassdrag som danner riksgrens](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2022-04-29-667.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-04-29-667) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-04-29-667.md) |
| [Forskrift om registrering, vurdering, godkjenning og begrensning av kjemikalier ](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2008-05-30-516.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2008-05-30-516) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2008-05-30-516.md) |
| [Forskrift om registreringssted for innføring i skipsregisteret av faste innretni](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1985-06-07-1016.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1985-06-07-1016) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1985-06-07-1016.md) |
| [Forskrift om regulativ for erleggelse av avgift for godkjennelse av og tilsyn me](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1987-12-18-991.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1987-12-18-991) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1987-12-18-991.md) |
| [Forskrift om rekvirentens ansvar for kostnadene ved konkursbehandling.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2005-01-27-70.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2005-01-27-70) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2005-01-27-70.md) |
| [Forskrift om rentesats etter ekteskapsloven](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2007-02-13-164.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2007-02-13-164) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2007-02-13-164.md) |
| [Forskrift om rentesatser etter dekningsloven § 6-2 og § 9-7.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2003-02-14-145.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2003-02-14-145) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2003-02-14-145.md) |
| [Forskrift om rettspsykiatriske undersøkelser og sakkyndige](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2020-09-30-1921.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-09-30-1921) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-09-30-1921.md) |
| [Forskrift om revisjon m.m. for Longyearbyen lokalstyre.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2001-12-14-1391.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2001-12-14-1391) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2001-12-14-1391.md) |
| [Forskrift om saksøktes ansvar for sakskostnader ved tvangsfullbyrdelse](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2020-10-23-2120.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-10-23-2120) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-10-23-2120.md) |
| [Forskrift om salær fra det offentlige til advokater m.fl. etter faste satser (st](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2005-12-12-1442.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2005-12-12-1442) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2005-12-12-1442.md) |
| [Forskrift om salær fra det offentlige til advokater m.v.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1997-12-03-1441.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1997-12-03-1441) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1997-12-03-1441.md) |
| [Forskrift om samarbeid med Danmark, Finland, Island og Sverige om fullbyrding av](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1963-12-03-1.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1963-12-03-1) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1963-12-03-1.md) |
| [Forskrift om satser for frikjøp av tilfluktsromplasser.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1995-03-14-251.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1995-03-14-251) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1995-03-14-251.md) |
| [Forskrift om selskapets opplysningsplikt før og etter generalforsamlingen i viss](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2009-07-06-983.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2009-07-06-983) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2009-07-06-983.md) |
| [Forskrift om sertifikater for forsikring og annen sikkerhet etter sjøloven mv.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2019-11-11-1492.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-11-11-1492) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-11-11-1492.md) |
| [Forskrift om signatur i domstolene mv.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-12-01-3314.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-12-01-3314) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-12-01-3314.md) |
| [Forskrift om sikkerhet i felt mv. på Svalbard (feltsikkerhetsforskriften)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-06-06-940.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-06-06-940) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-06-06-940.md) |
| [Forskrift om sikkerhet ved arbeid i og drift av elektriske anlegg.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2006-04-28-458.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2006-04-28-458) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2006-04-28-458.md) |
| [Forskrift om sikkerhet ved lekeplassutstyr](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1996-07-19-703.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1996-07-19-703) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1996-07-19-703.md) |
| [Forskrift om sikkerhet ved leketøy (leketøyforskriften)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2013-11-18-1403.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-11-18-1403) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-11-18-1403.md) |
| [Forskrift om sikkerheten ved rafting.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1994-09-19-994.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1994-09-19-994) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1994-09-19-994.md) |
| [Forskrift om sikkerhetsklarering og annen klarering (klareringsforskriften)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2018-12-20-2054.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2018-12-20-2054) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2018-12-20-2054.md) |
| [Forskrift om sikkerhetslovens anvendelse for Svalbard og Jan Mayen](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2018-12-20-2059.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2018-12-20-2059) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2018-12-20-2059.md) |
| [Forskrift om sikkerhetslovens anvendelse for virksomheter i Dronning Maud Land](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2019-12-06-1645.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-12-06-1645) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-12-06-1645.md) |
| [Forskrift om sinnsyke sikrings- eller forvaringsdømte](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1955-06-23-2.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1955-06-23-2) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1955-06-23-2.md) |
| [Forskrift om sivil håndtering av eksplosjonsfarlige stoffer (eksplosivforskrifte](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2017-06-15-844.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-06-15-844) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-06-15-844.md) |
| [Forskrift om sivilbeskyttelseslovens anvendelse på Svalbard og om beredskapsplik](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2012-12-18-1293.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2012-12-18-1293) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2012-12-18-1293.md) |
| [Forskrift om sivilforsvar (sivilforsvarsforskriften)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2022-02-14-253.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-02-14-253) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-02-14-253.md) |
| [Forskrift om skikkethetsvurdering, utvisning, bortvisning og utestenging av stud](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2024-09-27-2338.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-09-27-2338) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-09-27-2338.md) |
| [Forskrift om standardisert erstatning etter lov om yrkesskadeforsikring](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1990-12-21-1027.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1990-12-21-1027) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1990-12-21-1027.md) |
| [Forskrift om standardisert inntektstaperstatning til barn](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2018-02-16-236.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2018-02-16-236) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2018-02-16-236.md) |
| [Forskrift om standardsatser for oppreisning etter uberettiget strafforfølgning.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2003-12-12-1472.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2003-12-12-1472) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2003-12-12-1472.md) |
| [Forskrift om statens tilskudd m.v. ved bygging av offentlige tilfluktsrom.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1984-09-21-1674.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1984-09-21-1674) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1984-09-21-1674.md) |
| [Forskrift om stengning av et område i Kongsfjorden på Svalbard for fiskeaktivite](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2007-02-02-136.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2007-02-02-136) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2007-02-02-136.md) |
| [Forskrift om stevnevitners, politiansattes og fengselstjenestemenns utførelse av](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1927-06-24-9812.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1927-06-24-9812) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1927-06-24-9812.md) |
| [Forskrift om straffegjennomføring](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2002-02-22-183.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2002-02-22-183) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2002-02-22-183.md) |
| [Forskrift om studier og eksamen ved Politihøgskolen](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2016-12-07-1957.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2016-12-07-1957) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2016-12-07-1957.md) |
| [Forskrift om studiet bachelor i straffegjennomføring](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2018-11-16-1811.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2018-11-16-1811) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2018-11-16-1811.md) |
| [Forskrift om stønad til beboere i asylmottak](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2022-05-31-948.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-05-31-948) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-05-31-948.md) |
| [Forskrift om tap av retten til å føre motorvogn mv.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2003-12-19-1660.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2003-12-19-1660) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2003-12-19-1660.md) |
| [Forskrift om tilfluktsrom](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1995-03-15-254.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1995-03-15-254) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1995-03-15-254.md) |
| [Forskrift om tillitsmannens regnskapsplikt ved forvaltningen av beslagsfrie midl](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1985-09-20-1873.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1985-09-20-1873) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1985-09-20-1873.md) |
| [Forskrift om tilskudd til aktivitetstilbud for barn i asylmottak](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2020-12-17-2921.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-12-17-2921) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-12-17-2921.md) |
| [Forskrift om tilskudd til assistert retur og tvangsretur](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2020-02-17-183.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-02-17-183) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-02-17-183.md) |
| [Forskrift om tilskudd til forebygging av kriminalitet](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2020-12-10-2677.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-12-10-2677) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-12-10-2677.md) |
| [Forskrift om tilskudd til frivillige organisasjoner i kriminalomsorgen](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2020-12-10-2678.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-12-10-2678) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-12-10-2678.md) |
| [Forskrift om tilskudd til frivillige organisasjoner i redningstjenesten](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2020-12-10-2679.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-12-10-2679) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-12-10-2679.md) |
| [Forskrift om tilskudd til internasjonalt migrasjonsarbeid](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2023-11-20-1949.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-11-20-1949) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-11-20-1949.md) |
| [Forskrift om tilskudd til politiforeninger](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2022-12-20-2360.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-12-20-2360) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-12-20-2360.md) |
| [Forskrift om tilskudd til sikringstiltak for tros- og livssynssamfunn](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2020-10-15-2046.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-10-15-2046) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-10-15-2046.md) |
| [Forskrift om tilskudd til spesielle rettshjelptiltak](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2020-12-10-2676.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-12-10-2676) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-12-10-2676.md) |
| [Forskrift om tilskudd til tiltak for å nå personer uten lovlig opphold i Norge m](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2020-12-10-2681.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-12-10-2681) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-12-10-2681.md) |
| [Forskrift om tilskudd til tiltak mot menneskehandel og prostitusjon](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2020-12-10-2675.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-12-10-2675) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-12-10-2675.md) |
| [Forskrift om tilskudd til å forebygge og bekjempe vold i nære relasjoner](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2020-12-10-2680.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-12-10-2680) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-12-10-2680.md) |
| [Forskrift om tilsyn med omsorgen for enslige mindreårige som bor i asylmottak](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2022-06-26-1193.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-06-26-1193) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-06-26-1193.md) |
| [Forskrift om tilsynsrådet for kriminalomsorgen](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2024-12-09-3005.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-12-09-3005) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-12-09-3005.md) |
| [Forskrift om tilsynsrådet for tvangsreturer og utlendingsinternatet](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2022-06-13-1005.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-06-13-1005) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-06-13-1005.md) |
| [Forskrift om tiltak for å forebygge og begrense konsekvensene av storulykker i v](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2016-06-03-569.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2016-06-03-569) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2016-06-03-569.md) |
| [Forskrift om tomtefeste m.m.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2001-06-08-570.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2001-06-08-570) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2001-06-08-570.md) |
| [Forskrift om transportabelt trykkutstyr](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2012-11-22-1088.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2012-11-22-1088) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2012-11-22-1088.md) |
| [Forskrift om trekningskretser for meddommere ved Agder tingrett](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-03-15-996.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-03-15-996) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-03-15-996.md) |
| [Forskrift om trekningskretser for meddommere ved Buskerud tingrett](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-03-15-1008.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-03-15-1008) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-03-15-1008.md) |
| [Forskrift om trekningskretser for meddommere ved Follo og Nordre Østfold tingret](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-03-15-1010.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-03-15-1010) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-03-15-1010.md) |
| [Forskrift om trekningskretser for meddommere ved Gudbrandsdal tingrett](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-05-14-797.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-05-14-797) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-05-14-797.md) |
| [Forskrift om trekningskretser for meddommere ved Haugaland og Sunnhordland tingr](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-03-15-856.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-03-15-856) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-03-15-856.md) |
| [Forskrift om trekningskretser for meddommere ved Hedmarken og Østerdal tingrett](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-03-15-1012.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-03-15-1012) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-03-15-1012.md) |
| [Forskrift om trekningskretser for meddommere ved Helgeland tingrett](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-03-15-852.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-03-15-852) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-03-15-852.md) |
| [Forskrift om trekningskretser for meddommere ved Indre og Østre Finnmark tingret](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-03-15-849.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-03-15-849) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-03-15-849.md) |
| [Forskrift om trekningskretser for meddommere ved Midtre Hålogaland tingrett](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-03-15-851.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-03-15-851) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-03-15-851.md) |
| [Forskrift om trekningskretser for meddommere ved Nord-Troms og Senja tingrett](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-03-15-850.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-03-15-850) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-03-15-850.md) |
| [Forskrift om trekningskretser for meddommere ved Nordmøre og Romsdal tingrett](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-05-14-795.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-05-14-795) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-05-14-795.md) |
| [Forskrift om trekningskretser for meddommere ved Ringerike og Hallingdal tingret](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-05-14-799.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-05-14-799) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-05-14-799.md) |
| [Forskrift om trekningskretser for meddommere ved Romerike og Glåmdal tingrett](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-03-15-1066.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-03-15-1066) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-03-15-1066.md) |
| [Forskrift om trekningskretser for meddommere ved Salten og Lofoten tingrett](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-03-15-853.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-03-15-853) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-03-15-853.md) |
| [Forskrift om trekningskretser for meddommere ved Sunnmøre tingrett](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-05-14-796.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-05-14-796) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-05-14-796.md) |
| [Forskrift om trekningskretser for meddommere ved Søndre Østfold tingrett](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-03-15-767.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-03-15-767) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-03-15-767.md) |
| [Forskrift om trekningskretser for meddommere ved Sør-Rogaland tingrett](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-03-15-857.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-03-15-857) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-03-15-857.md) |
| [Forskrift om trekningskretser for meddommere ved Trøndelag tingrett](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-03-15-766.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-03-15-766) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-03-15-766.md) |
| [Forskrift om trekningskretser for meddommere ved Vestoppland og Valdres tingrett](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-05-14-798.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-05-14-798) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-05-14-798.md) |
| [Forskrift om trekningskretser for meddommere ved Vestre Finnmark tingrett](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-03-15-799.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-03-15-799) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-03-15-799.md) |
| [Forskrift om trekningskretser for meddommere ved Øvre Telemark tingrett](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-05-14-800.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-05-14-800) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-05-14-800.md) |
| [Forskrift om tryggleiken ved sportsdykking.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1994-11-10-1134.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1994-11-10-1134) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1994-11-10-1134.md) |
| [Forskrift om trykkpåkjent utstyr](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2017-10-10-1631.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-10-10-1631) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-10-10-1631.md) |
| [Forskrift om tvangssalg ved medhjelper](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1992-12-04-895.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1992-12-04-895) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1992-12-04-895.md) |
| [Forskrift om unntak fra kravet til redegjørelse om aksjeinnskudd med andre eiend](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2013-10-26-1271.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-10-26-1271) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-10-26-1271.md) |
| [Forskrift om utforming av grensemerker i saker for jordskiftedomstolene](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2015-12-07-1416.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-12-07-1416) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-12-07-1416.md) |
| [Forskrift om utgangsstoffer for eksplosiver](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2024-08-28-2049.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-08-28-2049) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-08-28-2049.md) |
| [Forskrift om utlegg ved lønnstrekk o.l. i særlige tilfelle etter lov om fordring](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1975-06-27-4943.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1975-06-27-4943) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1975-06-27-4943.md) |
| [Forskrift om utlendingers adgang til riket og deres opphold her (utlendingsforsk](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2009-10-15-1286.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2009-10-15-1286) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2009-10-15-1286.md) |
| [Forskrift om utlevering for å få iverksatt vedtak om frihetsinngrep i annet nord](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1970-12-18-2.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1970-12-18-2) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1970-12-18-2.md) |
| [Forskrift om utstyr og sikkerhetssystem til bruk i eksplosjonsfarlig område](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2017-11-29-1849.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-11-29-1849) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-11-29-1849.md) |
| [Forskrift om utvidelse av Svalbardutvalgets stedlige virkeområde m.v.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1971-08-06-3434.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1971-08-06-3434) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1971-08-06-3434.md) |
| [Forskrift om utvidelse av anvendelsesområdet for lov 20. juli 1991 nr 67 om over](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1995-02-01-90.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1995-02-01-90) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1995-02-01-90.md) |
| [Forskrift om utvidelse av virkeområdet for lov om vern av kretsmønstre for integ](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1995-12-27-1176.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1995-12-27-1176) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1995-12-27-1176.md) |
| [Forskrift om vaktvirksomhet (vaktvirksomhetsforskriften)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2011-03-28-337.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2011-03-28-337) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2011-03-28-337.md) |
| [Forskrift om valg av utleggsgjenstand](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-07-09-1508.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-07-09-1508) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-07-09-1508.md) |
| [Forskrift om virksomheters arbeid med forebyggende sikkerhet (virksomhetsikkerhe](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2018-12-20-2053.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2018-12-20-2053) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2018-12-20-2053.md) |
| [Forskrift om våpen, skytevåpen, våpendelar og ammunisjon (våpenforskrifta)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-05-07-1452.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-05-07-1452) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-05-07-1452.md) |
| [Forskrift om å innhente samtykke til eller uttalelse om innsyn i dokumenter innh](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2000-03-07-260.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2000-03-07-260) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2000-03-07-260.md) |
| [Forskrift om åremålsstillinger i politiet.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2001-06-22-704.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2001-06-22-704) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2001-06-22-704.md) |
| [Forskrift til arrestordreloven (arrestordreforskrifta)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2019-10-18-1388.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-10-18-1388) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-10-18-1388.md) |
| [Forskrift til arveloven](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2020-11-09-2327.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-11-09-2327) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-11-09-2327.md) |
| [Forskrift til designloven (designforskriften)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2003-04-04-418.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2003-04-04-418) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2003-04-04-418.md) |
| [Forskrift til forvaltningsloven (forvaltningslovforskriften)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2006-12-15-1456.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2006-12-15-1456) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2006-12-15-1456.md) |
| [Forskrift til inkassoloven m.m. (inkassoforskriften)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1989-07-14-562.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1989-07-14-562) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1989-07-14-562.md) |
| [Forskrift til lov om pant (pantelovforskriften).](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1980-11-21-14.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1980-11-21-14) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1980-11-21-14.md) |
| [Forskrift til lov om yrkesskadeforsikring](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1989-10-13-1041.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1989-10-13-1041) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1989-10-13-1041.md) |
| [Forskrift til offentleglova (offentlegforskrifta)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2008-10-17-1119.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2008-10-17-1119) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2008-10-17-1119.md) |
| [Forskrift til patentloven (patentforskriften)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2007-12-14-1417.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2007-12-14-1417) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2007-12-14-1417.md) |
| [Forskrift til sameigeloven § 15 fjerde ledd.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1966-05-25-8701.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1966-05-25-8701) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1966-05-25-8701.md) |
| [Forskrift til tvisteloven (tvistelovforskriften)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2007-12-21-1605.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2007-12-21-1605) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2007-12-21-1605.md) |
| [Forskrift til varemerkeloven (varemerkeforskriften)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2010-06-25-937.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2010-06-25-937) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2010-06-25-937.md) |
| [Forskrift til vergemålsloven (vergemålsforskriften)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2013-02-15-201.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-02-15-201) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-02-15-201.md) |
| [Forskrift til voldserstatningsloven (voldserstatningsforskriften)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2023-12-14-2088.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-12-14-2088) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-12-14-2088.md) |
| [Forskrifter angaaende Fremgangsmaaden ved Salg af Leilændingsgods tilhørende Sta](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1896-06-26-9805.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1896-06-26-9805) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1896-06-26-9805.md) |
| [Forskrifter angående innleggelse av alkoholister i kuranstalt i henhold til løsg](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1930-11-07-9534.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1930-11-07-9534) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1930-11-07-9534.md) |
| [Forskrifter for teknisk kontroll av gassvernmateriell.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1939-11-17-9575.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1939-11-17-9575) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1939-11-17-9575.md) |
| [Forskrifter for teknisk kontroll av tørrklosetter til bruk i offentlige og priva](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1965-03-09-9736.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1965-03-09-9736) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1965-03-09-9736.md) |
| [Forskrifter om det nøyaktige tidspunkt for frigjøringen av Norge.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1945-10-12-1.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1945-10-12-1) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1945-10-12-1.md) |
| [Forskrifter om forkynnelse av utenlandske dokumenter i Norge](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1969-09-12-5.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1969-09-12-5) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1969-09-12-5.md) |
| [Forskrifter om krigsutflytting.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1980-09-05-5.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1980-09-05-5) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1980-09-05-5.md) |
| [Forskrifter om tilfluktsrom ved industrivernpliktige bedrifter og virksomheter.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1976-08-03-9783.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1976-08-03-9783) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1976-08-03-9783.md) |
| [Forskrifter om unntak fra lov og forskrifter om brannfarlige varer.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1978-02-17-2.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1978-02-17-2) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1978-02-17-2.md) |
| [Forskrifter om utlendingers adgang til Jan Mayen](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1962-06-01-1.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1962-06-01-1) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1962-06-01-1.md) |
| [Forskrifter om vernepliktige sivilarbeidere.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1952-08-22-5.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1952-08-22-5) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1952-08-22-5.md) |
| [Forskrifter vedrørende sivilprosesskonvensjonen av 30. januar 1931 mellom Norge ](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1953-03-19-1.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1953-03-19-1) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1953-03-19-1.md) |
| [Gebyr- og fakturasatser for Longyearbyen lokalstyre 2026](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-12-10-3067.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-12-10-3067) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-12-10-3067.md) |
| [Godkjenning av hovedavtalen for Bankklagenemnda.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2000-05-19-442.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2000-05-19-442) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2000-05-19-442.md) |
| [Kunngjøring av York-Antwerpen reglene 1994.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1997-01-24-36.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1997-01-24-36) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1997-01-24-36.md) |
| [Overgangsbestemmelser for delt ikrafttredelse 1. mars 2023 av lov 12. juni 2020 ](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2023-02-17-230.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-02-17-230) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-02-17-230.md) |
| [Overgangsbestemmelser for gjennomføring av lov 20. april 2012 nr. 19 om endringe](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2012-05-25-465.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2012-05-25-465) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2012-05-25-465.md) |
| [Overgangsbestemmelser til lov 22. juni 2018 nr. 78 om endringer i utlendingslove](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2018-10-24-1610.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2018-10-24-1610) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2018-10-24-1610.md) |
| [Overgangsregler om behandling av personopplysninger](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2018-06-15-877.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2018-06-15-877) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2018-06-15-877.md) |
| [Overgangsregler til lov 11. mai 2023 nr. 13 om endringer i tvisteloven mv. (rett](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2023-06-02-779.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-06-02-779) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-06-02-779.md) |
| [Overgangsregler til lov 11. mai 2023 nr. 13 om endringer i tvisteloven mv. (rett](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2023-11-24-1903.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-11-24-1903) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-11-24-1903.md) |
| [Overgangsregler til lov 14. juni 2013 nr. 40 om endringer i aksjelovgivningen mv](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2013-06-19-662.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-06-19-662) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-06-19-662.md) |
| [Overgangsregler til lov 17. juni 2016 nr. 55 om endringer i konkursloven mv. (gr](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-05-21-1618.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-05-21-1618) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-05-21-1618.md) |
| [Overgangsregler til lov 17. juni 2022 nr. 57 om erstatning fra staten til voldsu](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2022-12-02-2073.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-12-02-2073) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-12-02-2073.md) |
| [Overgangsregler til lov 18. desember 2020 nr. 146 om finansavtaler](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2022-09-28-1675.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-09-28-1675) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-09-28-1675.md) |
| [Overgangsregler til lov 18. februar 2022 nr. 5 om endringer i forsikringsavtalel](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2022-03-04-382.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-03-04-382) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-03-04-382.md) |
| [Overgangsregler til lov 29. juni 2007 nr. 80 om endringar i lov 15. desember 196](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2007-12-14-1416.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2007-12-14-1416) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2007-12-14-1416.md) |
| [Regler om bruk av rettskapper m.v. ved domstolen](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1995-06-23-577.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1995-06-23-577) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1995-06-23-577.md) |
| [Regler om personundersøkelse i straffesaker.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1986-10-22-2373.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1986-10-22-2373) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1986-10-22-2373.md) |
| [Res. om bruk av telegraf og telefon til forkynnelser i henhold til domstollovens](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1932-12-10-3.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1932-12-10-3) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1932-12-10-3.md) |
| [Res. om dommerforsikring efter domstollovens § 60](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1927-06-10-3.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1927-06-10-3) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1927-06-10-3.md) |
| [Rundskriv om kunngjøring i Norsk Lovtidend avdeling I og II.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1992-10-28-1.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1992-10-28-1) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1992-10-28-1.md) |
| [Vedtak om godkjenning av vedtekter for klagenemnd for inkassotenester mellom For](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2003-03-07-287.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2003-03-07-287) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2003-03-07-287.md) |
