# Energidepartementet

*80 forskrifter*

| Forskrift | Lovdata | Historikk |
|-----------|---------|-----------|
| [Forskrift om Energiklagenemnda](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2019-10-24-1420.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-10-24-1420) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-10-24-1420.md) |
| [Forskrift om Havbunnsmineralregisteret](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-08-29-1747.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-08-29-1747) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-08-29-1747.md) |
| [Forskrift om Norgespris](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-09-08-1790.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-09-08-1790) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-09-08-1790.md) |
| [Forskrift om Norgespris og strømstønad til husholdninger som bruker fjernvarme](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-09-08-1792.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-09-08-1792) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-09-08-1792.md) |
| [Forskrift om Petroleumsregisteret.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1997-06-19-618.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1997-06-19-618) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1997-06-19-618.md) |
| [Forskrift om adgang til å kreve gebyr og sektoravgift for tilsyn og annen oppføl](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2013-01-08-16.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-01-08-16) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-01-08-16.md) |
| [Forskrift om andres bruk av innretninger.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2005-12-20-1625.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2005-12-20-1625) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2005-12-20-1625.md) |
| [Forskrift om angivelse av husholdningsapparaters energi- og ressursforbruk ved h](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1996-01-10-16.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1996-01-10-16) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1996-01-10-16.md) |
| [Forskrift om datainnsamling og dokumentasjon i mineralvirksomhet på kontinentals](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-09-01-1767.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-09-01-1767) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-09-01-1767.md) |
| [Forskrift om deklarering av kjemikalier til produktregisteret (deklareringsforsk](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2015-05-19-541.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-05-19-541) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-05-19-541.md) |
| [Forskrift om elektromagnetisk kompatibilitet](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2017-10-10-1597.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-10-10-1597) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-10-10-1597.md) |
| [Forskrift om elsertifikater](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2011-12-16-1398.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2011-12-16-1398) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2011-12-16-1398.md) |
| [Forskrift om endring i forskrift om miljøvennlig utforming av energirelaterte pr](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2026-03-05-354.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2026-03-05-354) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2026-03-05-354.md) |
| [Forskrift om endring i forskrift om sikkerhet og beredskap i kraftforsyningen (k](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2026-05-04-717.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2026-05-04-717) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2026-05-04-717.md) |
| [Forskrift om endring i forskrift om utføring av aktiviteter i petroleumsvirksomh](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2024-12-18-3263.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-12-18-3263) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-12-18-3263.md) |
| [Forskrift om endring i forskrift til lov om petroleumsvirksomhet.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1999-06-04-571.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1999-06-04-571) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1999-06-04-571.md) |
| [Forskrift om energikartlegging (energikartleggingsforskriften)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2024-09-25-2262.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-09-25-2262) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-09-25-2262.md) |
| [Forskrift om energimerking av bygninger og energivurdering av varme- og klimaanl](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2009-12-18-1665.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2009-12-18-1665) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2009-12-18-1665.md) |
| [Forskrift om energimerking av energirelaterte produkter (energimerkeforskriften ](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2013-05-27-534.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-05-27-534) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-05-27-534.md) |
| [Forskrift om energiutredninger](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2024-01-25-106.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-01-25-106) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-01-25-106.md) |
| [Forskrift om fastsettelse av tariffer mv. for bestemte innretninger](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2002-12-20-1724.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2002-12-20-1724) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2002-12-20-1724.md) |
| [Forskrift om fastsetting av normpriser](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1976-06-25-5.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1976-06-25-5) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1976-06-25-5.md) |
| [Forskrift om fiskal måling i petroleumsvirksomheten (måleforskriften)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2023-04-21-532.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-04-21-532) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-04-21-532.md) |
| [Forskrift om forbud mot bruk av mineralolje til oppvarming av bygninger og fossi](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2018-06-28-1060.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2018-06-28-1060) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2018-06-28-1060.md) |
| [Forskrift om gjennomføring i norsk rett av EØS-avtalen vedlegg IV nr. 47 (forord](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2019-10-24-1434.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-10-24-1434) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-10-24-1434.md) |
| [Forskrift om gjennomføring i norsk rett av EØS-avtalens vedlegg IV som retter se](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1992-12-11-1064.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1992-12-11-1064) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1992-12-11-1064.md) |
| [Forskrift om gjennomføring i norsk rett av vedlegg IV nr. 30 til EØS-avtala (for](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2010-06-25-940.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2010-06-25-940) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2010-06-25-940.md) |
| [Forskrift om gjennomføringsreglar for rådsdirektiv 92/75/EØF med omsyn til energ](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1998-05-04-463.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1998-05-04-463) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1998-05-04-463.md) |
| [Forskrift om helse, miljø og sikkerhet i petroleumsvirksomheten og på enkelte la](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2010-02-12-158.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2010-02-12-158) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2010-02-12-158.md) |
| [Forskrift om hvem som kan få rett til å foreta eiendomsinngrep etter lov om orei](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1989-07-14-565.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1989-07-14-565) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1989-07-14-565.md) |
| [Forskrift om håndtering av energiknapphet og kraftrasjonering](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2023-12-19-2161.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-12-19-2161) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-12-19-2161.md) |
| [Forskrift om innbetaling av påslag på nettariffen til Energifondet (forskrift om](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2001-12-10-1377.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2001-12-10-1377) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2001-12-10-1377.md) |
| [Forskrift om internkontroll etter vassdragslovgivningen (IK-vassdrag)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2011-10-28-1058.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2011-10-28-1058) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2011-10-28-1058.md) |
| [Forskrift om justering av konsesjonsavgifter, årlige erstatninger og fond m.v. i](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1987-12-04-945.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1987-12-04-945) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1987-12-04-945.md) |
| [Forskrift om kommunalt tilsyn med anlegg for sikring mot flom, erosjon og skred ](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2005-06-17-655.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2005-06-17-655) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2005-06-17-655.md) |
| [Forskrift om kommunens myndighet i mindre vannkraftsaker](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2017-12-15-2037.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-12-15-2037) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-12-15-2037.md) |
| [Forskrift om kompensasjon til fiskere for tapt fangsttid ved lokalisering, oppta](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2009-06-19-700.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2009-06-19-700) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2009-06-19-700.md) |
| [Forskrift om kost-nytteanalyse av mulighetene for å utnytte overskuddsvarme](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2024-09-25-2263.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-09-25-2263) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-09-25-2263.md) |
| [Forskrift om leveringskvalitet i kraftsystemet](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2004-11-30-1557.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2004-11-30-1557) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2004-11-30-1557.md) |
| [Forskrift om materiale og dokumentasjon ved undersøkelse etter og utnyttelse av ](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2017-12-13-2003.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-12-13-2003) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-12-13-2003.md) |
| [Forskrift om måling, avregning, fakturering av nettjenester og elektrisk energi,](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1999-03-11-301.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1999-03-11-301) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1999-03-11-301.md) |
| [Forskrift om nettregulering og energimarkedet (NEM)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2019-10-24-1413.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-10-24-1413) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-10-24-1413.md) |
| [Forskrift om oppgaveplikt ved brønnboring og grunnvannsundersøkelser.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1996-11-19-1066.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1996-11-19-1066) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1996-11-19-1066.md) |
| [Forskrift om opprinnelsesgarantier for produksjon av elektrisk energi](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2007-12-14-1652.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2007-12-14-1652) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2007-12-14-1652.md) |
| [Forskrift om pliktig innmelding av grunnundersøkelser og naturfareutredninger](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2024-12-17-3181.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-12-17-3181) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-12-17-3181.md) |
| [Forskrift om produksjon, omforming, overføring, omsetning, fordeling og bruk av ](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1990-12-07-959.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1990-12-07-959) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1990-12-07-959.md) |
| [Forskrift om rammer for vannforvaltningen](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2006-12-15-1446.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2006-12-15-1446) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2006-12-15-1446.md) |
| [Forskrift om rapporteringsplikt for kraftleveringsavtaler](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2015-03-09-194.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-03-09-194) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-03-09-194.md) |
| [Forskrift om ressursforvaltning i petroleumsvirksomheten (ressursforskriften)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2017-12-13-2004.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-12-13-2004) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-12-13-2004.md) |
| [Forskrift om sektoravgift for dekning av kostnader til Norges vassdrags- og ener](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2023-09-27-1518.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-09-27-1518) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-09-27-1518.md) |
| [Forskrift om sektoravgift og refusjon av utgifter for tilsyn med ressursforvaltn](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1997-06-27-652.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1997-06-27-652) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1997-06-27-652.md) |
| [Forskrift om sikkerhet for undersøkelse og leteboring etter petroleumsforekomste](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1988-03-25-250.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1988-03-25-250) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1988-03-25-250.md) |
| [Forskrift om sikkerhet og arbeidsmiljø ved mineralvirksomhet til havs (havbunnsm](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-10-15-2050.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-10-15-2050) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-10-15-2050.md) |
| [Forskrift om sikkerhet og arbeidsmiljø ved transport og injeksjon av CO2på konti](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2020-02-25-186.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-02-25-186) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-02-25-186.md) |
| [Forskrift om sikkerhet og beredskap i kraftforsyningen (kraftberedskapsforskrift](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2012-12-07-1157.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2012-12-07-1157) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2012-12-07-1157.md) |
| [Forskrift om sikkerhet ved vassdragsanlegg (damsikkerhetsforskriften)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2009-12-18-1600.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2009-12-18-1600) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2009-12-18-1600.md) |
| [Forskrift om strømnettselskapenes inntekter (nettinntektsforskriften)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-01-14-50.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-01-14-50) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-01-14-50.md) |
| [Forskrift om strømstønad](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-09-08-1791.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-09-08-1791) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-09-08-1791.md) |
| [Forskrift om systemansvaret i kraftsystemet](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2002-05-07-448.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2002-05-07-448) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2002-05-07-448.md) |
| [Forskrift om tariffer og rapporteringsplikt for omsetningskonsesjonærer (forskri](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1999-03-11-302.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1999-03-11-302) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1999-03-11-302.md) |
| [Forskrift om tilskudd til energitiltak i kommunalt eide utleieboliger, omsorgsbo](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2022-12-28-2525.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-12-28-2525) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-12-28-2525.md) |
| [Forskrift om tilskudd til flom- og skredforebygging (forskrift om naturfaretilsk](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2022-06-29-1237.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-06-29-1237) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-06-29-1237.md) |
| [Forskrift om trykkpåkjent utstyr](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2017-10-10-1631.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-10-10-1631) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-10-10-1631.md) |
| [Forskrift om undersøkelse og utvinning av skjellsand, sand og grus i kystnære om](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2023-12-20-2167.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-12-20-2167) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-12-20-2167.md) |
| [Forskrift om utleie av vannkraftanlegg](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2010-06-25-939.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2010-06-25-939) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2010-06-25-939.md) |
| [Forskrift om utnyttelse av undersjøiske reservoarer på kontinentalsokkelen til l](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2014-12-05-1517.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2014-12-05-1517) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2014-12-05-1517.md) |
| [Forskrift om vedtaksmyndighet etter energiloven](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2013-06-21-681.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-06-21-681) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-06-21-681.md) |
| [Forskrift om vilkår for tilgang til nett for utveksling av elektrisk kraft over ](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2006-12-20-1563.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2006-12-20-1563) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2006-12-20-1563.md) |
| [Forskrift til havbunnsmineralloven (havbunnsmineralforskriften)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-08-29-1740.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-08-29-1740) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-08-29-1740.md) |
| [Forskrift til havbunnsmineralloven kapittel 8 om erstatning til norske fiskere](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-08-29-1741.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-08-29-1741) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-08-29-1741.md) |
| [Forskrift til havenergilova (havenergilovforskrifta)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2020-06-12-1192.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-06-12-1192) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-06-12-1192.md) |
| [Forskrift til lov 29. november 1996 nr. 72 om petroleumsvirksomhet kapittel 8 om](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2008-12-12-1357.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2008-12-12-1357) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2008-12-12-1357.md) |
| [Forskrift til lov om felles regler for det indre marked for naturgass (naturgass](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2003-11-14-1342.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2003-11-14-1342) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2003-11-14-1342.md) |
| [Forskrift til lov om petroleumsvirksomhet](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1997-06-27-653.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1997-06-27-653) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1997-06-27-653.md) |
| [Midlertidig forskrift om bruk av flaskehalsinntekter](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2022-10-27-1806.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-10-27-1806) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-10-27-1806.md) |
| [Midlertidig forskrift om stønad til kunder av nærvarmeleverandører](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2023-10-30-1734.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-10-30-1734) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-10-30-1734.md) |
| [Midlertidig forskrift om støtte som følge av ekstraordinære utgifter til elektri](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2022-06-30-1273.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-06-30-1273) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-06-30-1273.md) |
| [Resolusjon om norsk statshøyhet over visse undersjøiske områder.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1963-05-31-1.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1963-05-31-1) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1963-05-31-1.md) |
| [Resolusjon om opprettelse av Olje- og energidepartementet.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1978-01-11-1.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1978-01-11-1) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1978-01-11-1.md) |
| [Resolusjon om vitenskapelige undersøkelser etter naturforekomster på den norske ](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1969-01-31-2.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1969-01-31-2) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1969-01-31-2.md) |
