# Samferdselsdepartementet

*323 forskrifter*

| Forskrift | Lovdata | Historikk |
|-----------|---------|-----------|
| [Delegering av Kongens myndighet etter lov 4. september 2015 nr. 91 om posttjenes](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2024-02-02-171.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-02-02-171) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-02-02-171.md) |
| [Forskrift etter luftfartsloven – utenlandsk luftfartøy innenfor norsk område.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1985-03-29-699.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1985-03-29-699) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1985-03-29-699.md) |
| [Forskrift for sivil transportberedskap](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2005-06-14-548.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2005-06-14-548) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2005-06-14-548.md) |
| [Forskrift for trafikklast på bruer, ferjekaier og andre bærende konstruksjoner i](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2017-11-17-1900.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-11-17-1900) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-11-17-1900.md) |
| [Forskrift om 12/100 for spesialtransport på riks-, fylkes- og kommunale veger (v](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2023-10-24-1698.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-10-24-1698) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-10-24-1698.md) |
| [Forskrift om 12/65 for mobilkran, betongpumpebil og liftbil på riks-, fylkes- og](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2023-10-24-1699.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-10-24-1699) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-10-24-1699.md) |
| [Forskrift om U-space og krav til en integrert digital luftfartspublikasjon for b](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2024-10-23-2572.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-10-23-2572) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-10-23-2572.md) |
| [Forskrift om alkolås, alkolåsverksteder mv.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2018-05-30-777.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2018-05-30-777) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2018-05-30-777.md) |
| [Forskrift om alminnelige regler om bygging og vedlikehold av avkjørsler fra offe](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1964-07-16-3905.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1964-07-16-3905) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1964-07-16-3905.md) |
| [Forskrift om anlegg av offentlig veg](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2007-03-29-363.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2007-03-29-363) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2007-03-29-363.md) |
| [Forskrift om arbeid på kjøretøy (verkstedforskriften)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2020-10-28-2170.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-10-28-2170) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-10-28-2170.md) |
| [Forskrift om arbeidsmaskiner på jernbanenettet og infrastruktur for sporvei, tun](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2022-05-25-924.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-05-25-924) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-05-25-924.md) |
| [Forskrift om arbeidstid for sjåfører og andre innenfor vegtransport](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2005-06-10-543.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2005-06-10-543) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2005-06-10-543.md) |
| [Forskrift om arbeidstid med mer for besetningsmedlemmer i sivile luftfartøyer (B](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2004-12-30-1817.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2004-12-30-1817) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2004-12-30-1817.md) |
| [Forskrift om autorisasjon mv. for utøvelse av lokal flygeinformasjonstjeneste, A](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2008-12-19-1574.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2008-12-19-1574) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2008-12-19-1574.md) |
| [Forskrift om avgift på flysikringstjenester](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2014-12-19-1847.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2014-12-19-1847) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2014-12-19-1847.md) |
| [Forskrift om avgifter for bruk av lufthavner drevet av Avinor AS](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2019-12-20-2137.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-12-20-2137) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-12-20-2137.md) |
| [Forskrift om avgiftssats for bruk av lufthavner med helikopterterminal drevet av](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-12-01-3358.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-12-01-3358) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-12-01-3358.md) |
| [Forskrift om avgiftssatser for bruk av lufthavner drevet av Avinor AS](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-11-19-3223.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-11-19-3223) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-11-19-3223.md) |
| [Forskrift om bakketjeneste ved flyplasser (BSL E 4-1)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2003-06-27-935.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2003-06-27-935) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2003-06-27-935.md) |
| [Forskrift om behandling av avkjørslesaker for riksveg](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1982-02-26-3791.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1982-02-26-3791) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1982-02-26-3791.md) |
| [Forskrift om betaling av bompenger på offentlig veg](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2023-01-27-105.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-01-27-105) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-01-27-105.md) |
| [Forskrift om betalingsløsning for betaling ved lading av elektrisk drevet kjøret](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2023-06-26-1152.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-06-26-1152) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-06-26-1152.md) |
| [Forskrift om billettering ved jernbanetransport](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2017-12-20-2333.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-12-20-2333) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-12-20-2333.md) |
| [Forskrift om brann- og redningstjeneste (BSL E 4-4).](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2006-05-12-545.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2006-05-12-545) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2006-05-12-545.md) |
| [Forskrift om bruk av hangglider og paraglider](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2010-01-05-1.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2010-01-05-1) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2010-01-05-1.md) |
| [Forskrift om bruk av kjøretøy](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1990-01-25-92.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1990-01-25-92) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1990-01-25-92.md) |
| [Forskrift om bruk av personlig verneutstyr under kjøring med motorvogn](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1979-09-21-7.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1979-09-21-7) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1979-09-21-7.md) |
| [Forskrift om bruk av system for sikkerhetsstyring innen bakketjenesten](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2003-08-21-1068.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2003-08-21-1068) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2003-08-21-1068.md) |
| [Forskrift om bruk av utenlandsk motorvogn i riket og om særskilt registrering av](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1967-03-28-9350.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1967-03-28-9350) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1967-03-28-9350.md) |
| [Forskrift om brukerfinansiering av Parkeringsklagenemnda](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2016-12-20-1787.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2016-12-20-1787) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2016-12-20-1787.md) |
| [Forskrift om busspassasjerrettigheter](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2016-02-25-193.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2016-02-25-193) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2016-02-25-193.md) |
| [Forskrift om charter- og taxiflyging fra og til norsk område.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1999-02-05-195.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1999-02-05-195) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1999-02-05-195.md) |
| [Forskrift om de grunnleggende parametrene for det transeuropeiske jernbanesystem](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2002-03-13-273.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2002-03-13-273) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2002-03-13-273.md) |
| [Forskrift om definisjon og bruk av kompatible tekniske spesifikasjonar og vedtek](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1995-06-02-517.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1995-06-02-517) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1995-06-02-517.md) |
| [Forskrift om dispensasjon fra krav om at dagsprøvekjennemerke kun kan brukes på ](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-03-23-990.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-03-23-990) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-03-23-990.md) |
| [Forskrift om eksport av luftfartøy, flymotor og flypropell](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-06-25-2245.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-06-25-2245) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-06-25-2245.md) |
| [Forskrift om elektrotjeneste (BSL E 4-3).](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2004-08-26-1245.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2004-08-26-1245) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2004-08-26-1245.md) |
| [Forskrift om en felles sikkerhetsmetode for risikoevaluering og -vurdering (CSM ](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2014-10-27-1344.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2014-10-27-1344) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2014-10-27-1344.md) |
| [Forskrift om endring i forskrift om bruk av kjøretøy](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2026-01-21-71.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2026-01-21-71) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2026-01-21-71.md) |
| [Forskrift om endring i forskrift om bruk av kjøretøy](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2026-01-21-91.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2026-01-21-91) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2026-01-21-91.md) |
| [Forskrift om endring i forskrift om bruk av kjøretøy](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2026-03-20-442.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2026-03-20-442) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2026-03-20-442.md) |
| [Forskrift om endring i forskrift om bruk av kjøretøy og opphevelse av forskrift ](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2026-05-05-742.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2026-05-05-742) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2026-05-05-742.md) |
| [Forskrift om endring i forskrift om endring i forskrift om bruk av kjøretøy](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2026-05-07-774.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2026-05-07-774) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2026-05-07-774.md) |
| [Forskrift om endring i forskrift om taubaner (taubaneforskriften)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-12-08-2457.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-12-08-2457) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-12-08-2457.md) |
| [Forskrift om endring i forskrift om utslippskrav til kjøretøy ved offentlig ansk](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2026-04-21-622.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2026-04-21-622) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2026-04-21-622.md) |
| [Forskrift om endring i forskrift om yrkestransport med motorvogn og fartøy (yrke](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2019-12-06-1646.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-12-06-1646) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-12-06-1646.md) |
| [Forskrift om endring i forskrift om yrkestransport med motorvogn og fartøy (yrke](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2026-01-29-108.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2026-01-29-108) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2026-01-29-108.md) |
| [Forskrift om endring i førerkortforskriften og trafikkopplæringsforskriften](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2026-04-15-596.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2026-04-15-596) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2026-04-15-596.md) |
| [Forskrift om energimerking mv. av nye personbiler](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2001-07-11-829.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2001-07-11-829) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2001-07-11-829.md) |
| [Forskrift om ervervsmessig luftfart med helikopter.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1976-09-06-4054.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1976-09-06-4054) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1976-09-06-4054.md) |
| [Forskrift om etablering og gjennomføring av Det felles europeiske luftrom](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2014-12-19-1846.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2014-12-19-1846) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2014-12-19-1846.md) |
| [Forskrift om etablering, organisering og drift av lufttrafikktjeneste](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2003-11-11-1345.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2003-11-11-1345) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2003-11-11-1345.md) |
| [Forskrift om fartsskriververksteder](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2018-09-26-1467.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2018-09-26-1467) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2018-09-26-1467.md) |
| [Forskrift om faste grenser for påvirkning av andre berusende eller bedøvende mid](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2012-01-20-85.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2012-01-20-85) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2012-01-20-85.md) |
| [Forskrift om felles sikkerhetsmål for jernbanesystemet](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2013-03-13-280.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-03-13-280) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-03-13-280.md) |
| [Forskrift om felleseuropeiske sikkerhetsregler for sivil luftfart og om etableri](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2024-06-27-1381.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-06-27-1381) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-06-27-1381.md) |
| [Forskrift om flygeoppvisning](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2015-04-23-424.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-04-23-424) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-04-23-424.md) |
| [Forskrift om flymaskinistsertifikat (BSL C 5-1a).](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2000-12-20-1638.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2000-12-20-1638) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2000-12-20-1638.md) |
| [Forskrift om flypassasjerers rettigheter ved nektet ombordstigning og innstilt e](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2005-02-17-141.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2005-02-17-141) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2005-02-17-141.md) |
| [Forskrift om flyredningstjenesten](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1956-08-10-3410.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1956-08-10-3410) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1956-08-10-3410.md) |
| [Forskrift om flyselskaper som er underlagt driftsforbud og om plikt til å inform](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2007-12-04-1353.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2007-12-04-1353) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2007-12-04-1353.md) |
| [Forskrift om flytelefonistsertifikat (flytelefonistforskriften) BSL C 5-2a](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2009-11-18-1383.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2009-11-18-1383) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2009-11-18-1383.md) |
| [Forskrift om flyværtjeneste på norsk kontinentalsokkel](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-02-23-526.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-02-23-526) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-02-23-526.md) |
| [Forskrift om forbud mot bruk av beltemotorsykkel (snøscooter) på offentlig veg.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2001-12-14-1411.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2001-12-14-1411) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2001-12-14-1411.md) |
| [Forskrift om forbud mot førers bruk av håndholdt mobiltelefon under kjøring med ](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1999-12-17-1309.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1999-12-17-1309) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1999-12-17-1309.md) |
| [Forskrift om forbud mot variabel reklame langs offentlig veg.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1990-05-23-380.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1990-05-23-380) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1990-05-23-380.md) |
| [Forskrift om fordeling av begrensede trafikkrettigheter på luftfartens område](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2009-03-10-293.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2009-03-10-293) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2009-03-10-293.md) |
| [Forskrift om fordeling av tidsluker (slots) på lufthavner](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2024-03-05-385.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-03-05-385) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-03-05-385.md) |
| [Forskrift om forebyggelse av anslag mot sikkerheten i luftfarten mv.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2011-03-01-214.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2011-03-01-214) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2011-03-01-214.md) |
| [Forskrift om forenklet forelegg i vegtrafikksaker](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1990-06-29-492.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1990-06-29-492) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1990-06-29-492.md) |
| [Forskrift om fornøyelsesinnretninger (tivoliforskriften)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2022-12-21-2431.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-12-21-2431) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-12-21-2431.md) |
| [Forskrift om fortrinnsrett og ventelønn for ansatte i Norges Statsbaner BA.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1997-07-18-803.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1997-07-18-803) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1997-07-18-803.md) |
| [Forskrift om fortrinnsrett og ventelønn for ansatte i Posten Norge BA.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1997-07-18-804.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1997-07-18-804) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1997-07-18-804.md) |
| [Forskrift om framgangsmåter for vurdering av samsvar, bruksegnethet og EF-verifi](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2011-10-04-994.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2011-10-04-994) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2011-10-04-994.md) |
| [Forskrift om fråhaldsplikt for personell som utfører oppgåver som gjeld trygglei](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2006-10-16-1160.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2006-10-16-1160) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2006-10-16-1160.md) |
| [Forskrift om førerkort m.m. (førerkortforskriften)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2004-01-19-298.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2004-01-19-298) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2004-01-19-298.md) |
| [Forskrift om gebyr for bruk av piggdekk og tilleggsgebyr](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1999-05-07-437.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1999-05-07-437) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1999-05-07-437.md) |
| [Forskrift om gebyr for overlasting](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1971-12-17-1.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1971-12-17-1) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1971-12-17-1.md) |
| [Forskrift om gebyr for parkeringsvirksomhet og opplæringstilbydere (gebyrforskri](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2016-12-06-1456.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2016-12-06-1456) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2016-12-06-1456.md) |
| [Forskrift om gebyr for uforsikret motorvogn mv.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2018-02-14-230.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2018-02-14-230) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2018-02-14-230.md) |
| [Forskrift om gebyr for visse overtredelser av vegtrafikklovgivningen](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-03-26-963.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-03-26-963) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-03-26-963.md) |
| [Forskrift om gebyr for visse overtredelser av yrkestransportregelverket](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2024-02-02-194.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-02-02-194) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-02-02-194.md) |
| [Forskrift om gebyr på tjenester utført av Statens vegvesen på trafikant- og kjør](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2023-10-10-1650.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-10-10-1650) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-10-10-1650.md) |
| [Forskrift om gebyr til Luftfartstilsynet mv.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2026-01-28-125.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2026-01-28-125) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2026-01-28-125.md) |
| [Forskrift om gebyrsatser for overlasting med kjøretøy på offentlig veg](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1987-12-18-1101.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1987-12-18-1101) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1987-12-18-1101.md) |
| [Forskrift om generelle bestemmelser om utstedelse av luftfartssertifikater (BSL ](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2000-12-20-1673.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2000-12-20-1673) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2000-12-20-1673.md) |
| [Forskrift om gjennomføring av Europeisk avtale om kjøre- og hviletid m.v. for ma](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2012-06-28-794.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2012-06-28-794) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2012-06-28-794.md) |
| [Forskrift om gjennomføring av Kommisjonsdelegert forordning (EU) nr. 305/2013 om](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2015-03-27-343.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-03-27-343) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-03-27-343.md) |
| [Forskrift om gjennomføring av Kommisjonsdelegert forordning (EU) nr. 885/2013 om](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2015-12-16-1691.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-12-16-1691) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-12-16-1691.md) |
| [Forskrift om gjennomføring av Kommisjonsdelegert forordning (EU) nr. 886/2013 om](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2015-12-16-1692.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-12-16-1692) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-12-16-1692.md) |
| [Forskrift om gjennomføring av TSI-rullende materiell – godsvogner på det nasjona](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2014-02-17-188.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2014-02-17-188) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2014-02-17-188.md) |
| [Forskrift om gjennomføring av TSI-rullende materiell – lokomotiver og rullende m](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2015-07-23-913.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-07-23-913) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-07-23-913.md) |
| [Forskrift om gjennomføring av den tekniske spesifikasjonen for samtrafikkevne so](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2015-11-12-1306.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-11-12-1306) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-11-12-1306.md) |
| [Forskrift om gjennomføring av felles sikkerhetsmetode for overvåking som skal an](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2013-07-02-853.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-07-02-853) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-07-02-853.md) |
| [Forskrift om gjennomføring av fellesregler om innenlands transport i EØS-avtalen](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1995-08-11-716.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1995-08-11-716) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1995-08-11-716.md) |
| [Forskrift om gjennomføring av forordning (EF) nr. 881/2004 av 29. april 2004 om ](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2005-12-16-1491.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2005-12-16-1491) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2005-12-16-1491.md) |
| [Forskrift om gjennomføring av forordning (EU) 2015/10 om kriterier for søkere av](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-07-08-2366.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-07-08-2366) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-07-08-2366.md) |
| [Forskrift om gjennomføring av forordning (EU) 2015/1100 om medlemsstatenes rappo](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-07-08-2362.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-07-08-2362) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-07-08-2362.md) |
| [Forskrift om gjennomføring av forordning (EU) 2015/171 av 4. februar 2015 om vis](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-09-08-2716.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-09-08-2716) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-09-08-2716.md) |
| [Forskrift om gjennomføring av forordning (EU) 2015/909 om metode og nærmere regl](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-07-08-2361.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-07-08-2361) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-07-08-2361.md) |
| [Forskrift om gjennomføring av forordning (EU) 2016/545 om framgangsmåter og krit](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-07-08-2363.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-07-08-2363) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-07-08-2363.md) |
| [Forskrift om gjennomføring av forordning (EU) 2017/2177 om tilgang til servicean](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-07-08-2364.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-07-08-2364) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-07-08-2364.md) |
| [Forskrift om gjennomføring av forordning (EU) 2017/6 om gjennomføringsplanen for](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-09-08-2704.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-09-08-2704) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-09-08-2704.md) |
| [Forskrift om gjennomføring av forordning (EU) 2018/1795 om fastsettelse av fremg](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-07-08-2365.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-07-08-2365) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-07-08-2365.md) |
| [Forskrift om gjennomføring av forordning (EU) 2018/545 av 4. april 2018 om prakt](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-09-08-2707.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-09-08-2707) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-09-08-2707.md) |
| [Forskrift om gjennomføring av forordning (EU) 2018/761 om felles sikkerhetsmetod](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-09-08-2702.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-09-08-2702) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-09-08-2702.md) |
| [Forskrift om gjennomføring av forordning (EU) 2018/762 om felles sikkerhetsmetod](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-09-08-2703.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-09-08-2703) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-09-08-2703.md) |
| [Forskrift om gjennomføring av forordning (EU) 2018/763 om praktiske ordninger fo](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-09-08-2706.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-09-08-2706) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-09-08-2706.md) |
| [Forskrift om gjennomføring av forordning (EU) 2019/250 av 12. februar 2019 om ma](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-09-08-2717.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-09-08-2717) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-09-08-2717.md) |
| [Forskrift om gjennomføring av forordning (EU) 2019/773 om tekniske spesifikasjon](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-09-08-2714.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-09-08-2714) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-09-08-2714.md) |
| [Forskrift om gjennomføring av forordning (EU) 2019/777 om de felles spesifikasjo](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-09-08-2710.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-09-08-2710) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-09-08-2710.md) |
| [Forskrift om gjennomføring av forordning (EU) 2019/779 av 16. mai 2019 om detalj](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-09-08-2712.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-09-08-2712) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-09-08-2712.md) |
| [Forskrift om gjennomføring av forordning (EU) 2020/424 av 19. mars 2020 om framl](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-09-08-2741.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-09-08-2741) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-09-08-2741.md) |
| [Forskrift om gjennomføring av forordning (EU) 2023/1695 om tekniske spesifikasjo](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-03-14-450.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-03-14-450) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-03-14-450.md) |
| [Forskrift om gjennomføring av forordning (EU) nr. 913/2010 om et europeisk jernb](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2014-02-17-190.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2014-02-17-190) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2014-02-17-190.md) |
| [Forskrift om gjennomføring av forordning (EØF) nr. 3922/91 om harmonisering av t](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2008-02-21-189.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2008-02-21-189) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2008-02-21-189.md) |
| [Forskrift om gjennomføring av kommisjonsbeslutning (EU) 2018/1614 av 25. oktober](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-09-08-2711.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-09-08-2711) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-09-08-2711.md) |
| [Forskrift om gjennomføring av kommisjonsbeslutning 2012/462/EU om endring av ved](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2014-06-24-862.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2014-06-24-862) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2014-06-24-862.md) |
| [Forskrift om gjennomføring av kommisjonsforordning (EU) 2020/420 av 16. mars 202](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-04-09-1194.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-04-09-1194) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-04-09-1194.md) |
| [Forskrift om gjennomføring av kommisjonsforordning (EU) nr. 1299/2014 om de tekn](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2015-10-05-1163.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-10-05-1163) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-10-05-1163.md) |
| [Forskrift om gjennomføring av kommisjonsforordning (EU) nr. 1300/2014 av 18. nov](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2015-09-28-1131.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-09-28-1131) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-09-28-1131.md) |
| [Forskrift om gjennomføring av kommisjonsforordning (EU) nr. 1301/2014 av 18. nov](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2015-06-19-720.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-06-19-720) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-06-19-720.md) |
| [Forskrift om gjennomføring av kommisjonsforordning (EU) nr. 1303/2014 av 18. nov](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2015-06-16-685.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-06-16-685) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-06-16-685.md) |
| [Forskrift om gjennomføring av rusmiddeltesting og forbud mot å tjenestegjøre i r](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2019-01-16-25.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-01-16-25) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-01-16-25.md) |
| [Forskrift om gjennomføring av vedtak 2009/460/EF om innføring av felles sikkerhe](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2010-01-29-72.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2010-01-29-72) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2010-01-29-72.md) |
| [Forskrift om gjennomføring i norsk rett av EØS-avtalen vedlegg XIII nr. 4a (foro](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2010-12-17-1673.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2010-12-17-1673) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2010-12-17-1673.md) |
| [Forskrift om gjennomføring og håndheving av ECAA-avtalen (European Common Aviati](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2007-07-02-839.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2007-07-02-839) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2007-07-02-839.md) |
| [Forskrift om gjennomføring og håndheving av EFTA-konvensjonen av 21. juni 2001, ](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2003-01-30-85.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2003-01-30-85) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2003-01-30-85.md) |
| [Forskrift om gjennomføring og håndheving av EØS-avtalen på luftfartens område](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1994-07-15-691.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1994-07-15-691) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1994-07-15-691.md) |
| [Forskrift om gjennomføringsbestemmelser til luftfartsloven.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1994-03-11-202.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1994-03-11-202) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1994-03-11-202.md) |
| [Forskrift om gjerde ved offentlig veg](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1969-10-09-3815.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1969-10-09-3815) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1969-10-09-3815.md) |
| [Forskrift om godkjenning av bil og tilhenger til bil (bilforskriften)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2022-06-28-1233.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-06-28-1233) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-06-28-1233.md) |
| [Forskrift om godkjenning av moped og motorsykkel (motorsykkelforskriften)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2016-06-01-560.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2016-06-01-560) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2016-06-01-560.md) |
| [Forskrift om godkjenning av traktor og tilhenger til traktor (traktorforskriften](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2016-06-01-561.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2016-06-01-561) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2016-06-01-561.md) |
| [Forskrift om godkjenning og registrering av amatørbygde kjøretøy](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2013-10-10-1217.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-10-10-1217) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-10-10-1217.md) |
| [Forskrift om godkjenning og registrering av utrykningskjøretøy](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2002-01-18-55.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2002-01-18-55) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2002-01-18-55.md) |
| [Forskrift om grunnutdanning og etterutdanning for yrkessjåfører (yrkessjåførfors](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2008-04-16-362.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2008-04-16-362) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2008-04-16-362.md) |
| [Forskrift om hastighetsgrenser ved prøving av bremser.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1976-11-15-2.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1976-11-15-2) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1976-11-15-2.md) |
| [Forskrift om helikopter offshoreoperasjoner](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2018-06-20-923.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2018-06-20-923) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2018-06-20-923.md) |
| [Forskrift om helsekrav for operativt personell på jernbane og signaler på tog](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2019-06-12-721.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-06-12-721) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-06-12-721.md) |
| [Forskrift om hvem som er luftfartsmyndighet etter luftfartsloven.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1999-12-10-1272.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1999-12-10-1272) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1999-12-10-1272.md) |
| [Forskrift om informasjonssikkerhet i sivil luftfart](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-10-24-2093.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-10-24-2093) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-10-24-2093.md) |
| [Forskrift om infrastruktur for alternativt drivstoff](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-09-07-2692.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-09-07-2692) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-09-07-2692.md) |
| [Forskrift om innkreving av bompenger fra tunge godskjøretøy med tillatt totalvek](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2013-06-14-614.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-06-14-614) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-06-14-614.md) |
| [Forskrift om innskrenkning av COTIF-lovens virkeområde.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2007-06-08-588.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2007-06-08-588) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2007-06-08-588.md) |
| [Forskrift om inspeksjoner på bakken av luftfartøy](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2007-10-05-1112.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2007-10-05-1112) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2007-10-05-1112.md) |
| [Forskrift om internkontroll i drosjenæringen](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2026-05-04-715.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2026-05-04-715) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2026-05-04-715.md) |
| [Forskrift om jernbanepassasjerers rettigheter og forpliktelser (jernbanepassasje](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2023-05-11-692.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-05-11-692) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-05-11-692.md) |
| [Forskrift om jernbanevirksomhet, serviceanlegg, avgifter og fordeling av infrast](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-06-30-2315.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-06-30-2315) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-06-30-2315.md) |
| [Forskrift om kjøre- og hviletid og fartsskriver for vegtransport i EØS](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2007-07-02-877.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2007-07-02-877) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2007-07-02-877.md) |
| [Forskrift om kjørende og gående trafikk (trafikkregler)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1986-03-21-747.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1986-03-21-747) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1986-03-21-747.md) |
| [Forskrift om kjøring med motorvogn i terrenget og på veg ikke åpen for alminneli](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2001-12-14-1412.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2001-12-14-1412) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2001-12-14-1412.md) |
| [Forskrift om kjøring på lukket bane eller annet avsperret område og om annen bru](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-06-18-2127.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-06-18-2127) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-06-18-2127.md) |
| [Forskrift om klagenemnd for passasjertransport (transportklagenemndforskriften)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2012-01-20-84.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2012-01-20-84) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2012-01-20-84.md) |
| [Forskrift om konkurransekjøring med motorvogn på veg åpen for alminnelig ferdsel](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2011-04-07-395.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2011-04-07-395) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2011-04-07-395.md) |
| [Forskrift om konsesjon for landingsplasser (BSL E 1-1).](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2007-01-11-40.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2007-01-11-40) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2007-01-11-40.md) |
| [Forskrift om kontinuerlig luftdyktighet for nasjonalt sertifiserte luftfartøy](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-06-25-2247.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-06-25-2247) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-06-25-2247.md) |
| [Forskrift om kontinuerlig luftdyktighet for sertifiserte ubemannede luftfartøysy](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-06-27-1359.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-06-27-1359) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-06-27-1359.md) |
| [Forskrift om kontinuerlig luftdyktighet mv. (vedlikeholdsforskriften)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2015-05-07-488.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-05-07-488) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-05-07-488.md) |
| [Forskrift om kontroll av kjøretøy langs veg](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2017-10-13-1615.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-10-13-1615) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-10-13-1615.md) |
| [Forskrift om kontrollantvirksomheten i norsk sivil luftfart (kontrollantforskrif](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2003-12-10-1745.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2003-12-10-1745) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2003-12-10-1745.md) |
| [Forskrift om krav til CO2-utslipp mv. for produsenter av person- og varebiler og](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2018-12-28-2247.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2018-12-28-2247) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2018-12-28-2247.md) |
| [Forskrift om krav til ballongførere](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2015-06-16-658.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-06-16-658) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-06-16-658.md) |
| [Forskrift om krav til bruk av elektronisk brikke i motorvogner over 3 500 kg](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2014-10-10-1276.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2014-10-10-1276) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2014-10-10-1276.md) |
| [Forskrift om krav til førerprøvesensorer m.m. (sensorforskriften)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2011-03-09-261.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2011-03-09-261) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2011-03-09-261.md) |
| [Forskrift om krav til godkjenning av utstyr til bruk i flysikringstjenestene, og](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2024-09-02-2066.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-09-02-2066) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-09-02-2066.md) |
| [Forskrift om krav til kjøretøy.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1990-01-25-91.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1990-01-25-91) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1990-01-25-91.md) |
| [Forskrift om krav til liten elektrisk motorvogn](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2022-05-25-918.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-05-25-918) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-05-25-918.md) |
| [Forskrift om krav til lufttrafikktjenester og ytere av lufttrafikkstyrings- og f](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2022-06-16-1029.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-06-16-1029) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-06-16-1029.md) |
| [Forskrift om krav til museumsbane (museumsbaneforskriften)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2014-12-10-1574.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2014-12-10-1574) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2014-12-10-1574.md) |
| [Forskrift om krav til nullutslipp av klimagasser ved offentlig anskaffelse av sj](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2024-11-13-3329.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-11-13-3329) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-11-13-3329.md) |
| [Forskrift om krav til og bruk av utstyr i luftfartøyer i Det felles europeiske l](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2024-09-02-2076.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-09-02-2076) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-09-02-2076.md) |
| [Forskrift om krav til opplæring, prøve og kompetanse for utrykningskjøring (utry](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2009-06-12-637.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2009-06-12-637) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2009-06-12-637.md) |
| [Forskrift om krav til privat sidespor og godsbane (sidesporforskriften)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2014-12-10-1573.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2014-12-10-1573) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2014-12-10-1573.md) |
| [Forskrift om krav til seilflygere](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2015-06-16-657.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-06-16-657) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-06-16-657.md) |
| [Forskrift om krav til sporvei, tunnelbane, forstadsbane m.m. (kravforskriften)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2014-12-10-1572.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2014-12-10-1572) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2014-12-10-1572.md) |
| [Forskrift om krav til sykkel](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1990-02-19-119.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1990-02-19-119) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1990-02-19-119.md) |
| [Forskrift om krav til teknisk/operativ godkjenning av flyplasser](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2001-10-30-1231.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2001-10-30-1231) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2001-10-30-1231.md) |
| [Forskrift om krav til utdanning, etterutdanning og godkjenning av trafikklærere ](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2024-10-15-2556.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-10-15-2556) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-10-15-2556.md) |
| [Forskrift om krav til ytelsesbasert navigasjon for ytere av lufttrafikkstyrings-](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2013-06-06-583.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-06-06-583) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-06-06-583.md) |
| [Forskrift om lavutslippssoner for biler](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2016-12-20-1681.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2016-12-20-1681) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2016-12-20-1681.md) |
| [Forskrift om luftdyktighets- og miljøsertifisering for luftfartøyer mv. og serti](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2013-03-04-252.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-03-04-252) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-03-04-252.md) |
| [Forskrift om luftfart med ballong](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2018-06-07-836.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2018-06-07-836) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2018-06-07-836.md) |
| [Forskrift om luftfart med helikopter – bruk av offshore helikopterdekk](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2019-05-14-604.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-05-14-604) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-05-14-604.md) |
| [Forskrift om luftfart med seilfly](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2019-05-15-663.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-05-15-663) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-05-15-663.md) |
| [Forskrift om luftfart på Jan Mayen.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1973-11-23-3460.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1973-11-23-3460) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1973-11-23-3460.md) |
| [Forskrift om luftfart på Svalbard](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1973-11-23-3427.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1973-11-23-3427) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1973-11-23-3427.md) |
| [Forskrift om luftfartsoperasjoner](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2013-08-07-956.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-08-07-956) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-08-07-956.md) |
| [Forskrift om luftfartsoperasjoner med nasjonalt sertifiserte luftfartøy](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-02-15-524.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-02-15-524) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-02-15-524.md) |
| [Forskrift om luftfartøy som ikke har fører om bord mv.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2015-11-30-1404.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-11-30-1404) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-11-30-1404.md) |
| [Forskrift om lufthavnrelaterte tjenester.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2000-11-03-1096.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2000-11-03-1096) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2000-11-03-1096.md) |
| [Forskrift om luftromsorganisering](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-12-14-3530.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-12-14-3530) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-12-14-3530.md) |
| [Forskrift om lufttrafikkregler og operative prosedyrer](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2016-12-14-1578.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2016-12-14-1578) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2016-12-14-1578.md) |
| [Forskrift om lufttransporttjenester i EØS](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2011-08-12-833.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2011-08-12-833) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2011-08-12-833.md) |
| [Forskrift om maksimalt overtredelsesgebyr etter luftfartsloven § 13a-5](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2024-02-15-264.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-02-15-264) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-02-15-264.md) |
| [Forskrift om medisinske krav for AFIS- og HFIS-fullmektig/operatør (BSL G 2-5).](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2002-06-18-701.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2002-06-18-701) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2002-06-18-701.md) |
| [Forskrift om medisinske krav for seilflygere, mikroflygere, førere av friballong](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2001-08-23-1068.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2001-08-23-1068) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2001-08-23-1068.md) |
| [Forskrift om medisinske undersøkelser av seilflygere, mikroflygere, førere av fr](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2001-08-23-1067.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2001-08-23-1067) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2001-08-23-1067.md) |
| [Forskrift om meldermyndighet og samsvarsvurderingsorganer for jernbanen](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-09-08-2705.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-09-08-2705) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-09-08-2705.md) |
| [Forskrift om merking av dekk vedrørende drivstoffeffektivitet m.m. (dekkmerkefor](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2012-12-17-1325.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2012-12-17-1325) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2012-12-17-1325.md) |
| [Forskrift om merking av og etablering av sikkerhetssoner tilknyttet innretning f](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2016-09-15-1066.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2016-09-15-1066) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2016-09-15-1066.md) |
| [Forskrift om midlertidige tiltak for yrkessjåførbevis utstedt av Ukraina](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2024-01-22-100.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-01-22-100) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-01-22-100.md) |
| [Forskrift om miljøkrav for sivile luftfartøyer](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1991-05-31-349.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1991-05-31-349) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1991-05-31-349.md) |
| [Forskrift om minimum sikkerhetskrav til visse tunneler på fylkesvegnettet og kom](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2014-12-10-1566.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2014-12-10-1566) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2014-12-10-1566.md) |
| [Forskrift om minimum sikkerhetskrav til visse vegtunneler (tunnelsikkerhetsforsk](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2007-05-15-517.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2007-05-15-517) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2007-05-15-517.md) |
| [Forskrift om minstestørrelser på forsikringssummer for passasjer- og tredjemanns](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2004-07-06-1101.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2004-07-06-1101) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2004-07-06-1101.md) |
| [Forskrift om modulvogntog på riks-, fylkes- og kommunale veger (veglister modulv](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2023-10-24-1696.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-10-24-1696) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-10-24-1696.md) |
| [Forskrift om motorhistoriske kjøretøyers bruk av lys om dagen.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1991-05-10-300.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1991-05-10-300) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1991-05-10-300.md) |
| [Forskrift om motorseilfly (BSL D 4-6)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1983-10-05-4605.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1983-10-05-4605) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1983-10-05-4605.md) |
| [Forskrift om multimodale reiseinformasjonstjenester](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-03-19-987.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-03-19-987) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-03-19-987.md) |
| [Forskrift om nasjonal beredskap på jernbane](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2022-01-20-102.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-01-20-102) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-01-20-102.md) |
| [Forskrift om nasjonal sertifisering av luftfartøy](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-06-25-2246.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-06-25-2246) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-06-25-2246.md) |
| [Forskrift om nasjonale tekniske krav m.m. for jernbaneinfrastruktur på det nasjo](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2011-04-11-388.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2011-04-11-388) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2011-04-11-388.md) |
| [Forskrift om nasjonale tekniske krav til jernbanekjøretøy (jernbanekjøretøyforsk](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2022-05-25-943.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-05-25-943) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-05-25-943.md) |
| [Forskrift om nasjonalitets- og registreringsmerking av luftfartøy (BSL A 1-8).](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2002-11-23-1332.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2002-11-23-1332) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2002-11-23-1332.md) |
| [Forskrift om nasjonalitetsmerke på utenlandske kjøretøyer i Norge.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1999-09-16-1076.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1999-09-16-1076) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1999-09-16-1076.md) |
| [Forskrift om normaltransport på riks-, fylkes- og kommunale veger (veglister nor](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2023-10-24-1694.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-10-24-1694) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-10-24-1694.md) |
| [Forskrift om offentlig parkeringsgebyr](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2016-03-18-261.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2016-03-18-261) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2016-03-18-261.md) |
| [Forskrift om offentlige trafikkskilt, vegoppmerking, trafikklyssignaler og anvis](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2005-10-07-1219.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2005-10-07-1219) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2005-10-07-1219.md) |
| [Forskrift om offentlige undersøkelser av jernbaneulykker og alvorlige jernbanehe](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2006-03-31-378.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2006-03-31-378) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2006-03-31-378.md) |
| [Forskrift om offentlige undersøkelser av luftfartsulykker og luftfartshendelser ](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2016-07-07-906.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2016-07-07-906) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2016-07-07-906.md) |
| [Forskrift om offentlige undersøkelser og om varsling av trafikkulykker mv.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2005-06-30-793.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2005-06-30-793) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2005-06-30-793.md) |
| [Forskrift om opplæring av personell med arbeidsoppgaver av betydning for trafikk](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2002-12-18-1679.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2002-12-18-1679) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2002-12-18-1679.md) |
| [Forskrift om opplæring i periodisk kontroll av kjøretøy (kontrollopplæringsforsk](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2018-05-22-741.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2018-05-22-741) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2018-05-22-741.md) |
| [Forskrift om opprettelse av et permanent restriksjonsområde i luftrommet over Ol](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2026-01-16-55.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2026-01-16-55) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2026-01-16-55.md) |
| [Forskrift om opprettelse av permanente restriksjonsområder over åtte fengsler](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2018-12-05-1807.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2018-12-05-1807) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2018-12-05-1807.md) |
| [Forskrift om overgangsbestemmelser i medhold av lov om havner og farvann](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1984-09-21-1672.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1984-09-21-1672) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1984-09-21-1672.md) |
| [Forskrift om overgangsregler for vegtransporttjenester mellom EØS og Det forente](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2019-10-24-1406.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-10-24-1406) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-10-24-1406.md) |
| [Forskrift om parkeringstillatelse for forflytningshemmede](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2016-03-18-264.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2016-03-18-264) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2016-03-18-264.md) |
| [Forskrift om periodisk kontroll av kjøretøy](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2009-05-13-591.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2009-05-13-591) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2009-05-13-591.md) |
| [Forskrift om persontransport med motorvogn mot vederlag innenfor Longyearbyen.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1991-05-28-343.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1991-05-28-343) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1991-05-28-343.md) |
| [Forskrift om persontransport med motorvogn mot vederlag på Svalbard.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1984-03-30-819.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1984-03-30-819) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1984-03-30-819.md) |
| [Forskrift om plassering av skogsvirke ved riksveg](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1966-11-04-4011.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1966-11-04-4011) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1966-11-04-4011.md) |
| [Forskrift om plasstjeneste (BSL E 4-2)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2004-04-27-670.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2004-04-27-670) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2004-04-27-670.md) |
| [Forskrift om post (postforskriften)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2015-09-18-1063.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-09-18-1063) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-09-18-1063.md) |
| [Forskrift om prikkbelastning](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2003-09-19-1164.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2003-09-19-1164) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2003-09-19-1164.md) |
| [Forskrift om prissammenlikning på drivstoff og elektrisitet på energistasjoner](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2022-03-15-422.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-03-15-422) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-03-15-422.md) |
| [Forskrift om radiotelefoniprosedyrer](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2011-07-01-733.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2011-07-01-733) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2011-07-01-733.md) |
| [Forskrift om rapportering, registrering og merking av luftfartshinder](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2014-07-15-980.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2014-07-15-980) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2014-07-15-980.md) |
| [Forskrift om rapporterings- og varslingsplikt ved luftfartsulykker og luftfartsh](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2016-07-01-868.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2016-07-01-868) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2016-07-01-868.md) |
| [Forskrift om referansedokument for krav til kjøretøy på det nasjonale jernbanene](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2011-12-05-1188.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2011-12-05-1188) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2011-12-05-1188.md) |
| [Forskrift om register over typegodkjente jernbanekjøretøy (ERATV-forskriften)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2013-02-04-138.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-02-04-138) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-02-04-138.md) |
| [Forskrift om registrering av luftfartøy m.m.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2004-02-05-393.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2004-02-05-393) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2004-02-05-393.md) |
| [Forskrift om reserverte områder for fleksibel bruk av luftrommet](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2024-09-10-2145.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-09-10-2145) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-09-10-2145.md) |
| [Forskrift om saksbehandling og ansvar ved legging og flytting av ledninger over,](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2013-10-08-1212.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-10-08-1212) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-10-08-1212.md) |
| [Forskrift om saksbehandlingsgebyr for Statens jernbanetilsyn](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-03-14-531.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-03-14-531) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-03-14-531.md) |
| [Forskrift om samtrafikkevnen i jernbanesystemet (samtrafikkforskriften)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-09-09-2742.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-09-09-2742) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-09-09-2742.md) |
| [Forskrift om selvbygde luftfartøy (selvbyggerforskriften), (BSL B 3-1)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2007-06-26-721.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2007-06-26-721) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2007-06-26-721.md) |
| [Forskrift om sertifisering av besetningsmedlemmer](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2015-11-28-1365.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-11-28-1365) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-11-28-1365.md) |
| [Forskrift om sertifisering av flyplasser mv.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2015-08-25-1000.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-08-25-1000) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-08-25-1000.md) |
| [Forskrift om sertifisering av førere av trekkraftkjøretøy på det nasjonale jernb](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2009-11-27-1414.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2009-11-27-1414) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2009-11-27-1414.md) |
| [Forskrift om sikkerhet og tekniske forhold ved jernbanen](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-09-03-2675.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-09-03-2675) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-09-03-2675.md) |
| [Forskrift om sikkerhet på jernbanenettet (sikkerhetsforskriften)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-09-08-2740.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-09-08-2740) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-09-08-2740.md) |
| [Forskrift om sikkerhetsforvaltning av veginfrastrukturen (vegsikkerhetsforskrift](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2011-10-28-1053.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2011-10-28-1053) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2011-10-28-1053.md) |
| [Forskrift om sikring av skyssberettigede skoleelever i buss](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2012-12-19-1342.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2012-12-19-1342) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2012-12-19-1342.md) |
| [Forskrift om sikring på jernbane (sikringsforskriften)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2022-01-19-100.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-01-19-100) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-01-19-100.md) |
| [Forskrift om sivil fallskjermhopping (BSL D 4-2).](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2006-01-12-42.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2006-01-12-42) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2006-01-12-42.md) |
| [Forskrift om sivil statsluftfart med offentligrettslig formål mv.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2020-05-26-1076.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-05-26-1076) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-05-26-1076.md) |
| [Forskrift om sivil statsluftfart med ubemannet luftfartøy mv.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2026-01-15-48.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2026-01-15-48) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2026-01-15-48.md) |
| [Forskrift om soloflygingsbevis.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1994-11-14-1280.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1994-11-14-1280) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1994-11-14-1280.md) |
| [Forskrift om spesialtransport på riks-, fylkes- og kommunale veger (veglister sp](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2023-10-24-1697.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-10-24-1697) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-10-24-1697.md) |
| [Forskrift om sportsflyging (BSL D 4-8)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2024-03-21-498.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-03-21-498) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-03-21-498.md) |
| [Forskrift om standarder, fravik, kontroll, godkjenning m.m. ved prosjektering, b](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2014-09-02-1128.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2014-09-02-1128) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2014-09-02-1128.md) |
| [Forskrift om støyemisjon fra luftfartøy](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2008-02-01-102.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2008-02-01-102) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2008-02-01-102.md) |
| [Forskrift om støyrelaterte driftsbegrensninger ved norske flyplasser](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2015-10-01-1168.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-10-01-1168) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-10-01-1168.md) |
| [Forskrift om sykkelritt på veg (sykkelrittforskriften)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2026-01-27-93.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2026-01-27-93) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2026-01-27-93.md) |
| [Forskrift om taubaner (taubaneforskriften)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2022-12-20-2383.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-12-20-2383) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-12-20-2383.md) |
| [Forskrift om tekniske krav og godkjenning av kjøretøy, deler og utstyr (kjøretøy](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1994-10-04-918.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1994-10-04-918) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1994-10-04-918.md) |
| [Forskrift om telematikkapplikasjoner for jernbanetransport i EØS (TSI TEL-forskr](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2026-05-04-697.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2026-05-04-697) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2026-05-04-697.md) |
| [Forskrift om tilgjengeliggjøring av sanntids veg- og trafikkinformasjonstjeneste](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2016-12-15-1600.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2016-12-15-1600) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2016-12-15-1600.md) |
| [Forskrift om tillatelse til å drive trafikkvirksomhet og infrastruktur for sporv](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2010-12-10-1569.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2010-12-10-1569) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2010-12-10-1569.md) |
| [Forskrift om tilleggskrav for ervervsmessige luftfartsoperasjoner på kortbaneluf](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2018-09-17-1339.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2018-09-17-1339) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2018-09-17-1339.md) |
| [Forskrift om tilleggskrav for luftfartsoperasjoner på Svalbard og i andre polare](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-08-17-2515.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-08-17-2515) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-08-17-2515.md) |
| [Forskrift om tilskudd til kulturminner i jernbanesektoren](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-04-20-1210.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-04-20-1210) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-04-20-1210.md) |
| [Forskrift om tiltak for et bærekraftig jernbanemarked i forbindelse med covid-19](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-09-24-2825.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-09-24-2825) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-09-24-2825.md) |
| [Forskrift om trafikkflytstyring](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2012-04-20-344.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2012-04-20-344) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2012-04-20-344.md) |
| [Forskrift om trafikkopplæring og førerprøve m.m. (trafikkopplæringsforskriften)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2004-10-01-1339.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2004-10-01-1339) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2004-10-01-1339.md) |
| [Forskrift om trafikktrygd m.v.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1974-04-01-3.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1974-04-01-3) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1974-04-01-3.md) |
| [Forskrift om transport av gods i luftfartøy (BSL D 1-7).](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2003-01-11-41.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2003-01-11-41) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2003-01-11-41.md) |
| [Forskrift om transport med ferje](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2003-03-26-403.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2003-03-26-403) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2003-03-26-403.md) |
| [Forskrift om treningsstandard for personell som attesterer for komponentvedlikeh](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2011-03-15-290.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2011-03-15-290) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2011-03-15-290.md) |
| [Forskrift om tømmertransport på riks-, fylkes- og kommunale veger (veglister tøm](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2023-10-24-1695.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-10-24-1695) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-10-24-1695.md) |
| [Forskrift om ubemannede luftfartøyer (BSL A 7-2)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2024-11-01-2777.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-11-01-2777) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-11-01-2777.md) |
| [Forskrift om universell utforming av lufthavner, og om funksjonshemmedes og beve](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2013-07-16-919.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-07-16-919) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-07-16-919.md) |
| [Forskrift om universell utforming av motorvogn i løyvepliktig transport mv.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2009-12-03-1438.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2009-12-03-1438) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2009-12-03-1438.md) |
| [Forskrift om unntak fra forsikringsplikt](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2014-06-13-725.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2014-06-13-725) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2014-06-13-725.md) |
| [Forskrift om utdanning og sertifisering av flygeledere](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2016-06-17-710.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2016-06-17-710) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2016-06-17-710.md) |
| [Forskrift om utdanningsorganisasjoner for flygeinformasjonstjenestepersonell](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2003-10-25-1302.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2003-10-25-1302) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2003-10-25-1302.md) |
| [Forskrift om utforming av sjøflyplasser (BSL E 3-4).](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2002-12-03-1383.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2002-12-03-1383) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2002-12-03-1383.md) |
| [Forskrift om utforming av små flyplasser (BSL E 3-3).](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2002-12-03-1382.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2002-12-03-1382) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2002-12-03-1382.md) |
| [Forskrift om utforming av små helikopterplasser (BSL E 3-6)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2004-04-16-629.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2004-04-16-629) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2004-04-16-629.md) |
| [Forskrift om utforming av store flyplasser (BSL E 3-2)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2006-07-06-968.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2006-07-06-968) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2006-07-06-968.md) |
| [Forskrift om utforming av store helikopterplasser (BSL E 3-5).](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2005-04-29-418.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2005-04-29-418) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2005-04-29-418.md) |
| [Forskrift om utprøving av selvkjørende motorvogn](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2017-12-19-2240.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-12-19-2240) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-12-19-2240.md) |
| [Forskrift om utsatte frister på transportområdet knyttet til covid-19](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2020-06-18-1227.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-06-18-1227) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-06-18-1227.md) |
| [Forskrift om utslippskrav til kjøretøy ved offentlig anskaffelse til veitranspor](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2022-12-20-2384.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-12-20-2384) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-12-20-2384.md) |
| [Forskrift om utstedelse, forlengelse og gjenutstedelse av rettigheter på klasse ](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1994-11-14-1298.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1994-11-14-1298) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1994-11-14-1298.md) |
| [Forskrift om utstedervirksomhet for bompenger og ferjebilletter (utstederforskri](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2018-12-14-1917.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2018-12-14-1917) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2018-12-14-1917.md) |
| [Forskrift om validerings- og kontrollflyorganisasjoner](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2015-10-27-1227.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-10-27-1227) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-10-27-1227.md) |
| [Forskrift om varsling av akutt forurensning eller fare for akutt forurensning.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1992-07-09-1269.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1992-07-09-1269) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1992-07-09-1269.md) |
| [Forskrift om varslings- og rapporteringsplikt i forbindelse med jernbaneulykker ](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2006-03-31-379.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2006-03-31-379) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2006-03-31-379.md) |
| [Forskrift om vegdata, trafikkinformasjon, trafikkberedskap og trafikkstyring m.m](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-02-28-375.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-02-28-375) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-02-28-375.md) |
| [Forskrift om vegtrafikkloven med forskrifters gyldighet på Jan Mayen.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1993-11-10-1019.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1993-11-10-1019) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1993-11-10-1019.md) |
| [Forskrift om vegtrafikkloven med forskrifters gyldighet på Svalbard](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1993-11-10-1018.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1993-11-10-1018) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1993-11-10-1018.md) |
| [Forskrift om vilkårsparkering for allmennheten og håndheving av private parkerin](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2016-03-18-260.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2016-03-18-260) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2016-03-18-260.md) |
| [Forskrift om virkeområdet til lov om utleie av små elektriske kjøretøy på offent](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2022-05-30-925.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-05-30-925) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-05-30-925.md) |
| [Forskrift om visse aspekter ved flysikkerheten i forbindelse med Storbritannias ](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2019-04-08-468.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-04-08-468) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-04-08-468.md) |
| [Forskrift om yrkestransport med motorvogn og fartøy (yrkestransportforskriften)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2003-03-26-401.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2003-03-26-401) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2003-03-26-401.md) |
| [Forskrift om ytterligere luftdyktighetsspesifikasjoner for luftfartsselskaper, P](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2015-06-18-719.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-06-18-719) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-06-18-719.md) |
| [Forskrifter om eigedomsinngrep etter veglova](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1981-09-11-8603.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1981-09-11-8603) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1981-09-11-8603.md) |
| [Forskrifter om kontroll av utenlandsk registrerte kjøretøyers transport i Norge.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1978-04-11-1.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1978-04-11-1) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1978-04-11-1.md) |
| [Forskrifter om trekking av uregistrerte belgiske, britiske og nederlandske semit](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1980-12-30-8608.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1980-12-30-8608) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1980-12-30-8608.md) |
| [Gebyrforskrift for fornøyelsesinnretninger](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2017-01-17-41.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-01-17-41) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-01-17-41.md) |
| [Gebyrforskrift for taubaner](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2017-01-13-37.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-01-13-37) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-01-13-37.md) |
| [Gebyrforskrift på seilfly- og ballongområdet](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-05-13-822.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-05-13-822) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-05-13-822.md) |
| [Operational Directive requiring the use of pressurized aircraft for air operator](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2016-05-24-512.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2016-05-24-512) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2016-05-24-512.md) |
| [Operational directive – operation to and from airfields north of 65° latitude – ](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2013-12-20-1648.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-12-20-1648) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-12-20-1648.md) |
| [Overenskomst 1985 mellom Danmark, Finland, Norge og Sverige om gjensidig godkjen](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1986-07-01-3055.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1986-07-01-3055) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1986-07-01-3055.md) |
| [Overgangsregler til lov av 4. november 1994 nr. 59 om endring i lov av 5. juni 1](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1994-11-18-1015.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1994-11-18-1015) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1994-11-18-1015.md) |
| [Regulations on observation flights conducted under the Treaty on Open Skies](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2017-12-20-2329.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-12-20-2329) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-12-20-2329.md) |
| [Tillatelse for Posten Norge BA til å utgi og godta bruk av frimerker og andre fr](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2001-08-31-1074.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2001-08-31-1074) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2001-08-31-1074.md) |
| [Utfyllende regler til § 1 og § 2 i lov av 4. juli 1952 nr 3.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1953-06-11-4014.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1953-06-11-4014) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1953-06-11-4014.md) |
