# Arbeids- og inkluderingsdepartementet

*325 forskrifter*

| Forskrift | Lovdata | Historikk |
|-----------|---------|-----------|
| [Forskrift for behandlingen av saker om krigsskader og krigsskadeerstatning i kom](/norwegian-laws/forskrifter/forskrift-1989-02-24-106.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1989-02-24-106) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1989-02-24-106.md) |
| [Forskrift for kullgruvene på Svalbard](/norwegian-laws/forskrifter/forskrift-1993-01-18-33.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1993-01-18-33) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1993-01-18-33.md) |
| [Forskrift om Arbeidsgiver- og arbeidstakerregisteret](/norwegian-laws/forskrifter/forskrift-2008-08-18-942.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2008-08-18-942) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2008-08-18-942.md) |
| [Forskrift om HMS-kort i virksomheter som transporterer andres varer med bil](/norwegian-laws/forskrifter/forskrift-2025-06-20-1152.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-06-20-1152) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-06-20-1152.md) |
| [Forskrift om HMS-kort på bygge- og anleggsplasser](/norwegian-laws/forskrifter/forskrift-2007-03-30-366.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2007-03-30-366) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2007-03-30-366.md) |
| [Forskrift om adgang til ved tariffavtale å fravike reglene om likebehandling ved](/norwegian-laws/forskrifter/forskrift-2015-07-06-874.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-07-06-874) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-07-06-874.md) |
| [Forskrift om adgang til å utbetale uredusert ytelse for visse persongrupper i in](/norwegian-laws/forskrifter/forskrift-2014-10-31-1375.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2014-10-31-1375) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2014-10-31-1375.md) |
| [Forskrift om administrasjon av pensjonstrygden for fiskere.](/norwegian-laws/forskrifter/forskrift-2002-03-01-215.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2002-03-01-215) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2002-03-01-215.md) |
| [Forskrift om administrative ordninger på arbeidsmiljølovens område (forskrift om](/norwegian-laws/forskrifter/forskrift-2011-12-06-1360.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2011-12-06-1360) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2011-12-06-1360.md) |
| [Forskrift om aktivitetshjelpemidler til personer over 26 år](/norwegian-laws/forskrifter/forskrift-2014-06-25-865.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2014-06-25-865) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2014-06-25-865.md) |
| [Forskrift om aldersgrenser for sykepleiere.](/norwegian-laws/forskrifter/forskrift-2000-01-05-4.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2000-01-05-4) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2000-01-05-4.md) |
| [Forskrift om alderspensjon i folketrygden](/norwegian-laws/forskrifter/forskrift-2009-12-22-1810.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2009-12-22-1810) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2009-12-22-1810.md) |
| [Forskrift om allmenngjøring av tariffavtale for jordbruks- og gartnerinæringene](/norwegian-laws/forskrifter/forskrift-2024-10-21-2533.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-10-21-2533) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-10-21-2533.md) |
| [Forskrift om anke til Trygderetten for medlemmer av kommunale pensjonsordninger ](/norwegian-laws/forskrifter/forskrift-2026-02-27-298.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2026-02-27-298) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2026-02-27-298.md) |
| [Forskrift om anvendelse av ferieloven på Svalbard](/norwegian-laws/forskrifter/forskrift-2021-11-26-3291.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-11-26-3291) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-11-26-3291.md) |
| [Forskrift om anvendelse av forholdstall når et medlem av Statens pensjonskasse o](/norwegian-laws/forskrifter/forskrift-2011-10-20-1039.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2011-10-20-1039) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2011-10-20-1039.md) |
| [Forskrift om arbeid i arbeidsgivers hjem og husholdning](/norwegian-laws/forskrifter/forskrift-2022-06-03-969.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-06-03-969) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-06-03-969.md) |
| [Forskrift om arbeid som utføres i arbeidstakers hjem](/norwegian-laws/forskrifter/forskrift-2002-07-05-715.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2002-07-05-715) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2002-07-05-715.md) |
| [Forskrift om arbeidervern og arbeidsmiljø m.v. for sivil luftfart.](/norwegian-laws/forskrifter/forskrift-1986-02-21-540.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1986-02-21-540) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1986-02-21-540.md) |
| [Forskrift om arbeidsavklaringspenger](/norwegian-laws/forskrifter/forskrift-2017-12-13-2100.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-12-13-2100) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-12-13-2100.md) |
| [Forskrift om arbeidsgivers innsyn i e-postkasse og annet elektronisk lagret mate](/norwegian-laws/forskrifter/forskrift-2018-07-02-1108.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2018-07-02-1108) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2018-07-02-1108.md) |
| [Forskrift om arbeidsgivers lønnsplikt under permittering, jf. lov om lønnsplikt ](/norwegian-laws/forskrifter/forskrift-2020-03-20-374.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-03-20-374) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-03-20-374.md) |
| [Forskrift om arbeidsmarkedstiltak (tiltaksforskriften)](/norwegian-laws/forskrifter/forskrift-2015-12-11-1598.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-12-11-1598) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-12-11-1598.md) |
| [Forskrift om arbeidsmiljølovens anvendelse for dykkeoperasjoner fra skip mv.](/norwegian-laws/forskrifter/forskrift-2024-04-11-607.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-04-11-607) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-04-11-607.md) |
| [Forskrift om arbeidsmiljølovens anvendelse for personer som ikke er arbeidstaker](/norwegian-laws/forskrifter/forskrift-2005-12-16-1568.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2005-12-16-1568) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2005-12-16-1568.md) |
| [Forskrift om arbeidstakernes rett til innflytelse i europeiske samvirkeforetak.](/norwegian-laws/forskrifter/forskrift-2006-11-03-1213.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2006-11-03-1213) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2006-11-03-1213.md) |
| [Forskrift om arbeidstakernes rett til innflytelse i europeiske selskaper](/norwegian-laws/forskrifter/forskrift-2005-04-01-273.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2005-04-01-273) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2005-04-01-273.md) |
| [Forskrift om arbeidstakernes rett til representasjon ved fusjon over landegrense](/norwegian-laws/forskrifter/forskrift-2008-01-09-50.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2008-01-09-50) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2008-01-09-50.md) |
| [Forskrift om arbeidstid for avlastere](/norwegian-laws/forskrifter/forskrift-2017-06-25-1052.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-06-25-1052) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-06-25-1052.md) |
| [Forskrift om arbeidstid i institusjoner som har medleverordninger](/norwegian-laws/forskrifter/forskrift-2005-06-24-686.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2005-06-24-686) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2005-06-24-686.md) |
| [Forskrift om arbeidstid mv. for arbeidstakere i grensekryssende jernbanetrafikk](/norwegian-laws/forskrifter/forskrift-2008-07-03-783.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2008-07-03-783) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2008-07-03-783.md) |
| [Forskrift om at saksopplysninger til Arbeids- og velferdsetaten skal gis elektro](/norwegian-laws/forskrifter/forskrift-2018-06-20-937.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2018-06-20-937) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2018-06-20-937.md) |
| [Forskrift om at visse vedtak kan ankes direkte inn for Trygderetten.](/norwegian-laws/forskrifter/forskrift-2006-06-30-743.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2006-06-30-743) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2006-06-30-743.md) |
| [Forskrift om avgifter til folketrygden for året 2026 for arbeidstakere utsendt t](/norwegian-laws/forskrifter/forskrift-2025-12-19-2786.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-12-19-2786) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-12-19-2786.md) |
| [Forskrift om avgifter til folketrygden for året 2026 for misjonærer mv. som er m](/norwegian-laws/forskrifter/forskrift-2025-12-19-2785.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-12-19-2785) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-12-19-2785.md) |
| [Forskrift om avkorting av samordningsfradrag for grunnpensjon og omstillingsstøn](/norwegian-laws/forskrifter/forskrift-1982-10-15-1515.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1982-10-15-1515) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1982-10-15-1515.md) |
| [Forskrift om avskrivning av statens krav etter lønnsgarantiordningen](/norwegian-laws/forskrifter/forskrift-1981-01-05-8825.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1981-01-05-8825) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1981-01-05-8825.md) |
| [Forskrift om avtalefestet pensjon for medlemmer av Statens pensjonskasse født i ](/norwegian-laws/forskrifter/forskrift-2024-12-13-3109.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-12-13-3109) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-12-13-3109.md) |
| [Forskrift om begrensning av fradrag for alderspensjon fra folketrygden i pensjon](/norwegian-laws/forskrifter/forskrift-1975-07-18-9410.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1975-07-18-9410) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1975-07-18-9410.md) |
| [Forskrift om behandling av tvister i arbeidsgiverperioden](/norwegian-laws/forskrifter/forskrift-1997-03-25-268.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1997-03-25-268) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1997-03-25-268.md) |
| [Forskrift om behovsprøvet gravferdsstønad](/norwegian-laws/forskrifter/forskrift-2002-12-12-1492.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2002-12-12-1492) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2002-12-12-1492.md) |
| [Forskrift om beregning av arbeidsavklaringspenger etter EØS-avtalen](/norwegian-laws/forskrifter/forskrift-2017-12-13-2099.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-12-13-2099) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-12-13-2099.md) |
| [Forskrift om beregning av arbeidsgiverandel m.m.](/norwegian-laws/forskrifter/forskrift-2009-12-22-1804.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2009-12-22-1804) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2009-12-22-1804.md) |
| [Forskrift om beregning av kapitalverdier av trygdeytelser.](/norwegian-laws/forskrifter/forskrift-1997-03-25-273.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1997-03-25-273) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1997-03-25-273.md) |
| [Forskrift om beregning av lønnsveksten som skal benyttes ved regulering av grunn](/norwegian-laws/forskrifter/forskrift-2011-05-06-465.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2011-05-06-465) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2011-05-06-465.md) |
| [Forskrift om beregning av sluttpoengtall etter samordningsloven § 23 nr. 2.](/norwegian-laws/forskrifter/forskrift-1991-12-23-895.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1991-12-23-895) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1991-12-23-895.md) |
| [Forskrift om beregning av tilleggspensjon ved yrkesskade.](/norwegian-laws/forskrifter/forskrift-1997-03-11-209.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1997-03-11-209) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1997-03-11-209.md) |
| [Forskrift om beregning av uførepensjon og godskriving av pensjonspoeng ved yrkes](/norwegian-laws/forskrifter/forskrift-1997-03-11-208.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1997-03-11-208) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1997-03-11-208.md) |
| [Forskrift om beregning av uføretrygd etter EØS-avtalen](/norwegian-laws/forskrifter/forskrift-2015-02-12-130.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-02-12-130) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-02-12-130.md) |
| [Forskrift om beregning av uføretrygd og pensjon mv. under opphold i institusjon](/norwegian-laws/forskrifter/forskrift-2014-10-31-1376.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2014-10-31-1376) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2014-10-31-1376.md) |
| [Forskrift om beregning og innbetaling av avgift på omsetning av fisk til pensjon](/norwegian-laws/forskrifter/forskrift-1958-01-31-9412.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1958-01-31-9412) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1958-01-31-9412.md) |
| [Forskrift om biocider (Biocidforskriften)](/norwegian-laws/forskrifter/forskrift-2017-04-18-480.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-04-18-480) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-04-18-480.md) |
| [Forskrift om bortfall av rett til dekning av utgifter til helsetjenester mv på g](/norwegian-laws/forskrifter/forskrift-1997-04-15-316.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1997-04-15-316) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1997-04-15-316.md) |
| [Forskrift om bruk av vilkår etter sosialtjenesteloven](/norwegian-laws/forskrifter/forskrift-2020-12-16-2938.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-12-16-2938) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-12-16-2938.md) |
| [Forskrift om dagpenger under arbeidsløshet](/norwegian-laws/forskrifter/forskrift-1998-09-16-890.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1998-09-16-890) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1998-09-16-890.md) |
| [Forskrift om de ansattes rett til representasjon i aksjeselskapers og allmennaks](/norwegian-laws/forskrifter/forskrift-2017-08-24-1277.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-08-24-1277) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-08-24-1277.md) |
| [Forskrift om de ansattes rett til representasjon i sparebankenes og forretningsb](/norwegian-laws/forskrifter/forskrift-1977-12-23-9386.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1977-12-23-9386) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1977-12-23-9386.md) |
| [Forskrift om de ansattes rett til representasjon i styrer i interkommunale selsk](/norwegian-laws/forskrifter/forskrift-2017-08-24-1280.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-08-24-1280) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-08-24-1280.md) |
| [Forskrift om de ansattes rett til representasjon i styret i statsforetak mv.](/norwegian-laws/forskrifter/forskrift-2026-03-20-449.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2026-03-20-449) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2026-03-20-449.md) |
| [Forskrift om dekning av utgifter til båretransport i Norge.](/norwegian-laws/forskrifter/forskrift-1997-03-11-216.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1997-03-11-216) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1997-03-11-216.md) |
| [Forskrift om delvis allmenngjøring av Industrioverenskomsten/VO-delen for skips-](/norwegian-laws/forskrifter/forskrift-2024-10-21-2535.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-10-21-2535) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-10-21-2535.md) |
| [Forskrift om delvis allmenngjøring av Landsoverenskomsten for elektrofagene](/norwegian-laws/forskrifter/forskrift-2024-10-21-2536.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-10-21-2536) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-10-21-2536.md) |
| [Forskrift om delvis allmenngjøring av biloverenskomsten](/norwegian-laws/forskrifter/forskrift-2026-04-13-592.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2026-04-13-592) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2026-04-13-592.md) |
| [Forskrift om delvis allmenngjøring av tariffavtale for byggeplasser i Norge](/norwegian-laws/forskrifter/forskrift-2024-10-21-2544.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-10-21-2544) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-10-21-2544.md) |
| [Forskrift om delvis allmenngjøring av tariffavtale for fiskeindustribedrifter](/norwegian-laws/forskrifter/forskrift-2024-10-21-2542.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-10-21-2542) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-10-21-2542.md) |
| [Forskrift om delvis allmenngjøring av tariffavtale for overnattings-, serverings](/norwegian-laws/forskrifter/forskrift-2024-10-21-2543.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-10-21-2543) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-10-21-2543.md) |
| [Forskrift om delvis allmenngjøring av tariffavtale for renholdsbedrifter](/norwegian-laws/forskrifter/forskrift-2024-10-21-2545.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-10-21-2545) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-10-21-2545.md) |
| [Forskrift om delvis allmenngjøring av tariffavtaler for godstransport på vei](/norwegian-laws/forskrifter/forskrift-2024-10-29-2601.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-10-29-2601) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-10-29-2601.md) |
| [Forskrift om delvis allmenngjøring av tariffavtaler for persontransport med turb](/norwegian-laws/forskrifter/forskrift-2024-10-21-2534.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-10-21-2534) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-10-21-2534.md) |
| [Forskrift om det generelle samordningssystemet (samordningsforskrift 1)](/norwegian-laws/forskrifter/forskrift-1966-12-31-4076.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1966-12-31-4076) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1966-12-31-4076.md) |
| [Forskrift om dispensasjon fra taushetsplikten i arbeids- og velferdsforvaltnings](/norwegian-laws/forskrifter/forskrift-2007-04-30-460.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2007-04-30-460) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2007-04-30-460.md) |
| [Forskrift om elektronisk kommunikasjon med Arbeids- og velferdsetaten](/norwegian-laws/forskrifter/forskrift-2009-10-02-1285.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2009-10-02-1285) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2009-10-02-1285.md) |
| [Forskrift om endring i forskrift om arbeidervern og arbeidsmiljø i petroleumsvir](/norwegian-laws/forskrifter/forskrift-1995-06-30-603.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1995-06-30-603) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1995-06-30-603.md) |
| [Forskrift om endring i forskrift om arbeidsmarkedstiltak](/norwegian-laws/forskrifter/forskrift-2007-12-21-1773.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2007-12-21-1773) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2007-12-21-1773.md) |
| [Forskrift om endring i forskrift om arbeidsmarkedstiltak (tiltaksforskriften)](/norwegian-laws/forskrifter/forskrift-2025-12-18-2918.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-12-18-2918) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-12-18-2918.md) |
| [Forskrift om endring i forskrift om reduksjon av uførepensjon fra lovfestet offe](/norwegian-laws/forskrifter/forskrift-2025-12-18-2692.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-12-18-2692) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-12-18-2692.md) |
| [Forskrift om enke- eller enkemannspensjon som er delt mellom gjenlevende ektefel](/norwegian-laws/forskrifter/forskrift-1966-12-31-4097.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1966-12-31-4097) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1966-12-31-4097.md) |
| [Forskrift om erverv og tap av norsk statsborgerskap (statsborgerforskriften)](/norwegian-laws/forskrifter/forskrift-2006-06-30-756.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2006-06-30-756) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2006-06-30-756.md) |
| [Forskrift om europeiske samarbeidsutvalg mv.](/norwegian-laws/forskrifter/forskrift-2000-07-28-797.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2000-07-28-797) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2000-07-28-797.md) |
| [Forskrift om faglig utvalg for førerhundspørsmål.](/norwegian-laws/forskrifter/forskrift-1997-04-15-322.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1997-04-15-322) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1997-04-15-322.md) |
| [Forskrift om fastsettelse av avgiftsgrunnlag og avgiftssatser i folketrygden for](/norwegian-laws/forskrifter/forskrift-2025-12-19-2784.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-12-19-2784) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-12-19-2784.md) |
| [Forskrift om fastsettelse av pensjonsgivende inntekt mv. for medlemmer med innte](/norwegian-laws/forskrifter/forskrift-2017-02-13-179.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-02-13-179) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-02-13-179.md) |
| [Forskrift om fastsetting av enke- og enkemannspensjon der en del av pensjonen sk](/norwegian-laws/forskrifter/forskrift-2010-07-06-1075.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2010-07-06-1075) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2010-07-06-1075.md) |
| [Forskrift om fastsetting av fradrag i tjenestepensjon fra Statens pensjonskasse,](/norwegian-laws/forskrifter/forskrift-1973-04-09-9549.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1973-04-09-9549) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1973-04-09-9549.md) |
| [Forskrift om fastsetting av pensjonsgivende inntekt for året før det året da et ](/norwegian-laws/forskrifter/forskrift-1997-03-11-202.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1997-03-11-202) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1997-03-11-202.md) |
| [Forskrift om flere tjenestepensjoner og grunnpensjon og omstillingsstønad fra fo](/norwegian-laws/forskrifter/forskrift-1966-12-31-4099.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1966-12-31-4099) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1966-12-31-4099.md) |
| [Forskrift om flere tjenestepensjoner, begrensning av fradraget (samordningsforsk](/norwegian-laws/forskrifter/forskrift-1974-03-15-4092.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1974-03-15-4092) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1974-03-15-4092.md) |
| [Forskrift om forbud mot oppankring og fiske med visse redskaper i Gullfaksområde](/norwegian-laws/forskrifter/forskrift-1988-04-22-308.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1988-04-22-308) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1988-04-22-308.md) |
| [Forskrift om forbud mot oppankring og fiske med visse redskaper rundt Snorre und](/norwegian-laws/forskrifter/forskrift-1989-06-23-413.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1989-06-23-413) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1989-06-23-413.md) |
| [Forskrift om forbud mot oppankring og fiske med visse redskaper rundt brønnramme](/norwegian-laws/forskrifter/forskrift-1990-06-29-487.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1990-06-29-487) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1990-06-29-487.md) |
| [Forskrift om forbud mot oppankring og mot fiske med visse redskaper i Gullfaksom](/norwegian-laws/forskrifter/forskrift-1987-02-13-76.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1987-02-13-76) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1987-02-13-76.md) |
| [Forskrift om forbud mot oppankring og mot fiske med visse redskaper i Statfjord-](/norwegian-laws/forskrifter/forskrift-1983-12-02-1706.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1983-12-02-1706) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1983-12-02-1706.md) |
| [Forskrift om forbud mot oppankring og mot fiske med visse redskaper i Statfjord-](/norwegian-laws/forskrifter/forskrift-1983-08-15-4326.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1983-08-15-4326) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1983-08-15-4326.md) |
| [Forskrift om forbud mot oppankring og mot fiske med visse redskaper i Statfjordo](/norwegian-laws/forskrifter/forskrift-1986-09-05-1802.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1986-09-05-1802) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1986-09-05-1802.md) |
| [Forskrift om forsikring for tillegg til sykepenger for frilansere](/norwegian-laws/forskrifter/forskrift-1997-03-25-262.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1997-03-25-262) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1997-03-25-262.md) |
| [Forskrift om forsikring for tillegg til sykepenger for selvstendig næringsdriven](/norwegian-laws/forskrifter/forskrift-1997-03-25-261.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1997-03-25-261) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1997-03-25-261.md) |
| [Forskrift om forsikring mot ansvar for sykepenger i arbeidsgiverperioden for små](/norwegian-laws/forskrifter/forskrift-1997-03-25-260.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1997-03-25-260) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1997-03-25-260.md) |
| [Forskrift om forsikringsbasert refusjon av trygdeutgifter ved yrkesskade og yrke](/norwegian-laws/forskrifter/forskrift-1997-03-25-270.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1997-03-25-270) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1997-03-25-270.md) |
| [Forskrift om forsøk med fireårig lønnstilskudd for unge](/norwegian-laws/forskrifter/forskrift-2026-02-04-163.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2026-02-04-163) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2026-02-04-163.md) |
| [Forskrift om forsøk med ungdomsprogram og ungdomsprogramytelse](/norwegian-laws/forskrifter/forskrift-2025-06-20-1182.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-06-20-1182) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-06-20-1182.md) |
| [Forskrift om forsøk med å gi kommunen ansvar for å arrangere tilrettelagt arbeid](/norwegian-laws/forskrifter/forskrift-2017-12-20-2308.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-12-20-2308) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-12-20-2308.md) |
| [Forskrift om forvaltningen av likviditetsfondet i Pensjonstrygden for fiskere](/norwegian-laws/forskrifter/forskrift-2000-11-10-1134.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2000-11-10-1134) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2000-11-10-1134.md) |
| [Forskrift om fri rørsle av arbeidstakarar innanfor EØS-området mv.](/norwegian-laws/forskrifter/forskrift-2021-02-19-475.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-02-19-475) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-02-19-475.md) |
| [Forskrift om frivillig yrkesskadetrygd for elever som ikke er obligatorisk yrkes](/norwegian-laws/forskrifter/forskrift-1997-03-25-267.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1997-03-25-267) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1997-03-25-267.md) |
| [Forskrift om frivillig yrkesskadetrygd for selvstendig næringsdrivende og frilan](/norwegian-laws/forskrifter/forskrift-1997-03-11-210.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1997-03-11-210) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1997-03-11-210.md) |
| [Forskrift om føring av statistikk over sykefravær og fravær ved barns sykdom.](/norwegian-laws/forskrifter/forskrift-1997-03-25-272.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1997-03-25-272) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1997-03-25-272.md) |
| [Forskrift om garantitillegg for å hindre nedgang i samlet pensjon etter samordni](/norwegian-laws/forskrifter/forskrift-1988-11-02-888.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1988-11-02-888) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1988-11-02-888.md) |
| [Forskrift om gjennomføring av bilaterale trygdeavtaler](/norwegian-laws/forskrifter/forskrift-2024-11-15-2778.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-11-15-2778) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-11-15-2778.md) |
| [Forskrift om gjennomføring av refusjonskrav ved utbetaling av pensjons- og trygd](/norwegian-laws/forskrifter/forskrift-2000-07-06-726.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2000-07-06-726) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2000-07-06-726.md) |
| [Forskrift om gjennomføring av samordningsloven § 7 nr. 1 i relasjon til lov om p](/norwegian-laws/forskrifter/forskrift-1958-10-15-8686.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1958-10-15-8686) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1958-10-15-8686.md) |
| [Forskrift om gjennomføringen av folketrygdloven § 22-18 og bidragsinnkrevingslov](/norwegian-laws/forskrifter/forskrift-1999-04-23-534.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1999-04-23-534) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1999-04-23-534.md) |
| [Forskrift om godskriving av pensjonspoeng (omsorgspoeng) for omsorgsarbeid for e](/norwegian-laws/forskrifter/forskrift-1997-03-11-204.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1997-03-11-204) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1997-03-11-204.md) |
| [Forskrift om godskriving av pensjonspoeng (omsorgspoeng) for personer som har om](/norwegian-laws/forskrifter/forskrift-1997-03-11-203.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1997-03-11-203) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1997-03-11-203.md) |
| [Forskrift om godskriving av pensjonspoeng for mottakere av avtalefestet pensjon ](/norwegian-laws/forskrifter/forskrift-2014-11-26-1465.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2014-11-26-1465) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2014-11-26-1465.md) |
| [Forskrift om gradering av pleiepenger](/norwegian-laws/forskrifter/forskrift-2017-09-14-1405.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-09-14-1405) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-09-14-1405.md) |
| [Forskrift om gravferdsstønad og stønad til båretransport for person som er plikt](/norwegian-laws/forskrifter/forskrift-2002-12-12-1493.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2002-12-12-1493) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2002-12-12-1493.md) |
| [Forskrift om grunnbeløp, reguleringsfaktorer, satser for minste pensjonsnivå og ](/norwegian-laws/forskrifter/forskrift-2025-05-23-837.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-05-23-837) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-05-23-837.md) |
| [Forskrift om helse og sikkerhet i eksplosjonsfarlige atmosfærer](/norwegian-laws/forskrifter/forskrift-2003-06-30-911.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2003-06-30-911) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2003-06-30-911.md) |
| [Forskrift om helse og sikkerhet i forbindelse med boringsrelatert utvinningsindu](/norwegian-laws/forskrifter/forskrift-1998-09-17-982.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1998-09-17-982) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1998-09-17-982.md) |
| [Forskrift om hjelpemiddelsentralenes virksomhet og ansvar](/norwegian-laws/forskrifter/forskrift-1997-04-15-323.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1997-04-15-323) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1997-04-15-323.md) |
| [Forskrift om hvordan retten til utsettelse av oppsigelser ved masseoppsigelser s](/norwegian-laws/forskrifter/forskrift-1994-09-19-897.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1994-09-19-897) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1994-09-19-897.md) |
| [Forskrift om individuell plan ved ytelse av velferdstjenester](/norwegian-laws/forskrifter/forskrift-2022-06-22-1110.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-06-22-1110) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-06-22-1110.md) |
| [Forskrift om informasjons- og påseplikt og innsynsrett](/norwegian-laws/forskrifter/forskrift-2008-02-22-166.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2008-02-22-166) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2008-02-22-166.md) |
| [Forskrift om innleie av avløser fra avløserlag](/norwegian-laws/forskrifter/forskrift-2025-07-01-1377.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-07-01-1377) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-07-01-1377.md) |
| [Forskrift om innleie fra bemanningsforetak](/norwegian-laws/forskrifter/forskrift-2013-01-11-33.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-01-11-33) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-01-11-33.md) |
| [Forskrift om internrevisjon i Arbeids- og velferdsetaten.](/norwegian-laws/forskrifter/forskrift-2006-06-30-745.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2006-06-30-745) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2006-06-30-745.md) |
| [Forskrift om kameraovervåking i virksomhet](/norwegian-laws/forskrifter/forskrift-2018-07-02-1107.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2018-07-02-1107) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2018-07-02-1107.md) |
| [Forskrift om klassifisering, merking og emballering av stoffer og stoffblandinge](/norwegian-laws/forskrifter/forskrift-2012-06-16-622.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2012-06-16-622) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2012-06-16-622.md) |
| [Forskrift om kombinasjon av avtalefestet pensjon for medlemmer av Statens pensjo](/norwegian-laws/forskrifter/forskrift-2010-11-30-1493.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2010-11-30-1493) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2010-11-30-1493.md) |
| [Forskrift om konstruksjon, utforming og fremstilling av arbeidsutstyr og kjemika](/norwegian-laws/forskrifter/forskrift-2011-12-06-1359.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2011-12-06-1359) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2011-12-06-1359.md) |
| [Forskrift om konstruksjon, utforming og produksjon av personlig verneutstyr (PVU](/norwegian-laws/forskrifter/forskrift-2018-06-22-1019.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2018-06-22-1019) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2018-06-22-1019.md) |
| [Forskrift om kontroll med retten til supplerande stønad.](/norwegian-laws/forskrifter/forskrift-2005-12-16-1513.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2005-12-16-1513) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2005-12-16-1513.md) |
| [Forskrift om kvalifiseringsprogram og kvalifiseringsstønad](/norwegian-laws/forskrifter/forskrift-2011-12-21-1471.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2011-12-21-1471) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2011-12-21-1471.md) |
| [Forskrift om levealdersjustering av alderspensjon når et medlem av Statens pensj](/norwegian-laws/forskrifter/forskrift-2010-11-30-1492.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2010-11-30-1492) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2010-11-30-1492.md) |
| [Forskrift om læreplan i norsk for voksne innvandrere](/norwegian-laws/forskrifter/forskrift-2021-06-20-2053.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-06-20-2053) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-06-20-2053.md) |
| [Forskrift om læreplan i norsk for voksne innvandrere nivå C1](/norwegian-laws/forskrifter/forskrift-2021-06-20-2086.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-06-20-2086) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-06-20-2086.md) |
| [Forskrift om læreplan i samfunnskunnskap for voksne innvandrere](/norwegian-laws/forskrifter/forskrift-2021-06-20-2054.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-06-20-2054) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-06-20-2054.md) |
| [Forskrift om lønn 1. og 17. mai.](/norwegian-laws/forskrifter/forskrift-1947-04-26-1.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1947-04-26-1) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1947-04-26-1.md) |
| [Forskrift om lønns- og arbeidsvilkår i offentlige kontrakter mv.](/norwegian-laws/forskrifter/forskrift-2008-02-08-112.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2008-02-08-112) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2008-02-08-112.md) |
| [Forskrift om lønnsplikt under permittering](/norwegian-laws/forskrifter/forskrift-2016-06-21-764.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2016-06-21-764) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2016-06-21-764.md) |
| [Forskrift om løsning av tvister mellom Arbeids- og velferdsetaten og kommunene e](/norwegian-laws/forskrifter/forskrift-2007-03-12-294.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2007-03-12-294) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2007-03-12-294.md) |
| [Forskrift om maskiner](/norwegian-laws/forskrifter/forskrift-2009-05-20-544.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2009-05-20-544) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2009-05-20-544.md) |
| [Forskrift om medlemskap i trygden under fengselsopphold mv.](/norwegian-laws/forskrifter/forskrift-2012-06-22-603.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2012-06-22-603) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2012-06-22-603.md) |
| [Forskrift om medlemspremie i pensjonstrygden for fiskere for 2026](/norwegian-laws/forskrifter/forskrift-2025-11-28-2354.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-11-28-2354) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-11-28-2354.md) |
| [Forskrift om mellombels område med forbod mot oppankring og fiske på Njordfeltet](/norwegian-laws/forskrifter/forskrift-1997-04-11-277.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1997-04-11-277) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1997-04-11-277.md) |
| [Forskrift om menerstatning ved yrkesskade.](/norwegian-laws/forskrifter/forskrift-1997-04-21-373.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1997-04-21-373) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1997-04-21-373.md) |
| [Forskrift om nemnd for behandling av klager på erstatning fra Arbeids- og velfer](/norwegian-laws/forskrifter/forskrift-2020-03-22-889.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-03-22-889) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-03-22-889.md) |
| [Forskrift om når økt tilleggspensjon på grunn av omsorgspoeng etter folketrygdlo](/norwegian-laws/forskrifter/forskrift-2004-12-21-1742.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2004-12-21-1742) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2004-12-21-1742.md) |
| [Forskrift om obligatorisk opplæring i sykmeldingsarbeid for leger](/norwegian-laws/forskrifter/forskrift-2012-12-07-1147.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2012-12-07-1147) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2012-12-07-1147.md) |
| [Forskrift om offentlig godkjenning av bemanningsforetak](/norwegian-laws/forskrifter/forskrift-2008-06-04-541.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2008-06-04-541) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2008-06-04-541.md) |
| [Forskrift om offentlig godkjenning av renholdsvirksomheter og om kjøp av renhold](/norwegian-laws/forskrifter/forskrift-2012-05-08-408.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2012-05-08-408) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2012-05-08-408.md) |
| [Forskrift om offentlig godkjenning av virksomheter som tilbyr bilpleie, hjulskif](/norwegian-laws/forskrifter/forskrift-2022-02-11-206.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-02-11-206) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-02-11-206.md) |
| [Forskrift om omregning av avtalefestet pensjon for medlemmer av Statens pensjons](/norwegian-laws/forskrifter/forskrift-2010-11-30-1494.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2010-11-30-1494) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2010-11-30-1494.md) |
| [Forskrift om omregning av uførepensjon til uføretrygd](/norwegian-laws/forskrifter/forskrift-2014-07-03-947.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2014-07-03-947) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2014-07-03-947.md) |
| [Forskrift om område med forbud mot oppankring og fiske på Balderfeltet.](/norwegian-laws/forskrifter/forskrift-1996-12-06-1128.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1996-12-06-1128) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1996-12-06-1128.md) |
| [Forskrift om område med forbud mot oppankring og fiske på Heidrunfeltet.](/norwegian-laws/forskrifter/forskrift-1995-07-13-646.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1995-07-13-646) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1995-07-13-646.md) |
| [Forskrift om område med forbud mot oppankring og fiske på Nornefeltet.](/norwegian-laws/forskrifter/forskrift-1995-04-21-378.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1995-04-21-378) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1995-04-21-378.md) |
| [Forskrift om område med forbud mot oppankring og fiske på Åsgard-feltet.](/norwegian-laws/forskrifter/forskrift-1996-03-29-310.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1996-03-29-310) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1996-03-29-310.md) |
| [Forskrift om område med forbud mot oppankring og fiske rundt Troll B-plattformen](/norwegian-laws/forskrifter/forskrift-1995-08-11-715.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1995-08-11-715) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1995-08-11-715.md) |
| [Forskrift om oppfølgingstiltak i Arbeids- og velferdsetatens egenregi](/norwegian-laws/forskrifter/forskrift-2023-06-20-1073.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-06-20-1073) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-06-20-1073.md) |
| [Forskrift om opptjening av pensjonsrettigheter i lovfestet offentlig tjenestepen](/norwegian-laws/forskrifter/forskrift-2015-06-19-710.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-06-19-710) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-06-19-710.md) |
| [Forskrift om organisering, ledelse og medvirkning](/norwegian-laws/forskrifter/forskrift-2011-12-06-1355.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2011-12-06-1355) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2011-12-06-1355.md) |
| [Forskrift om overgangsregler for beregning av redusert ytelse under opphold i in](/norwegian-laws/forskrifter/forskrift-2014-10-31-1377.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2014-10-31-1377) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2014-10-31-1377.md) |
| [Forskrift om overgangsregler for fastsettelse av høyeste pensjon i Statens pensj](/norwegian-laws/forskrifter/forskrift-2000-07-07-743.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2000-07-07-743) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2000-07-07-743.md) |
| [Forskrift om overgangsregler for personer som har rett til barnetillegg til ufør](/norwegian-laws/forskrifter/forskrift-2015-09-23-1095.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-09-23-1095) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-09-23-1095.md) |
| [Forskrift om overgangsregler for samordning av enkelte pensjoner fra tjenestepen](/norwegian-laws/forskrifter/forskrift-2014-07-03-948.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2014-07-03-948) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2014-07-03-948.md) |
| [Forskrift om overgangsregler for trygdekoordinering ved Storbritannias uttreden ](/norwegian-laws/forskrifter/forskrift-2019-04-10-476.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-04-10-476) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-04-10-476.md) |
| [Forskrift om overgangsregler for uførepensjon fra lovfestet offentlig tjenestepe](/norwegian-laws/forskrifter/forskrift-2014-07-03-949.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2014-07-03-949) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2014-07-03-949.md) |
| [Forskrift om overgangsregler i forbindelse med endringer i folketrygdloven kapit](/norwegian-laws/forskrifter/forskrift-2015-07-02-869.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-07-02-869) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-07-02-869.md) |
| [Forskrift om overgangsregler i forbindelse med endringer i folketrygdloven kapit](/norwegian-laws/forskrifter/forskrift-2022-12-21-2456.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-12-21-2456) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-12-21-2456.md) |
| [Forskrift om overgangsregler i forbindelse med endringer i folketrygdloven § 15-](/norwegian-laws/forskrifter/forskrift-2024-01-26-123.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-01-26-123) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-01-26-123.md) |
| [Forskrift om overgangsregler i forbindelse med ikrafttredelse av endring av folk](/norwegian-laws/forskrifter/forskrift-2023-12-21-2260.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-12-21-2260) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-12-21-2260.md) |
| [Forskrift om overgangsregler til lov 13. juni 1997 nr. 59 om endringer i lov 16.](/norwegian-laws/forskrifter/forskrift-1997-06-19-619.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1997-06-19-619) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1997-06-19-619.md) |
| [Forskrift om overtredelsesgebyr og tvangsmulkt etter folketrygdloven § 25-3 ved ](/norwegian-laws/forskrifter/forskrift-2014-07-10-968.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2014-07-10-968) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2014-07-10-968.md) |
| [Forskrift om pensjonsberegning, om tilståelse og beregning av barnetillegg og ba](/norwegian-laws/forskrifter/forskrift-1993-12-23-1251.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1993-12-23-1251) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1993-12-23-1251.md) |
| [Forskrift om pensjonsgrunnlag i Statens pensjonskasse ved midlertidig tjeneste i](/norwegian-laws/forskrifter/forskrift-1984-03-19-2319.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1984-03-19-2319) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1984-03-19-2319.md) |
| [Forskrift om pensjonsgrunnlag i pensjonsordning for apotekvirksomhet ved midlert](/norwegian-laws/forskrifter/forskrift-2017-12-20-2306.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-12-20-2306) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-12-20-2306.md) |
| [Forskrift om pensjonsordninger for folkevalgte i kommune eller fylkeskommune](/norwegian-laws/forskrifter/forskrift-1997-04-22-375.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1997-04-22-375) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1997-04-22-375.md) |
| [Forskrift om pensjonsordninger for kommunalt eller fylkeskommunalt ansatte](/norwegian-laws/forskrifter/forskrift-1997-04-22-374.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1997-04-22-374) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1997-04-22-374.md) |
| [Forskrift om personskadetrygd – garantiregler (samordningsforskrift 34)](/norwegian-laws/forskrifter/forskrift-1974-01-01-4107.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1974-01-01-4107) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1974-01-01-4107.md) |
| [Forskrift om pilotprosjekt med oppfølging av deltakere i varig tilrettelagt arbe](/norwegian-laws/forskrifter/forskrift-2024-07-02-1800.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-07-02-1800) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-07-02-1800.md) |
| [Forskrift om plikt til å utarbeide arbeidsreglement ved virksomheter innen hotel](/norwegian-laws/forskrifter/forskrift-1991-10-31-1014.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1991-10-31-1014) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1991-10-31-1014.md) |
| [Forskrift om politiattest i henhold til arbeidsmarkedsloven](/norwegian-laws/forskrifter/forskrift-2012-03-23-248.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2012-03-23-248) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2012-03-23-248.md) |
| [Forskrift om rammer for delegering mellom stat og kommune om oppgaveutførelsen i](/norwegian-laws/forskrifter/forskrift-2007-01-26-107.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2007-01-26-107) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2007-01-26-107.md) |
| [Forskrift om reduksjon av enke- eller enkemannspensjon fra en offentlig tjeneste](/norwegian-laws/forskrifter/forskrift-1978-09-05-4.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1978-09-05-4) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1978-09-05-4.md) |
| [Forskrift om reduksjon av tidligpensjon og livsvarig reduksjon av særalderspåsla](/norwegian-laws/forskrifter/forskrift-2025-10-23-2080.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-10-23-2080) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-10-23-2080.md) |
| [Forskrift om reduksjon av uførepensjon fra lovfestet offentlig tjenestepensjonso](/norwegian-laws/forskrifter/forskrift-2014-11-26-1467.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2014-11-26-1467) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2014-11-26-1467.md) |
| [Forskrift om redusert samordningsfradrag når pensjon til gjenlevende ektefelle f](/norwegian-laws/forskrifter/forskrift-1966-12-31-4095.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1966-12-31-4095) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1966-12-31-4095.md) |
| [Forskrift om registrering og utveksling av opplysninger (meldesystem) for å gjen](/norwegian-laws/forskrifter/forskrift-2000-07-06-727.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2000-07-06-727) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2000-07-06-727.md) |
| [Forskrift om registrering, vurdering, godkjenning og begrensning av kjemikalier ](/norwegian-laws/forskrifter/forskrift-2008-05-30-516.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2008-05-30-516) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2008-05-30-516.md) |
| [Forskrift om rentesats etter folketrygdloven § 22-17 første ledd](/norwegian-laws/forskrifter/forskrift-2009-12-14-1513.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2009-12-14-1513) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2009-12-14-1513.md) |
| [Forskrift om sammenlegging av tjenestetid for rett til pensjon (samordningsforsk](/norwegian-laws/forskrifter/forskrift-1958-11-25-4078.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1958-11-25-4078) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1958-11-25-4078.md) |
| [Forskrift om samordning av alders- og uførepensjon fra tjenestepensjonsordninger](/norwegian-laws/forskrifter/forskrift-1979-10-01-4084.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1979-10-01-4084) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1979-10-01-4084.md) |
| [Forskrift om samordning av alderspensjon fra offentlig tjenestepensjonsordning f](/norwegian-laws/forskrifter/forskrift-2010-10-12-1330.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2010-10-12-1330) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2010-10-12-1330.md) |
| [Forskrift om samordning av alderspensjon fra offentlig tjenestepensjonsordning m](/norwegian-laws/forskrifter/forskrift-2020-05-28-1084.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-05-28-1084) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-05-28-1084.md) |
| [Forskrift om samordning av alderspensjon før 67 år og enke- og enkemannspensjon ](/norwegian-laws/forskrifter/forskrift-2015-12-01-1374.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-12-01-1374) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-12-01-1374.md) |
| [Forskrift om samordning av alderspensjoner fra tjenestepensjonsordning etter sam](/norwegian-laws/forskrifter/forskrift-2011-10-20-1038.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2011-10-20-1038) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2011-10-20-1038.md) |
| [Forskrift om samordning av enke- eller enkemannspensjon fra tjenestepensjonsordn](/norwegian-laws/forskrifter/forskrift-1989-12-20-1268.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1989-12-20-1268) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1989-12-20-1268.md) |
| [Forskrift om samordning av enke- eller enkemannspensjon fra tjenestepensjonsordn](/norwegian-laws/forskrifter/forskrift-1992-09-04-663.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1992-09-04-663) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1992-09-04-663.md) |
| [Forskrift om samordning av enke- eller enkemannspensjon og uførepensjon fra fors](/norwegian-laws/forskrifter/forskrift-1968-04-01-4088.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1968-04-01-4088) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1968-04-01-4088.md) |
| [Forskrift om samordning av enke- og enkemannspensjon der en del av pensjonen ska](/norwegian-laws/forskrifter/forskrift-2010-07-06-1076.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2010-07-06-1076) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2010-07-06-1076.md) |
| [Forskrift om samordning av enke- og enkemannspensjon fra tjenestepensjonsordning](/norwegian-laws/forskrifter/forskrift-2015-01-22-50.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-01-22-50) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-01-22-50.md) |
| [Forskrift om samordning av fraskiltes enke- og enkemannspensjon fra tjenestepens](/norwegian-laws/forskrifter/forskrift-2015-01-22-51.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-01-22-51) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-01-22-51.md) |
| [Forskrift om samordning av offentlig og privat tjenestepensjon for opptjening fø](/norwegian-laws/forskrifter/forskrift-1979-10-01-4082.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1979-10-01-4082) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1979-10-01-4082.md) |
| [Forskrift om samordning av pensjon fra pensjonsordning for stortingsrepresentant](/norwegian-laws/forskrifter/forskrift-1996-07-01-683.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1996-07-01-683) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1996-07-01-683.md) |
| [Forskrift om samordning av pensjons- og trygdeytelser når en av pensjonene bereg](/norwegian-laws/forskrifter/forskrift-1989-01-03-3.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1989-01-03-3) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1989-01-03-3.md) |
| [Forskrift om samordning av personskadetrygd med ventetillegg fra folketrygden](/norwegian-laws/forskrifter/forskrift-1988-12-16-1133.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1988-12-16-1133) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1988-12-16-1133.md) |
| [Forskrift om samordning av tjenestepensjon med sjømannspensjon som er utløst med](/norwegian-laws/forskrifter/forskrift-1993-08-02-779.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1993-08-02-779) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1993-08-02-779.md) |
| [Forskrift om samordning av tjenestepensjon og pensjon fra personskadetrygd (samo](/norwegian-laws/forskrifter/forskrift-1966-12-31-4089.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1966-12-31-4089) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1966-12-31-4089.md) |
| [Forskrift om samordning når folketrygdens grunnpensjon, uføretrygd og omstilling](/norwegian-laws/forskrifter/forskrift-1966-12-31-4098.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1966-12-31-4098) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1966-12-31-4098.md) |
| [Forskrift om samordningsgaranti ved innføring av etterlattereformen i folketrygd](/norwegian-laws/forskrifter/forskrift-2023-12-20-2233.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-12-20-2233) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-12-20-2233.md) |
| [Forskrift om samordningslovens omfang (samordningsforskrift 2)](/norwegian-laws/forskrifter/forskrift-1958-08-30-4077.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1958-08-30-4077) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1958-08-30-4077.md) |
| [Forskrift om sektoravgift og refusjon av utgifter for tilsyn med ressursforvaltn](/norwegian-laws/forskrifter/forskrift-1997-06-27-652.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1997-06-27-652) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1997-06-27-652.md) |
| [Forskrift om sikkerhet, helse og arbeidsmiljø på bygge- eller anleggsplasser (by](/norwegian-laws/forskrifter/forskrift-2009-08-03-1028.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2009-08-03-1028) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2009-08-03-1028.md) |
| [Forskrift om sosiale tjenester for personer uten fast bopel i Norge](/norwegian-laws/forskrifter/forskrift-2011-12-16-1251.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2011-12-16-1251) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2011-12-16-1251.md) |
| [Forskrift om statsgaranti for lønnskrav ved konkurs m.v.](/norwegian-laws/forskrifter/forskrift-1998-10-28-999.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1998-10-28-999) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1998-10-28-999.md) |
| [Forskrift om styring og opplysningsplikt i petroleumsvirksomheten og på enkelte ](/norwegian-laws/forskrifter/forskrift-2010-04-29-611.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2010-04-29-611) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2010-04-29-611.md) |
| [Forskrift om stønad til arbeids- og utdanningsreiser](/norwegian-laws/forskrifter/forskrift-2014-05-16-648.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2014-05-16-648) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2014-05-16-648.md) |
| [Forskrift om stønad til briller til barn](/norwegian-laws/forskrifter/forskrift-2022-07-19-1364.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-07-19-1364) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-07-19-1364.md) |
| [Forskrift om stønad til dekning av utgifter til helsetjenester i utlandet.](/norwegian-laws/forskrifter/forskrift-1997-04-30-390.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1997-04-30-390) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1997-04-30-390.md) |
| [Forskrift om stønad til dekning av utgifter til ortopediske hjelpemidler til per](/norwegian-laws/forskrifter/forskrift-2024-08-06-1876.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-08-06-1876) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-08-06-1876.md) |
| [Forskrift om stønad til dekning av utgifter til ortopediske hjelpemidler, brystp](/norwegian-laws/forskrifter/forskrift-1997-04-18-336.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1997-04-18-336) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1997-04-18-336.md) |
| [Forskrift om stønad til enslig mor eller far etter folketrygdloven kapittel 15](/norwegian-laws/forskrifter/forskrift-2015-11-21-1341.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-11-21-1341) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-11-21-1341.md) |
| [Forskrift om stønad til hjelpemidler mv til bedring av funksjonsevnen i arbeidsl](/norwegian-laws/forskrifter/forskrift-1997-04-15-318.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1997-04-15-318) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1997-04-15-318.md) |
| [Forskrift om stønad til høreapparat og tinnitusmaskerer](/norwegian-laws/forskrifter/forskrift-1997-04-18-337.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1997-04-18-337) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1997-04-18-337.md) |
| [Forskrift om stønad til lese- og sekretærhjelp for blinde og svaksynte](/norwegian-laws/forskrifter/forskrift-1997-04-15-319.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1997-04-15-319) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1997-04-15-319.md) |
| [Forskrift om stønad til motorkjøretøy eller annet transportmiddel](/norwegian-laws/forskrifter/forskrift-2003-03-07-290.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2003-03-07-290) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2003-03-07-290.md) |
| [Forskrift om stønad til servicehund for personer med nedsatt funksjonsevne](/norwegian-laws/forskrifter/forskrift-2017-12-20-2305.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-12-20-2305) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-12-20-2305.md) |
| [Forskrift om stønad til tolke- og ledsagerhjelp for døvblinde](/norwegian-laws/forskrifter/forskrift-1997-04-15-321.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1997-04-15-321) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1997-04-15-321.md) |
| [Forskrift om stønad til tolkehjelp for hørselshemmede](/norwegian-laws/forskrifter/forskrift-1997-04-15-320.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1997-04-15-320) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1997-04-15-320.md) |
| [Forskrift om stønader til dekning av utgifter knyttet til å komme i eller å beho](/norwegian-laws/forskrifter/forskrift-2015-07-02-867.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-07-02-867) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-07-02-867.md) |
| [Forskrift om sykdommer og forgiftninger m.v. som skal likestilles med yrkesskade](/norwegian-laws/forskrifter/forskrift-1997-03-11-219.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1997-03-11-219) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1997-03-11-219.md) |
| [Forskrift om systematisk helse-, miljø- og sikkerhetsarbeid i virksomheter (Inte](/norwegian-laws/forskrifter/forskrift-1996-12-06-1127.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1996-12-06-1127) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1996-12-06-1127.md) |
| [Forskrift om særskilte delingstall i pensjonsordning for stortingsrepresentanter](/norwegian-laws/forskrifter/forskrift-2014-06-26-920.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2014-06-26-920) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2014-06-26-920.md) |
| [Forskrift om tekniske og operasjonelle forhold på landanlegg i petroleumsvirksom](/norwegian-laws/forskrifter/forskrift-2010-04-29-612.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2010-04-29-612) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2010-04-29-612.md) |
| [Forskrift om tilgang for Innkrevingsmyndigheten til opplysninger fra Arbeids- og](/norwegian-laws/forskrifter/forskrift-2018-03-13-338.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2018-03-13-338) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2018-03-13-338.md) |
| [Forskrift om tilskudd til brukerstyrte organisasjoner som arbeider mot fattigdom](/norwegian-laws/forskrifter/forskrift-2021-01-13-84.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-01-13-84) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-01-13-84.md) |
| [Forskrift om tilskudd til ekspertbistand](/norwegian-laws/forskrifter/forskrift-2019-08-29-1105.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-08-29-1105) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-08-29-1105.md) |
| [Forskrift om tilskudd til integreringsarbeid i regi av frivillige organisasjoner](/norwegian-laws/forskrifter/forskrift-2025-11-30-2373.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-11-30-2373) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-11-30-2373.md) |
| [Forskrift om tilskudd til lavterskel arbeidsrettede aktiviteter i regi av frivil](/norwegian-laws/forskrifter/forskrift-2025-11-27-2357.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-11-27-2357) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-11-27-2357.md) |
| [Forskrift om tilskudd til partsstyrte bransjeprogrammer under avtale om redusert](/norwegian-laws/forskrifter/forskrift-2025-02-04-118.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-02-04-118) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-02-04-118.md) |
| [Forskrift om tilskudd til pensjonistenes organisasjoner](/norwegian-laws/forskrifter/forskrift-2012-10-31-1016.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2012-10-31-1016) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2012-10-31-1016.md) |
| [Forskrift om tilskudd til utvikling av de sosiale tjenestene i NAV-kontoret, kap](/norwegian-laws/forskrifter/forskrift-2020-12-15-2787.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-12-15-2787) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-12-15-2787.md) |
| [Forskrift om tilsyn med ordninger for avtalefestet pensjon](/norwegian-laws/forskrifter/forskrift-2014-06-18-837.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2014-06-18-837) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2014-06-18-837.md) |
| [Forskrift om tiltakspenger mv. (tiltakspengeforskriften)](/norwegian-laws/forskrifter/forskrift-2013-11-04-1286.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-11-04-1286) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-11-04-1286.md) |
| [Forskrift om tiltaksverdier og grenseverdier for fysiske og kjemiske faktorer i ](/norwegian-laws/forskrifter/forskrift-2011-12-06-1358.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2011-12-06-1358) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2011-12-06-1358.md) |
| [Forskrift om tjenestepensjon og sykepenger (samordningsforskrift 43)](/norwegian-laws/forskrifter/forskrift-1986-05-15-4115.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1986-05-15-4115) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1986-05-15-4115.md) |
| [Forskrift om trygdedekning for asylsøkere og deres familiemedlemmer](/norwegian-laws/forskrifter/forskrift-2008-05-14-460.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2008-05-14-460) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2008-05-14-460.md) |
| [Forskrift om tvisteløsningsnemnd etter arbeidsmiljøloven](/norwegian-laws/forskrifter/forskrift-2005-12-16-1569.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2005-12-16-1569) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2005-12-16-1569.md) |
| [Forskrift om uførepensjon som også inneholder etterlattefordeler (samordningsfor](/norwegian-laws/forskrifter/forskrift-1985-12-31-4104.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1985-12-31-4104) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1985-12-31-4104.md) |
| [Forskrift om uføretrygd fra folketrygden](/norwegian-laws/forskrifter/forskrift-2014-12-05-1602.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2014-12-05-1602) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2014-12-05-1602.md) |
| [Forskrift om unntak fra anke til Trygderetten](/norwegian-laws/forskrifter/forskrift-1997-04-15-324.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1997-04-15-324) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1997-04-15-324.md) |
| [Forskrift om unntak fra arbeidsmiljøloven for visse typer arbeid og arbeidstaker](/norwegian-laws/forskrifter/forskrift-2005-12-16-1567.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2005-12-16-1567) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2005-12-16-1567.md) |
| [Forskrift om unntak fra arbeidsmiljøloven med tilhørende forskrifter for sivil l](/norwegian-laws/forskrifter/forskrift-2018-12-20-2182.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2018-12-20-2182) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2018-12-20-2182.md) |
| [Forskrift om unntak fra arbeidsmiljøloven § 50 for Sjøfartsdirektoratets og Skip](/norwegian-laws/forskrifter/forskrift-1983-04-29-3349.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1983-04-29-3349) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1983-04-29-3349.md) |
| [Forskrift om unntak fra arbeidsmiljøloven – medbestemmelse for tilsatte i staten](/norwegian-laws/forskrifter/forskrift-1980-06-06-6.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1980-06-06-6) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1980-06-06-6.md) |
| [Forskrift om unntak fra arbeidsmiljølovens arbeidstidsbestemmelser for polititje](/norwegian-laws/forskrifter/forskrift-2009-06-26-873.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2009-06-26-873) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2009-06-26-873.md) |
| [Forskrift om unntak fra arbeidstidsregler for arbeid ved teater og opera.](/norwegian-laws/forskrifter/forskrift-1985-02-08-293.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1985-02-08-293) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1985-02-08-293.md) |
| [Forskrift om unntak fra bestemmelsen om utdanningspermisjon innenfor Forsvarets ](/norwegian-laws/forskrifter/forskrift-2000-12-21-1368.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2000-12-21-1368) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2000-12-21-1368.md) |
| [Forskrift om unntak fra forskrift om bortfall av rett til dekning av utgifter ti](/norwegian-laws/forskrifter/forskrift-2007-06-08-587.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2007-06-08-587) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2007-06-08-587.md) |
| [Forskrift om unntak fra lov 10. desember 2004 nr. 76 om arbeidsmarkedstjenester ](/norwegian-laws/forskrifter/forskrift-2005-08-12-893.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2005-08-12-893) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2005-08-12-893.md) |
| [Forskrift om unntak fra medlemskap i Statens pensjonskasse](/norwegian-laws/forskrifter/forskrift-2003-12-19-1618.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2003-12-19-1618) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2003-12-19-1618.md) |
| [Forskrift om unntak fra medlemskap i folketrygden for person som er omfattet av ](/norwegian-laws/forskrifter/forskrift-1997-04-15-314.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1997-04-15-314) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1997-04-15-314.md) |
| [Forskrift om unntak fra pålegg om elektronisk kommunikasjon ved innsending av er](/norwegian-laws/forskrifter/forskrift-2009-12-07-1480.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2009-12-07-1480) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2009-12-07-1480.md) |
| [Forskrift om unntak fra samordning av alderspensjon fra tjenestepensjonsordning ](/norwegian-laws/forskrifter/forskrift-2015-01-22-52.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-01-22-52) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-01-22-52.md) |
| [Forskrift om unntak fra vilkåret om legeerklæring når kiropraktorer og manuellte](/norwegian-laws/forskrifter/forskrift-2005-12-21-1668.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2005-12-21-1668) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2005-12-21-1668.md) |
| [Forskrift om unntak i samordningsberegningen for inntekt som stammer fra tjenest](/norwegian-laws/forskrifter/forskrift-2020-12-04-2590.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-12-04-2590) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-12-04-2590.md) |
| [Forskrift om utbetaling og beregning av oppsatt alderspensjon fra pensjonsordnin](/norwegian-laws/forskrifter/forskrift-2000-03-10-216.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2000-03-10-216) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2000-03-10-216.md) |
| [Forskrift om utforming og innretning av arbeidsplasser, arbeidslokaler og innkva](/norwegian-laws/forskrifter/forskrift-2011-12-06-1356.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2011-12-06-1356) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2011-12-06-1356.md) |
| [Forskrift om utforming og utrustning av innretninger med mer i petroleumsvirksom](/norwegian-laws/forskrifter/forskrift-2010-04-29-634.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2010-04-29-634) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2010-04-29-634.md) |
| [Forskrift om utførelse av arbeid, psykososialt arbeidsmiljø, bruk av arbeidsutst](/norwegian-laws/forskrifter/forskrift-2011-12-06-1357.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2011-12-06-1357) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2011-12-06-1357.md) |
| [Forskrift om utføring av aktiviteter i petroleumsvirksomheten (aktivitetsforskri](/norwegian-laws/forskrifter/forskrift-2010-04-29-613.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2010-04-29-613) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2010-04-29-613.md) |
| [Forskrift om utlendingers adgang til riket og deres opphold her (utlendingsforsk](/norwegian-laws/forskrifter/forskrift-2009-10-15-1286.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2009-10-15-1286) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2009-10-15-1286.md) |
| [Forskrift om utmelding fra pensjonsordning for apotekvirksomhet mv.](/norwegian-laws/forskrifter/forskrift-2014-05-20-663.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2014-05-20-663) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2014-05-20-663.md) |
| [Forskrift om utsendte arbeidstakere](/norwegian-laws/forskrifter/forskrift-2005-12-16-1566.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2005-12-16-1566) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2005-12-16-1566.md) |
| [Forskrift om utstyr og sikkerhetssystem til bruk i eksplosjonsfarlig område](/norwegian-laws/forskrifter/forskrift-2017-11-29-1849.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-11-29-1849) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-11-29-1849.md) |
| [Forskrift om utveksling av opplysninger mellom Arbeids- og velferdsetaten og pen](/norwegian-laws/forskrifter/forskrift-2009-03-11-294.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2009-03-11-294) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2009-03-11-294.md) |
| [Forskrift om utvidet stønad til helsetjenester under opphold i utlandet](/norwegian-laws/forskrifter/forskrift-1997-04-30-391.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1997-04-30-391) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1997-04-30-391.md) |
| [Forskrift om vartpenger](/norwegian-laws/forskrifter/forskrift-2003-12-17-1783.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2003-12-17-1783) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2003-12-17-1783.md) |
| [Forskrift om videreføring av forskrifter til bidragsinnkrevingsloven (1955).](/norwegian-laws/forskrifter/forskrift-2005-12-16-1563.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2005-12-16-1563) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2005-12-16-1563.md) |
| [Forskrift om videreføring av to forskrifter gitt med hjemmel i lov om folketrygd](/norwegian-laws/forskrifter/forskrift-1998-01-16-37.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1998-01-16-37) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1998-01-16-37.md) |
| [Forskrift om vilkår for rett til ytelser etter lov om Statens pensjonskasse og e](/norwegian-laws/forskrifter/forskrift-2010-12-20-1711.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2010-12-20-1711) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2010-12-20-1711.md) |
| [Forskrift om vilkår for statstilskott til arbeidstakere som tar ut avtalefestet ](/norwegian-laws/forskrifter/forskrift-2010-11-30-1496.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2010-11-30-1496) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2010-11-30-1496.md) |
| [Forskrift om virkningstidspunkt for bestemmelsene i kapittel 2 i midlertidig for](/norwegian-laws/forskrifter/forskrift-2020-03-26-458.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-03-26-458) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-03-26-458.md) |
| [Forskrift om yrkesskadetrygd for lotter og flysøstre.](/norwegian-laws/forskrifter/forskrift-1964-09-04-8677.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1964-09-04-8677) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1964-09-04-8677.md) |
| [Forskrift om yrkesskadetrygd for personer som under opphold på sykehus eller lik](/norwegian-laws/forskrifter/forskrift-1964-05-29-8678.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1964-05-29-8678) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1964-05-29-8678.md) |
| [Forskrift om yrkessykdommer, klimasykdommer og epidemiske sykdommer som skal lik](/norwegian-laws/forskrifter/forskrift-1997-03-11-220.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1997-03-11-220) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1997-03-11-220.md) |
| [Forskrift om ytelser til gjenlevende ektefelle og tidligere familiepleier etter ](/norwegian-laws/forskrifter/forskrift-2023-06-21-1007.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-06-21-1007) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-06-21-1007.md) |
| [Forskrift om økt beregningsgrunnlag for gifte og samboende uføretrygdede som mot](/norwegian-laws/forskrifter/forskrift-2016-05-26-529.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2016-05-26-529) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2016-05-26-529.md) |
| [Forskrift til folketrygdloven § 25-10 om arbeidsgivers og oppdragsgivers opplysn](/norwegian-laws/forskrifter/forskrift-2014-07-10-969.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2014-07-10-969) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2014-07-10-969.md) |
| [Forskrift til gjennomføring av Haag-konvensjonen 15. april 1958 om anerkjennelse](/norwegian-laws/forskrifter/forskrift-1965-10-29-3635.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1965-10-29-3635) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1965-10-29-3635.md) |
| [Forskrift til gjennomføring av Haag-konvensjonen 2. juni 1978 om anerkjennelse o](/norwegian-laws/forskrifter/forskrift-1978-06-02-7.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1978-06-02-7) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1978-06-02-7.md) |
| [Forskrift til gjennomføring av konvensjonen av 23. mars 1962 mellom Norge, Danma](/norwegian-laws/forskrifter/forskrift-1963-05-31-9813.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1963-05-31-9813) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1963-05-31-9813.md) |
| [Forskrift til integreringsloven (integreringsforskriften)](/norwegian-laws/forskrifter/forskrift-2020-12-15-2912.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-12-15-2912) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-12-15-2912.md) |
| [Forskrift til jernbanetrafikkselskapslovens bestemmelser om de tilsattes rett ti](/norwegian-laws/forskrifter/forskrift-1998-03-20-204.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1998-03-20-204) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1998-03-20-204.md) |
| [Forskrift til lov om pensjonsordning for oppdragstaker i statlig beredskapshjem ](/norwegian-laws/forskrifter/forskrift-2011-02-03-109.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2011-02-03-109) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2011-02-03-109.md) |
| [Forskrift til postselskapslovens bestemmelser om de tilsattes rett til represent](/norwegian-laws/forskrifter/forskrift-1998-03-20-203.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1998-03-20-203) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1998-03-20-203.md) |
| [Forskrift til selskapslovens regler om de ansattes rett til representasjon i sty](/norwegian-laws/forskrifter/forskrift-2017-08-24-1279.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-08-24-1279) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-08-24-1279.md) |
| [Forskrift til tolkeloven (tolkeforskriften)](/norwegian-laws/forskrifter/forskrift-2021-09-13-2744.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-09-13-2744) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-09-13-2744.md) |
| [Forskrifter (midl.) om arbeidervern og arbeidsmiljø for Svalbard (særregler). De](/norwegian-laws/forskrifter/forskrift-1977-06-24-9453.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1977-06-24-9453) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1977-06-24-9453.md) |
| [Forskrifter for Jan Mayen i henhold til lov om arbeidervern og arbeidsmiljø. Del](/norwegian-laws/forskrifter/forskrift-1978-12-15-5.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1978-12-15-5) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1978-12-15-5.md) |
| [Forskrifter om arbeids- og fritid for personale ved helse- og sosialinstitusjone](/norwegian-laws/forskrifter/forskrift-1980-06-13-2.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1980-06-13-2) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1980-06-13-2.md) |
| [Forskrifter om epidemiske sykdommer og klimatsykdommer som stilles likt med yrke](/norwegian-laws/forskrifter/forskrift-1959-07-24-7.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1959-07-24-7) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1959-07-24-7.md) |
| [Forskrifter om forbud mot oppankring og mot fiske med visse redskaper i Ekofisk-](/norwegian-laws/forskrifter/forskrift-1978-04-14-12.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1978-04-14-12) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1978-04-14-12.md) |
| [Forskrifter om forgiftninger som skal likestilles med yrkesskade i h.t. lov om y](/norwegian-laws/forskrifter/forskrift-1962-08-03-5.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1962-08-03-5) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1962-08-03-5.md) |
| [Forskrifter om gjennomføringen av bestemmelsene i yrkesskadetrygdlovens § 57 om ](/norwegian-laws/forskrifter/forskrift-1980-05-16-8.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1980-05-16-8) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1980-05-16-8.md) |
| [Forskrifter om innbetaling av medlemspremie og om fritak for å betale premie.](/norwegian-laws/forskrifter/forskrift-1970-12-30-9395.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1970-12-30-9395) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1970-12-30-9395.md) |
| [Forskrifter om sjømannspensjonering](/norwegian-laws/forskrifter/forskrift-2000-11-15-1274.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2000-11-15-1274) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2000-11-15-1274.md) |
| [Forskrifter om utbetaling av ytelser etter lov om yrkesskadetrygd under opphold ](/norwegian-laws/forskrifter/forskrift-1974-12-12-1.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1974-12-12-1) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1974-12-12-1.md) |
| [Forskrifter om utbetaling av ytelser etter lovene om krigspensjonering under opp](/norwegian-laws/forskrifter/forskrift-1980-09-19-9554.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1980-09-19-9554) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1980-09-19-9554.md) |
| [Forskrifter om yrkessykdommer og infeksjonssykdommer som likestilles med yrkessk](/norwegian-laws/forskrifter/forskrift-1960-02-19-6.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1960-02-19-6) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1960-02-19-6.md) |
| [Kunngjøring av virkningstidspunktet for regulering av kravet til minsteinntekt i](/norwegian-laws/forskrifter/forskrift-2012-05-25-461.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2012-05-25-461) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2012-05-25-461.md) |
| [Midlertidig forskrift om endring i integreringsforskriften som følge av ankomst ](/norwegian-laws/forskrifter/forskrift-2024-06-26-1359.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-06-26-1359) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-06-26-1359.md) |
| [Overføring av ansvar for landtransport av farlig gods fra Samferdselsdepartement](/norwegian-laws/forskrifter/forskrift-1996-06-07-533.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1996-06-07-533) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1996-06-07-533.md) |
| [Overgangsregel om integreringsloven § 20 fjerde ledd](/norwegian-laws/forskrifter/forskrift-2024-06-25-1215.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-06-25-1215) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-06-25-1215.md) |
| [Overgangsregler om integreringsloven kapittel 6A](/norwegian-laws/forskrifter/forskrift-2022-06-10-995.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-06-10-995) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-06-10-995.md) |
| [Overgangsregler om integreringsloven kapittel 6A](/norwegian-laws/forskrifter/forskrift-2024-06-25-1217.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-06-25-1217) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-06-25-1217.md) |
| [Overgangsregler til lov om endringer i arbeidsmiljøloven m.m. (inn- og utleie fr](/norwegian-laws/forskrifter/forskrift-2022-12-20-2301.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-12-20-2301) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-12-20-2301.md) |
| [Regler om trygd for personer innsatt i fengselsvesenets anstalter.](/norwegian-laws/forskrifter/forskrift-1961-12-01-5.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1961-12-01-5) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1961-12-01-5.md) |
| [Vedtak om at forskrift om systematisk helse-, miljø- og sikkerhetsarbeid i virks](/norwegian-laws/forskrifter/forskrift-2002-12-13-1497.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2002-12-13-1497) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2002-12-13-1497.md) |
| [Vedtak om at midlertidig forskrift 19. desember 2003 nr. 1595 om sikkerhet og ar](/norwegian-laws/forskrifter/forskrift-2006-03-03-394.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2006-03-03-394) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2006-03-03-394.md) |
| [Vedtak om at midlertidig forskrift 19. desember 2003 nr. 1595 om sikkerhet og ar](/norwegian-laws/forskrifter/forskrift-2008-06-02-526.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2008-06-02-526) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2008-06-02-526.md) |
| [Vedtak om at midlertidig forskrift av 19. desember 2003 nr. 1595 om sikkerhet og](/norwegian-laws/forskrifter/forskrift-2003-12-19-1874.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2003-12-19-1874) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2003-12-19-1874.md) |
| [Vedtak om premietillegg til folketrygden for motorvogner fra 2004.](/norwegian-laws/forskrifter/forskrift-2003-12-05-1426.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2003-12-05-1426) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2003-12-05-1426.md) |
| [Vedtak om utvidelse av forskrifter til å gjelde for Svalbard.](/norwegian-laws/forskrifter/forskrift-2002-11-14-1632.html) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2002-11-14-1632) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2002-11-14-1632.md) |
