# Landbruks- og matdepartementet

*363 forskrifter*

| Forskrift | Lovdata | Historikk |
|-----------|---------|-----------|
| [Forskrift for Reindriftens Utviklingsfond](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2019-06-20-864.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-06-20-864) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-06-20-864.md) |
| [Forskrift for godkjenning av gjeterhytter i reindriften.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1982-11-01-1569.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1982-11-01-1569) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1982-11-01-1569.md) |
| [Forskrift for tilskott til erosjonsforebyggende tiltak](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1990-07-16-3965.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1990-07-16-3965) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1990-07-16-3965.md) |
| [Forskrift om EU-gjødselvarer (EU-gjødselvareforskriften)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2024-03-06-538.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-03-06-538) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-03-06-538.md) |
| [Forskrift om Omsetningsrådets myndighet vedrørende markedsregulering for jordbru](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2003-07-01-919.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2003-07-01-919) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2003-07-01-919.md) |
| [Forskrift om adgang for viderekomne veterinærstudenter til å utføre kortvarig as](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1985-04-10-838.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1985-04-10-838) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1985-04-10-838.md) |
| [Forskrift om administrative nedsettelser av tollavgiftssatser for landbruksvarer](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2005-12-22-1723.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2005-12-22-1723) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2005-12-22-1723.md) |
| [Forskrift om alkoholsterke og aromatiserte drikker mv.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2006-10-11-1148.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2006-10-11-1148) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2006-10-11-1148.md) |
| [Forskrift om allmenne prinsipper og krav i næringsmiddelregelverket (matlovsfors](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2008-12-22-1620.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2008-12-22-1620) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2008-12-22-1620.md) |
| [Forskrift om animalske biprodukter som ikke er beregnet på konsum (animaliebipro](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2016-09-14-1064.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2016-09-14-1064) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2016-09-14-1064.md) |
| [Forskrift om ansvar og oppgaver til nasjonale referanselaboratorier for salmonel](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2008-01-02-16.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2008-01-02-16) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2008-01-02-16.md) |
| [Forskrift om anvendelse av helselover og -forskrifter for Svalbard og Jan Mayen](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2015-06-22-747.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-06-22-747) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-06-22-747.md) |
| [Forskrift om at ører med reinmerke skal følge skinnet ved slakt](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-09-24-1915.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-09-24-1915) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-09-24-1915.md) |
| [Forskrift om avgift ved brudd på bruksregler etter reindriftsloven](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2011-11-07-1083.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2011-11-07-1083) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2011-11-07-1083.md) |
| [Forskrift om avl av storfe, svin, sau, geit og hest (husdyravlsforskriften)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2018-01-31-145.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2018-01-31-145) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2018-01-31-145.md) |
| [Forskrift om avliving av dyr](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2013-01-13-60.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-01-13-60) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-01-13-60.md) |
| [Forskrift om avliving av hund og katt](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1998-10-11-991.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1998-10-11-991) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1998-10-11-991.md) |
| [Forskrift om avlsfremmende tiltak på bier](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2001-04-18-426.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2001-04-18-426) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2001-04-18-426.md) |
| [Forskrift om behandling av opplysninger til Totalregnskapet for reindriftsnæring](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-06-24-1285.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-06-24-1285) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-06-24-1285.md) |
| [Forskrift om beiteområder for svensk rein i Norge.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2005-06-21-717.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2005-06-21-717) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2005-06-21-717.md) |
| [Forskrift om beredskapslagring av såkorn](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2012-10-30-1020.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2012-10-30-1020) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2012-10-30-1020.md) |
| [Forskrift om berekraftig skogbruk](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2006-06-07-593.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2006-06-07-593) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2006-06-07-593.md) |
| [Forskrift om beskyttelse av Badsturøkt kjøtt på namdalsk vis som betegnelse for ](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2010-11-03-1400.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2010-11-03-1400) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2010-11-03-1400.md) |
| [Forskrift om beskyttelse av Fenalår fra Norge som geografisk betegnelse](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2012-10-03-935.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2012-10-03-935) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2012-10-03-935.md) |
| [Forskrift om beskyttelse av Festsodd fra Trøndelag som geografisk betegnelse](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2012-10-17-976.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2012-10-17-976) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2012-10-17-976.md) |
| [Forskrift om beskyttelse av Gorgonzola som opprinnelsesbetegnelse](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2016-06-07-585.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2016-06-07-585) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2016-06-07-585.md) |
| [Forskrift om beskyttelse av Gulløye fra Nord-Norge som opprinnelsesbetegnelse](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2007-09-14-1094.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2007-09-14-1094) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2007-09-14-1094.md) |
| [Forskrift om beskyttelse av Høgfjellslam fra Nord-Gudbrandsdal som geografisk be](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2012-08-16-820.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2012-08-16-820) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2012-08-16-820.md) |
| [Forskrift om beskyttelse av Kvitsøylam som geografisk betegnelse](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-01-28-104.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-01-28-104) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-01-28-104.md) |
| [Forskrift om beskyttelse av Lofotlam som geografisk betegnelse](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2012-10-03-936.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2012-10-03-936) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2012-10-03-936.md) |
| [Forskrift om beskyttelse av Lyngenlam som geografisk betegnelse](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2019-03-11-247.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-03-11-247) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-03-11-247.md) |
| [Forskrift om beskyttelse av Målselvnepe fra Nord-Norge som geografisk betegnelse](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2018-01-12-42.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2018-01-12-42) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2018-01-12-42.md) |
| [Forskrift om beskyttelse av Parmigiano Reggiano som opprinnelsesbetegnelse](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2012-04-20-340.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2012-04-20-340) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2012-04-20-340.md) |
| [Forskrift om beskyttelse av Pinnekjøtt fra Norge som geografisk betegnelse](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2017-10-25-1665.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-10-25-1665) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-10-25-1665.md) |
| [Forskrift om beskyttelse av Prosciutto di Parma som opprinnelsesbetegnelse](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2012-04-20-339.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2012-04-20-339) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2012-04-20-339.md) |
| [Forskrift om beskyttelse av Prosciutto di San Daniele som opprinnelsesbetegnelse](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2022-03-08-346.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-03-08-346) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-03-08-346.md) |
| [Forskrift om beskyttelse av Setersmør/Stølssmør som betegnelse for tradisjonelt ](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2019-09-02-1104.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-09-02-1104) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-09-02-1104.md) |
| [Forskrift om beskyttelse av Skjørost fra Røros-traktene som geografisk betegnels](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2016-01-19-39.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2016-01-19-39) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2016-01-19-39.md) |
| [Forskrift om beskyttelse av Småmat som betegnelse for tradisjonelt særpreg](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2024-03-14-434.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-03-14-434) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-03-14-434.md) |
| [Forskrift om beskyttelse av Telemarksepler/Epler fra Telemark som geografisk bet](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2015-12-14-1863.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-12-14-1863) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-12-14-1863.md) |
| [Forskrift om beskyttelse av Telemarksmoreller/Moreller fra Telemark som geografi](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2016-04-12-369.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2016-04-12-369) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2016-04-12-369.md) |
| [Forskrift om beskyttelse av Telemarksplommer/Plommer fra Telemark som geografisk](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2016-04-12-370.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2016-04-12-370) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2016-04-12-370.md) |
| [Forskrift om beskyttelse av Tørrfisk fra Lofoten som geografisk betegnelse](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2007-12-11-1814.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2007-12-11-1814) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2007-12-11-1814.md) |
| [Forskrift om beskyttelse av opprinnelsesbetegnelser, geografiske betegnelser og ](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2002-07-05-698.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2002-07-05-698) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2002-07-05-698.md) |
| [Forskrift om beskyttelse av produktbetegnelsen Fjellmandel fra Oppdal som Beskyt](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2006-05-26-554.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2006-05-26-554) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2006-05-26-554.md) |
| [Forskrift om beskyttelse av produktbetegnelsen Ishavsrøye Vesterålen som beskytt](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2007-05-25-563.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2007-05-25-563) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2007-05-25-563.md) |
| [Forskrift om beskyttelse av produktbetegnelsen Rakfisk fra Valdres som Beskyttet](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2006-10-27-1196.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2006-10-27-1196) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2006-10-27-1196.md) |
| [Forskrift om beskyttelse av produktbetegnelsen Ringerikserter som Beskyttet oppr](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2004-06-01-819.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2004-06-01-819) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2004-06-01-819.md) |
| [Forskrift om beskyttelse av produktbetegnelsen Ringerikspotet fra Ringerike som ](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2007-06-25-695.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2007-06-25-695) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2007-06-25-695.md) |
| [Forskrift om beskyttelse av produktbetegnelsen Skjenning som Beskyttet opprinnel](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2006-05-15-531.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2006-05-15-531) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2006-05-15-531.md) |
| [Forskrift om beskyttelse av produktbetegnelsen Økologisk Tjukkmjølk fra Røros so](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2004-02-10-581.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2004-02-10-581) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2004-02-10-581.md) |
| [Forskrift om bruk av avløpsvann til vanning i landbruket](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2024-10-30-2596.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-10-30-2596) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-10-30-2596.md) |
| [Forskrift om bruk av dyr i forsøk](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2015-06-18-761.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-06-18-761) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-06-18-761.md) |
| [Forskrift om bruk av elektrisk strøm ved trening av hund](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2008-03-14-256.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2008-03-14-256) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2008-03-14-256.md) |
| [Forskrift om bruk av krumkniv](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2008-07-30-866.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2008-07-30-866) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2008-07-30-866.md) |
| [Forskrift om bruk av visse legemidler til dyr av hestefamilien](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2007-01-16-50.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2007-01-16-50) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2007-01-16-50.md) |
| [Forskrift om den offentlige kontrollen med bruken av farmakologisk virksomme sto](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2020-03-04-705.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-03-04-705) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-03-04-705.md) |
| [Forskrift om dokumentasjon, saksbehandling og erstatning etter naturskader (natu](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2016-07-07-904.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2016-07-07-904) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2016-07-07-904.md) |
| [Forskrift om dyrehelse (dyrehelseforskriften)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2022-04-06-631.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-04-06-631) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-04-06-631.md) |
| [Forskrift om dyrepleiere](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2003-05-27-657.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2003-05-27-657) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2003-05-27-657.md) |
| [Forskrift om dyrevelferd ved fremvisning av dyr](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2016-09-05-1035.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2016-09-05-1035) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2016-09-05-1035.md) |
| [Forskrift om eksport av næringsmidler, animaliebiprodukter, fôrvarer, levende dy](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2020-06-18-1547.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-06-18-1547) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-06-18-1547.md) |
| [Forskrift om ekstrautbetaling av produksjonstilskudd i 2022](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2022-07-01-1280.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-07-01-1280) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-07-01-1280.md) |
| [Forskrift om ekstrautbetaling av tilskudd for grovfôrbasert husdyrhold og tilsku](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2018-10-26-1624.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2018-10-26-1624) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2018-10-26-1624.md) |
| [Forskrift om endring av landbruksfagskulane sin struktur og plass i skulesysteme](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1988-07-08-562.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1988-07-08-562) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1988-07-08-562.md) |
| [Forskrift om endring i forskrift om EU-gjødselvarer](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2026-02-10-232.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2026-02-10-232) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2026-02-10-232.md) |
| [Forskrift om endring i forskrift om næringsmiddelhygiene](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-07-01-1399.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-07-01-1399) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-07-01-1399.md) |
| [Forskrift om endring i forskrift om overføring av myndighet til kommunen, statsf](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2024-12-10-3031.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-12-10-3031) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-12-10-3031.md) |
| [Forskrift om endring i forskrift om satser i prisutjevningsordningen for melk og](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2026-05-07-766.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2026-05-07-766) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2026-05-07-766.md) |
| [Forskrift om erstatning etter offentlige pålegg i plante- og husdyrproduksjon](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2016-05-29-545.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2016-05-29-545) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2016-05-29-545.md) |
| [Forskrift om fastsettelse av metoder for prøvetaking og analyse i forbindelse me](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2020-02-28-702.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-02-28-702) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-02-28-702.md) |
| [Forskrift om fastsettelse av nedsatte tollavgiftssatser ved import av industriel](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2012-12-20-1424.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2012-12-20-1424) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2012-12-20-1424.md) |
| [Forskrift om fastsettelse av tvangsmulkt etter reindriftsloven](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2011-11-07-1082.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2011-11-07-1082) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2011-11-07-1082.md) |
| [Forskrift om floghavre](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2015-06-22-752.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-06-22-752) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-06-22-752.md) |
| [Forskrift om forbud mot innførsel av dyr og smitteførende gjenstander](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1991-07-02-507.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1991-07-02-507) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1991-07-02-507.md) |
| [Forskrift om forbud mot innførsel av dyr til Svalbard.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1988-08-31-744.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1988-08-31-744) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1988-08-31-744.md) |
| [Forskrift om forbud mot å bruke levende dyr som lotterigevinster](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1985-01-10-16.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1985-01-10-16) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1985-01-10-16.md) |
| [Forskrift om forbud mot å innføre, omsette og holde eksotiske dyr](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2017-05-11-597.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-05-11-597) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-05-11-597.md) |
| [Forskrift om forbud mot å stille ut hunder som har fått øre og/eller hale kupert](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2003-04-25-614.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2003-04-25-614) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2003-04-25-614.md) |
| [Forskrift om fordeling av overskuddet fra pengespill på hest](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2023-03-13-327.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-03-13-327) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-03-13-327.md) |
| [Forskrift om fordeling av tollkvoter for landbruksvarer](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2008-10-10-1132.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2008-10-10-1132) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2008-10-10-1132.md) |
| [Forskrift om forebygging av, kontroll med og utryddelse av overførbare spongifor](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2004-03-30-595.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2004-03-30-595) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2004-03-30-595.md) |
| [Forskrift om forenklet saksbehandling av søknader om naturskadeerstatning etter ](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2023-09-18-1440.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-09-18-1440) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-09-18-1440.md) |
| [Forskrift om forlenget gyldighet for autorisasjonsbevis for plantevernmidler](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2026-01-15-47.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2026-01-15-47) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2026-01-15-47.md) |
| [Forskrift om formidling av pristilskudd i landbrukssektoren](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2008-12-19-1491.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2008-12-19-1491) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2008-12-19-1491.md) |
| [Forskrift om forskningsavgift på landbruksprodukter](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2012-12-20-1417.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2012-12-20-1417) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2012-12-20-1417.md) |
| [Forskrift om fortegnelse over fremmedstoffer som omfattes av matloven.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2001-03-28-357.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2001-03-28-357) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2001-03-28-357.md) |
| [Forskrift om forvaltning av bever](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2017-04-26-519.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-04-26-519) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-04-26-519.md) |
| [Forskrift om forvaltning av hjortevilt](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2016-01-08-12.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2016-01-08-12) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2016-01-08-12.md) |
| [Forskrift om fruktjuice og lignende produkter (juiceforskriften)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2013-05-13-509.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-05-13-509) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-05-13-509.md) |
| [Forskrift om fôrhygiene](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2010-01-14-39.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2010-01-14-39) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2010-01-14-39.md) |
| [Forskrift om fôrvarer](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2002-11-07-1290.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2002-11-07-1290) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2002-11-07-1290.md) |
| [Forskrift om førehandsvarsling og om fjellstyrevedtak.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1983-06-08-1257.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1983-06-08-1257) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1983-06-08-1257.md) |
| [Forskrift om gebyr for behandling av konsesjons- og delingssaker](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2011-12-14-1336.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2011-12-14-1336) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2011-12-14-1336.md) |
| [Forskrift om gebyr til Mattilsynet](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2026-04-27-745.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2026-04-27-745) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2026-04-27-745.md) |
| [Forskrift om gjennomføring av forordning (EF) nr. 136/2004 om fastsettelse av fr](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2005-11-30-1347.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2005-11-30-1347) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2005-11-30-1347.md) |
| [Forskrift om gjennomføring av forordning (EF) nr. 599/2004 om vedtakelse av en h](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2005-11-30-1349.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2005-11-30-1349) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2005-11-30-1349.md) |
| [Forskrift om gjennomføring av forordning (EF) nr. 745/2004 om fastsettelse av ti](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2006-01-31-103.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2006-01-31-103) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2006-01-31-103.md) |
| [Forskrift om gjennomføringen av bestemmelsene om sammenslåing av eiendommer til ](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1984-10-24-1878.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1984-10-24-1878) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1984-10-24-1878.md) |
| [Forskrift om gjennomføringen av bestemmelsene om sammenslåing for å oppnå minste](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1984-10-24-1879.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1984-10-24-1879) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1984-10-24-1879.md) |
| [Forskrift om gjødslingsplanlegging](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1999-07-01-791.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1999-07-01-791) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1999-07-01-791.md) |
| [Forskrift om godkjenning av omsetningsledd for deltakelse i markedsordningen for](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2005-05-04-403.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2005-05-04-403) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2005-05-04-403.md) |
| [Forskrift om godtgjørelse for nødhjelp til dyr](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2012-04-17-330.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2012-04-17-330) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2012-04-17-330.md) |
| [Forskrift om grenselengdegebyr](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2015-11-10-1267.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-11-10-1267) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-11-10-1267.md) |
| [Forskrift om grenseverdier for koksidiostatika eller histomonostatika i næringsm](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2013-07-01-814.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-07-01-814) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-07-01-814.md) |
| [Forskrift om grenseverdier for legemiddelrester i næringsmidler fra dyr](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2012-05-30-512.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2012-05-30-512) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2012-05-30-512.md) |
| [Forskrift om handel med gjødsel og kalkingsmidler mv.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2003-07-04-1063.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2003-07-04-1063) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2003-07-04-1063.md) |
| [Forskrift om helsesertifikater – akvatiske dyr og visse animalske produkter dera](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2022-04-06-626.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-04-06-626) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-04-06-626.md) |
| [Forskrift om helsesertifikater – landdyr og avlsmateriale derav – forordning (EU](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2022-04-06-627.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-04-06-627) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-04-06-627.md) |
| [Forskrift om helsesertifikater – næringsmidler og dyr – forordning (EU) 2020/223](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2022-04-06-625.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-04-06-625) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-04-06-625.md) |
| [Forskrift om hold av høns og kalkun](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2001-12-12-1494.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2001-12-12-1494) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2001-12-12-1494.md) |
| [Forskrift om hold av pelsdyr](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2011-03-17-296.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2011-03-17-296) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2011-03-17-296.md) |
| [Forskrift om hold av storfe](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2004-04-22-665.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2004-04-22-665) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2004-04-22-665.md) |
| [Forskrift om hold av strutsefugl](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1998-10-02-951.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1998-10-02-951) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1998-10-02-951.md) |
| [Forskrift om hold av svin](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2003-02-18-175.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2003-02-18-175) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2003-02-18-175.md) |
| [Forskrift om honning](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2003-07-08-931.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2003-07-08-931) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2003-07-08-931.md) |
| [Forskrift om hunder](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2004-08-20-1204.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2004-08-20-1204) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2004-08-20-1204.md) |
| [Forskrift om håndtering av dyrekadaver ved utbrudd av smittsomme dyresjukdommer](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2008-05-07-438.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2008-05-07-438) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2008-05-07-438.md) |
| [Forskrift om høyeste midlertidige grenseverdier for radioaktiv forurensning i næ](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2022-09-14-1580.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-09-14-1580) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-09-14-1580.md) |
| [Forskrift om ikke-kommersiell forflytning av kjæledyr (kjæledyrforskriften)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2016-05-19-542.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2016-05-19-542) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2016-05-19-542.md) |
| [Forskrift om ikke-næringsmessig transport av dyr og transport av sirkusdyr](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2012-02-08-129.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2012-02-08-129) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2012-02-08-129.md) |
| [Forskrift om import av matpoteter fra Egypt](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2007-11-16-1259.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2007-11-16-1259) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2007-11-16-1259.md) |
| [Forskrift om import av toskallede bløtdyr, pigghuder, sekkdyr og sjøsnegler fra ](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2020-11-20-2424.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-11-20-2424) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-11-20-2424.md) |
| [Forskrift om infisert sone for høypatogen aviær influensa og Newcastlesyke](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2022-06-23-1161.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-06-23-1161) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-06-23-1161.md) |
| [Forskrift om inndeling i jordskiftesokn og tilordning til lagmannsrettane](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2020-12-11-2714.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-12-11-2714) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-12-11-2714.md) |
| [Forskrift om innførsel av næringsmidler og fôrvarer](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1998-12-23-1471.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1998-12-23-1471) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1998-12-23-1471.md) |
| [Forskrift om innførselstillatelse av visse produkter som kan anvendes til kraftf](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1995-06-09-556.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1995-06-09-556) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1995-06-09-556.md) |
| [Forskrift om innkreving av omsetningsavgift og overproduksjonsavgift.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1996-12-20-1343.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1996-12-20-1343) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1996-12-20-1343.md) |
| [Forskrift om innsamling og overføring av molekylære analytiske data ved utbrudd ](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2026-03-17-426.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2026-03-17-426) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2026-03-17-426.md) |
| [Forskrift om internkontroll for å oppfylle næringsmiddellovgivningen](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1994-12-15-1187.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1994-12-15-1187) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1994-12-15-1187.md) |
| [Forskrift om jakt på reinsdyr som eies](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2020-01-31-100.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-01-31-100) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-01-31-100.md) |
| [Forskrift om jakt, felling, fangst og fiske i statsallmenning](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-03-11-681.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-03-11-681) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-03-11-681.md) |
| [Forskrift om jakt, felling, fangst og fiske på statsgrunn utenfor statsallmennin](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2007-08-20-987.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2007-08-20-987) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2007-08-20-987.md) |
| [Forskrift om jordskiftemeddommeres forsikring](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2016-06-01-547.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2016-06-01-547) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2016-06-01-547.md) |
| [Forskrift om journal for dyrehelsepersonell.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2006-02-20-229.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2006-02-20-229) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2006-02-20-229.md) |
| [Forskrift om kaffe- og sikoriekstrakter.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2000-08-31-887.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2000-08-31-887) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2000-08-31-887.md) |
| [Forskrift om kakao- og sjokoladeprodukter.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2002-09-09-986.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2002-09-09-986) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2002-09-09-986.md) |
| [Forskrift om kaseiner og kaseinater](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2017-05-08-561.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-05-08-561) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-05-08-561.md) |
| [Forskrift om klassifisering, merking og emballering av stoffer og stoffblandinge](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2012-06-16-622.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2012-06-16-622) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2012-06-16-622.md) |
| [Forskrift om kommunale og fylkeskommunale viltfond og fellingsavgift for elg og ](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2011-05-15-537.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2011-05-15-537) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2011-05-15-537.md) |
| [Forskrift om kompensasjon for frivillig redusert verpeperiode](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2020-06-22-1397.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-06-22-1397) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-06-22-1397.md) |
| [Forskrift om kompensasjon for produksjonstap etter pålegg om nedslakting av svin](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2015-06-26-795.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-06-26-795) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-06-26-795.md) |
| [Forskrift om kompensasjon for utgifter, merarbeid og økonomiske tap som reineier](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2015-07-01-814.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-07-01-814) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-07-01-814.md) |
| [Forskrift om kompensasjon ved restriksjoner i bruk av utmarksbeite på grunn av r](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2010-07-09-1087.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2010-07-09-1087) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2010-07-09-1087.md) |
| [Forskrift om kompensasjonstilskudd til deltakere i prosjekt «Friskere geiter»](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2013-07-01-818.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-07-01-818) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-07-01-818.md) |
| [Forskrift om kompetansekrav for bruk av særlige undersøkelses- og behandlingsmet](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1995-03-27-276.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1995-03-27-276) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1995-03-27-276.md) |
| [Forskrift om kondensert melk og melkepulver](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2003-07-08-930.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2003-07-08-930) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2003-07-08-930.md) |
| [Forskrift om konsesjonsfrihet for visse erverv av fast eiendom, egenerklæring ve](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2003-12-08-1434.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2003-12-08-1434) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2003-12-08-1434.md) |
| [Forskrift om kontroll av Salmonella og andre matbårne zoonotiske smittestoffer](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2005-12-23-1703.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2005-12-23-1703) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2005-12-23-1703.md) |
| [Forskrift om kontroll med Salmonella i fjørfe, fjørfefôr, fjørfekjøtt og egg](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2007-06-08-603.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2007-06-08-603) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2007-06-08-603.md) |
| [Forskrift om kontrollområder for å forebygge, begrense og bekjempe pærebrann (Er](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2020-01-08-51.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-01-08-51) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-01-08-51.md) |
| [Forskrift om kontrolltiltak for restmengder av visse stoffer i animalske nærings](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2000-01-27-65.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2000-01-27-65) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2000-01-27-65.md) |
| [Forskrift om krav for å beskytte fiske-, dyre- og plantehelse i forbindelse med ](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-11-21-2316.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-11-21-2316) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-11-21-2316.md) |
| [Forskrift om kunstig sædoverføring hos husdyr utført av andre enn veterinær](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1995-03-06-239.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1995-03-06-239) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1995-03-06-239.md) |
| [Forskrift om kvalitet på melk og melkeprodukter](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2015-06-03-607.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-06-03-607) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-06-03-607.md) |
| [Forskrift om kvoteordningen for melk](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2011-12-23-1502.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2011-12-23-1502) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2011-12-23-1502.md) |
| [Forskrift om lagring og bruk av gjødsel mv.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-01-29-115.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-01-29-115) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-01-29-115.md) |
| [Forskrift om legemidler til dyr](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2022-09-08-1573.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-09-08-1573) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-09-08-1573.md) |
| [Forskrift om markedsregulering til å fremme omsetningen av jordbruksvarer](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2008-10-22-1136.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2008-10-22-1136) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2008-10-22-1136.md) |
| [Forskrift om matinformasjon til forbrukerne (matinformasjonsforskriften)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2014-11-28-1497.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2014-11-28-1497) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2014-11-28-1497.md) |
| [Forskrift om matloven, Svalbard.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1978-06-01-3389.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1978-06-01-3389) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1978-06-01-3389.md) |
| [Forskrift om matpoteter.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1999-04-30-634.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1999-04-30-634) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1999-04-30-634.md) |
| [Forskrift om medisinfôr (medisinfôrforskriften)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2022-04-07-587.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-04-07-587) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-04-07-587.md) |
| [Forskrift om melding av opplysninger om utleverte og brukte legemidler til dyr](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2009-07-03-971.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2009-07-03-971) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2009-07-03-971.md) |
| [Forskrift om melding om reindrift](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2023-12-19-2180.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-12-19-2180) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-12-19-2180.md) |
| [Forskrift om merking av rein utenfor det samiske reinbeiteområdet](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2008-07-04-791.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2008-07-04-791) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2008-07-04-791.md) |
| [Forskrift om merking og omsetning av fôrvarer](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2011-04-02-360.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2011-04-02-360) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2011-04-02-360.md) |
| [Forskrift om midler til investering og bedriftsutvikling i landbruket](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2014-12-19-1816.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2014-12-19-1816) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2014-12-19-1816.md) |
| [Forskrift om midler til satsing på bærekraftig matproduksjon og verdiskaping i n](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2023-08-08-1312.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-08-08-1312) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-08-08-1312.md) |
| [Forskrift om midlertidige bekjempelses- og nødtiltak for å hindre spredning av n](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-05-05-1407.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-05-05-1407) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-05-05-1407.md) |
| [Forskrift om minstekvantum av epleråstoff til bearbeidingsindustrien](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-12-01-3359.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-12-01-3359) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-12-01-3359.md) |
| [Forskrift om nasjonale tilretteleggingsmidler til næringsutvikling og kompetanse](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-01-15-92.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-01-15-92) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-01-15-92.md) |
| [Forskrift om nedsettelse av tollavgiftssatser for landbruksvarer som gjeninnføre](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2007-06-01-580.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2007-06-01-580) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2007-06-01-580.md) |
| [Forskrift om nydyrking](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1997-05-02-423.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1997-05-02-423) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1997-05-02-423.md) |
| [Forskrift om næringsmessig transport av dyr](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2012-02-08-139.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2012-02-08-139) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2012-02-08-139.md) |
| [Forskrift om næringsmiddelhygiene (næringsmiddelhygieneforskriften)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2008-12-22-1623.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2008-12-22-1623) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2008-12-22-1623.md) |
| [Forskrift om offentlig kontroll for å sikre etterlevelse av regelverket for mat,](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2020-03-03-704.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-03-03-704) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-03-03-704.md) |
| [Forskrift om offentlig kontroll – IMSOC – forordning (EU) 2019/1715](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2020-03-09-715.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-03-09-715) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-03-09-715.md) |
| [Forskrift om offentlig kontroll – animalsk produksjon, forordning (EU) 2019/624 ](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2020-03-09-720.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-03-09-720) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-03-09-720.md) |
| [Forskrift om offentlig kontroll – dokumentasjonskrav ved import, forordning (EU)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2020-03-09-710.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-03-09-710) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-03-09-710.md) |
| [Forskrift om offentlig kontroll – dyrehelse, forordning (EU) 2022/160 og forordn](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2024-06-13-975.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-06-13-975) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-06-13-975.md) |
| [Forskrift om offentlig kontroll – dyrevelferd ved transport av levende dyr i dyr](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2024-05-28-968.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-05-28-968) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-05-28-968.md) |
| [Forskrift om offentlig kontroll – generelle regler for grensekontroll forordning](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2020-03-09-708.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-03-09-708) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-03-09-708.md) |
| [Forskrift om offentlig kontroll – grensekontrollstasjoner – forordning (EU) 2019](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2020-03-09-709.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-03-09-709) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-03-09-709.md) |
| [Forskrift om offentlig kontroll – importkontroll av ikke animalske produkter – f](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2020-03-09-717.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-03-09-717) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-03-09-717.md) |
| [Forskrift om offentlig kontroll – importkontroll for antimikrobielle legemidler ](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-03-24-620.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-03-24-620) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-03-24-620.md) |
| [Forskrift om offentlig kontroll – krav til transporten ved import og transitt, f](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2020-03-09-711.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-03-09-711) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-03-09-711.md) |
| [Forskrift om offentlig kontroll – lister over tredjestater det er tillatt å innf](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-08-26-2617.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-08-26-2617) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-08-26-2617.md) |
| [Forskrift om offentlig kontroll – opprettelse av den europeiske unions referanse](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2022-09-07-1558.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-09-07-1558) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-09-07-1558.md) |
| [Forskrift om offentlig kontroll – positivlisten 2021 – forordning (EU) 2021/630 ](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2022-06-02-1010.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-06-02-1010) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-06-02-1010.md) |
| [Forskrift om offentlig kontroll – referansesentre for dyrevelferd forordning (EU](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2020-03-02-703.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-03-02-703) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-03-02-703.md) |
| [Forskrift om offentlig kontroll – standardmal for årsrapport, forordning (EU) 20](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2020-03-04-706.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-03-04-706) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-03-04-706.md) |
| [Forskrift om offentlig kontroll – særlige regler om grensekontrollen, forordning](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2020-03-09-712.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-03-09-712) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-03-09-712.md) |
| [Forskrift om offentlig kontroll – utfyllende bestemmelser om krav til import – f](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2023-12-27-2337.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-12-27-2337) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-12-27-2337.md) |
| [Forskrift om offentlig kontroll – utfyllende bestemmelser om utpeking av offisie](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2022-05-03-836.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-05-03-836) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-05-03-836.md) |
| [Forskrift om offentlig kontrollert telling av rein](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2009-06-22-842.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2009-06-22-842) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2009-06-22-842.md) |
| [Forskrift om omregningsfaktorer for råvarer til matmel og kraftfôrproduksjon ved](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2009-06-30-954.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2009-06-30-954) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2009-06-30-954.md) |
| [Forskrift om omsetning av tømmer og treprodukter med opprinnelse i Norge](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2015-04-24-403.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-04-24-403) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-04-24-403.md) |
| [Forskrift om omsetning og midlertidig hold av dyr](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2015-08-11-958.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-08-11-958) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-08-11-958.md) |
| [Forskrift om omsetningsavgift på jordbruksvarer, og om overproduksjonsavgift på ](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1999-06-29-763.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1999-06-29-763) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1999-06-29-763.md) |
| [Forskrift om opphevelse av forskrift om avgift til fremme av fellestiltak for sk](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2020-12-21-3049.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-12-21-3049) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-12-21-3049.md) |
| [Forskrift om opplysninger til Mattilsynet](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2010-09-28-1302.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2010-09-28-1302) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2010-09-28-1302.md) |
| [Forskrift om overgangsbestemmelser til lov 15. juni 2007 nr. 40 om reindrift (re](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2007-06-29-818.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2007-06-29-818) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2007-06-29-818.md) |
| [Forskrift om overtredelsesgebyr etter dyrevelferdsloven](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2014-06-30-925.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2014-06-30-925) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2014-06-30-925.md) |
| [Forskrift om overvåkning av og kontroll med forekomst av salmonella i ferskt kjø](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1995-04-10-368.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1995-04-10-368) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1995-04-10-368.md) |
| [Forskrift om overvåkning av og kontroll med forekomsten av salmonella hos levend](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1995-01-31-107.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1995-01-31-107) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1995-01-31-107.md) |
| [Forskrift om planlegging og godkjenning av landbruksveier](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2015-05-28-550.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-05-28-550) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-05-28-550.md) |
| [Forskrift om planteforedlerrett](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1993-08-06-832.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1993-08-06-832) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1993-08-06-832.md) |
| [Forskrift om planter og tiltak mot planteskadegjørere](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2000-12-01-1333.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2000-12-01-1333) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2000-12-01-1333.md) |
| [Forskrift om plantevernmidler](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2015-05-06-455.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-05-06-455) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-05-06-455.md) |
| [Forskrift om priskompensasjon ved innenlands produksjon av skilleprodukter av eg](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2020-06-22-1398.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-06-22-1398) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-06-22-1398.md) |
| [Forskrift om prisnedskriving av melk solgt til skoler og barnehager](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2020-06-22-1399.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-06-22-1399) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-06-22-1399.md) |
| [Forskrift om prisnedskriving ved salg til spesialmarkeder](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2020-06-22-1400.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-06-22-1400) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-06-22-1400.md) |
| [Forskrift om pristilskudd i landbrukssektoren](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2008-12-19-1490.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2008-12-19-1490) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2008-12-19-1490.md) |
| [Forskrift om prisutjevningsbeløp på kraftfôr og råvarer til kraftfôr](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2008-12-19-1492.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2008-12-19-1492) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2008-12-19-1492.md) |
| [Forskrift om prisutjevningsordningen for melk](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2007-06-29-832.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2007-06-29-832) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2007-06-29-832.md) |
| [Forskrift om produksjon, omsetning og import av gjødselvarer av organisk opphav ](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-01-29-116.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-01-29-116) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-01-29-116.md) |
| [Forskrift om produksjonstilskudd og avløsertilskudd i jordbruket](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2014-12-19-1817.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2014-12-19-1817) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2014-12-19-1817.md) |
| [Forskrift om prøving og godkjenning av plantesorter](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1999-10-01-1069.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1999-10-01-1069) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1999-10-01-1069.md) |
| [Forskrift om rapportering av slaktet rein og lagerbeholdning](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2011-06-21-617.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2011-06-21-617) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2011-06-21-617.md) |
| [Forskrift om refusjon av fôrkostnader i pelsdyrnæringen](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1997-12-01-1249.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1997-12-01-1249) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1997-12-01-1249.md) |
| [Forskrift om regionale tilretteleggingsmidler i landbruket](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2019-12-20-2082.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-12-20-2082) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-12-20-2082.md) |
| [Forskrift om regnskapsføring av reindriftsfond og reinbeitedistriktenes regnskap](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1993-12-14-1435.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1993-12-14-1435) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1993-12-14-1435.md) |
| [Forskrift om regulering av svine- og fjørfeproduksjonen](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2004-04-01-611.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2004-04-01-611) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2004-04-01-611.md) |
| [Forskrift om regulering av svine- og fjørfeproduksjonen.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2003-04-11-461.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2003-04-11-461) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2003-04-11-461.md) |
| [Forskrift om reindriftsfond.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1992-02-14-1271.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1992-02-14-1271) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1992-02-14-1271.md) |
| [Forskrift om reinmerker](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2022-08-29-1504.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-08-29-1504) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-08-29-1504.md) |
| [Forskrift om rester av plantevernmidler i næringsmidler og fôrvarer](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2009-08-18-1117.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2009-08-18-1117) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2009-08-18-1117.md) |
| [Forskrift om rett til å arbeide som dyrehelsepersonell eller seminpersonell ette](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2009-01-19-77.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2009-01-19-77) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2009-01-19-77.md) |
| [Forskrift om råvareprisutjevning for bearbeidede jordbruksvarer](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2009-06-10-636.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2009-06-10-636) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2009-06-10-636.md) |
| [Forskrift om saksbehandling i saker om odelsfrigjering etter odelslova § 30 og §](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2011-02-11-138.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2011-02-11-138) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2011-02-11-138.md) |
| [Forskrift om saksbehandling mv. i kommunen i saker etter konsesjonsloven, jordlo](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2003-12-08-1480.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2003-12-08-1480) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2003-12-08-1480.md) |
| [Forskrift om samarbeid om produksjon og omsetning av visse hagebruks-, gartneri-](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2004-06-30-1104.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2004-06-30-1104) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2004-06-30-1104.md) |
| [Forskrift om satser for beiteavgift.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2005-06-21-716.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2005-06-21-716) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2005-06-21-716.md) |
| [Forskrift om satser for frakttilskudd til transport av kraftfôr](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-12-12-2584.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-12-12-2584) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-12-12-2584.md) |
| [Forskrift om satser for og beregning av tilskudd ved produksjonssvikt i plante- ](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2018-08-01-1215.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2018-08-01-1215) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2018-08-01-1215.md) |
| [Forskrift om satser for tilskudd til frakt av slaktedyr](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2024-12-17-3183.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-12-17-3183) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-12-17-3183.md) |
| [Forskrift om satser for tilskudd til import av karbohydratvare](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2022-06-29-1241.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-06-29-1241) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-06-29-1241.md) |
| [Forskrift om satser for visse tilskuddsordninger for bearbeidede jordbruksvarer](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2005-01-28-60.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2005-01-28-60) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2005-01-28-60.md) |
| [Forskrift om satser i prisutjevningsordningen for melk og satser for produksjons](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2007-06-29-904.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2007-06-29-904) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2007-06-29-904.md) |
| [Forskrift om sertifikatmodell for handel med uflådd slakt av viltlevende storvil](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2017-02-06-141.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-02-06-141) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-02-06-141.md) |
| [Forskrift om seter og tilleggsjord m.m. i statsallmenning](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1984-06-22-1302.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1984-06-22-1302) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1984-06-22-1302.md) |
| [Forskrift om settepoteter](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1996-07-02-1447.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1996-07-02-1447) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1996-07-02-1447.md) |
| [Forskrift om sikkerhetsmekanisme ved import av landbruksvarer omfattet av ordnin](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2008-03-07-228.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2008-03-07-228) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2008-03-07-228.md) |
| [Forskrift om skadefelling, dødt vilt og bruk av vilt i oppdrett, forskning og dy](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2020-04-01-565.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-04-01-565) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-04-01-565.md) |
| [Forskrift om skogfond o.a.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2006-07-03-881.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2006-07-03-881) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2006-07-03-881.md) |
| [Forskrift om skogfrø og skogplanter.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1996-03-01-291.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1996-03-01-291) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1996-03-01-291.md) |
| [Forskrift om smittefarlig avfall fra helsetjeneste og dyrehelsetjeneste mv.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2005-10-11-1196.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2005-10-11-1196) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2005-10-11-1196.md) |
| [Forskrift om smitteforebyggende tiltak mot visse antibiotikaresistente bakterier](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2018-02-14-247.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2018-02-14-247) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2018-02-14-247.md) |
| [Forskrift om soner ved påvisning av Chronic Wasting Disease (CWD-sone)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2017-06-12-734.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-06-12-734) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-06-12-734.md) |
| [Forskrift om sporbarhet og merking av storfekjøtt](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2010-07-09-1131.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2010-07-09-1131) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2010-07-09-1131.md) |
| [Forskrift om sukker m.m.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2003-07-03-924.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2003-07-03-924) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2003-07-03-924.md) |
| [Forskrift om syltetøy og lignende produkter.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2003-07-03-939.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2003-07-03-939) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2003-07-03-939.md) |
| [Forskrift om såvarer](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1999-09-13-1052.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1999-09-13-1052) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1999-09-13-1052.md) |
| [Forskrift om særlige hygieneregler for næringsmidler av animalsk opprinnelse (an](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2008-12-22-1624.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2008-12-22-1624) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2008-12-22-1624.md) |
| [Forskrift om særskilte beskyttelsestiltak i forbindelse med aviær influensa ved ](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2006-01-23-66.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2006-01-23-66) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2006-01-23-66.md) |
| [Forskrift om særskilte beskyttelsestiltak mot ondartet lungesyke hos storfe ved ](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1999-03-01-275.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1999-03-01-275) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1999-03-01-275.md) |
| [Forskrift om særskilte beskyttelsestiltak rettet mot import av muslinger fra Tyr](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2022-03-25-469.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-03-25-469) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-03-25-469.md) |
| [Forskrift om særskilte beskyttelsestiltak ved import av akvakulturprodukter fra ](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2011-05-19-507.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2011-05-19-507) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2011-05-19-507.md) |
| [Forskrift om særskilte beskyttelsestiltak ved import av kjøtt og kjøttprodukter ](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2007-09-10-1032.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2007-09-10-1032) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2007-09-10-1032.md) |
| [Forskrift om særskilte beskyttelsestiltak ved import av ris og risprodukter fra ](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2012-01-12-35.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2012-01-12-35) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2012-01-12-35.md) |
| [Forskrift om særskilte beskyttelsestiltak ved innførsel av hund, katt og flygehu](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2001-01-04-7.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2001-01-04-7) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2001-01-04-7.md) |
| [Forskrift om særskilte beskyttelsestiltak ved innførsel av præriehunder fra USA,](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2003-07-09-945.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2003-07-09-945) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2003-07-09-945.md) |
| [Forskrift om særskilte beskyttelsestiltak ved innførsel fra Ukraina av visse pro](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2002-10-21-1166.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2002-10-21-1166) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2002-10-21-1166.md) |
| [Forskrift om særskilte kompensasjonsordninger mv. etter avvikling av hold av pel](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2022-07-08-1335.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-07-08-1335) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-07-08-1335.md) |
| [Forskrift om søknads- og rapporteringsfrister for pristilskudd og formidling av ](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2016-12-07-1458.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2016-12-07-1458) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2016-12-07-1458.md) |
| [Forskrift om tekniske tilpasninger og overgangsordninger på matområdet i forbind](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2004-05-20-756.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2004-05-20-756) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2004-05-20-756.md) |
| [Forskrift om tekniske tilpasninger og overgangsordninger på matområdet i forbind](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2007-10-29-1199.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2007-10-29-1199) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2007-10-29-1199.md) |
| [Forskrift om tekniske tilpasninger og overgangsordninger på matområdet i forbind](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2014-08-22-1121.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2014-08-22-1121) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2014-08-22-1121.md) |
| [Forskrift om tidligpensjon i reindriften](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2010-06-14-887.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2010-06-14-887) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2010-06-14-887.md) |
| [Forskrift om tilgjengeliggjøring av reintall i reindriftsnæringen](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2022-06-21-1119.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-06-21-1119) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-06-21-1119.md) |
| [Forskrift om tillatelse til innenlandsk bearbeiding av landbruksvarer (IB-forskr](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2020-06-23-1349.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-06-23-1349) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-06-23-1349.md) |
| [Forskrift om tilleggskrav ved import av høy og halm til dyrefôr](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2018-10-22-1599.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2018-10-22-1599) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2018-10-22-1599.md) |
| [Forskrift om tilsetningsstoffer til bruk i fôrvarer](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2005-04-12-319.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2005-04-12-319) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2005-04-12-319.md) |
| [Forskrift om tilskot til avløysing ved sjukdom og fødsel mv.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2014-12-19-1821.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2014-12-19-1821) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2014-12-19-1821.md) |
| [Forskrift om tilskot til landbruksvikarordninga](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2007-10-22-1167.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2007-10-22-1167) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2007-10-22-1167.md) |
| [Forskrift om tilskudd for levering av husdyrgjødsel til biogassanlegg](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2014-12-19-1815.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2014-12-19-1815) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2014-12-19-1815.md) |
| [Forskrift om tilskudd til arbeidsrettet kompetanseheving for pelsdyroppdrettere](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2020-07-03-1496.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-07-03-1496) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-07-03-1496.md) |
| [Forskrift om tilskudd til avløsning ved svangerskap, fødsel, adopsjon og dødsfal](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-06-22-2268.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-06-22-2268) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-06-22-2268.md) |
| [Forskrift om tilskudd til avrensordningen for poteter](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2009-04-02-386.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2009-04-02-386) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2009-04-02-386.md) |
| [Forskrift om tilskudd til distriktsplaner](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2024-06-20-1069.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-06-20-1069) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-06-20-1069.md) |
| [Forskrift om tilskudd til drenering av jordbruksjord](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2013-06-25-769.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-06-25-769) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-06-25-769.md) |
| [Forskrift om tilskudd til etablering og drift av produsentsammenslutninger for p](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2004-12-21-1745.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2004-12-21-1745) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2004-12-21-1745.md) |
| [Forskrift om tilskudd til fellesanlegg for frukt](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-12-21-3789.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-12-21-3789) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-12-21-3789.md) |
| [Forskrift om tilskudd til frøavl](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2016-12-12-1567.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2016-12-12-1567) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2016-12-12-1567.md) |
| [Forskrift om tilskudd til genressurstiltak – husdyr, planter og skogtrær](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2017-12-18-2236.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2017-12-18-2236) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2017-12-18-2236.md) |
| [Forskrift om tilskudd til investeringer i setrer med melkeproduksjon](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2026-04-29-683.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2026-04-29-683) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2026-04-29-683.md) |
| [Forskrift om tilskudd til klimarådgiving](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2026-02-23-262.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2026-02-23-262) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2026-02-23-262.md) |
| [Forskrift om tilskudd til konfliktforebyggende tiltak i forholdet mellom reindri](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2008-06-19-707.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2008-06-19-707) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2008-06-19-707.md) |
| [Forskrift om tilskudd til nærings- og miljøtiltak i skogbruket](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2004-02-04-447.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2004-02-04-447) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2004-02-04-447.md) |
| [Forskrift om tilskudd til pelsdyrfôrlag og andre tilvirkere av pelsdyrfôr.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2000-07-13-772.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2000-07-13-772) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2000-07-13-772.md) |
| [Forskrift om tilskudd til produsenter og slakterier som gjennomfører tiltak om ø](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2023-10-12-1623.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2023-10-12-1623) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2023-10-12-1623.md) |
| [Forskrift om tilskudd til produsenter og slakterier som gjennomfører tiltak om ø](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2024-10-24-2637.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-10-24-2637) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-10-24-2637.md) |
| [Forskrift om tilskudd til produsenter som gjennomfører opphold i eggproduksjonen](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2022-09-21-1626.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-09-21-1626) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-09-21-1626.md) |
| [Forskrift om tilskudd til produsentretta rådgiving i potetsektoren](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1999-09-09-1009.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1999-09-09-1009) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1999-09-09-1009.md) |
| [Forskrift om tilskudd til reinbeitedistrikter og reinlag](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2022-12-21-2468.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-12-21-2468) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-12-21-2468.md) |
| [Forskrift om tilskudd til reindriften for andel av verdiskaping fra vindkraft](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-11-26-2331.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-11-26-2331) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-11-26-2331.md) |
| [Forskrift om tilskudd til sertifisert settepotetavl](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2002-07-03-780.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2002-07-03-780) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2002-07-03-780.md) |
| [Forskrift om tilskudd til siidaandeler og reinlag](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2019-06-20-865.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-06-20-865) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-06-20-865.md) |
| [Forskrift om tilskudd til skogbruksplanlegging med miljøregistreringer](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2004-02-04-449.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2004-02-04-449) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2004-02-04-449.md) |
| [Forskrift om tilskudd til smågrisprodusenter som gjennomfører forlenget opphold ](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2024-03-13-448.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-03-13-448) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-03-13-448.md) |
| [Forskrift om tilskudd til spesielle miljøtiltak i jordbruket](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2004-02-04-448.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2004-02-04-448) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2004-02-04-448.md) |
| [Forskrift om tilskudd til tidligpensjonsordningen](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1999-02-03-190.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1999-02-03-190) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1999-02-03-190.md) |
| [Forskrift om tilskudd til tiltak for å gi barn og unge økt forståelse for bruk a](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2019-07-04-983.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-07-04-983) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-07-04-983.md) |
| [Forskrift om tilskudd til tiltak i Utvalgte kulturlandskap i jordbruket og verde](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2019-12-18-2024.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-12-18-2024) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-12-18-2024.md) |
| [Forskrift om tilskudd til tiltak i beiteområder](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2013-02-04-206.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-02-04-206) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-02-04-206.md) |
| [Forskrift om tilskudd til utgifter ved fôring og flytting som følge av manglende](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-06-22-2267.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-06-22-2267) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-06-22-2267.md) |
| [Forskrift om tilskudd til utjevning av kostnadene ved forsendelse av sæd og inse](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2015-04-30-427.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-04-30-427) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-04-30-427.md) |
| [Forskrift om tilskudd til veterinærreiser](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2015-04-30-426.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2015-04-30-426) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2015-04-30-426.md) |
| [Forskrift om tilskudd til viltformål](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2018-12-19-2172.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2018-12-19-2172) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2018-12-19-2172.md) |
| [Forskrift om tilskudd ved frakt av rein i forbindelse med slakting](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2009-06-17-657.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2009-06-17-657) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2009-06-17-657.md) |
| [Forskrift om tilskudd ved produksjonssvikt i plante- og honningproduksjon](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2012-01-17-56.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2012-01-17-56) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2012-01-17-56.md) |
| [Forskrift om tilsyn og kontroll ved import og eksport av levende dyr, annet avls](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1998-12-31-1484.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1998-12-31-1484) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1998-12-31-1484.md) |
| [Forskrift om tiltak for å begrense spredning av Chronic Wasting Disease (CWD)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2016-07-11-913.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2016-07-11-913) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2016-07-11-913.md) |
| [Forskrift om tiltak for å begrense spredningen av blåtunge hos drøvtyggere](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2024-09-27-2374.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-09-27-2374) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-09-27-2374.md) |
| [Forskrift om tiltak mot Phytophthora ramorum (Werres et al., 2001).](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2003-03-17-341.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2003-03-17-341) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2003-03-17-341.md) |
| [Forskrift om tiltak mot mørk ringråte i potet.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1996-05-14-498.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1996-05-14-498) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1996-05-14-498.md) |
| [Forskrift om tiltak mot sjukdommer og zoonotiske agens hos dyr på Svalbard](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2002-06-27-732.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2002-06-27-732) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2002-06-27-732.md) |
| [Forskrift om transporttilskott i skogbruket.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1993-11-11-1042.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1993-11-11-1042) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1993-11-11-1042.md) |
| [Forskrift om unntak fra båndtvang for servicehunder godkjent og tildelt av NAV](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-08-20-1673.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-08-20-1673) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-08-20-1673.md) |
| [Forskrift om unntak fra kravene om kontroll av økologiske produkter ved en grens](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2022-06-21-1172.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-06-21-1172) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-06-21-1172.md) |
| [Forskrift om unntak fra plikten til å sørge for oppholdsrom for dyr](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2014-08-11-1074.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2014-08-11-1074) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2014-08-11-1074.md) |
| [Forskrift om unntak frå lov om utnytting av rettar og lunnende m.m. i statsallme](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2010-08-12-1171.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2010-08-12-1171) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2010-08-12-1171.md) |
| [Forskrift om utlegging av åte og fôring av vilt](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2019-12-17-1878.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2019-12-17-1878) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2019-12-17-1878.md) |
| [Forskrift om utøvelse av jakt, felling og fangst](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2002-03-22-313.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2002-03-22-313) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2002-03-22-313.md) |
| [Forskrift om valg av tillitsmannsutvalg (distriktsstyre) og dets arbeidsoppgaver](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1987-03-04-164.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1987-03-04-164) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1987-03-04-164.md) |
| [Forskrift om varsel og melding om sjukdom hos dyr på Svalbard](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2014-12-19-1841.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2014-12-19-1841) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2014-12-19-1841.md) |
| [Forskrift om varsling ved eksport av visse farlige kjemikalier](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2020-11-04-2293.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-11-04-2293) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-11-04-2293.md) |
| [Forskrift om velferd for hest](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2005-06-02-505.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2005-06-02-505) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2005-06-02-505.md) |
| [Forskrift om velferd for hest og hund i konkurranser](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2020-12-09-2647.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-12-09-2647) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-12-09-2647.md) |
| [Forskrift om velferd for produksjonsdyr](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2006-07-03-885.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2006-07-03-885) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2006-07-03-885.md) |
| [Forskrift om velferd for småfe](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2005-02-18-160.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2005-02-18-160) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2005-02-18-160.md) |
| [Forskrift om vern av Eplejuice frå Hardanger/Eplemost frå Hardanger som geografi](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2005-11-22-1468.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2005-11-22-1468) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2005-11-22-1468.md) |
| [Forskrift om vern av Fjellam frå Ryfylke/Fjellam fra Ryfylke som geografisk nemn](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2024-03-14-435.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-03-14-435) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-03-14-435.md) |
| [Forskrift om vern av Hardangereple / Eple frå Hardanger / Hardangerepler / Epler](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2006-08-25-996.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2006-08-25-996) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2006-08-25-996.md) |
| [Forskrift om vern av Hardangermorellar / Morellar frå Hardanger / Hardangermorel](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2006-08-25-1006.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2006-08-25-1006) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2006-08-25-1006.md) |
| [Forskrift om vern av Hardangerplommer / Plommer frå Hardanger / Plommer fra Hard](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2006-08-25-998.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2006-08-25-998) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2006-08-25-998.md) |
| [Forskrift om vern av Hardangerpærer / Pærer frå Hardanger / Pærer fra Hardanger ](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2006-08-25-997.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2006-08-25-997) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2006-08-25-997.md) |
| [Forskrift om vern av Kurv frå Valdres som geografisk nemning](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2011-04-07-367.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2011-04-07-367) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2011-04-07-367.md) |
| [Forskrift om vern av Rein frå Jotunheimen/Rein fra Jotunheimen som geografisk ne](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2021-08-24-2570.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2021-08-24-2570) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2021-08-24-2570.md) |
| [Forskrift om vern av Sider frå Sogn / Cider frå Sogn som geografisk nemning](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-11-17-2283.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-11-17-2283) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-11-17-2283.md) |
| [Forskrift om vern av Villsau frå Norskekysten/Villsau fra Norskekysten som geogr](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2010-11-04-1402.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2010-11-04-1402) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2010-11-04-1402.md) |
| [Forskrift om vern av produktnemninga Gamalost frå Vik som beskytta geografisk ne](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2006-11-14-1235.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2006-11-14-1235) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2006-11-14-1235.md) |
| [Forskrift om vern av produktnemninga Sider frå Hardanger som beskytta geografisk](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2009-04-17-420.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2009-04-17-420) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2009-04-17-420.md) |
| [Forskrift om vin (vinforskriften)](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2013-03-21-370.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2013-03-21-370) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2013-03-21-370.md) |
| [Forskrift om volummodell melk](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2024-10-31-2605.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2024-10-31-2605) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2024-10-31-2605.md) |
| [Forskrift om å fjerne horn på dyr](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1976-11-20-1.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1976-11-20-1) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1976-11-20-1.md) |
| [Forskrift om økning i tollavgift – beskyttelsestollavgift – på landbruksvarer](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1998-12-17-1448.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1998-12-17-1448) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1998-12-17-1448.md) |
| [Forskrift om økologisk produksjon og merking av økologiske landbruksprodukter, a](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2022-06-11-1171.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-06-11-1171) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-06-11-1171.md) |
| [Forskrift som utfyller dyrehelseforskriften med bestemmelser om avlsmateriale fr](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2022-04-06-630.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-04-06-630) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-04-06-630.md) |
| [Forskrift som utfyller dyrehelseforskriften med bestemmelser om forebygging og b](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2022-04-06-634.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-04-06-634) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-04-06-634.md) |
| [Forskrift som utfyller dyrehelseforskriften med bestemmelser om forflytning av l](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2022-04-07-636.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-04-07-636) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-04-07-636.md) |
| [Forskrift som utfyller dyrehelseforskriften med bestemmelser om import av visse ](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2022-04-06-633.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-04-06-633) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-04-06-633.md) |
| [Forskrift som utfyller dyrehelseforskriften med bestemmelser om landdyranlegg og](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2022-04-07-637.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-04-07-637) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-04-07-637.md) |
| [Forskrift som utfyller dyrehelseforskriften med bestemmelser om melding, rapport](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2022-04-06-632.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-04-06-632) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-04-06-632.md) |
| [Forskrifter om pelsing av pelsdyr.](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1964-10-09-3.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1964-10-09-3) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1964-10-09-3.md) |
| [Midlertidig forskrift om forbud mot jakt på utsatt fugl](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1990-08-24-761.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1990-08-24-761) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1990-08-24-761.md) |
| [Midlertidig forskrift om støtte som følge av ekstraordinære utgifter til elektri](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2022-06-30-1273.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2022-06-30-1273) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2022-06-30-1273.md) |
| [Midlertidig forskrift om tilskudd til kornkjøpere – tilbud om utsatt leveranse a](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-10-29-2137.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-10-29-2137) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-10-29-2137.md) |
| [Midlertidig forskrift om tilskudd til kraftfôrprodusenter – kompensasjon for økt](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2025-10-29-2136.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2025-10-29-2136) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2025-10-29-2136.md) |
| [Midlertidig forskrift om tilskudd til reinbeitedistrikt 16 og reinbeitedistrikte](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2026-05-08-769.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2026-05-08-769) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2026-05-08-769.md) |
| [Midlertidig forskrift om unntak fra bestemmelsene i økologiforskriften om kontro](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-2020-09-28-1914.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/2020-09-28-1914) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-2020-09-28-1914.md) |
| [Overføring av fullmakt til Landbruksdepartementet etter lov om kvalitetskontroll](https://github.com/sondreskarsten/norwegian-laws/blob/main/forskrifter/forskrift-1991-11-15-737.md) | [lovdata.no](https://lovdata.no/dokument/SF/forskrift/1991-11-15-737) | [log](https://github.com/sondreskarsten/norwegian-laws/commits/law-history/forskrifter/forskrift-1991-11-15-737.md) |
