# Næringsrett

*73 lover*

| Lov | Korttittel | Departement |
|-----|-----------|-------------|
| [Bergverksordning for Svalbard](../lover/lov-1925-08-07.html) | Bergverksordning for Svalbard | Nærings- og fiskeridepartementet |
| [Lov om Aktieselskapet Vinmonopolet [vinmonopolloven]](../lover/lov-1931-06-19-18.html) | Vinmonopolloven | Helse- og omsorgsdepartementet |
| [Lov om Innovasjon Norge](../lover/lov-2003-12-19-130.html) | Lov om Innovasjon Norge | Nærings- og fiskeridepartementet |
| [Lov om Norges kontinentalsokkel](../lover/lov-2021-06-18-89.html) | Lov om Norges kontinentalsokkel | Utenriksdepartementet |
| [Lov om apotek (apotekloven)](../lover/lov-2000-06-02-39.html) | Apotekloven – apotl | Helse- og omsorgsdepartementet |
| [Lov om avgift av kull, jordoljer og andre mineraler og bergarter som utføres fra](../lover/lov-1925-07-17-2.html) | Lov om avgift av kull m.v. fra Svalbard | Justis- og beredskapsdepartementet |
| [Lov om avgift til forskning og utvikling i fiskeri- og havbruksnæringen](../lover/lov-2000-07-07-68.html) | Lov om eksportavgift på fiskevarer – fiskekspal | Nærings- og fiskeridepartementet |
| [Lov om avtalar med forbrukar om oppføring av ny bustad m.m. (bustadoppføringslov](../lover/lov-1997-06-13-43.html) | Bustadoppføringslova – buofl | Justis- og beredskapsdepartementet |
| [Lov om avtaler om deltidsbruksrett og langtidsferieprodukter mv. (tidspartloven)](../lover/lov-2012-05-25-27.html) | Tidspartloven | Barne- og familiedepartementet |
| [Lov om behandling av forbrukerklager i Forbrukertilsynet og Forbrukerklageutvalg](../lover/lov-2020-06-23-98.html) | Forbrukerklageloven | Barne- og familiedepartementet |
| [Lov om beskyttelse av mindreårige mot skadelige bildeprogram mv.](../lover/lov-2015-02-06-7.html) | Bildeprogramloven | Kultur- og likestillingsdepartementet |
| [Lov om besøksbidrag (besøksbidragsloven)](../lover/lov-2025-06-20-104.html) | Besøksbidragsloven | Nærings- og fiskeridepartementet |
| [Lov om betalingsutjevning [betalingsutjevningsloven]](../lover/lov-1935-05-31-2.html) | Betalingsutjevningsloven | Utenriksdepartementet |
| [Lov om bærekraftige produkter og verdikjeder (bærekraftige produkter-loven)](../lover/lov-2024-06-25-69.html) | Bærekraftige produkter-loven | Klima- og miljødepartementet |
| [Lov om det frie varebytte i EØS (EØS-vareloven)](../lover/lov-2013-04-12-13.html) | EØS-vareloven | Nærings- og fiskeridepartementet |
| [Lov om endringer i kringkastingsloven mv. (gjennomføring av endringsdirektiv til](../lover/lov-2025-02-28-2.html) | Endringslov til kringkastingsloven mv. | Kultur- og likestillingsdepartementet |
| [Lov om endringer i matloven (hjemmel for overtredelsesgebyr ved brudd på forskri](../lover/lov-2025-06-20-75.html) | Endringslov til matloven | Helse- og omsorgsdepartementet |
| [Lov om endringer i tobakksskadeloven (gjennomføring av direktiv 2014/40/EU og st](../lover/lov-2017-02-10-5.html) | Endringslov til tobakksskadeloven | Helse- og omsorgsdepartementet |
| [Lov om endringer i tobakksskadeloven (strengere regulering av e-sigaretter)](../lover/lov-2023-12-20-107.html) | Endringslov til tobakksskadeloven | Helse- og omsorgsdepartementet |
| [Lov om endringer i tobakksskadeloven (ulovlig handel med tobakksvarer mv.)](../lover/lov-2018-06-22-77.html) | Endringslov til tobakkskadeloven | Helse- og omsorgsdepartementet |
| [Lov om endringer i verdipapirhandelloven (forskriftshjemmel om tilbudsprisen ved](../lover/lov-2020-04-24-32.html) | Endringslov til verdipapirhandelloven og pakkereiseloven | Finansdepartementet |
| [Lov om erverv og utvinning av mineralressurser (mineralloven)](../lover/lov-2009-06-19-101.html) | Mineralloven | Nærings- og fiskeridepartementet |
| [Lov om europeisk meldeplikt for tekniske regler m.m. (EØS-høringsloven)](../lover/lov-2004-12-17-101.html) | EØS-høringsloven | Nærings- og fiskeridepartementet |
| [Lov om film og videogram](../lover/lov-1987-05-15-21.html) | Film- og videogramlova – filml | Kultur- og likestillingsdepartementet |
| [Lov om forbrukerkjøp (forbrukerkjøpsloven)](../lover/lov-2002-06-21-34.html) | Forbrukerkjøpsloven – fkjl | Justis- og beredskapsdepartementet |
| [Lov om forebygging og reduksjon av matsvinn (matsvinnloven)](../lover/lov-2025-06-20-103.html) | Matsvinnloven | Landbruks- og matdepartementet |
| [Lov om fristar og betalingsutsetjing og ymist anna i serlege tilhøve](../lover/lov-1964-12-04-1.html) | Lov om fristar og betalingsutsetjing | Justis- og beredskapsdepartementet |
| [Lov om frivillige auksjoner [auksjonsloven]](../lover/lov-1918-08-14-3.html) | Auksjonsloven | Justis- og beredskapsdepartementet |
| [Lov om førstehandsomsetning av viltlevande marine ressursar (fiskesalslagslova)](../lover/lov-2013-06-21-75.html) | Fiskesalslagslova | Nærings- og fiskeridepartementet |
| [Lov om gjennomføring av internasjonale sanksjoner (sanksjonsloven)](../lover/lov-2021-04-16-18.html) | Sanksjonsloven | Utenriksdepartementet |
| [Lov om gjennomføring og kontroll av EØS-avtalens konkurranseregler mv. (EØS-konk](../lover/lov-2004-03-05-11.html) | EØS-konkurranseloven | Nærings- og fiskeridepartementet |
| [Lov om handelsagenter og handelsreisende (agenturloven)](../lover/lov-1992-06-19-56.html) | Agenturloven – agl | Justis- og beredskapsdepartementet |
| [Lov om handelsverksemd med brukte og kasserte ting (brukthandellova)](../lover/lov-1999-12-22-105.html) | Brukthandellova – brhll | Nærings- og fiskeridepartementet |
| [Lov om handheving av det frie varebyttet innan EØS](../lover/lov-2005-03-04-12.html) | Lov om det frie varebyttet innan EØS | Justis- og beredskapsdepartementet |
| [Lov om helligdager og helligdagsfred](../lover/lov-1995-02-24-12.html) | Helligdagsfredloven | Barne- og familiedepartementet |
| [Lov om håndverkertjenester m.m for forbrukere [håndverkertjenesteloven]](../lover/lov-1989-06-16-63.html) | Håndverkertjenesteloven – hvtjl | Justis- og beredskapsdepartementet |
| [Lov om innførsle- og utførsleregulering](../lover/lov-1997-06-06-32.html) | Innførsle- og utførslereguleringslova | Utenriksdepartementet |
| [Lov om kommisjon (kommisjonsloven)](../lover/lov-1916-06-30-1.html) | Kommisjonsloven – kml | Justis- og beredskapsdepartementet |
| [Lov om kontroll med eksport av strategiske varer, tjenester og teknologi m.v. [e](../lover/lov-1987-12-18-93.html) | Eksportkontrolloven – ekspktrl | Utenriksdepartementet |
| [Lov om kontroll med markedsføring og avtalevilkår mv. (markedsføringsloven)](../lover/lov-2009-01-09-2.html) | Markedsføringsloven – mfl | Barne- og familiedepartementet |
| [Lov om kontroll med produkter og forbrukertjenester (produktkontrolloven)](../lover/lov-1976-06-11-79.html) | Produktkontrolloven – prodktrl | Justis- og beredskapsdepartementet |
| [Lov om kornforvaltning m.v.](../lover/lov-2000-01-21-7.html) | Kornforvaltningsloven | Landbruks- og matdepartementet |
| [Lov om kosmetikk og kroppspleieprodukt m.m. (kosmetikklova)](../lover/lov-2005-12-21-126.html) | Kosmetikklova | Helse- og omsorgsdepartementet |
| [Lov om matproduksjon og mattrygghet mv. (matloven)](../lover/lov-2003-12-19-124.html) | Matloven – matl | Helse- og omsorgsdepartementet |
| [Lov om medisinsk utstyr](../lover/lov-2020-05-07-37.html) | Lov om medisinsk utstyr | Helse- og omsorgsdepartementet |
| [Lov om merking av forbruksvarer mv. (forbrukermerkeloven)](../lover/lov-1981-12-18-90.html) | Forbrukermerkeloven | Barne- og familiedepartementet |
| [Lov om mesterbrev i håndverk og annen næring [mesterbrevloven]](../lover/lov-1986-06-20-35.html) | Mesterbrevloven | Nærings- og fiskeridepartementet |
| [Lov om midlertidig endring av alkoholloven (unntak fra maksimaltiden for skjenki](../lover/lov-2026-05-29-21.html) | Endringslov til alkoholloven | Helse- og omsorgsdepartementet |
| [Lov om midlertidig tilskuddsordning for foretak med utgifter til innreisekarante](../lover/lov-2020-12-21-175.html) | Lov om midl. tilskudd for innreisekarantene | Nærings- og fiskeridepartementet |
| [Lov om mineralvirksomhet og forvaltning av mineralressurser (mineralloven)](../lover/lov-2025-06-20-107.html) | Mineralloven | Nærings- og fiskeridepartementet |
| [Lov om mineralvirksomhet på kontinentalsokkelen (havbunnsmineralloven)](../lover/lov-2019-03-22-7.html) | Havbunnsmineralloven | Energidepartementet |
| [Lov om næringsberedskap (næringsberedskapsloven)](../lover/lov-2011-12-16-65.html) | Næringsberedskapsloven | Nærings- og fiskeridepartementet |
| [Lov om omsetning av alkoholholdig drikk m.v. (alkoholloven)](../lover/lov-1989-06-02-27.html) | Alkoholloven – alkhl | Helse- og omsorgsdepartementet |
| [Lov om opphevelse av omstillingslova](../lover/lov-2019-12-13-83.html) | Lov om opphevelse av omstillingslova | Nærings- og fiskeridepartementet |
| [Lov om oppheving av lov om erverv av næringsverksemd](../lover/lov-2002-06-21-38.html) | Lov om oppheving av ervervsloven mv. | Nærings- og fiskeridepartementet |
| [Lov om opplysningsplikt og angrerett ved fjernsalg og salg utenom faste forretni](../lover/lov-2014-06-20-27.html) | Angrerettloven – angrl | Barne- og familiedepartementet |
| [Lov om pakkereiser og reisegaranti mv. (pakkereiseloven)](../lover/lov-2018-06-15-32.html) | Pakkereiseloven | Barne- og familiedepartementet |
| [Lov om petroleumsvirksomhet [petroleumsloven]](../lover/lov-1996-11-29-72.html) | Petroleumsloven – petrl | Energidepartementet |
| [Lov om prisregler for jern og stål](../lover/lov-1974-06-07-22.html) | Lov om prisregler for jern og stål | Nærings- og fiskeridepartementet |
| [Lov om prisregulering ved import av fisk og fiskevarer m.v.](../lover/lov-1993-06-11-73.html) | Lov om prisregulering ved fiskeimport m.v. | Nærings- og fiskeridepartementet |
| [Lov om produktansvar [produktansvarsloven]](../lover/lov-1988-12-23-104.html) | Produktansvarsloven – prodansvl | Justis- og beredskapsdepartementet |
| [Lov om registrering av import og leveranser av råolje i Det europeiske økonomisk](../lover/lov-1999-06-25-54.html) | Lov om registrering av råoljehandel – råolregl | Energidepartementet |
| [Lov om regulering av eksporten av fisk, fiskevarer og marine produkter (fiskeeks](../lover/lov-1990-04-27-9.html) | Fiskeeksportloven – fiskeekspl | Nærings- og fiskeridepartementet |
| [Lov om reservasjonssystemer for flyreiser mv.](../lover/lov-2016-09-09-80.html) | Lov om reservasjonssystemer for flyreiser mv. | Samferdselsdepartementet |
| [Lov om rett for handverkarar o.a. til å selja ting som ikkje vert henta](../lover/lov-1953-05-29-1.html) | Lov om rett til å selja uhenta ting | Justis- og beredskapsdepartementet |
| [Lov om serveringsvirksomhet (serveringsloven)](../lover/lov-1997-06-13-55.html) | Serveringsloven | Nærings- og fiskeridepartementet |
| [Lov om tilsyn med elektriske anlegg og elektrisk utstyr (el-tilsynsloven)](../lover/lov-1929-05-24-4.html) | El-tilsynsloven | Justis- og beredskapsdepartementet |
| [Lov om tjenestevirksomhet (tjenesteloven)](../lover/lov-2009-06-19-103.html) | Tjenesteloven | Nærings- og fiskeridepartementet |
| [Lov om varer av edelt metall mv. [edelmetalloven]](../lover/lov-2010-09-03-52.html) | Edelmetalloven | Nærings- og fiskeridepartementet |
| [Lov om vern mot tobakksskader (tobakksskadeloven)](../lover/lov-1973-03-09-14.html) | Tobakksskadeloven – tobskl | Helse- og omsorgsdepartementet |
| [Lov om visse sider av elektronisk handel og andre informasjonssamfunnstjenester ](../lover/lov-2003-05-23-35.html) | Ehandelsloven – e-hl | Digitaliserings- og forvaltningsdepartementet |
| [Lov om vitenskapelig utforskning og undersøkelse etter og utnyttelse av andre un](../lover/lov-1963-06-21-12.html) | Lov om andre undersjøiske naturforekomster | Nærings- og fiskeridepartementet |
| [Lov til å fremja umsetnaden av jordbruksvaror](../lover/lov-1936-07-10-6.html) | Lov til å fremja umsetnaden av jordbruksvaror | Landbruks- og matdepartementet |
