# Pensjons- og trygderettStats-, statsforfatnings- og statsborgerrett

*5 lover*

| Lov | Korttittel | Departement |
|-----|-----------|-------------|
| [Lov om pensjonering av militært tilsatte som etter søknad er gitt avskjed med re](/norwegian-laws/lover/lov-1957-05-03.html) | Lov om pensjonering av militært tilsatte | Arbeids- og inkluderingsdepartementet |
| [Lov om pensjonsordning for Stortingets ombudsmann for forvaltningen](/norwegian-laws/lover/lov-1966-05-06.html) | Lov om pensjonsordning for sivilombudsmannen | Arbeids- og inkluderingsdepartementet |
| [Lov om pensjonsordning for ledsagere i utenrikstjenesten](/norwegian-laws/lover/lov-1999-01-15-1.html) | Lov om ledsagerpensjon i utenrikstjenesten | Arbeids- og inkluderingsdepartementet |
| [Lov om pensjonsordning for stortingsrepresentanter og regjeringsmedlemmer (stort](/norwegian-laws/lover/lov-2011-12-16-60.html) | Stortings- og regjeringspensjonsloven | Arbeids- og inkluderingsdepartementet |
| [Lov om utvalget for gjennomgang av stortingspensjoner](/norwegian-laws/lover/lov-2008-10-17-79.html) | Stortingspensjonsutvalgsloven | Justis- og beredskapsdepartementet |
