# Tvangsfullbyrdelse

*7 lover*

| Lov | Korttittel | Departement |
|-----|-----------|-------------|
| [Lov om anerkjennelse og fullbyrding av nordiske dommer på privatrettens område](../lover/lov-1977-06-10-71.html) | Lov om nordiske privatrettslige dommer | Justis- og beredskapsdepartementet |
| [Lov om besøksbidrag (besøksbidragsloven)](../lover/lov-2025-06-20-104.html) | Besøksbidragsloven | Nærings- og fiskeridepartementet |
| [Lov om eierseksjoner (eierseksjonsloven)](../lover/lov-2017-06-16-65.html) | Eierseksjonsloven – eiersl | Kommunal- og distriktsdepartementet |
| [Lov om endringer i konfliktrådsloven, straffeloven og straffeprosessloven mv. (s](../lover/lov-2023-12-20-110.html) | Endringslov til konfliktrådsloven, straffeloven mv | Justis- og beredskapsdepartementet |
| [Lov om innkreving av statlige krav mv. (innkrevingsloven)](../lover/lov-2025-04-25-12.html) | Innkrevingsloven | Finansdepartementet |
| [Lov om innkreving av underholdsbidrag mv. (bidragsinnkrevingsloven)](../lover/lov-2005-04-29-20.html) | Bidragsinnkrevingsloven | Barne- og familiedepartementet |
| [Lov om tvangsfullbyrdelse (tvangsfullbyrdelsesloven)](../lover/lov-1992-06-26-86.html) | Tvangsfullbyrdelsesloven – tvangsloven | Justis- og beredskapsdepartementet |
