# Fast eiendoms rettsforhold

*38 lover*

| Lov | Korttittel | Departement |
|-----|-----------|-------------|
| [Lov om avhending av fast eigedom (avhendingslova)](../lover/lov-1992-07-03-93.html) | Avhendingslova – avhl | Justis- og beredskapsdepartementet |
| [Lov om behandling av opplysninger i kredittopplysningsvirksomhet (kredittopplysn](../lover/lov-2019-12-20-109.html) | Kredittopplysningsloven | Barne- og familiedepartementet |
| [Lov om burettslag (burettslagslova)](../lover/lov-2003-06-06-39.html) | Burettslagslova – brl | Kommunal- og distriktsdepartementet |
| [Lov om bustadbyggjelag (bustadbyggjelagslova)](../lover/lov-2003-06-06-38.html) | Bustadbyggjelagslova – bbl | Kommunal- og distriktsdepartementet |
| [Lov om dokumentavgift (dokumentavgiftsloven)](../lover/lov-1975-12-12-59.html) | Dokumentavgiftsloven – dal | Finansdepartementet |
| [Lov om eiendomsmegling (eiendomsmeglingsloven)](../lover/lov-2007-06-29-73.html) | Eiendomsmeglingsloven – emgll | Finansdepartementet |
| [Lov om eierseksjoner (eierseksjonsloven)](../lover/lov-2017-06-16-65.html) | Eierseksjonsloven – eiersl | Kommunal- og distriktsdepartementet |
| [Lov om eigedomsregistrering (matrikkellova)](../lover/lov-2005-06-17-101.html) | Matrikkellova | Kommunal- og distriktsdepartementet |
| [Lov om endringer i barnetrygdloven og midlertidige endringer i lovverket som føl](../lover/lov-2024-06-25-53.html) | Endringslov til barnetrygdloven mv. (Ukraina) | Arbeids- og inkluderingsdepartementet |
| [Lov om endringer i konfliktrådsloven, straffeloven og straffeprosessloven mv. (s](../lover/lov-2023-12-20-110.html) | Endringslov til konfliktrådsloven, straffeloven mv | Justis- og beredskapsdepartementet |
| [Lov om endringer i plan- og bygningsloven og matrikkellova (nye virkemidler ved ](../lover/lov-2025-06-20-93.html) | Endringslov til plan- og bygningsloven og matrikkellova | Kommunal- og distriktsdepartementet |
| [Lov om endringer i regnskapsloven mv. (bærekraftsrapportering)](../lover/lov-2024-06-21-42.html) | Endringslov til regnskapsloven mv. | Finansdepartementet |
| [Lov om endringer i skipsarbeidsloven og NIS-loven (tydelige og mer forutsigbare ](../lover/lov-2026-04-10-14.html) | Endringslov til skipsarbeidsloven og NIS-loven | Nærings- og fiskeridepartementet |
| [Lov om endringer i tomtefesteloven (festeavgift ved forlengelse m.m.)](../lover/lov-2015-06-19-63.html) | Endringslov til tomtefesteloven | Justis- og beredskapsdepartementet |
| [Lov om endringer i veglova mv. (overføring av fylkesveiadministrasjon)](../lover/lov-2019-06-21-68.html) | Endringslov til veglova mv. (overføring av fylkesveiadministrasjon) | Samferdselsdepartementet |
| [Lov om enerett til foretaksnavn og andre forretningskjennetegn mv. (foretaksnavn](../lover/lov-1985-06-21-79.html) | Foretaksnavneloven – ftnavnl | Nærings- og fiskeridepartementet |
| [Lov om fiendegods [fiendegodsloven]](../lover/lov-1950-12-15-4.html) | Fiendegodsloven | Justis- og beredskapsdepartementet |
| [Lov om godtroerverv av løsøre [godtroervervloven]](../lover/lov-1978-06-02-37.html) | Godtroervervloven – ekstl | Justis- og beredskapsdepartementet |
| [Lov om grannegjerde [grannegjerdelova]](../lover/lov-1961-05-05.html) | Grannegjerdelova – ggl | Landbruks- og matdepartementet |
| [Lov om hendelege eigedomshøve](../lover/lov-1969-04-10-17.html) | Hendelege eigedomshøvelova – hendl | Justis- og beredskapsdepartementet |
| [Lov om hevd [hevdslova]](../lover/lov-1966-12-09-1.html) | Hevdslova – hevdsl | Justis- og beredskapsdepartementet |
| [Lov om hittegods [hittegodslova]](../lover/lov-1953-05-29-3.html) | Hittegodslova – hgl | Justis- og beredskapsdepartementet |
| [Lov om husleieavtaler (husleieloven)](../lover/lov-1999-03-26-17.html) | Husleieloven – husll | Kommunal- og distriktsdepartementet |
| [Lov om infrastruktur for geografisk informasjon (geodataloven)](../lover/lov-2010-09-03-56.html) | Geodataloven | Kommunal- og distriktsdepartementet |
| [Lov om kommunal forkjøpsrett til leiegårder](../lover/lov-1977-04-29-34.html) | Lov om kommunal forkjøpsrett til leiegårder | Kommunal- og distriktsdepartementet |
| [Lov om løysingsrettar](../lover/lov-1994-12-09-64.html) | Lov om løysingsrettar – løysl | Justis- og beredskapsdepartementet |
| [Lov om mortifikasjon av skuldbrev m.v. [mortifikasjonslova]](../lover/lov-1959-12-18-1.html) | Mortifikasjonslova | Justis- og beredskapsdepartementet |
| [Lov om norsk internasjonalt skipsregister [NIS-loven]](../lover/lov-1987-06-12-48.html) | NIS-loven – NISl | Nærings- og fiskeridepartementet |
| [Lov om oreigning av fast eigedom (oreigningslova)](../lover/lov-1959-10-23-3.html) | Oreigningslova – orl | Justis- og beredskapsdepartementet |
| [Lov om registrering av elektriske kraftledninger [kraftledningsregisterloven]](../lover/lov-1927-07-01-1.html) | Kraftledningsregisterloven – kregl | Justis- og beredskapsdepartementet |
| [Lov om rett for handverkarar o.a. til å selja ting som ikkje vert henta](../lover/lov-1953-05-29-1.html) | Lov om rett til å selja uhenta ting | Justis- og beredskapsdepartementet |
| [Lov om rettshøve mellom grannar (grannelova)](../lover/lov-1961-06-16-15.html) | Grannelova – gl | Justis- og beredskapsdepartementet |
| [Lov om sameige [sameigelova]](../lover/lov-1965-06-18-6.html) | Sameigelova – saml | Justis- og beredskapsdepartementet |
| [Lov om skjønn og ekspropriasjonssaker [skjønnsprosessloven]](../lover/lov-1917-06-01-1.html) | Skjønnsprosessloven – skjl | Justis- og beredskapsdepartementet |
| [Lov om tinglysing [tinglysingsloven]](../lover/lov-1935-06-07-2.html) | Tinglysingsloven – tingl | Justis- og beredskapsdepartementet |
| [Lov om tomtefeste](../lover/lov-1996-12-20-106.html) | Tomtefestelova – tfl | Justis- og beredskapsdepartementet |
| [Lov om vederlag ved oreigning av fast eigedom [ekspropriasjonserstatningslova]](../lover/lov-1984-04-06-17.html) | Ekspropriasjonserstatningslova – orvl | Justis- og beredskapsdepartementet |
| [Lov um særlege råderettar over framand eigedom [servituttlova]](../lover/lov-1968-11-29.html) | Servituttlova – servl | Justis- og beredskapsdepartementet |
