# Sivil- og straffeprosess

*44 lover*

| Lov | Korttittel | Departement |
|-----|-----------|-------------|
| [Lov om Likestillings- og diskrimineringsombudet og Diskrimineringsnemnda (diskri](/norwegian-laws/lover/lov-2017-06-16-50.html) | Diskrimineringsombudsloven – diskrol | Kultur- og likestillingsdepartementet |
| [Lov om advokater og andre som yter rettslig bistand (advokatloven)](/norwegian-laws/lover/lov-2022-05-12-28.html) | Advokatloven | Justis- og beredskapsdepartementet |
| [Lov om anke til Trygderetten (trygderettsloven)](/norwegian-laws/lover/lov-1966-12-16-9.html) | Trygderettsloven – trrl | Arbeids- og inkluderingsdepartementet |
| [Lov om behandling av forbrukerklager i Forbrukertilsynet og Forbrukerklageutvalg](/norwegian-laws/lover/lov-2020-06-23-98.html) | Forbrukerklageloven | Barne- og familiedepartementet |
| [Lov om domstolene (domstolloven)](/norwegian-laws/lover/lov-1915-08-13-5.html) | Domstolloven – dl | Justis- og beredskapsdepartementet |
| [Lov om endringar i straffegjennomføringsloven mv.](/norwegian-laws/lover/lov-2013-06-14-44.html) | Endringslov til straffegjennomføringsloven mv. | Justis- og beredskapsdepartementet |
| [Lov om endringer i domstolloven mv. (saksfordeling m.m.)](/norwegian-laws/lover/lov-2026-05-07-17.html) | Endringslov til domstolloven mv. | Justis- og beredskapsdepartementet |
| [Lov om endringer i ekomloven og straffeprosessloven mv. (gjennomføring av EUs da](/norwegian-laws/lover/lov-2011-04-15-11.html) | Endringslov om datalagringsdirektivet | Justis- og beredskapsdepartementet |
| [Lov om endringer i folketrygdloven og enkelte andre lover](/norwegian-laws/lover/lov-2019-12-20-84.html) | Endringslov til folketrygdloven og enkelte andre lover | Arbeids- og inkluderingsdepartementet |
| [Lov om endringer i forsvarsloven mv. (militær disiplinærmyndighet)](/norwegian-laws/lover/lov-2023-11-24-84.html) | Endringslov til forsvarsloven mv. (militær disiplinærmyndighet) | Forsvarsdepartementet |
| [Lov om endringer i konfliktrådsloven og straffeloven mv. (strafferettslige reaks](/norwegian-laws/lover/lov-2024-11-29-73.html) | Endringslov til konfliktrådsloven og straffeloven mv. | Justis- og beredskapsdepartementet |
| [Lov om endringer i konfliktrådsloven, straffeloven og straffeprosessloven mv. (s](/norwegian-laws/lover/lov-2023-12-20-110.html) | Endringslov til konfliktrådsloven, straffeloven mv | Justis- og beredskapsdepartementet |
| [Lov om endringer i rettshjelpsloven mv. (prioriterte sakstyper for rettshjelp mv](/norwegian-laws/lover/lov-2025-06-20-82.html) | Endringslov til rettshjelpsloven mv. | Justis- og beredskapsdepartementet |
| [Lov om endringer i straffegjennomføringsloven mv. (isolasjon i fengsel)](/norwegian-laws/lover/lov-2026-05-12-18.html) | Endringslov til straffegjennomføringsloven mv. | Justis- og beredskapsdepartementet |
| [Lov om endringer i straffeloven og legemiddelloven mv. (befatning med mindre men](/norwegian-laws/lover/lov-2025-06-20-83.html) | Endringslov til straffeloven og legemiddelloven mv. | Justis- og beredskapsdepartementet |
| [Lov om endringer i straffeloven, straffeprosessloven, straffegjennomføringsloven](/norwegian-laws/lover/lov-2012-01-20-6.html) | Endringslov til straffeloven mv. | Justis- og beredskapsdepartementet |
| [Lov om endringer i trygderettsloven mv. (ankeerklæring til Trygderetten, avgjøre](/norwegian-laws/lover/lov-2025-06-20-38.html) | Endringslov til trygderettsloven mv. | Arbeids- og inkluderingsdepartementet |
| [Lov om endringer i utleveringsloven m.m](/norwegian-laws/lover/lov-2012-06-22-52.html) | Endringslov til utleveringsloven m.m | Justis- og beredskapsdepartementet |
| [Lov om foreldelse av fordringer (foreldelsesloven)](/norwegian-laws/lover/lov-1979-05-18-18.html) | Foreldelsesloven – fl | Justis- og beredskapsdepartementet |
| [Lov om fri rettshjelp [rettshjelploven]](/norwegian-laws/lover/lov-1980-06-13-35.html) | Rettshjelploven – rhjl | Justis- og beredskapsdepartementet |
| [Lov om fullbyrding av nordiske dommer på straff m.v.](/norwegian-laws/lover/lov-1963-11-15.html) | Lov om fullbyrding av nordiske straffedommer | Justis- og beredskapsdepartementet |
| [Lov om gjennomføring av straff mv. (straffegjennomføringsloven)](/norwegian-laws/lover/lov-2001-05-18-21.html) | Straffegjennomføringsloven – strgjfl | Justis- og beredskapsdepartementet |
| [Lov om gjennomføring i norsk rett av De forente nasjoners sikkerhetsråds vedtak ](/norwegian-laws/lover/lov-1994-06-24-38.html) | Lov om krigsforbryterdomstol, Jugoslavia m m | Justis- og beredskapsdepartementet |
| [Lov om gjennomføring i norsk rett av Den internasjonale straffedomstols vedtekte](/norwegian-laws/lover/lov-2001-06-15-65.html) | Lov om gjennomføring av Roma-vedtektene | Justis- og beredskapsdepartementet |
| [Lov om granskingskommisjonen for brannen på Scandinavian Star](/norwegian-laws/lover/lov-2016-04-29-6.html) | Lov om granskingskommisjonen for Scandinavian Star | Justis- og beredskapsdepartementet |
| [Lov om informasjonstilgang for Riksrevisjonen ved undersøkelser av saker som gje](/norwegian-laws/lover/lov-2022-06-17-49.html) | Lov om informasjonstilgang for Riksrevisjonen | Finansdepartementet |
| [Lov om informasjonstilgang m.m. for det uavhengige utvalget som skal granske str](/norwegian-laws/lover/lov-2023-06-09-26.html) | Lov om informasjonstilgang m.m. for Baneheia-utvalget | Justis- og beredskapsdepartementet |
| [Lov om konfliktrådsbehandling (konfliktrådsloven)](/norwegian-laws/lover/lov-2014-06-20-49.html) | Konfliktrådsloven – konfrådl | Justis- og beredskapsdepartementet |
| [Lov om mekling og rettergang i sivile tvister (tvisteloven)](/norwegian-laws/lover/lov-2005-06-17-90.html) | Tvisteloven – tvl | Justis- og beredskapsdepartementet |
| [Lov om nordisk vitneplikt](/norwegian-laws/lover/lov-1975-03-21-9.html) | Lov om nordisk vitneplikt | Justis- og beredskapsdepartementet |
| [Lov om notarius publicus](/norwegian-laws/lover/lov-2002-04-26-12.html) | Lov om notarius publicus | Justis- og beredskapsdepartementet |
| [Lov om overføring av domfelte](/norwegian-laws/lover/lov-1991-07-20-67.html) | Lov om overføring av domfelte – domfovfl | Justis- og beredskapsdepartementet |
| [Lov om overføring av straffeforfølging fra eller til annet europeisk land](/norwegian-laws/lover/lov-1977-03-25-22.html) | Lov om overføring av straffeforfølging | Justis- og beredskapsdepartementet |
| [Lov om pågriping og overlevering til og frå Noreg for straffbare forhold på grun](/norwegian-laws/lover/lov-2012-01-20-4.html) | Arrestordreloven | Justis- og beredskapsdepartementet |
| [Lov om rettergangsmåten i straffesaker (Straffeprosessloven)](/norwegian-laws/lover/lov-1981-05-22-25.html) | Straffeprosessloven – strpl | Justis- og beredskapsdepartementet |
| [Lov om rettergangsordningens ikrafttræden](/norwegian-laws/lover/lov-1918-08-14-4.html) | Rettergangsordningens ikrafttrædelseslov | Justis- og beredskapsdepartementet |
| [Lov om rettsgebyr (rettsgebyrloven)](/norwegian-laws/lover/lov-1982-12-17-86.html) | Rettsgebyrloven | Justis- og beredskapsdepartementet |
| [Lov om utdrag i sivile saker og straffesaker [rettsutdragsloven]](/norwegian-laws/lover/lov-1918-08-14-2.html) | Rettsutdragsloven | Justis- og beredskapsdepartementet |
| [Lov om utlevering av lovbrytere m.v. [utleveringsloven]](/norwegian-laws/lover/lov-1975-06-13-39.html) | Utleveringsloven – utlevl | Justis- og beredskapsdepartementet |
| [Lov om utlevering for å få iverksatt vedtak om frihetsinngrep truffet av myndigh](/norwegian-laws/lover/lov-1970-06-05-35.html) | Lov om utlevering mellom nordiske land | Justis- og beredskapsdepartementet |
| [Lov om vidners og sakkyndiges godtgjørelse m.v.](/norwegian-laws/lover/lov-1916-07-21-2.html) | Lov om vidners og sakkyndiges godtgjørelse | Justis- og beredskapsdepartementet |
| [Lov om voldgift](/norwegian-laws/lover/lov-2004-05-14-25.html) | Voldgiftsloven – vogl | Justis- og beredskapsdepartementet |
| [Overenskomst mellem Norge og Storbritannia angående den civile rettergang](/norwegian-laws/lover/lov-1931-01-30.html) | Rettergangsoverenskomst med Storbritannia | Justis- og beredskapsdepartementet |
| [Overenskomst mellom Norge og Storbritannia om gjensidig anerkjennelse og fullbyr](/norwegian-laws/lover/lov-1961-06-12.html) | Sivildomsoverenskomst med Storbritannia | Justis- og beredskapsdepartementet |
