# Utlendingsrett

*19 lover*

| Lov | Korttittel | Departement |
|-----|-----------|-------------|
| [Lov om endringer i barnetrygdloven og midlertidige endringer i lovverket som føl](../lover/lov-2024-06-25-53.html) | Endringslov til barnetrygdloven mv. (Ukraina) | Arbeids- og inkluderingsdepartementet |
| [Lov om endringer i barnevernsloven mv. (kvalitetsløftet i barnevernet)](../lover/lov-2025-06-20-39.html) | Endringslov til barnevernsloven mv. | Barne- og familiedepartementet |
| [Lov om endringer i folketrygdloven og enkelte andre lover](../lover/lov-2019-12-20-84.html) | Endringslov til folketrygdloven og enkelte andre lover | Arbeids- og inkluderingsdepartementet |
| [Lov om endringer i grenseloven og utlendingsloven mv. (interoperabilitet og visu](../lover/lov-2024-06-21-47.html) | Endringslov til grenseloven og utlendingsloven mv. | Justis- og beredskapsdepartementet |
| [Lov om endringer i integreringsloven (integreringserklæring)](../lover/lov-2026-06-12-23.html) | Endringslov til integreringsloven | Arbeids- og inkluderingsdepartementet |
| [Lov om endringer i integreringsloven mv. (økt arbeidsretting og formell opplærin](../lover/lov-2025-06-20-35.html) | Endringslov til integreringsloven mv. | Arbeids- og inkluderingsdepartementet |
| [Lov om endringer i konfliktrådsloven, straffeloven og straffeprosessloven mv. (s](../lover/lov-2023-12-20-110.html) | Endringslov til konfliktrådsloven, straffeloven mv | Justis- og beredskapsdepartementet |
| [Lov om endringer i rettshjelpsloven mv. (prioriterte sakstyper for rettshjelp mv](../lover/lov-2025-06-20-82.html) | Endringslov til rettshjelpsloven mv. | Justis- og beredskapsdepartementet |
| [Lov om endringer i utlendingsloven (partsbegrepet mv. i utlendingssaker)](../lover/lov-2022-03-25-15.html) | Endringslov til utlendingsloven | Justis- og beredskapsdepartementet |
| [Lov om endringer i utlendingsloven (visitasjon og undersøkelse i forbindelse med](../lover/lov-2022-12-20-120.html) | Endringslov til utlendingsloven | Justis- og beredskapsdepartementet |
| [Lov om endringer i utlendingsloven mv. (familieinnvandring m.m.)](../lover/lov-2025-06-20-84.html) | Endringslov til utlendingsloven mv. | Justis- og beredskapsdepartementet |
| [Lov om endringer i utlendingsloven mv. (straff for utilbørlig utnyttelse av utle](../lover/lov-2026-06-12-32.html) | Endringslov til utlendingsloven mv. | Justis- og beredskapsdepartementet |
| [Lov om grensetilsyn og grensekontroll av personer (grenseloven)](../lover/lov-2018-04-20-8.html) | Grenseloven | Justis- og beredskapsdepartementet |
| [Lov om integrering gjennom opplæring, utdanning og arbeid (integreringsloven)](../lover/lov-2020-11-06-127.html) | Integreringsloven | Arbeids- og inkluderingsdepartementet |
| [Lov om midlertidige endringer i lovverket som følge av ankomst av fordrevne fra ](../lover/lov-2026-06-12-22.html) | Midlertidig endringslov, ankomst av fordrevne fra Ukraina | Arbeids- og inkluderingsdepartementet |
| [Lov om midlertidige endringer i utlendingsloven (beredskapshjemmel for innkvarte](../lover/lov-2024-06-21-50.html) | Midlertidig endringslov til utlendingsloven | Justis- og beredskapsdepartementet |
| [Lov om offentlige organers ansvar for bruk av tolk mv. (tolkeloven)](../lover/lov-2021-06-11-79.html) | Tolkeloven | Arbeids- og inkluderingsdepartementet |
| [Lov om supplerande stønad til personar med kort butid i Noreg](../lover/lov-2005-04-29-21.html) | Lov om supplerande stønad ved kort butid | Arbeids- og inkluderingsdepartementet |
| [Lov om utlendingers adgang til riket og deres opphold her (utlendingsloven)](../lover/lov-2008-05-15-35.html) | Utlendingsloven – utlendl | Justis- og beredskapsdepartementet |
