# Forvaltnings- og kommunalrett

*84 lover*

| Lov | Korttittel | Departement |
|-----|-----------|-------------|
| [Lov om Enhetsregisteret (enhetsregisterloven)](/norwegian-laws/lover/lov-2025-06-20-105.html) | Enhetsregisterloven | Nærings- og fiskeridepartementet |
| [Lov om Foretaksregisteret (foretaksregisterloven)](/norwegian-laws/lover/lov-2025-06-20-106.html) | Foretaksregisterloven | Nærings- og fiskeridepartementet |
| [Lov om Norsk Lovtidend m.v.](/norwegian-laws/lover/lov-1969-06-19-53.html) | Lov om Norsk Lovtidend | Justis- og beredskapsdepartementet |
| [Lov om Norsk Lysingsblad](/norwegian-laws/lover/lov-1946-10-11-1.html) | Lov om Norsk Lysingsblad | Digitaliserings- og forvaltningsdepartementet |
| [Lov om Oppgaveregisteret](/norwegian-laws/lover/lov-1997-06-06-35.html) | Oppgaveregisterloven – oppgregl | Nærings- og fiskeridepartementet |
| [Lov om Schengen informasjonssystem (SIS) [SIS-loven]](/norwegian-laws/lover/lov-1999-07-16-66.html) | SIS-loven – SISl | Justis- og beredskapsdepartementet |
| [Lov om Statens kommisjon for partnerdrap](/norwegian-laws/lover/lov-2025-03-28-5.html) | Lov om Statens kommisjon for partnerdrap | Justis- og beredskapsdepartementet |
| [Lov om Stortingets ombud for kontroll med forvaltningen (sivilombudsloven)](/norwegian-laws/lover/lov-2021-06-18-121.html) | Sivilombudsloven | Justis- og beredskapsdepartementet |
| [Lov om arbeids- og velferdsforvaltningen (arbeids- og velferdsforvaltningsloven)](/norwegian-laws/lover/lov-2006-06-16-20.html) | Nav-loven | Arbeids- og inkluderingsdepartementet |
| [Lov om arbeidsgivers innrapportering av ansettelses- og inntektsforhold m.m. (a-](/norwegian-laws/lover/lov-2012-06-22-43.html) | A-opplysningsloven | Finansdepartementet |
| [Lov om avleveringsplikt for allment tilgjengelege dokument (pliktavleveringslova](/norwegian-laws/lover/lov-1989-06-09-32.html) | Pliktavleveringslova – avlvl | Kultur- og likestillingsdepartementet |
| [Lov om behandling av helseopplysninger ved ytelse av helsehjelp (pasientjournall](/norwegian-laws/lover/lov-2014-06-20-42.html) | Pasientjournalloven | Helse- og omsorgsdepartementet |
| [Lov om behandling av opplysninger i kredittopplysningsvirksomhet (kredittopplysn](/norwegian-laws/lover/lov-2019-12-20-109.html) | Kredittopplysningsloven | Barne- og familiedepartementet |
| [Lov om behandling av opplysninger i politiet og påtalemyndigheten (politiregiste](/norwegian-laws/lover/lov-2010-05-28-16.html) | Politiregisterloven | Justis- og beredskapsdepartementet |
| [Lov om behandlingsmåten i forvaltningssaker (forvaltningsloven)](/norwegian-laws/lover/lov-1967-02-10.html) | Forvaltningsloven – fvl | Justis- og beredskapsdepartementet |
| [Lov om besøksbidrag (besøksbidragsloven)](/norwegian-laws/lover/lov-2025-06-20-104.html) | Besøksbidragsloven | Nærings- og fiskeridepartementet |
| [Lov om bevaring og bærekraftig bruk av marint naturmangfold i områder utenfor na](/norwegian-laws/lover/lov-2025-05-27-21.html) | Lov om bevaring og bærekraftig bruk av marint naturmangfold i områder utenfor nasjonal jurisdiksjon | Klima- og miljødepartementet |
| [Lov om det frie varebytte i EØS (EØS-vareloven)](/norwegian-laws/lover/lov-2013-04-12-13.html) | EØS-vareloven | Nærings- og fiskeridepartementet |
| [Lov om endringar i lov om interkommunale selskaper (møteoffentlegheit, økonomifo](/norwegian-laws/lover/lov-2023-06-02-22.html) | Endringslov til lov om interkommunale selskaper | Kommunal- og distriktsdepartementet |
| [Lov om endringar i pasient- og brukarrettslova, helsepersonellova m.m. (styrking](/norwegian-laws/lover/lov-2017-06-16-53.html) | Endringslov til pasient- og brukarrettslova, helsepersonellova m.m. | Helse- og omsorgsdepartementet |
| [Lov om endringer i anskaffelsesloven (samfunnshensyn mv.)](/norwegian-laws/lover/lov-2026-03-06-8.html) | Endringslov til anskaffelsesloven | Nærings- og fiskeridepartementet |
| [Lov om endringer i barnetrygdloven og midlertidige endringer i lovverket som føl](/norwegian-laws/lover/lov-2024-06-25-53.html) | Endringslov til barnetrygdloven mv. (Ukraina) | Arbeids- og inkluderingsdepartementet |
| [Lov om endringer i barnevernloven og sosialtjenesteloven mv. (saksbehandlingsreg](/norwegian-laws/lover/lov-2006-12-01-65.html) | Endringslov til barnevernl. og sosialtjenestel. | Barne- og familiedepartementet |
| [Lov om endringer i grenseloven og utlendingsloven mv. (interoperabilitet og visu](/norwegian-laws/lover/lov-2024-06-21-47.html) | Endringslov til grenseloven og utlendingsloven mv. | Justis- og beredskapsdepartementet |
| [Lov om endringer i helseforskningsloven mv. (vilkår for medisinsk og helsefaglig](/norwegian-laws/lover/lov-2025-06-20-71.html) | Endringslov til helseforskningsloven mv. | Helse- og omsorgsdepartementet |
| [Lov om endringer i helsepersonelloven og pasientjournalloven mv. (taushetsplikt ](/norwegian-laws/lover/lov-2026-01-23-1.html) | Endringslov til helsepersonelloven og pasientjournalloven mv. | Helse- og omsorgsdepartementet |
| [Lov om endringer i konfliktrådsloven, straffeloven og straffeprosessloven mv. (s](/norwegian-laws/lover/lov-2023-12-20-110.html) | Endringslov til konfliktrådsloven, straffeloven mv | Justis- og beredskapsdepartementet |
| [Lov om endringer i pengespill- og lotterilovgivningen](/norwegian-laws/lover/lov-2003-08-29-90.html) | Endringslov til pengespill- og lotterilover | Kultur- og likestillingsdepartementet |
| [Lov om endringer i plan- og bygningsloven (planbestemmelser om borettslag)](/norwegian-laws/lover/lov-2026-03-06-7.html) | Endringslov til plan- og bygningsloven | Kommunal- og distriktsdepartementet |
| [Lov om endringer i plan- og bygningsloven og matrikkellova (nye virkemidler ved ](/norwegian-laws/lover/lov-2025-06-20-93.html) | Endringslov til plan- og bygningsloven og matrikkellova | Kommunal- og distriktsdepartementet |
| [Lov om endringer i psykisk helsevernloven og pasient- og brukerrettighetsloven m](/norwegian-laws/lover/lov-2025-06-20-67.html) | Endringslov til psykisk helsevernloven mv | Helse- og omsorgsdepartementet |
| [Lov om endringer i skipsarbeidsloven og NIS-loven (tydelige og mer forutsigbare ](/norwegian-laws/lover/lov-2026-04-10-14.html) | Endringslov til skipsarbeidsloven og NIS-loven | Nærings- og fiskeridepartementet |
| [Lov om endringer i straffeloven og legemiddelloven mv. (befatning med mindre men](/norwegian-laws/lover/lov-2025-06-20-83.html) | Endringslov til straffeloven og legemiddelloven mv. | Justis- og beredskapsdepartementet |
| [Lov om endringer i veglova mv. (overføring av fylkesveiadministrasjon)](/norwegian-laws/lover/lov-2019-06-21-68.html) | Endringslov til veglova mv. (overføring av fylkesveiadministrasjon) | Samferdselsdepartementet |
| [Lov om fastsetjing og endring av kommune- og fylkesgrenser (inndelingslova)](/norwegian-laws/lover/lov-2001-06-15-70.html) | Inndelingslova | Kommunal- og distriktsdepartementet |
| [Lov om fiendegods [fiendegodsloven]](/norwegian-laws/lover/lov-1950-12-15-4.html) | Fiendegodsloven | Justis- og beredskapsdepartementet |
| [Lov om flagging på kommunenes offentlige bygninger](/norwegian-laws/lover/lov-1933-06-29-2.html) | Lov om flagging på kommunale bygninger | Kommunal- og distriktsdepartementet |
| [Lov om folkeregistrering (folkeregisterloven)](/norwegian-laws/lover/lov-2016-12-09-88.html) | Folkeregisterloven | Finansdepartementet |
| [Lov om forsøk i offentlig forvaltning (forsøksloven)](/norwegian-laws/lover/lov-1992-06-26-87.html) | Forsøksloven | Kommunal- og distriktsdepartementet |
| [Lov om gjennomføring av internasjonale sanksjoner (sanksjonsloven)](/norwegian-laws/lover/lov-2021-04-16-18.html) | Sanksjonsloven | Utenriksdepartementet |
| [Lov om grensetilsyn og grensekontroll av personer (grenseloven)](/norwegian-laws/lover/lov-2018-04-20-8.html) | Grenseloven | Justis- og beredskapsdepartementet |
| [Lov om helligdager og helligdagsfred](/norwegian-laws/lover/lov-1995-02-24-12.html) | Helligdagsfredloven | Barne- og familiedepartementet |
| [Lov om helseregistre og behandling av helseopplysninger (helseregisterloven)](/norwegian-laws/lover/lov-2014-06-20-43.html) | Helseregisterloven – hregl | Helse- og omsorgsdepartementet |
| [Lov om informasjonsplikt, karantene og saksforbud for politikere, embetsmenn og ](/norwegian-laws/lover/lov-2015-06-19-70.html) | Karanteneloven | Digitaliserings- og forvaltningsdepartementet |
| [Lov om informasjonstilgang m.m. for Ekstremismekommisjonen](/norwegian-laws/lover/lov-2022-12-20-97.html) | Lov om informasjonstilgang m.m. for Ekstremismekommisjonen | Arbeids- og inkluderingsdepartementet |
| [Lov om informasjonstilgang m.m. for Koronautvalget, og endringer i voldserstatni](/norwegian-laws/lover/lov-2022-12-20-118.html) | Lov om informasjonstilgang m.m. for Koronautvalget mv. | Justis- og beredskapsdepartementet |
| [Lov om infrastruktur for geografisk informasjon (geodataloven)](/norwegian-laws/lover/lov-2010-09-03-56.html) | Geodataloven | Kommunal- og distriktsdepartementet |
| [Lov om innførsle- og utførsleregulering](/norwegian-laws/lover/lov-1997-06-06-32.html) | Innførsle- og utførslereguleringslova | Utenriksdepartementet |
| [Lov om interkommunale selskaper (IKS-loven)](/norwegian-laws/lover/lov-1999-01-29-6.html) | IKS-loven | Kommunal- og distriktsdepartementet |
| [Lov om kommunal forkjøpsrett til leiegårder](/norwegian-laws/lover/lov-1977-04-29-34.html) | Lov om kommunal forkjøpsrett til leiegårder | Kommunal- og distriktsdepartementet |
| [Lov om kommunale vass- og avløpsanlegg (vass- og avløpsanleggslova)](/norwegian-laws/lover/lov-2025-06-06-26.html) | Vass- og avløpsanleggslova | Klima- og miljødepartementet |
| [Lov om kommunenes ansvar på det boligsosiale feltet [boligsosialloven]](/norwegian-laws/lover/lov-2022-12-20-121.html) | Boligsosialloven | Kommunal- og distriktsdepartementet |
| [Lov om kommuner og fylkeskommuner (kommuneloven)](/norwegian-laws/lover/lov-2018-06-22-83.html) | Kommuneloven | Kommunal- og distriktsdepartementet |
| [Lov om kompensasjon av merverdiavgift for kommuner, fylkeskommuner mv. (merverdi](/norwegian-laws/lover/lov-2003-12-12-108.html) | Merverdiavgiftskompensasjonsloven | Finansdepartementet |
| [Lov om kontroll med etterretnings-, overvåkings- og sikkerhetstjeneste (EOS-kont](/norwegian-laws/lover/lov-1995-02-03-7.html) | EOS-kontrolloven | Justis- og beredskapsdepartementet |
| [Lov om levering av digitale ytelser til forbrukere (digitalytelsesloven)](/norwegian-laws/lover/lov-2022-06-17-56.html) | Digitalytelsesloven | Justis- og beredskapsdepartementet |
| [Lov om militær politimyndighet (militærpolitiloven)](/norwegian-laws/lover/lov-2023-11-24-85.html) | Militærpolitiloven | Forsvarsdepartementet |
| [Lov om målenheter, måling og normaltid](/norwegian-laws/lover/lov-2007-01-26-4.html) | Lov om målenheter, måling og normaltid | Nærings- og fiskeridepartementet |
| [Lov om nasjonale saksbehandlingsregler i saker om offentlig støtte (støtteproses](/norwegian-laws/lover/lov-2022-03-04-7.html) | Støtteprosessloven | Nærings- og fiskeridepartementet |
| [Lov om nasjonalt identitetskort (ID-kortloven)](/norwegian-laws/lover/lov-2015-06-05-39.html) | ID-kortloven | Justis- og beredskapsdepartementet |
| [Lov om norsk internasjonalt skipsregister [NIS-loven]](/norwegian-laws/lover/lov-1987-06-12-48.html) | NIS-loven – NISl | Nærings- og fiskeridepartementet |
| [Lov om offentlege styresmakters ansvar for kulturverksemd (kulturlova)](/norwegian-laws/lover/lov-2007-06-29-89.html) | Kulturlova | Kultur- og likestillingsdepartementet |
| [Lov om offentlige anskaffelser (anskaffelsesloven)](/norwegian-laws/lover/lov-2016-06-17-73.html) | Anskaffelsesloven | Nærings- og fiskeridepartementet |
| [Lov om offentlige organers ansvar for bruk av tolk mv. (tolkeloven)](/norwegian-laws/lover/lov-2021-06-11-79.html) | Tolkeloven | Arbeids- og inkluderingsdepartementet |
| [Lov om offisiell statistikk og Statistisk sentralbyrå (statistikkloven)](/norwegian-laws/lover/lov-2019-06-21-32.html) | Statistikkloven | Finansdepartementet |
| [Lov om omdanning av Noregs Kommunalbank til aksjeselskap](/norwegian-laws/lover/lov-1999-07-16-68.html) | Lov om Kommunalbanken AS – Kombl | Kommunal- og distriktsdepartementet |
| [Lov om overføring av rettigheter og forpliktelser ved omklassifisering av veg et](/norwegian-laws/lover/lov-2009-06-19-109.html) | Lov om omklassifisering av veg | Samferdselsdepartementet |
| [Lov om pass (passloven)](/norwegian-laws/lover/lov-1997-06-19-82.html) | Passloven – passl | Justis- og beredskapsdepartementet |
| [Lov om planlegging og byggesaksbehandling (plan- og bygningsloven)](/norwegian-laws/lover/lov-2008-06-27-71.html) | Plan- og bygningsloven – pbl | Kommunal- og distriktsdepartementet |
| [Lov om politiet (politiloven)](/norwegian-laws/lover/lov-1995-08-04-53.html) | Politiloven – politil | Justis- og beredskapsdepartementet |
| [Lov om pristiltak](/norwegian-laws/lover/lov-1993-06-11-66.html) | Pristiltaksloven – pristl | Nærings- og fiskeridepartementet |
| [Lov om register for frivillig virksomhet](/norwegian-laws/lover/lov-2007-06-29-88.html) | Frivillighetsregisterloven | Kultur- og likestillingsdepartementet |
| [Lov om register over opplysninger om valutaveksling og overføring av betalingsmi](/norwegian-laws/lover/lov-2004-05-28-29.html) | Valutaregisterloven – valregl | Finansdepartementet |
| [Lov om registrering av regjeringsmedlemmers, statssekretærers og politiske rådgi](/norwegian-laws/lover/lov-2012-11-30-70.html) | Lov om registrering av verv og økonomiske interesser | Kommunal- og distriktsdepartementet |
| [Lov om rett til innsyn i dokument i offentleg verksemd (offentleglova)](/norwegian-laws/lover/lov-2006-05-19-16.html) | Offentleglova – offl | Justis- og beredskapsdepartementet |
| [Lov om rett til miljøinformasjon og deltakelse i offentlige beslutningsprosesser](/norwegian-laws/lover/lov-2003-05-09-31.html) | Miljøinformasjonsloven – mlinfl | Klima- og miljødepartementet |
| [Lov om saksbehandlingen i offentlig forvaltning (forvaltningsloven)](/norwegian-laws/lover/lov-2025-06-20-81.html) | Forvaltningsloven | Justis- og beredskapsdepartementet |
| [Lov om sivil beskyttelse og beredskap (sivilbeskyttelsesloven)](/norwegian-laws/lover/lov-2010-06-25-45.html) | Sivilbeskyttelsesloven | Justis- og beredskapsdepartementet |
| [Lov om språk (språklova)](/norwegian-laws/lover/lov-2021-05-21-42.html) | Språklova | Kultur- og likestillingsdepartementet |
| [Lov om statsbidrag til anlegg m.v. av skytebaner](/norwegian-laws/lover/lov-1974-04-05-14.html) | Lov om statsbidrag til skytebaner | Forsvarsdepartementet |
| [Lov om tjenesteplikt i politiet [polititjenestepliktloven]](/norwegian-laws/lover/lov-1952-11-21-3.html) | Polititjenestepliktloven | Justis- og beredskapsdepartementet |
| [Lov om utvalget for evaluering av EOS-utvalget](/norwegian-laws/lover/lov-2015-02-13-10.html) | Lov om utvalget for evaluering av EOS-utvalget | Justis- og beredskapsdepartementet |
| [Lov om valg til Stortinget, fylkesting og kommunestyrer (valgloven)](/norwegian-laws/lover/lov-2023-06-16-62.html) | Valgloven | Kommunal- og distriktsdepartementet |
| [Lov om våpen, skytevåpen, våpendelar og ammunisjon (våpenlova)](/norwegian-laws/lover/lov-2018-04-20-7.html) | Våpenlova | Justis- og beredskapsdepartementet |
