# Skatte- og avgiftsrett

*45 lover*

| Lov | Korttittel | Departement |
|-----|-----------|-------------|
| [Lov om adgang for Kongen til å inngå overenskomster med fremmede stater til fore](/norwegian-laws/lover/lov-1949-07-28-15.html) | Dobbeltbeskatningsavtaleloven | Finansdepartementet |
| [Lov om arbeidsgivers innrapportering av ansettelses- og inntektsforhold m.m. (a-](/norwegian-laws/lover/lov-2012-06-22-43.html) | A-opplysningsloven | Finansdepartementet |
| [Lov om avgift av kull, jordoljer og andre mineraler og bergarter som utføres fra](/norwegian-laws/lover/lov-1925-07-17-2.html) | Lov om avgift av kull m.v. fra Svalbard | Justis- og beredskapsdepartementet |
| [Lov om avgift på offentlig framføring av utøvende kunstneres prestasjoner m.v.](/norwegian-laws/lover/lov-1956-12-14-4.html) | Lov om avgift til fond for utøvende kunstnere | Kultur- og likestillingsdepartementet |
| [Lov om avgift på omsetning av billedkunst m.m. (kunstavgiftsloven)](/norwegian-laws/lover/lov-1948-11-04-1.html) | Kunstavgiftsloven | Kultur- og likestillingsdepartementet |
| [Lov om avgift på utslipp av CO2i petroleumsvirksomhet på kontinentalsokkelen](/norwegian-laws/lover/lov-1990-12-21-72.html) | Lov om avgift på utslipp av CO2 | Finansdepartementet |
| [Lov om avgift til Det norske komponistfond](/norwegian-laws/lover/lov-1965-04-09-1.html) | Lov om avgift til Det norske komponistfond | Kultur- og likestillingsdepartementet |
| [Lov om avgift til forskning og utvikling i fiskeri- og havbruksnæringen](/norwegian-laws/lover/lov-2000-07-07-68.html) | Lov om eksportavgift på fiskevarer – fiskekspal | Nærings- og fiskeridepartementet |
| [Lov om avgift til statskassen på inngangspenger til forestillinger og framvisnin](/norwegian-laws/lover/lov-1966-06-10-3.html) | Lov om avgift på forestillinger m.v. | Finansdepartementet |
| [Lov om avgifter vedrørende motorkjøretøyer og båter (motorkjøretøy- og båtavgift](/norwegian-laws/lover/lov-1959-06-19-2.html) | Motorkjøretøy- og båtavgiftsloven | Finansdepartementet |
| [Lov om betaling og innkreving av skatte- og avgiftskrav (skattebetalingsloven)](/norwegian-laws/lover/lov-2005-06-17-67.html) | Skattebetalingsloven – sktbl | Finansdepartementet |
| [Lov om dokumentavgift (dokumentavgiftsloven)](/norwegian-laws/lover/lov-1975-12-12-59.html) | Dokumentavgiftsloven – dal | Finansdepartementet |
| [Lov om eigedomsskatt til kommunane (eigedomsskattelova)](/norwegian-laws/lover/lov-1975-06-06-29.html) | Eigedomsskattelova | Finansdepartementet |
| [Lov om endringar i folketrygdlova og enkelte andre lover (oppfølging av tiltak i](/norwegian-laws/lover/lov-2025-12-22-117.html) | Endringslov til folketrygdlova og enkelte andre lover | Arbeids- og inkluderingsdepartementet |
| [Lov om endringer i finansforetaksloven mv. (innskuddsgaranti og krisehåndtering ](/norwegian-laws/lover/lov-2018-03-23-2.html) | Endringslov til finansforetaksloven mv. | Finansdepartementet |
| [Lov om endringer i lov 26. mars 1999 nr. 14 om skatt av formue og inntekt](/norwegian-laws/lover/lov-2006-12-15-81.html) | Endringslov til skatteloven | Finansdepartementet |
| [Lov om endringer i lov 26. mars 1999 nr. 14 om skatt av formue og inntekt (skatt](/norwegian-laws/lover/lov-2008-12-12-99.html) | Endringslov til skatteloven | Finansdepartementet |
| [Lov om endringer i lov 6. juni 1975 nr. 29 om eigedomsskatt til kommunane (eiged](/norwegian-laws/lover/lov-2017-12-19-118.html) | Endringslov til eigedomsskattelova | Finansdepartementet |
| [Lov om endringer i lov om Statens pensjonsfond](/norwegian-laws/lover/lov-2023-12-20-104.html) | Endringslov til lov om Statens pensjonsfond | Finansdepartementet |
| [Lov om endringer i merverdiavgiftsloven](/norwegian-laws/lover/lov-2025-12-22-121.html) | Endringslov til merverdiavgiftsloven | Finansdepartementet |
| [Lov om endringer i skatte- og avgiftslovgivningen mv.](/norwegian-laws/lover/lov-2004-12-10-77.html) | Endringslov til skatte- og avgiftslovgivningen mv. | Finansdepartementet |
| [Lov om endringer i skatteloven](/norwegian-laws/lover/lov-2011-12-09-52.html) | Endringslov til skatteloven | Finansdepartementet |
| [Lov om endringer i skatteloven](/norwegian-laws/lover/lov-2024-01-12-2.html) | Endringslov til skatteloven | Finansdepartementet |
| [Lov om endringer i veglova mv. (overføring av fylkesveiadministrasjon)](/norwegian-laws/lover/lov-2019-06-21-68.html) | Endringslov til veglova mv. (overføring av fylkesveiadministrasjon) | Samferdselsdepartementet |
| [Lov om forskningsavgift på landbruksprodukter](/norwegian-laws/lover/lov-1970-06-26-74.html) | Lov om forskningsavgift i landbruket | Landbruks- og matdepartementet |
| [Lov om inn- og utførsel av varer (vareførselsloven)](/norwegian-laws/lover/lov-2022-03-11-9.html) | Vareførselsloven – vfl. | Finansdepartementet |
| [Lov om innkreving av statlige krav mv. (innkrevingsloven)](/norwegian-laws/lover/lov-2025-04-25-12.html) | Innkrevingsloven | Finansdepartementet |
| [Lov om kompensasjon av merverdiavgift for kommuner, fylkeskommuner mv. (merverdi](/norwegian-laws/lover/lov-2003-12-12-108.html) | Merverdiavgiftskompensasjonsloven | Finansdepartementet |
| [Lov om merverdiavgift (merverdiavgiftsloven)](/norwegian-laws/lover/lov-2009-06-19-58.html) | Merverdiavgiftsloven – mval | Finansdepartementet |
| [Lov om midlertidig kompensasjonsordning for arbeidsgivere med nullsats for bereg](/norwegian-laws/lover/lov-2020-06-23-110.html) | Lov om midl. kompensasjon ved nullsats for arbeidsgiveravgift | Finansdepartementet |
| [Lov om midlertidig tillegg til lov av 13. juni 1975 nr. 35 om skattlegging av un](/norwegian-laws/lover/lov-1983-12-23-76.html) | Tilleggslov til petroleumsskatteloven | Finansdepartementet |
| [Lov om offisiell statistikk og Statistisk sentralbyrå (statistikkloven)](/norwegian-laws/lover/lov-2019-06-21-32.html) | Statistikkloven | Finansdepartementet |
| [Lov om oppheving av lov 19. juni 1964 nr. 14 om avgift på arv og visse gaver (ar](/norwegian-laws/lover/lov-2013-12-13-110.html) | Oppheving av arveavgiftsloven | Finansdepartementet |
| [Lov om oppheving av lov om avgift på utslipp av CO2i petroleumsvirksomhet på kon](/norwegian-laws/lover/lov-2023-12-20-96.html) | Endringslov til lov om avgift på utslipp av CO2 | Finansdepartementet |
| [Lov om skatt av formue og inntekt (skatteloven)](/norwegian-laws/lover/lov-1999-03-26-14.html) | Skatteloven – sktl | Finansdepartementet |
| [Lov om skatt på honorar til utenlandske artister mv (artistskatteloven)](/norwegian-laws/lover/lov-1996-12-13-87.html) | Artistskatteloven | Finansdepartementet |
| [Lov om skatt til Svalbard (Svalbardskatteloven)](/norwegian-laws/lover/lov-1996-11-29-68.html) | Svalbardskatteloven – svalbsktl | Finansdepartementet |
| [Lov om skatteforvaltning (skatteforvaltningsloven)](/norwegian-laws/lover/lov-2016-05-27-14.html) | Skatteforvaltningsloven – sktfvl | Finansdepartementet |
| [Lov om skattlegging av personer på Jan Mayen og i Antarktis (Jan Mayen-skattelov](/norwegian-laws/lover/lov-1996-11-29-69.html) | Jan Mayen-skatteloven | Finansdepartementet |
| [Lov om skattlegging av undersjøiske petroleumsforekomster mv. (petroleumsskattel](/norwegian-laws/lover/lov-1975-06-13-35.html) | Petroleumsskatteloven – petrsktl | Finansdepartementet |
| [Lov om suppleringsskatt på underbeskattet inntekt i konsern (suppleringsskattelo](/norwegian-laws/lover/lov-2024-01-12-1.html) | Suppleringsskatteloven | Finansdepartementet |
| [Lov om særavgifter (særavgiftsloven)](/norwegian-laws/lover/lov-1933-05-19-11.html) | Særavgiftsloven | Finansdepartementet |
| [Lov om tilskudd ved avbrutt permittering (økonomiske tiltak i møte med virusutbr](/norwegian-laws/lover/lov-2020-06-23-99.html) | Lov om tilskudd ved avbrutt permittering | Finansdepartementet |
| [Lov om tollavgift (tollavgiftsloven)](/norwegian-laws/lover/lov-2022-03-11-8.html) | Tollavgiftsloven – tavl | Finansdepartementet |
| [Midlertidig lov om tillegg til merverdiavgiftsloven](/norwegian-laws/lover/lov-2017-12-19-126.html) | Midlertidig lov om tillegg til merverdiavgiftsloven | Finansdepartementet |
