# Familie-, person- og barnerett

*60 lover*

| Lov | Korttittel | Departement |
|-----|-----------|-------------|
| [Konvensjon mellem Norge, Danmark, Finnland, Island og Sverige inneholdende inter](../lover/lov-1931-02-06.html) | Nordisk familierettslig konvensjon | Justis- og beredskapsdepartementet |
| [Konvensjon mellem Norge, Danmark, Finnland, Island og Sverige om arv og dødsbosk](../lover/lov-1934-11-19.html) | Nordisk konvensjon om arv og dødsboskifte | Justis- og beredskapsdepartementet |
| [Konvensjon mellom Norge, Danmark, Finnland, Island og Sverige om inndriving av u](../lover/lov-1962-03-23.html) | Nordisk konvensjon om underholdsbidrag | Utenriksdepartementet |
| [Lov om Digitaliseringsdirektoratets tilgang til taushetsbelagte opplysninger i F](../lover/lov-2023-06-09-29.html) | Lov om Digdirs tilgang til opplysninger i Folkeregisteret | Digitaliserings- og forvaltningsdepartementet |
| [Lov om Likestillings- og diskrimineringsombudet og Diskrimineringsnemnda (diskri](../lover/lov-2017-06-16-50.html) | Diskrimineringsombudsloven – diskrol | Kultur- og likestillingsdepartementet |
| [Lov om adopsjon (adopsjonsloven)](../lover/lov-2017-06-16-48.html) | Adopsjonsloven | Barne- og familiedepartementet |
| [Lov om anerkjennelse av utenlandske skilsmisser og separasjoner](../lover/lov-1978-06-02-38.html) | Lov om utenlandske skilsmisser | Barne- og familiedepartementet |
| [Lov om anerkjennelse og fullbyrding av utenlandske avgjørelser om foreldreansvar](../lover/lov-1988-07-08-72.html) | Barnebortføringsloven | Barne- og familiedepartementet |
| [Lov om arv og dødsboskifte (arveloven)](../lover/lov-2019-06-14-21.html) | Arveloven | Justis- og beredskapsdepartementet |
| [Lov om barn og foreldre (barnelova)](../lover/lov-1981-04-08-7.html) | Barnelova – bl | Barne- og familiedepartementet |
| [Lov om barn og foreldre (barnelova)](../lover/lov-2025-06-20-40.html) | Barnelova | Barne- og familiedepartementet |
| [Lov om barnehager (barnehageloven)](../lover/lov-2005-06-17-64.html) | Barnehageloven – bhl | Kunnskapsdepartementet |
| [Lov om barneombud [barneombudsloven]](../lover/lov-1981-03-06-5.html) | Barneombudsloven | Barne- og familiedepartementet |
| [Lov om barnetrygd (barnetrygdloven)](../lover/lov-2002-03-08-4.html) | Barnetrygdloven – btrl | Barne- og familiedepartementet |
| [Lov om barnevern (barnevernsloven)](../lover/lov-2021-06-18-97.html) | Barnevernsloven – bvl | Barne- og familiedepartementet |
| [Lov om behandling av opplysninger i kredittopplysningsvirksomhet (kredittopplysn](../lover/lov-2019-12-20-109.html) | Kredittopplysningsloven | Barne- og familiedepartementet |
| [Lov om behandling av opplysninger i politiet og påtalemyndigheten (politiregiste](../lover/lov-2010-05-28-16.html) | Politiregisterloven | Justis- og beredskapsdepartementet |
| [Lov om behandling av personopplysninger (personopplysningsloven)](../lover/lov-2018-06-15-38.html) | Personopplysningsloven | Justis- og beredskapsdepartementet |
| [Lov om behandling av personopplysninger i Norges idrettsforbund og olympiske og ](../lover/lov-2025-06-20-95.html) | Lov om behandling av personopplysninger i Norges idrettsforbund mv | Kultur- og likestillingsdepartementet |
| [Lov om bidragsforskott (forskotteringsloven)](../lover/lov-1989-02-17-2.html) | Forskotteringsloven – forskl | Barne- og familiedepartementet |
| [Lov om ekteskap (ekteskapsloven)](../lover/lov-1991-07-04-47.html) | Ekteskapsloven – el | Barne- og familiedepartementetJustis- og beredskapsdepartementet |
| [Lov om endring av juridisk kjønn](../lover/lov-2016-06-17-46.html) | Lov om endring av juridisk kjønn | Helse- og omsorgsdepartementet |
| [Lov om endringer i barnehageloven (styring og finansiering av barnehagesektoren)](../lover/lov-2025-06-20-100.html) | Endringslov til barnehageloven | Kunnskapsdepartementet |
| [Lov om endringer i barnetrygdloven og midlertidige endringer i lovverket som føl](../lover/lov-2024-06-25-53.html) | Endringslov til barnetrygdloven mv. (Ukraina) | Arbeids- og inkluderingsdepartementet |
| [Lov om endringer i barnevernloven](../lover/lov-2013-06-21-63.html) | Endringslov til barnevernloven | Barne- og familiedepartementet |
| [Lov om endringer i barnevernloven mv. (tverrfaglig helsekartlegging)](../lover/lov-2022-03-25-13.html) | Endringslov til barnevernloven mv. | Barne- og familiedepartementet |
| [Lov om endringer i barnevernloven og sosialtjenesteloven mv. (saksbehandlingsreg](../lover/lov-2006-12-01-65.html) | Endringslov til barnevernl. og sosialtjenestel. | Barne- og familiedepartementet |
| [Lov om endringer i barnevernsloven mv. (kvalitetsløftet i barnevernet)](../lover/lov-2025-06-20-39.html) | Endringslov til barnevernsloven mv. | Barne- og familiedepartementet |
| [Lov om endringer i grenseloven og utlendingsloven mv. (interoperabilitet og visu](../lover/lov-2024-06-21-47.html) | Endringslov til grenseloven og utlendingsloven mv. | Justis- og beredskapsdepartementet |
| [Lov om endringer i konfliktrådsloven, straffeloven og straffeprosessloven mv. (s](../lover/lov-2023-12-20-110.html) | Endringslov til konfliktrådsloven, straffeloven mv | Justis- og beredskapsdepartementet |
| [Lov om endringer i rettshjelpsloven mv. (prioriterte sakstyper for rettshjelp mv](../lover/lov-2025-06-20-82.html) | Endringslov til rettshjelpsloven mv. | Justis- og beredskapsdepartementet |
| [Lov om familievernkontorer](../lover/lov-1997-06-19-62.html) | Familievernkontorloven | Barne- og familiedepartementet |
| [Lov om folkeregistrering (folkeregisterloven)](../lover/lov-2016-12-09-88.html) | Folkeregisterloven | Finansdepartementet |
| [Lov om forskriftshjemmel for behandling av personopplysninger for frivillige til](../lover/lov-2022-06-17-44.html) | Lov om forskriftshjemmel, personopplysninger | Barne- og familiedepartementet |
| [Lov om forsvunne personar](../lover/lov-2015-05-12-27.html) | Lov om forsvunne personar – fsvl | Justis- og beredskapsdepartementet |
| [Lov om gjeldsinformasjon ved kredittvurdering av privatpersoner (gjeldsinformasj](../lover/lov-2017-06-16-47.html) | Gjeldsinformasjonsloven | Barne- og familiedepartementet |
| [Lov om gjennomføring av konvensjon 19. oktober 1996 om jurisdiksjon, lovvalg, an](../lover/lov-2015-09-04-85.html) | Lov om Haagkonvensjonen 1996 | Barne- og familiedepartementet |
| [Lov om gjennomføring av nordiske konvensjoner om visse internasjonal-privatretts](../lover/lov-1969-12-19-75.html) | Lov om gjennomføring av nordiske konvensjoner | Justis- og beredskapsdepartementet |
| [Lov om gravplasser, kremasjon og gravferd (gravplassloven)](../lover/lov-1996-06-07-32.html) | Gravplassloven | Barne- og familiedepartementet |
| [Lov om helligdager og helligdagsfred](../lover/lov-1995-02-24-12.html) | Helligdagsfredloven | Barne- og familiedepartementet |
| [Lov om humanmedisinsk bruk av bioteknologi m.m. (bioteknologiloven)](../lover/lov-2003-12-05-100.html) | Bioteknologiloven – biotl | Helse- og omsorgsdepartementet |
| [Lov om informasjonstilgang m.m. for Barnevoldsutvalget](../lover/lov-2016-05-27-13.html) | Lov om informasjonstilgang m.m. for Barnevoldsutvalget | Barne- og familiedepartementet |
| [Lov om informasjonstilgang m.m. for utvalget som skal granske utenlandsadopsjone](../lover/lov-2024-04-12-16.html) | Lov om informasjonstilgang, gransking av utenlandsadopsjoner | Barne- og familiedepartementet |
| [Lov om informasjonstilgang mv. for Statens helsetilsyn ved gjennomgang av et utv](../lover/lov-2017-03-24-10.html) | Lov om informasjonstilgang mv. for Statens helsetilsyn | Barne- og familiedepartementet |
| [Lov om informasjonstilgang mv. for utvalget for ekstern gransking av saken knytt](../lover/lov-2019-12-20-85.html) | Lov om informasjonstilgang mv. for NAV-granskingsutvalget | Arbeids- og inkluderingsdepartementet |
| [Lov om innkreving av underholdsbidrag mv. (bidragsinnkrevingsloven)](../lover/lov-2005-04-29-20.html) | Bidragsinnkrevingsloven | Barne- og familiedepartementet |
| [Lov om kommunale krisesentertilbod (krisesenterlova)](../lover/lov-2009-06-19-44.html) | Krisesenterlova | Barne- og familiedepartementet |
| [Lov om kontantstøtte til småbarnsforeldre (kontantstøtteloven)](../lover/lov-1998-06-26-41.html) | Kontantstøtteloven | Barne- og familiedepartementet |
| [Lov om likestilling og forbud mot diskriminering (likestillings- og diskrimineri](../lover/lov-2017-06-16-51.html) | Likestillings- og diskrimineringsloven – ldl | Kultur- og likestillingsdepartementet |
| [Lov om når norsk tenestemakt kan halda brudvigjing i utlandet og utenlandsk tene](../lover/lov-1955-06-30-20.html) | Lov om brudvigjing i utlandet | Barne- og familiedepartementet |
| [Lov om offisiell statistikk og Statistisk sentralbyrå (statistikkloven)](../lover/lov-2019-06-21-32.html) | Statistikkloven | Finansdepartementet |
| [Lov om omdanning av Opplysningsvesenets fond til aksjeselskap](../lover/lov-2024-06-25-58.html) | Lov om omdanning av Opplysningsvesenets fond til aksjeselskap | Nærings- og fiskeridepartementet |
| [Lov om oppheving av lov 19. juni 1964 nr. 14 om avgift på arv og visse gaver (ar](../lover/lov-2013-12-13-110.html) | Oppheving av arveavgiftsloven | Finansdepartementet |
| [Lov om oppløsning av stamhuset Ekeberg](../lover/lov-2005-12-21-129.html) | Lov om oppløsning av stamhuset Ekeberg | Nærings- og fiskeridepartementet |
| [Lov om personnavn (navneloven)](../lover/lov-2002-06-07-19.html) | Navneloven | Justis- og beredskapsdepartementet |
| [Lov om rett til felles bolig og innbo når husstandsfellesskap opphører [husstand](../lover/lov-1991-07-04-45.html) | Husstandsfellesskapsloven – husfskl | Justis- og beredskapsdepartementet |
| [Lov om stamhuset Rosendal og om forandring i arverettsreglene for stamhuset Jarl](../lover/lov-1927-07-04-11.html) | Stamhusloven | Nærings- og fiskeridepartementet |
| [Lov om stans i utbetalinga av offentlege ytingar og barnebidrag når ein av forel](../lover/lov-2014-06-06-19.html) | Lov om stans i utbetalinger etter barnebortføring | Barne- og familiedepartementet |
| [Lov om tros- og livssynssamfunn (trossamfunnsloven)](../lover/lov-2020-04-24-31.html) | Trossamfunnsloven | Barne- og familiedepartementet |
| [Lov om vergemål (vergemålsloven)](../lover/lov-2010-03-26-9.html) | Vergemålsloven – vgml | Justis- og beredskapsdepartementet |
