# Internasjonal rett

*54 lover*

| Lov | Korttittel | Departement |
|-----|-----------|-------------|
| [Konvensjon mellem Norge, Danmark, Finnland, Island og Sverige inneholdende inter](../lover/lov-1931-02-06.html) | Nordisk familierettslig konvensjon | Justis- og beredskapsdepartementet |
| [Konvensjon mellem Norge, Danmark, Finnland, Island og Sverige om arv og dødsbosk](../lover/lov-1934-11-19.html) | Nordisk konvensjon om arv og dødsboskifte | Justis- og beredskapsdepartementet |
| [Konvensjon mellem Norge, Danmark, Finnland, Island og Sverige om konkurs](../lover/lov-1933-11-07.html) | Nordisk konkurskonvensjon | Justis- og beredskapsdepartementet |
| [Konvensjon mellom Norge, Danmark, Finnland, Island og Sverige om inndriving av u](../lover/lov-1962-03-23.html) | Nordisk konvensjon om underholdsbidrag | Utenriksdepartementet |
| [Lov i henhold til konvensjonen mellem Norge og Sverige om visse spørsmål vedrøre](../lover/lov-1931-06-12-1.html) | Vassdragslov i h.t. konvensjon Norge/Sverige | Energidepartementet |
| [Lov om Likestillings- og diskrimineringsombudet og Diskrimineringsnemnda (diskri](../lover/lov-2017-06-16-50.html) | Diskrimineringsombudsloven – diskrol | Kultur- og likestillingsdepartementet |
| [Lov om Norges institusjon for menneskerettigheter (NIM-loven)](../lover/lov-2015-05-22-33.html) | NIM-loven | Justis- og beredskapsdepartementet |
| [Lov om Norges kontinentalsokkel](../lover/lov-2021-06-18-89.html) | Lov om Norges kontinentalsokkel | Utenriksdepartementet |
| [Lov om Norges territorialfarvann og tilstøtende sone [territorialfarvannsloven]](../lover/lov-2003-06-27-57.html) | Territorialfarvannsloven – terfl | Utenriksdepartementet |
| [Lov om Norges økonomiske sone [økonomiske soneloven]](../lover/lov-1976-12-17-91.html) | Økonomiske soneloven – øksonl | Nærings- og fiskeridepartementet |
| [Lov om Overenskomst om internasjonal jernbanetrafikk (COTIF-loven)](../lover/lov-2004-12-10-82.html) | COTIF-loven | Samferdselsdepartementet |
| [Lov om Stortingets ombud for kontroll med forvaltningen (sivilombudsloven)](../lover/lov-2021-06-18-121.html) | Sivilombudsloven | Justis- og beredskapsdepartementet |
| [Lov om aktiviteter i verdensrommet (romloven)](../lover/lov-2025-12-22-128.html) | Romloven | Nærings- og fiskeridepartementet |
| [Lov om anerkjennelse av utenlandske skilsmisser og separasjoner](../lover/lov-1978-06-02-38.html) | Lov om utenlandske skilsmisser | Barne- og familiedepartementet |
| [Lov om anerkjennelse og fullbyrding av nordiske dommer på privatrettens område](../lover/lov-1977-06-10-71.html) | Lov om nordiske privatrettslige dommer | Justis- og beredskapsdepartementet |
| [Lov om anerkjennelse og fullbyrding av utenlandske avgjørelser om foreldreansvar](../lover/lov-1988-07-08-72.html) | Barnebortføringsloven | Barne- og familiedepartementet |
| [Lov om betalingsutjevning [betalingsutjevningsloven]](../lover/lov-1935-05-31-2.html) | Betalingsutjevningsloven | Utenriksdepartementet |
| [Lov om bevaring og bærekraftig bruk av marint naturmangfold i områder utenfor na](../lover/lov-2025-05-27-21.html) | Lov om bevaring og bærekraftig bruk av marint naturmangfold i områder utenfor nasjonal jurisdiksjon | Klima- og miljødepartementet |
| [Lov om endringar i lov om Overenskomst om internasjonal jernbanetrafikk (COTIF-l](../lover/lov-2023-06-20-81.html) | Endringslov til COTIF-lova | Samferdselsdepartementet |
| [Lov om gjennomføring av Konvensjonen om forbod mot utvikling, produksjon, lagrin](../lover/lov-1994-05-06-10.html) | Lov om konvensjon om kjemiske våpen | Utenriksdepartementet |
| [Lov om gjennomføring av Konvensjonen om forbud mot bruk, lagring, produksjon og ](../lover/lov-1998-07-17-54.html) | Lov om Konvensjonen mot antipersonellminer | Utenriksdepartementet |
| [Lov om gjennomføring av Konvensjonen om klaseammunisjon](../lover/lov-2009-05-15-28.html) | Klaseammunisjonsloven | Utenriksdepartementet |
| [Lov om gjennomføring av Traktat om totalforbod mot kjernefysiske prøvesprenginga](../lover/lov-1999-06-18-40.html) | Lov om traktat mot kjernefysiske prøvesprengingar | Utenriksdepartementet |
| [Lov om gjennomføring av europarådsavtale 31. januar 1995 om ulovlig håndtering a](../lover/lov-1997-06-13-47.html) | Lov om europarådsavtale om handel med narkotika | Justis- og beredskapsdepartementet |
| [Lov om gjennomføring av internasjonale sanksjoner (sanksjonsloven)](../lover/lov-2021-04-16-18.html) | Sanksjonsloven | Utenriksdepartementet |
| [Lov om gjennomføring av nordiske konvensjoner om visse internasjonal-privatretts](../lover/lov-1969-12-19-75.html) | Lov om gjennomføring av nordiske konvensjoner | Justis- og beredskapsdepartementet |
| [Lov om gjennomføring av tilleggsavtale mellom Norge og USA om forsvarssamarbeid ](../lover/lov-2022-06-10-36.html) | Forsvarssamarbeidsloven | Forsvarsdepartementet |
| [Lov om gjennomføring i norsk rett av De forente nasjoners sikkerhetsråds vedtak ](../lover/lov-1994-06-24-38.html) | Lov om krigsforbryterdomstol, Jugoslavia m m | Justis- og beredskapsdepartementet |
| [Lov om gjennomføring i norsk rett av miljøvernkonvensjon mellom Norge, Danmark, ](../lover/lov-1976-04-09-21.html) | Lov om nordisk miljøvernkonvensjon | Klima- og miljødepartementet |
| [Lov om immunitet og privilegier for internasjonale organisasjoner m.v.](../lover/lov-1947-06-19-5.html) | Lov om internasjonale organisasjoner m.v. | Justis- og beredskapsdepartementet |
| [Lov om inngåelse av avtale mellom Kongeriket Norge og Folkerepublikken Kina vedr](../lover/lov-1985-05-03-24.html) | Lov om avtale mellom Norge og Kina | Nærings- og fiskeridepartementet |
| [Lov om inspeksjoner i samsvar med Avtalen om konvensjonelle styrker i Europa (CF](../lover/lov-1992-05-29-50.html) | Lov om inspeksjoner av styrker i Europa | Utenriksdepartementet |
| [Lov om internasjonale sikkerhetsretter i mobilt løsøre](../lover/lov-2010-11-12-58.html) | Lov om internasjonal sikkerhet i mobilt løsøre | Justis- og beredskapsdepartementet |
| [Lov om kvoteplikt og handel med kvoter for utslipp av klimagasser (klimakvotelov](../lover/lov-2004-12-17-99.html) | Klimakvoteloven | Klima- og miljødepartementet |
| [Lov om likestilling og forbud mot diskriminering (likestillings- og diskrimineri](../lover/lov-2017-06-16-51.html) | Likestillings- og diskrimineringsloven – ldl | Kultur- og likestillingsdepartementet |
| [Lov om lovvalg i forsikring [forsikringslovvalgsloven]](../lover/lov-1992-11-27-111.html) | Forsikringslovvalgsloven – intprfal | Justis- og beredskapsdepartementet |
| [Lov om mellomfolkeleg-privatrettslege reglar for lausøyrekjøp [kjøpslovvalgslove](../lover/lov-1964-04-03-1.html) | Kjøpslovvalgsloven – intprkjl | Justis- og beredskapsdepartementet |
| [Lov om nasjonale saksbehandlingsregler i saker om offentlig støtte (støtteproses](../lover/lov-2022-03-04-7.html) | Støtteprosessloven | Nærings- og fiskeridepartementet |
| [Lov om oppskyting av gjenstander fra norsk territorium m.m. ut i verdensrommet](../lover/lov-1969-06-13-38.html) | Lov om oppskyting i verdensrommet | Nærings- og fiskeridepartementet |
| [Lov om overføring av domfelte](../lover/lov-1991-07-20-67.html) | Lov om overføring av domfelte – domfovfl | Justis- og beredskapsdepartementet |
| [Lov om pass (passloven)](../lover/lov-1997-06-19-82.html) | Passloven – passl | Justis- og beredskapsdepartementet |
| [Lov om pågriping og overlevering til og frå Noreg for straffbare forhold på grun](../lover/lov-2012-01-20-4.html) | Arrestordreloven | Justis- og beredskapsdepartementet |
| [Lov om register over opplysninger om valutaveksling og overføring av betalingsmi](../lover/lov-2004-05-28-29.html) | Valutaregisterloven – valregl | Finansdepartementet |
| [Lov om sikre containere [containerloven]](../lover/lov-1982-12-17-84.html) | Containerloven | Nærings- og fiskeridepartementet |
| [Lov om språk (språklova)](../lover/lov-2021-05-21-42.html) | Språklova | Kultur- og likestillingsdepartementet |
| [Lov om styrking av menneskerettighetenes stilling i norsk rett (menneskerettslov](../lover/lov-1999-05-21-30.html) | Menneskerettsloven – mrl | Justis- og beredskapsdepartementet |
| [Lov om svensk reinbeiting i Norge og norsk reinbeiting i Sverige (grensereinbeit](../lover/lov-1972-06-09-31.html) | Grensereinbeiteloven | Landbruks- og matdepartementet |
| [Lov om tiltak mot diskriminering i internasjonal skipsfart](../lover/lov-1967-07-07-1.html) | Lov om diskriminering i internasj. skipsfart | Nærings- og fiskeridepartementet |
| [Lov om vegfraktavtaler [vegfraktloven]](../lover/lov-1974-12-20-68.html) | Vegfraktloven – vegfrl | Justis- og beredskapsdepartementet |
| [Lov om vern av marin natur utenfor territorialfarvannet (havvernloven)](../lover/lov-2025-06-10-33.html) | Havvernloven | Klima- og miljødepartementet |
| [Lov om å setja i verk avtala 18 mars 1965 om løysing av tvistar mellom ein stat ](../lover/lov-1967-06-08-3.html) | Lov om internasjonale investeringstvistar | Justis- og beredskapsdepartementet |
| [Overenskomst mellem Norge og Storbritannia angående den civile rettergang](../lover/lov-1931-01-30.html) | Rettergangsoverenskomst med Storbritannia | Justis- og beredskapsdepartementet |
| [Overenskomst mellom Norge og Storbritannia om gjensidig anerkjennelse og fullbyr](../lover/lov-1961-06-12.html) | Sivildomsoverenskomst med Storbritannia | Justis- og beredskapsdepartementet |
| [Samarbeidsavtale mellom Norge, Danmark, Finland, Island og Sverige [Helsingforsa](../lover/lov-1962-03-23-2.html) | Helsingforsavtalen | Utenriksdepartementet |
