# Erstatnings- og forsikringsrett

*35 lover*

| Lov | Korttittel | Departement |
|-----|-----------|-------------|
| [Lov om Finanstilsynet (finanstilsynsloven)](../lover/lov-2024-06-21-41.html) | Finanstilsynsloven | Finansdepartementet |
| [Lov om ansvar for skade som motorvogner gjer (bilansvarslova)](../lover/lov-1961-02-03.html) | Bilansvarslova – bal | Justis- og beredskapsdepartementet |
| [Lov om digital operasjonell motstandsdyktighet i finanssektoren (DORA-loven)](../lover/lov-2025-05-27-18.html) | DORA-loven | Finansdepartementet |
| [Lov om endringar i folketrygdlova og enkelte andre lover (oppfølging av tiltak i](../lover/lov-2025-12-22-117.html) | Endringslov til folketrygdlova og enkelte andre lover | Arbeids- og inkluderingsdepartementet |
| [Lov om endringar i pasient- og brukarrettslova, helsepersonellova m.m. (styrking](../lover/lov-2017-06-16-53.html) | Endringslov til pasient- og brukarrettslova, helsepersonellova m.m. | Helse- og omsorgsdepartementet |
| [Lov om endringer i folketrygdloven (yrkessykdommer og elektronisk melding av yrk](../lover/lov-2025-06-10-30.html) | Endringslov til folketrygdloven | Arbeids- og inkluderingsdepartementet |
| [Lov om endringer i foretakspensjonsloven og forsikringsvirksomhetsloven (forvalt](../lover/lov-2026-05-07-16.html) | Endringslov til foretakspensjonsloven og forsikringsvirksomhetsloven | Finansdepartementet |
| [Lov om endringer i forsikringsvirksomhetsloven (skadeforsikring)](../lover/lov-2010-12-17-84.html) | Endringslov til forsikringsvirksomhetsloven | Finansdepartementet |
| [Lov om endringer i helsepersonelloven og pasientjournalloven mv. (taushetsplikt ](../lover/lov-2026-01-23-1.html) | Endringslov til helsepersonelloven og pasientjournalloven mv. | Helse- og omsorgsdepartementet |
| [Lov om endringer i konfliktrådsloven og straffeloven mv. (strafferettslige reaks](../lover/lov-2024-11-29-73.html) | Endringslov til konfliktrådsloven og straffeloven mv. | Justis- og beredskapsdepartementet |
| [Lov om endringer i konfliktrådsloven, straffeloven og straffeprosessloven mv. (s](../lover/lov-2023-12-20-110.html) | Endringslov til konfliktrådsloven, straffeloven mv | Justis- og beredskapsdepartementet |
| [Lov om erstatning for krigsskade på eiendom og interesse [krigsskadeerstatningsl](../lover/lov-1953-07-17-2.html) | Krigsskadeerstatningsloven | Arbeids- og inkluderingsdepartementet |
| [Lov om erstatning for naturskader (naturskadeerstatningsloven)](../lover/lov-2014-08-15-59.html) | Naturskadeerstatningsloven | Landbruks- og matdepartementet |
| [Lov om erstatning fra staten til voldsutsatte (voldserstatningsloven)](../lover/lov-2022-06-17-57.html) | Voldserstatningsloven | Justis- og beredskapsdepartementet |
| [Lov om erstatning ved pasientskader mv. (pasientskadeloven)](../lover/lov-2001-06-15-53.html) | Pasientskadeloven – passkl | Helse- og omsorgsdepartementet |
| [Lov om foretakspensjon (foretakspensjonsloven)](../lover/lov-2000-03-24-16.html) | Foretakspensjonsloven – ftpensjl | Finansdepartementet |
| [Lov om forsikringsavtaler (forsikringsavtaleloven)](../lover/lov-1989-06-16-69.html) | Forsikringsavtaleloven – fal | Justis- og beredskapsdepartementet |
| [Lov om forsikringsformidling (forsikringsformidlingsloven)](../lover/lov-2021-12-22-163.html) | Forsikringsformidlingsloven | Finansdepartementet |
| [Lov om forsikringsvirksomhet (forsikringsvirksomhetsloven)](../lover/lov-2005-06-10-44.html) | Forsikringsvirksomhetsloven – forsvl | Finansdepartementet |
| [Lov om informasjonstilgang m.m. for Koronautvalget, og endringer i voldserstatni](../lover/lov-2022-12-20-118.html) | Lov om informasjonstilgang m.m. for Koronautvalget mv. | Justis- og beredskapsdepartementet |
| [Lov om innskuddspensjon i arbeidsforhold (innskuddspensjonsloven)](../lover/lov-2000-11-24-81.html) | Innskuddspensjonsloven – innskpensjl | Finansdepartementet |
| [Lov om jernbaneansvar (jernbaneansvarsloven)](../lover/lov-1977-06-10-73.html) | Jernbaneansvarsloven – jbansvl | Justis- og beredskapsdepartementet |
| [Lov om kompensasjonsordning for kjemikalieskadde oljepionerar](../lover/lov-2025-12-22-116.html) | Lov om kompensasjonsordning for kjemikalieskadde oljepionerar | Arbeids- og inkluderingsdepartementet |
| [Lov om konfliktrådsbehandling (konfliktrådsloven)](../lover/lov-2014-06-20-49.html) | Konfliktrådsloven – konfrådl | Justis- og beredskapsdepartementet |
| [Lov om kontroll med produkter og forbrukertjenester (produktkontrolloven)](../lover/lov-1976-06-11-79.html) | Produktkontrolloven – prodktrl | Justis- og beredskapsdepartementet |
| [Lov om naturskadeforsikring](../lover/lov-1989-06-16-70.html) | Naturskadeforsikringsloven – natskforsl | Justis- og beredskapsdepartementet |
| [Lov om produktansvar [produktansvarsloven]](../lover/lov-1988-12-23-104.html) | Produktansvarsloven – prodansvl | Justis- og beredskapsdepartementet |
| [Lov om redaksjonell uavhengighet og ansvar i redaktørstyrte journalistiske medie](../lover/lov-2020-05-29-59.html) | Medieansvarsloven | Kultur- og likestillingsdepartementet |
| [Lov om sikring mot naturskader](../lover/lov-1994-03-25-7.html) | Naturskadeloven | Energidepartementet |
| [Lov om sjøtrygdelag [sjøtrygdelagloven]](../lover/lov-1953-07-03-2.html) | Sjøtrygdelagloven | Finansdepartementet |
| [Lov om skadeserstatning (skadeserstatningsloven)](../lover/lov-1969-06-13-26.html) | Skadeserstatningsloven – skl | Justis- og beredskapsdepartementet |
| [Lov om statleg varekrigsforsikring](../lover/lov-2003-12-12-115.html) | Varekrigsforsikringslova | Nærings- og fiskeridepartementet |
| [Lov om tilskudd til visse private virksomheter med offentlig tjenestepensjonsord](../lover/lov-2019-03-01-3.html) | Lov om tilskudd til virksomheter med offentlig tjenestepensjonsordning | Helse- og omsorgsdepartementet |
| [Lov om tjenestepensjon (tjenestepensjonsloven)](../lover/lov-2013-12-13-106.html) | Tjenestepensjonsloven | Finansdepartementet |
| [Lov om yrkesskadeforsikring (yrkesskadeforsikringsloven)](../lover/lov-1989-06-16-65.html) | Yrkesskadeforsikringsloven – yforsl | Justis- og beredskapsdepartementet |
